### ISSUE TITLE
`--continue` probably shall ignore already fully transferred files.

### ISSUE THREAD

**Issue by starrify** [s3tools/s3cmd#1009]
Version:
`s3cmd version 2.0.2`

How to reproduce the issue:
Assuming `s3://some_bucket/some_file` has been already downloaded to the current path, executing `s3cmd get s3://some_bucket/some_file . --continue` would generate an error: `ERROR: S3 error: 416 (InvalidRange): The requested range is not satisfiable`

Expected behavior:
No error shall appear if the file is already fully transferred.

A probably common use case:
When trying to download a directory and the transmission is unexpectedly interrupted, one may want to try `s3cmd get s3://some_bucket/some_path some_local_path --recursive --skip-existing --continue` to recover the progress.

**Comment by vinsec** [comment]
So could you pls tell me how to solve this problem?

**Comment by fviard** [comment]
I just pushed some changes in MASTER to solve the 2 use cases that are reported in this issue.  
Thanks to @basic-system for the investigation.  
Please give a try to the change and let me know if you are still encountering any issue.
