### ISSUE TITLE
signurl does not check bucket name dns support

### ISSUE THREAD

**Issue by straywarrior** [s3tools/s3cmd#1019]
I use s3cmd for an S3-compatible service (which is hosted in our intranet). However, this service has a  difference compared to official S3: bucket name cannot be the prefix of the hostname (sub-domain). So an S3 URL "s3://bucket_name" with host "s3intra.domain.com" can only be accessed via "s3intra.domain.com/bucket_name".
I find that "signurl" just uses `Crypto.sign_url_base_v2` and this function does not behave like `S3UriS3.public_url()`, which detects if the bucket has dns support. Is it possible for `Crypto.sign_url_base_v2` to use `public_url()` to get the correct URL for file location?

**Comment by fghaas** [comment]
This has been reported before, and #1011 exists to fix it — unfortunately, it hasn't landed yet.

**Comment by fviard** [comment]
Should be fixed now, thanks to @zmedico .
