### ISSUE TITLE
Support of One Zone-IA	 and Intelligent-Tiering

### ISSUE THREAD

**Issue by trouty00** [s3tools/s3cmd#1020]
Are these options on the roadmap for s3cmd to support? would be useful as life cycle rules means a minimum of 30 days is required before transitioning to the One Zone-IA storage class. Also assume its not possible to put files straight to glacier and this is done via the life cycle rules?

**Comment by simonweil** [comment]
I'd love to see this too, especially for Intelligent-Tiering as it saves a lot if $$$ in high volumes.

**Comment by tomasz-oponowicz** [comment]
Looks like setting the `--storage-class=ONEZONE_IA` option works as expected. Uploaded files have the _One Zone-IA_ storage class. Tested against 2.0.2 version.

**Comment by fviard** [comment]
As explained by @tomasz-oponowicz, you can already use the new storage class as this command does not have a limited list of values for the moment.
Still, I updated the list of storage class in the help command to add the new classes.

Final list: STANDARD, STANDARD_IA, ONEZONE_IA, INTELLIGENT_TIERING, GLACIER or DEEP_ARCHIVE

**Comment by mpoisot** [comment]
Please add these additional storage classes to the [usage page](https://s3tools.org/usage).
