### ISSUE TITLE
s3cmd info command fails

### ISSUE THREAD

**Issue by ironashram** [s3tools/s3cmd#1024]
with latest s3cmd 2.0.2 i have a problem with the following command:

s3cmd info s3://monitorip/test.txt

s3://monitorip/test.txt (object):
   File size: 4
   Last mod:  Mon, 03 Dec 2018 12:17:17 GMT
   MIME type: text/plain
   Storage:   STANDARD
   MD5 sum:   098f6bcd4621d373cade4e832627b4f6
   SSE:       none
   Policy:    none
ERROR: S3 error: 403 (SignatureDoesNotMatch)

if i do the same command using version 1.6.1 for example i get it working correctly

s3cmd info s3://monitorip/test.txt
s3://monitorip/test.txt (object):
   File size: 4
   Last mod:  Mon, 03 Dec 2018 12:17:17 GMT
   MIME type: text/plain
   Storage:   STANDARD
   MD5 sum:   098f6bcd4621d373cade4e832627b4f6
   SSE:       none
   policy:    none
   cors:      none
   ACL:       user: FULL_CONTROL
   ACL:       user: READ
   ACL:       *anon*: READ
   URL:       http://******/test.txt
   x-amz-meta-s3b-last-modified: 20140206T142155Z

the backend used is a custom Scality installation, S3 Compatible solution

My config looks like this:

[default]
access_key = user
host_base = ******
host_bucket = %(bucket)s.******
secret_key = password
signature_v2 = True

**Comment by fviard** [comment]
Hi, are you still encountering this issue?
if you don't use any special character in the bucket/object names.
It was probably a scality configuration issue I think?
You should maybe let it use signature v4 by using:
`signature_v2 = False`
instead.

**Comment by retry** [comment]
I am having intermittent problems with s3cmd info using 2.1.0 .  I use info after a put to fetch the MD5 checksum to ensure data integrity.  Sometimes svn info fails like so:

`
Invoked as: /usr/bin/s3cmd info s3://trac-xxxx/20200624103846.mp3
Problem: <class 'ConnectionResetError: [Errno 104] Connection reset by peer
S3cmd:   2.1.0
python:   3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3121, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 3030, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 930, in cmd_info
    info = s3.object_info(uri)
  File "/usr/local/bin/S3/S3.py", line 941, in object_info
    response = self.send_request(request)
  File "/usr/local/bin/S3/S3.py", line 1281, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "/usr/local/bin/S3/ConnMan.py", line 251, in get
    conn.c.connect()
  File "/usr/lib/python3.7/http/client.py", line 1407, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 853, in _create
    self.do_handshake()
  File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer
`

The error is not consistent, but I get several of these per day.

**Comment by fviard** [comment]
Closing as original issue was probably a Scaleway issue that has already been resolved.

@retry Your issue in not related to the one related in this issue. It is probably more related to #1114 
I just pushed a fix for that in the github MASTER branch. Would it be possible for you to give it a try?
Thanks
