### ISSUE TITLE
s3cmd run failed with the libmagic problem

### ISSUE THREAD

**Issue by lylklb** [s3tools/s3cmd#1031]
We have installed the s3tools successfully,  but  when firstly run the following s3cmd,  the problem happened .....！

[root@cspt3db5 ~]# 
[root@cspt3db5 ~]# 
[root@cspt3db5 ~]# s3cmd --configure

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

Error loading some components of s3cmd (Import Error)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /bin/s3cmd --configure
Problem: AttributeError: /lib64/libmagic.so.1: undefined symbol: magic_setparam
S3cmd:   1.6.1
python:   2.7.5 (default, May  3 2017, 07:55:04) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-14)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2900, in <module>
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 39, in <module>
  File "build/bdist.linux-x86_64/egg/magic.py", line 293, in <module>
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 373, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 378, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /lib64/libmagic.so.1: undefined symbol: magic_setparam

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

[root@cspt3db5 ~]#   
[root@cspt3db5 ~]#

**Comment by sjaenick** [comment]
This works for me:

```
RUN apt-get -y update && DEBIAN_FRONTEND=noninteractive apt-get -y install python3-pip python3-minimal
RUN pip3 install -I s3cmd python-dateutil python-magic six
RUN apt-get -y purge python3-pip && apt-get -y autoremove
```

**Comment by lylklb** [comment]
Thanks！  But I doubt this problem might have sth to do with my OS platform(RHEL 7)！

[root@cspt3db5 install]# 
[root@cspt3db5 install]#
[root@cspt3db5 install]# rpm -qf /lib64/libmagic.so.1
file-libs-5.11-35.el7.x86_64
[root@cspt3db5 install]# 
[root@cspt3db5 install]# 
[root@cspt3db5 install]# nm -D /lib64/libmagic.so.1|grep -Ei "setpar"
[root@cspt3db5 install]#
[root@cspt3db5 install]#

**Comment by fviard** [comment]
omg, magic is a crazy clusterfuck...
Looking at the backtrace, the thing explode just when calling "import magic".
So, I guess that the issue is in an incompatibility between whatever python-magic you have installed with whatever magic library you have installed.
I can guess that maybe that could have happened from a system update mixing old and new packages?

if it is what i'm thinking, you can simply do:
python3 (or python2 for lylklb)
>> import magic
And see if you have the same issue happening.

And from there, follow the trail to find what version is wrong on your system python-magic or something like "file".

**Comment by fviard** [comment]
As stated before, probably a system setup issue between libmagic installed and python-magic package. But so unrelated to s3cmd except that it breaks it.
You can test what i suggested before to investigate.
Don't hesitate to reopen the issue if you find something related to s3cmd.
