### ISSUE TITLE
Crashes on Synology DSM 6.0

### ISSUE THREAD

**Issue by brunobhr** [s3tools/s3cmd#1038]
I'm trying to use s3cmd on a Synology NAS with DSM 6.0, and I'm getting this error. I've installed the python-magic libs but still.

[root@OFFICE_01 arc]# s3cmd --version

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

Error loading some components of s3cmd (Import Error)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /bin/s3cmd --version
Problem: RuntimeError: can not find library magic
S3cmd:   2.0.1+
python:   2.7.12 (default, Apr 20 2017, 02:26:22) 
[GCC 4.9.3 20150311 (prerelease)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/s3cmd-2.0.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 3054, in <module>
  File "/usr/bin/S3/S3.py", line 50, in <module>
    import magic
  File "/usr/lib/python2.7/site-packages/magic.py", line 155, in <module>
    dll = ctypes.util.find_library('magic') or ctypes.util.find_library('magic1') or ctypes.util.find_library('cygmagic-1')
  File "/usr/lib/python2.7/ctypes/util.py", line 242, in find_library
    raise RuntimeError("can not find library %s" % name)
RuntimeError: can not find library magic

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by fviard** [comment]
Python-magic is not enough, it is just a wrapper over the real "magic" binary library.
So, you should also install libmagic on your nas.

**Comment by brunobhr** [comment]
Sorry by libs I meant both python-magic and libmagic are installed.

**Comment by brunobhr** [comment]
I manage to make use of s3cmd by upgrading to Python 3 and pip3:

>opkg install python3-pip

>pip3 install s3cmd

[root@OFFICE_01 ~]# s3cmd --version
s3cmd version 2.0.2

Sorry for the noise.
