### ISSUE TITLE
AttributeError: 'file' object has no attribute 'stream_name'

### ISSUE THREAD

**Issue by jarednielsen** [s3tools/s3cmd#1047]
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/bin/s3cmd get --recursive --force s3://my-bucket /mnt/folder/
Problem: AttributeError: 'file' object has no attribute 'stream_name'
S3cmd:   2.0.2
python:   2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 548, in cmd_object_get
    response = s3.object_get(uri, dst_stream, destination, start_position = start_position, extra_label = seq_label)
  File "/home/jnielsen/.local/lib/python2.7/site-packages/S3/S3.py", line 716, in object_get
    response = self.recv_file(request, stream, labels, start_position)
  File "/home/jnielsen/.local/lib/python2.7/site-packages/S3/S3.py", line 1636, in recv_file
    filename = stream.stream_name
AttributeError: 'file' object has no attribute 'stream_name'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

Has anyone run into this issue?

**Comment by jarednielsen** [comment]
It occurs in s3cmd version 2.0.2, but not in version 1.6.1.

**Comment by DdMad** [comment]
@jarednielsen in case you haven't solve the issue. I also encounter the same issue when using `s3cmd get xxxx`. Then I tried s3cmd-2.0.1 and it worked. (I suspect it's related to the python version according to the error message, but no time to dig yet)

**Comment by DdMad** [comment]
The root cause should be the "S3" folder is missing, and I just realize I forgot copy S3 folder together with s3cmd(v2.0.2) binary to the PATH. 

According to the INSTALL doc, it requires S3 together with s3cmd binary. So if you have s3cmd binary in /usr/bin/, then you should also copy S3 folder to /usr/bin/ (i.e. you will have /usr/bin/S3). I jsut tried this with s3cmd v2.0.2 and it works now.

**Comment by fviard** [comment]
@DdMad Thanks to the investigation of @DdMad, it does not look like a bug, but an installation issue.

You are right that s3cmd and the S3 folder are going together.
Normally, the s3cmd file will go to /usr/bin and the S3 folder, should go inside the normal PYTHONPATH. Most of the time, it is a folder like /usr/lib/python3.x/site-packages/.

What happens very often is that people install s3cmd through their distribution (apt for example), then try to update it using the source, or pip without removing the origin "apt" package.
As different installation source (apt, pip, ...) are not putting the python packages in the same PYTHONPATH folders, sometimes it is the oldest S3 folder that has the priority over the newest one, and then you have the kind of case reported here.
