### ISSUE TITLE
S3cmd  "--add-header" can not use underline

### ISSUE THREAD

**Issue by Zstro** [s3tools/s3cmd#1054]
I can not use s3cmd to put a file with “--add-header=X-Amz-meta-asd_ad:asdad”, just because of underline.
```
s3cmd put --add-header="X-Amz-meta-asd_ad:asdad" test.go s3://zztest
ERROR: Parameter problem: Invalid character(s) in header name 'X-Amz-meta-asd_ad': "_"
```
Is there any solution?

**Comment by fviard** [comment]
Thank you for the report.
It was a legacy limitation.
I just pushed a fix to remove this limitation in MASTER.
