### ISSUE TITLE
s3cmd sync does not preserve original timestamp when dealing with path changes and remote copy

### ISSUE THREAD

**Issue by addtechhub-it** [s3tools/s3cmd#1058]
Regardless to specifying -p ,
s3cmd sync DOES NOT preserve original timestamp when dealing with path changes and remote copy
while new uploads DO preserve original timestamp from local file.

**Comment by fviard** [comment]
I have pushed a few fixes in MASTER, and the issue should now be fixed.
(Will be in releases >= 2.2.0)
