### ISSUE TITLE
run-tests.py: Error in test "Buckets list"

### ISSUE THREAD

**Issue by NotTheDr01ds** [s3tools/s3cmd#1066]
The most recent commit (b790be56ae6e8f79fa7c7c01bc237edea7e1029d) to run-tests.py changed the  name of the third test bucket from {prefix}-Autotest-3 to all lowercase to match the updated AWS naming rules.  This was a necessary change, but oddly it seems that the "Buckets list" test still checks for the capitalized version, failing as a result when it doesn't find it.

Is it really possible that run-tests.py has been broken for over a year, or am I missing something basic?   Wouldn't this have been caught by running run-tests.py when b790be56ae6e8f79fa7c7c01bc237edea7e1029d was accepted?

**Comment by fviard** [comment]
Fixed thanks to the PR of @NotTheDr01ds .
