### ISSUE TITLE
put  files error

### ISSUE THREAD

**Issue by liyin37** [s3tools/s3cmd#1076]
![image](https://user-images.githubusercontent.com/42507175/76385223-2c72f200-639c-11ea-870b-b9110fc45fd0.png)
upload: '/home/test1.jar' -> 's3://liyin/test1.jar'  [1 of 3]
 0 of 0     0% in    0s     0.00 B/s  failed
WARNING: Retrying failed request: /test1.jar ([Errno 111] Connection refused)
WARNING: Waiting 3 sec...
upload: '/home/test1.jar' -> 's3://liyin/test1.jar'  [1 of 3]
 0 of 0     0% in    0s     0.00 B/s  failed
WARNING: Retrying failed request: /test1.jar ([Errno 111] Connection refused)
WARNING: Waiting 6 sec...
upload: '/home/test1.jar' -> 's3://liyin/test1.jar'  [1 of 3]
 0 of 0     0% in    0s     0.00 B/s  failed
WARNING: Retrying failed request: /test1.jar ([Errno 111] Connection refused)
WARNING: Waiting 9 sec...
upload: '/home/test1.jar' -> 's3://liyin/test1.jar'  [1 of 3]
 0 of 0     0% in    0s     0.00 B/s  failed
WARNING: Retrying failed request: /test1.jar ([Errno 111] Connection refused)
WARNING: Waiting 12 sec...
upload: '/home/test1.jar' -> 's3://liyin/test1.jar'  [1 of 3]
 0 of 0     0% in    0s     0.00 B/s  failed
WARNING: Retrying failed request: /test1.jar ([Errno 111] Connection refused)
WARNING: Waiting 15 sec...
upload: '/home/test1.jar' -> 's3://liyin/test1.jar'  [1 of 3]
 0 of 0     0% in    0s     0.00 B/s  failed
ERROR: Upload of '/home/test1.jar' failed too many times (Last reason: Upload failed for: /test1.jar)
upload: '/home/test2.jar' -> 's3://liyin/test2.jar'  [2 of 3]
 0 of 0     0% in    0s     0.00 B/s  failed
WARNING: Retrying failed request: /test2.jar ([Errno 111] Connection refused)
WARNING: Waiting 3 sec...
upload: '/home/test2.jar' -> 's3://liyin/test2.jar'  [2 of 3]
 0 of 0     0% in    0s     0.00 B/s  failed
WARNING: Retrying failed request: /test2.jar ([Errno 111] Connection refused)
WARNING: Waiting 6 sec...

**Comment by fviard** [comment]
You should check your configuration file (~/.s3cfg) because you have probably made some errors filling the server info. Are you targeting the official Amazon s3 servers?
