### ISSUE TITLE
Please tag 2.0.3 or 2.1.0 release

### ISSUE THREAD

**Issue by WarheadsSE** [s3tools/s3cmd#1077]
![Screenshot_20200318_092838](https://user-images.githubusercontent.com/585036/76965659-106ed380-68fb-11ea-8561-6ce8d790362b.png)

It has been nearly 2 years since the last tag was issued, and a release made.

Some teams _can not_ ship code from `master` into production, and _at best_ are forced to maintain a fork or custom patch set.

Please tag a new release, so that those of who need the fixes currently only present on master can ship productions & services that consume this library.

#930 #1006 et al.

**Comment by fviard** [comment]
Sorry that it took a so long time but a new release is coming soon.

**Comment by WarheadsSE** [comment]
@fviard Could you please provide a definition for "coming soon"?

**Comment by fviard** [comment]
Normally, I will do the release today.
I'm currently testing it and looking if there is no remain small bug fix to put inside.

**Comment by WarheadsSE** [comment]
Thank you for the timeline :+1:

**Comment by fviard** [comment]
Fyi, the new release v2.1.0 is out and available in github and in Pypi.

**Comment by WarheadsSE** [comment]
Many thanks @fviard :bow:
