### ISSUE TITLE
no such option --access_token 

### ISSUE THREAD

**Issue by shukriadams** [s3tools/s3cmd#1078]
Hey

According to the documentation at https://s3tools.org/usage --access_token exists at CLI parameter, but when I used it I get 

        s3cmd: error: no such option: --access_token

Is there a way around this? Thanks.

**Comment by fviard** [comment]
Hum, it is curious because the option exists.
Example:
```
$ ./s3cmd  ls --access_token abcdeffsfds
ERROR: S3 error: 400 (InvalidToken): The provided token is malformed or otherwise invalid.
```

Are you sure of the command you entered into your console? maybe try to type it manually, because sometimes copy/pasting can introduce weird characters.

Otherwise, which version of s3cmd are you using, one that is recent enough?

**Comment by shukriadams** [comment]
I'm on version 2.0.2 - I tried installing that from Sourceforge first, then from Github. When I copy/paste your command above

    s3cmd  ls --access_token abcdeffsfds

I get

    ERROR: /home/vagrant/.s3cfg: Network is unreachable
    ERROR: Configuration file not available.
    ERROR: Consider using --configure parameter to create one.

which is the same error I get when running s3cmd with no args at all. I'm running Python 2 ...would that make any difference?

**Comment by shukriadams** [comment]
Closing this ticket as it looks like the original problem (s3cmd: error: no such option: --access_token) was just due to installation weirdness. Found out Linode _does_ do id/secrets, they don't seem to work as pure command line args, but that's another matte entirely.
