### ISSUE TITLE
BucketAlreadyExists

### ISSUE THREAD

**Issue by acs-ferreira** [s3tools/s3cmd#1079]
I'm trying to create a new bucket, but:

```
# s3cmd rb s3://mybucket
ERROR: S3 error: 404 (NoSuchBucket): The specified bucket does not exist.

# s3cmd rb --force s3://mybucket

# s3cmd mb s3://mybucket
ERROR: Bucket 'mybucket' already exists
ERROR: S3 error: 409 (BucketAlreadyExists): The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.

# s3cmd ls s3://mybucket
ERROR: Bucket 'mybucket' does not exist
```

What is this, some sort of "bucket cache"?

**Comment by fviard** [comment]
No, probably this bucket name is already used by someone else.
Bucket names are like website domain names, they are shared between all users.
So, you can't use (create/remove/store) a bucket that is already used by another user.
So try again with different bucket name.
