### ISSUE TITLE
Version 2.0.2 macOS via Homebrew "Syntax Warning"

### ISSUE THREAD

**Issue by MingyJ** [s3tools/s3cmd#1086]
I just grabbed s3cmd from Homebrew today, and received the following:

```
brett@macbrett Desktop% s3cmd ls
/usr/local/bin/s3cmd:308: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if response["status"] is 200:
/usr/local/bin/s3cmd:310: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif response["status"] is 204:
```
I can confirm that changing the "is" to "==" does indeed make the warning disappear and normal, expected function occurs.

**Comment by fviard** [comment]
Hi, thank you for your report.
This issue is already fixed and you can find it inside the new version that I have released today:
v2.1.0.
