### ISSUE TITLE
s3cmd sync does not retry (with delay) on 429 (Too Many Requests) response

### ISSUE THREAD

**Issue by BarneyL** [s3tools/s3cmd#1096]
While building up the list of remote files, s3cmd will fail and completely stop if it receives a 429 response. The correct action would be to do what it does for responses >= 500, i.e. wait and try again.

**Comment by fviard** [comment]
Thank you for the report, in theory, you should not encounter this error but a 503 slowdown error, based on the protocol:
https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

But I guess that maybe the 429 can happen if there is a gateway somewhere in between or for other s3 compatible server, and it does not cost anything to add the 429 to the list of retry-able errors.

Just by curiosity, @BarneyL would you mind to share which kind of s3 server you used to have encountered such an error? Aws s3, ceph, minio?

**Comment by BarneyL** [comment]
> Just by curiosity, @BarneyL would you mind to share which kind of s3 server you used to have encountered such an error? Aws s3, ceph, minio?
Some kind of proprietary implementation. Not sure exactly what, but it's reasonably compatible with s3, with some issues like the one I reported here.

**Comment by fviard** [comment]
This should be fixed in MASTER.
It would be nice if you can give it a try.
