### ISSUE TITLE
Include Vultr Object Storage in Wiki

### ISSUE THREAD

**Issue by dfinster** [s3tools/s3cmd#1106]
Vultr has a guide to use s3cmd with Vultr Object Storage. Can the wiki page be updated?

https://github.com/s3tools/s3cmd/wiki/How-to-configure-s3cmd-for-alternative-S3-compatible-services

***

### Vultr Object Storage
"How to" link:  
<https://www.vultr.com/docs/how-to-use-s3cmd-with-vultr-object-storage>

***

**Comment by fviard** [comment]
Thank you for the info, I added it to the wiki!
