### ISSUE TITLE
s3cmd 2.1.0 SyntaxWarning in magic.py:193

### ISSUE THREAD

**Issue by thinkedem** [s3tools/s3cmd#1107]
> I have s3cmd 2.1.0 installed (via homebrew) but still getting the SyntaxWarning:
> `/usr/local/Cellar/s3cmd/2.1.0/libexec/lib/python3.8/site-packages/magic.py:193: SyntaxWarning: "is" with a literal. Did you mean "=="?`

_Originally posted by @laurenz-glueck in https://github.com/s3tools/s3cmd/issues/1055#issuecomment-627170479_

Same here.

**Comment by fviard** [comment]
@thinkedem First, this error is just an annoyance on debug, but nothing to be worried.
Second, this error is not coming from s3cmd itself, but from the python-magic dependency.

If you can update the python-magic package to a version 0.4.17 or 0.4.18, this issue should be resolved.

**Comment by fviard** [comment]
I see that @thinkedem looks like to be using mac.

@neilclypd As you did update s3cmd on homebrew last time, with the following recipe:
https://github.com/Homebrew/homebrew-core/pull/52727/files
Would it be possible for you to update it with a more recent version of the python-magic dependency? 0.4.17 or 0.4.18 (I have checked that they have the right fix for this issue).

Thanks

**Comment by neilclypd** [comment]
@fviard submitted updated formula in https://github.com/Homebrew/homebrew-core/pull/55575

**Comment by fviard** [comment]
Thank you very much!

**Comment by hmt** [comment]
This pull request has never been merged...
