### ISSUE TITLE
is eu-south-1 supported?

### ISSUE THREAD

**Issue by mati8** [s3tools/s3cmd#1111]
Hi,
I have s3cmd version 1.6.1 but I can't upload anything to a bucket in eu-south-1 (Milan) region.

I receive this error:
S3 error: 400 (IllegalLocationConstraintException): The eu-south-1 location constraint is incompatible for the region specific endpoint this request was sent to.

I even configured s3cmd for eu-south-1 but it doesn't work.
Is it supported?
Thank you!

**Comment by fviard** [comment]
Is it possible for you to try with the latest release 2.1.0 ?
(Available here or on pypi)
Or even better, with the latest github MASTER?

Because I just tried and had no issue, and a lot of changes were pushed in 2.1.0 related to the handling of regions and signature v4 only regions.

Otherwise, did you create the target bucket yourself? Are you sure that it is located in this region?

**Comment by mati8** [comment]
I tried with release 2.1.0+ from s3cmd master and still doesn't work.

- I tried again to create another bucket in same region (eu-south-1) from the online console. then I tried to upload with s3cmd and the error message is the same.
- from online console I tried to create another bucket in the US region. And in the exactly same policy (and same keys etc.) I added that bucket. And in this case s3cmd is working perfectly as usual.

Any ideas? Thank you so much!

**Comment by fviard** [comment]
Can you share the .s3cfg configuration that you are using?
!! Take care to remove any access_key, secret_key, access_token from it.

**Comment by mati8** [comment]
Below you can find my configuration file.
With this exactly configuration (and appropriate IAM setting) I do not have any problem at uploading in US region.

**Useful information**: maybe it's useful for you to know that if I disable the IAM key and I try to upload in US region I get this (of course, as usual):
_The AWS Access Key Id you provided does not exist in our records._ 

BUT...if with the same IAM key disabled I try to upload in eu-south-1 I get the same error that I get even when the key is enabled: S3 error: 400 (IllegalLocationConstraintException): The eu-south-1 location constraint is incompatible for the region specific endpoint this request was sent to.

Thank you!
 
[default]
access_key = my_key_removed
access_token = 
add_encoding_exts = 
add_headers = 
bucket_location = eu-south-1
ca_certs_file = 
cache_file = 
check_ssl_certificate = True
check_ssl_hostname = True
cloudfront_host = cloudfront.amazonaws.com
connection_pooling = True
content_disposition = 
content_type = 
default_mime_type = binary/octet-stream
delay_updates = False
delete_after = False
delete_after_fetch = False
delete_removed = False
dry_run = False
enable_multipart = True
encrypt = False
expiry_date = 
expiry_days = 
expiry_prefix = 
follow_symlinks = False
force = False
get_continue = False
gpg_command = /usr/bin/gpg
gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_passphrase = 
guess_mime_type = True
host_base = s3.amazonaws.com
host_bucket = %(bucket)s.s3.amazonaws.com
human_readable_sizes = False
invalidate_default_index_on_cf = False
invalidate_default_index_root_on_cf = True
invalidate_on_cf = False
kms_key = 
limit = -1
limitrate = 0
list_md5 = False
log_target_prefix = 
long_listing = False
max_delete = -1
mime_type = 
multipart_chunk_size_mb = 15
multipart_copy_chunk_size_mb = 1024
multipart_max_chunks = 10000
preserve_attrs = True
progress_meter = True
proxy_host = 
proxy_port = 0
public_url_use_https = False
put_continue = False
recursive = False
recv_chunk = 65536
reduced_redundancy = False
requester_pays = False
restore_days = 1
restore_priority = Standard
secret_key = my_key_removed
send_chunk = 65536
server_side_encryption = False
signature_v2 = False
signurl_use_https = False
simpledb_host = sdb.amazonaws.com
skip_existing = False
socket_timeout = 300
ssl_client_cert_file = 
ssl_client_key_file = 
stats = False
stop_on_error = False
storage_class = 
throttle_max = 100
upload_id = 
urlencoding_mode = normal
use_http_expect = False
use_https = True
use_mime_magic = True
verbosity = WARNING
website_endpoint = http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
website_error = 
website_index = index.html

**Comment by fviard** [comment]
Ok, I think that it might be because latest regions does not support anymore direct access with the url s3.amazonaws.com .

Can you try to modify your configuration with the 2 following values:
{{{
host_base = s3.eu-south-1.amazonaws.com
host_bucket = %(bucket)s.s3.eu-south-1.amazonaws.com
}}}

(the region is added between s3 and amazonaws)

**Comment by mati8** [comment]
It's working perfectly!
Thank you so much!  ❤️
