### ISSUE TITLE
High CPU when file being uploaded is rotated

### ISSUE THREAD

**Issue by mkrokosz** [s3tools/s3cmd#1125]
If a file being uploaded is rotated, a race condition in object_put() between opening the stream and calculating the length will cause this function to get stuck in a while loop because it will be trying to read more bytes then exist in the file which this function opens.  When this occurs, read will return 0 bytes causing this function to get stuck into a while loop causing the script to peg a single core to 100% cpu.

https://github.com/s3tools/s3cmd/blob/a163fd430e52280d30526bb8d88afdf9290b4227/S3/Crypto.py#L264

**Comment by fviard** [comment]
Thank you very much for your detailed report!
I'm especially grateful to you for having investigated the root cause of this tricky corner case, so that now the fix will be easy.

**Comment by fviard** [comment]
Finally fixed, thank you very much!
