### ISSUE TITLE
`s3cmd info` fails on bucket

### ISSUE THREAD

**Issue by oseiberts11** [s3tools/s3cmd#1126]
```
$ s3cmd info s3://mytestbucket-write
s3://mytestbucket-write/ (bucket):
   Location:  us-east-1
   Payer:     None

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /opt/local/bin/s3cmd info s3://mytestbucket-write
Problem: <class 'TypeError: can only concatenate str (not "NoneType") to str
S3cmd:   2.1.0
python:   3.8.5 (default, Jul 21 2020, 18:31:53)
[Clang 10.0.1 (clang-1001.0.46.4)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/opt/local/bin/s3cmd", line 3121, in <module>
    rc = main()
  File "/opt/local/bin/s3cmd", line 3030, in main
    rc = cmd_func(args)
  File "/opt/local/bin/s3cmd", line 958, in cmd_info
    expiration_desc += "objects with key prefix '" + expiration['prefix'] + "' "
TypeError: can only concatenate str (not "NoneType") to str

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
The `Location:  us-east-1` is incorrect. I'm not using AWS but a Quobyte object storage.
The fix is very simple:
```diff
--- /opt/local/bin/s3cmd	2020-08-06 11:33:19.000000000 +0200
+++ /Users/oseibert/bin/s3cmd	2020-08-20 16:51:19.000000000 +0200
@@ -955,7 +955,7 @@
                     if expiration['prefix'] == "":
                         expiration_desc += "all objects in this bucket "
                     else:
-                        expiration_desc += "objects with key prefix '" + expiration['prefix'] + "' "
+                        expiration_desc += "objects with key prefix '" + str(expiration['prefix']) + "' "
                     expiration_desc += "will expire in '"
                     if expiration['days']:
                         expiration_desc += expiration['days'] + "' day(s) after creation"
```

**Comment by oseiberts11** [comment]
Well, maybe the fix is slightly more complex, now that I'm matching the output to the source.
This is the output:
```
$ ~/bin/s3cmd info s3://mytestbucket-write
s3://mytestbucket-write/ (bucket):
   Location:  us-east-1
   Payer:     None
   Expiration Rule: objects with key prefix 'None' will expire in '
   Policy:    none
   CORS:      <?xml version="1.0" encoding="UTF-8"?><CORSConfiguration/>
   ACL:       42514270ba154559a1c6fbb69bdf5d58: FULL_CONTROL
```

**Comment by fviard** [comment]
Is it possible for you to run your request with the "-d" flag in command line and show me the debug log?
> s3cmd -d info s3://mytestbucket-write

When we do the sub requests to generate the "info" for the bucket, one of them will be a request for the "?lifecycle" resource.
Normally, either the server support the request and return a valid response, or it does not, and in that case we skip the lifecycle part.

In your case, it looks like that the server is sending a "valid" kind of empty request. So I would be very curious to see what the server reply.

**Comment by oseiberts11** [comment]
I think I removed the previous buckets but I made a new one. Fortunately the issue is repeatable :) 
I attached a log file. I have xxxxx-ed out some numbers that might be private.
[failed.log](https://github.com/s3tools/s3cmd/files/5156276/failed.log)
The S3-like storage is implemented by Quobyte (which is mainly a distributed storage system, but they also have an S3 proxy to provide S3-like access).

**Comment by fviard** [comment]
Thank you for the log.
In fact, this issue is coming from an incorrect behavior of the s3 frontend of Quobyte.
It is the same issue a #1090 .

Still, I already added a workaround/safety fix to cover for this situation.
So, you can give a try to the github "MASTER" that already has this fix, otherwise it will be delivered with the next release (>= 2.2.0).

But, btw, if you can report the original issue to Quobyte so that they improve their connector, here you can find my recommandation about that: https://github.com/s3tools/s3cmd/issues/1090#issuecomment-616563704

**Comment by oseiberts11** [comment]
Thanks! Yes the version in the master branch doesn't have the problem. I will pass on your comment to Quobyte.
