### ISSUE TITLE
Decrypt without s3cmd?

### ISSUE THREAD

**Issue by dm17** [s3tools/s3cmd#1138]
So if you have some *.tar.gz files in an s3 bucket, download them with the UI... Now you want to untar the file, but you encrypted it before upload with s3cmd. How to decrypt it?
1) I want this to gain confidence in the way s3cmd encrypts my files
2) I want to do this for convenience on occasion

It should be like this, right?
tar -cvzf - folder | gpg -c > folder.tar.gz.gpg

**Comment by dm17** [comment]
Sorry for the duplicate... GitHub returned an error & I didn't realize it posted.

**Comment by fviard** [comment]
So, s3cmd is quite straightforward with the way it handle the encryption.
If you have not modified the commands, that are in the configuration, here they are:
```
    gpg_encrypt = u"%(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s"
    gpg_decrypt = u"%(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s"
```

To be noted, s3cmd does not tar folders.
It just encrypt and send each file individually.
