### ISSUE TITLE
Decrypting s3cmd uploaded files

### ISSUE THREAD

**Issue by dm17** [s3tools/s3cmd#1139]
So if you have some *.tar.gz files in an s3 bucket, download them with the UI... Now you want to untar the file, but you encrypted it before upload with s3cmd. How to decrypt it?
1) I want this to gain confidence in the way s3cmd encrypts my files
2) I want to do this for convenience on occasion

It should be like this, right?
tar -cvzf - folder | gpg -c > folder.tar.gz.gpg

**Comment by dm17** [comment]
Seems like this should work:
```
gpg -d folder.tar.gz.gpg | tar -xvzf -
```

Blessed by s3cmd pros?

**Comment by fviard** [comment]
Replied here:
https://github.com/s3tools/s3cmd/issues/1138#issuecomment-706798418

**Comment by fviard** [comment]
(So the short reply is yes :-) )
