### ISSUE TITLE
`s3cmd multipart ...` makes no attempt to paginate through results

### ISSUE THREAD

**Issue by ivancich** [s3tools/s3cmd#1140]
In the function `cmd_list_multipart` I do not see it consulting the "limit" configuration, nor do I see a loop to receive paginated results.

I do know that the `aws` command-line client *does* paginate results. So it seems that s3cmd presently can only list the first 1000 incomplete multipart uploads for a bucket.

**Comment by ivancich** [comment]
For example:

> aws s3api list-multipart-uploads --bucket=_bucket_ --endpoint=_endpoint_

will paginate through results when it received 1000 at a time.

**Comment by fviard** [comment]
s3cmd used to only be able to list the first 1000 parts, but changes were done recently to support pagination.
They are already in the github MASTER version and will be in the next release 2.2.0.

Fyi, pagination is handled deeper in the code, inside S3.py.
