### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by nizaevrd** [s3tools/s3cmd#1148]
My commands(s3cmd du s3://nexus2 or s3cmd ls s3://nexus2) fail with error

` s3cmd du s3://nexus2

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/bin/s3cmd du s3://nexus2
Problem: IndexError: list index out of range
S3cmd:   2.1.0
python:   2.7.5 (default, Sep 26 2019, 13:23:47) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
environment LANG=ru_RU.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3121, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 3030, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 87, in cmd_du
    subcmd_bucket_usage(s3, uri)
  File "/usr/bin/s3cmd", line 123, in subcmd_bucket_usage
    for _, _, objects in s3.bucket_list_streaming(bucket, prefix=prefix, recursive=True):
  File "/usr/lib/python2.7/site-packages/S3/S3.py", line 368, in bucket_list_streaming
    uri_params['marker'] = current_prefixes[-1]["Prefix"]
IndexError: list index out of range

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

`

**Comment by fviard** [comment]
Hi, your issue is known and already fixed in MASTER:
https://github.com/s3tools/s3cmd/issues/1088
The fix should also be in the next release >= 2.2.0.
