### ISSUE TITLE
size compare too coarse

### ISSUE THREAD

**Issue by rustleg** [s3tools/s3cmd#1158]
For a long time I used sync with --no-check-md5 until I discovered that it missed a lot of files which were updated but the size didn't change a lot. I wonder if the size check is using kb rather than bytes? If so can it be done in bytes?

As I understand it the reason for not doing the md5 check is to avoid the time it takes but checking size shouldn't take any longer if it is done in bytes rather than a larger unit.

**Comment by fviard** [comment]
We take the size as is from the filesystem through the following structure:
https://docs.python.org/3/library/os.html#os.stat_result

The size is normally already in bytes, and it is what is compared.
So, probably, in your case, there should be something else that mess with the situation but not the size precision.

**Comment by fviard** [comment]
Closing as no recent feedback.
Please reopen if you are still encountering the issue and have more details to provide. Thanks.
