### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by k0ste** [s3tools/s3cmd#1164]
Python 3.9 is shipped to distros, such Archlinux, it will be nice to get new tarball.

**Comment by kaiwalyajoshi** [comment]
:+1: on a new `2.2.0` release.
I'm hitting the bug found in #1094 and worked around it by commenting out line 301 in the `2.1.0` release.
Would really benefit from a new release so that `s3cmd` on PyPI will get updated.

**Comment by KeithCu** [comment]
Python 3.9 came out in October, so hopefully the fix can be released soon.

**Comment by salty-horse** [comment]
If a new release is planned, I suggest also testing it with the new 3.10, and updating the list of supported versions in `setup.py`.

**Comment by salty-horse** [comment]
2.2.0 was released 6 days ago and is [available on PyPI](https://pypi.org/project/s3cmd/2.2.0/).

It's compatible with 3.9 even though it's not mentioned in `setup.py`.
