### ISSUE TITLE
s3cmd configure doesn't accept a remote path

### ISSUE THREAD

**Issue by FromOopsToOps** [s3tools/s3cmd#1167]
Hello developers;

I'm trying to configure for a client's server s3cmd so we can run backup scripts on it. 
I can connect to and list buckets using Transmission (for Mac) but server is Linux and I need s3cmd.

On transmission I input the following information (redacted because of NDA):

address: s3.amazonaws.com
Access key: [redacted]
Secret: [redacted]
**Remote path: domain.com**

On Mac, like I said, this works and I can list buckets. The fully qualified name for the bucket is: https://domain.com.s3.us-west-2.amazonaws.com/bucketname .

With s3cmd, though, I can't seem to figure out how to input the same information.

I tried setting `DNS-style bucket+hostname:port template for accessing a bucket: https://domain.com.s3.us-west-2.amazonaws.com/bucketname` and variations, like changing bucketname to %(bucket)s, us-west-2 to %(location)s. Nothing works.

Is there any way I can solve this?

Thanks for any input, I really appreciate it.

**Comment by fviard** [comment]
Closing this issue as it is very old.
Please let me know if, after so long, you still have the issue with your configuration.
