### ISSUE TITLE
Where is the GPG Public KEy to check asc signatures of downloaded distributions ? 

### ISSUE THREAD

**Issue by Jean-Baptiste-Lasselle** [s3tools/s3cmd#1173]
Hi, I have searched this git repo, and https://s3tools.org/ website, but i can't get my hands on the GPG Public Key to use, to check signature of the downloaded distributions, e.g. of the `https://github.com/s3tools/s3cmd/releases/download/v${S3CMD_VERISON}/s3cmd-${S3CMD_VERISON}.zip` files.

Where Can I find this GPGP Public Key, to import oin my GPG Keyring  ?

**Comment by fviard** [comment]
Hi, you can get the gpg pub key from the gnupg official key server:
 gpg --recv-keys 241769189AC3D00B
(if you want to look for it, it is the one associated with my email florent at sodria dot com)
