### ISSUE TITLE
Problems with Debian repository (Debian Buster) - Struggling to install

### ISSUE THREAD

**Issue by jamesspittal** [s3tools/s3cmd#1176]
As per the docs in https://s3tools.org/repositories, I installed using:

`wget -O- -q http://s3tools.org/repo/deb-all/stable/s3tools.key | sudo apt-key add -`
`sudo wget -O/etc/apt/sources.list.d/s3tools.list http://s3tools.org/repo/deb-all/stable/s3tools.list`
`sudo apt-get update && sudo apt-get install s3cmd`

I get the following error:

```
W: GPG error: https://s3tools.org/repo/deb-all stable/ Release: Detached signature file '/var/lib/apt/lis                                                                                                                                    ts/partial/s3tools.org_repo_deb-all_stable_Release.gpg' is in unsupported binary format
E: The repository 'http://s3tools.org/repo/deb-all stable/ Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

I'm on `Debian GNU/Linux 10 (buster)`.

**Comment by jamesspittal** [comment]
Tried with `apt-get update --allow-insecure-repositories` and that didn't work either. I'll try install via `pip` instead.

**Comment by fviard** [comment]
Has said on top of this webpage, the custom debian repository is not maintained anymore.
So, please don't try to use it :-)
If possible, the best way to have the most up-to-date version is to get it with pip as you did.
