### ISSUE TITLE
pip fails to install development version of s3cmd due to invalid version string

### ISSUE THREAD

**Issue by salty-horse** [s3tools/s3cmd#1183]
When attempting to install s3cmd from git, this error appears:

```
$ pip install https://github.com/s3tools/s3cmd/archive/5834228d5bddde3819a3ae5506dd656b62dfb2d1.zip
[...]
  WARNING: Built wheel for s3cmd is invalid: Metadata 1.2 mandates PEP 440 version, but '2.1.0-' is not
```

This is due to a recent change in pip 20.3.4:
> `pip wheel` now verifies the built wheel contains valid metadata, and can be installed by a subsequent `pip install`. This can be disabled with `--no-verify`.

I believe it doesn't like the `+` in the current development version string `2.1.0+`. Please consider using a valid version number for development versions in the future.

See https://github.com/s3tools/s3cmd/issues/1182#issuecomment-819503832 for a workaround.

**Comment by fviard** [comment]
Thank you very much for the investigation as the problem was not obvious.
I have pushed a change to rename the dev version to 2.1.0-dev.
I hope that pip should now be happy.
Please let me know if you encounter another issue.

**Comment by salty-horse** [comment]
@fviard Nothing was pushed to `master` yet - the last commits are pushed in December. Am I missing anything?

**Comment by fviard** [comment]
You are right, sorry, i'm losing my head. It is rightly pushed now!
Thank you!

**Comment by salty-horse** [comment]
Thanks! I can confirm it fixes the `pip install` issue.
