### ISSUE TITLE
It's possible to remove "everything but" files?

### ISSUE THREAD

**Issue by AdrianoCahete** [s3tools/s3cmd#1186]
I, I'm new in all this S3 thing and have a bucket with some files per user, like:

```
user0001/gallery/file001.png
user0001/gallery/file002.png
user0001/gallery/file003.png
(...)
user0002/gallery/file001.png
user0002/gallery/file004.png
user0002/gallery/file8.png
```

I know that the "folder" thing is just a prefix, but with this library, it's possible to remove the older files when the gallery from each user reaches an X number (like 10, for example)? If yes, can you give me some direction?

As far I know, the default S3 lifecycle doesn't do that (or I'm wrong?)

**Comment by fviard** [comment]
No, it is not possible to do that with s3cmd.
And I'm not a specialist of S3 lifecycle, but I also don't think that a policy for your case exists

Your best solution would probably to do a script for that: listiing all the files per user, calculating files that have to be deleted, and issuing the delete command for these files.
