### ISSUE TITLE
Default length of `--restore-days` not documented

### ISSUE THREAD

**Issue by mlissner** [s3tools/s3cmd#1187]
A bunch of examples show how to restore from Glacier using the restore command like:

    s3cmd restore s3://some-bucket/

When these guides omit the `--restore-days` parameter, I assume one is being set by default, because it works, but the length of the restoration isn't documented in the help file. I tried searching the code too, but couldn't find it. It'd be great to get this documented.

**Comment by robd003** [comment]
@mlissner the default restore period is 1 day

**Comment by fviard** [comment]
Thanks @robd003 for the reply.

@mlissner I think that it is documented already for some time "Number of days to keep restored file available (only for 'restore' command). Default is 1 day.". Or am I mistaken?

**Comment by mlissner** [comment]
Guess I missed it or it got updated? Huh.

**Comment by ServaneC** [comment]
Hello, the default number of restore days is still not documented, why is that ? 
<img width="552" alt="image" src="https://github.com/s3tools/s3cmd/assets/51002863/c30170c0-8dfe-4128-afd5-10645ae3e8ee">

**Comment by robd003** [comment]
@ServaneC the default number of days for restoration documented in the man page here: https://github.com/robd003/s3cmd/blob/master/s3cmd.1#L286-L288

It's also shown in the help message as you posted above. https://github.com/robd003/s3cmd/blob/master/s3cmd#L3057

```
  -D NUM, --restore-days=NUM
                        Number of days to keep restored file available (only
                        for 'restore' command). Default is 1 day.
```

This has been in the code base since 2018, are you running an up to date version of s3cmd?

**Comment by ServaneC** [comment]
I was talking about the online documentation: https://s3tools.org/usage
