### ISSUE TITLE
s3cmd in chinese Windows can't process chinese character

### ISSUE THREAD

**Issue by chang-cancan** [s3tools/s3cmd#1191]
I use s3cmd-master in Windows Server 2016, install python 3.9.7 and some necessary packages, normal operate is fine, but if filename use chinese character, operate will fail, 

C:\s3cmd-master>python s3cmd put c:\test\test04\新文字文件.txt s3://across/cloud_folder/Test05/
ERROR: Parameter problem: Nothing to upload.

OR

local folder
2021/05/12  下午 05:25    <DIR>          test01
2021/05/12  下午 05:38    <DIR>          test02
2021/05/12  下午 05:25    <DIR>          test03
2021/05/12  下午 06:08    <DIR>          Test04
2021/05/12  下午 06:00    <DIR>          新增資料夾

use sync command
S3 folder
                          DIR  s3://ndc2-dns/test/test/Test04/
                          DIR  s3://ndc2-dns/test/test/test01/
                          DIR  s3://ndc2-dns/test/test/test02/
                          DIR  s3://ndc2-dns/test/test/test03/

chinese folder did not sync to S3 space

does s3cmd not support Chinese Windows? because same s3cmd-master in Linux work fine. or need extra setting?

thanks

**Comment by chang-cancan** [comment]
Sorry!
when I try to modify s3cmd.ini, change encoding = cp950 to utf-8, then seems work fine.

**Comment by fviard** [comment]
Good that you have found the solution.
