### ISSUE TITLE
S3cmd unexpected error

### ISSUE THREAD

**Issue by nirajvara** [s3tools/s3cmd#1192]
I have s3cmd 2.0.1 version and getting some issue to copy files to s3 bucket for few days. getting 503 slow down error but the server did not copy  files more than  3500/second.  and getting error like "An unexpected error has occurred". 

attaching screenshot of error for more clarity. Please guide to solve this error.
![s3_sync_error](https://user-images.githubusercontent.com/20708475/118086187-2e41a680-b3e1-11eb-9f44-0369f67da361.jpg)
![s3_sync_error1](https://user-images.githubusercontent.com/20708475/118086194-30a40080-b3e1-11eb-81fc-d53ac0909214.jpg)

**Comment by fviard** [comment]
Hi,
Can you give a try to the version in MASTER from gitlab? this should already be fixed normally.
