### ISSUE TITLE
Can s3cmd offer resumable upload file? 

### ISSUE THREAD

**Issue by beckhamaaa** [s3tools/s3cmd#1194]
Hi, i want to know that the s3cmd offer the resumable upload file, it is based the amazon s3 resumable upload protocol, and  i use s3cmd as a client, a minio server is a server ,thanks a lot!

**Comment by fviard** [comment]
Yes it can do that.

Please have a look at "--continue", "--continue-put" and "--upload-id" in the manual pages:
https://s3tools.org/usage
