### ISSUE TITLE
Support adding customer header to s3cmd mb

### ISSUE THREAD

**Issue by sebvajda** [s3tools/s3cmd#1197]
Using Cloudian Hyperstore S3 implementation we need to have the possibility to add custom header to the create bucket command.
This is needed as we have to pass a custom header `x-gmt-policyid` that would inform the Cloudian Hyperstore backend to create the new bucket using a non default storage policy. Storage policies in Cloudian Hyperstore are defining the resiliency level of the object in the bucket like the number of copies and which data centers the copies need to reside.

s3cmd does not complain about passing `--add-header` option to the `mb` command but it is silently ignored.

**Comment by fviard** [comment]
Should be fixed now in master with:
https://github.com/s3tools/s3cmd/pull/1198
