### ISSUE TITLE
Wrong URL in restore request XML namespace

### ISSUE THREAD

**Issue by akete** [s3tools/s3cmd#1203]
When using s3cmd with MinIO server (Version: 2021-08-05T22:01:19Z), restore object request results in `400 Bad Request error`:

 <pre>$ s3cmd --config s3cmd-local-minio.conf restore s3://bucket0/other/testFile
 ERROR: S3 error: 400 (MalformedXML): expected element <RestoreRequest> in name space http://s3.amazonaws.com/doc/2006-03-01/ but have http://s3.amazonaws.com/doc/2006-3-01</pre>

**Comment by fviard** [comment]
Merged in Master.
