### ISSUE TITLE
Problem: IOError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by sogreater** [s3tools/s3cmd#1209]
Invoked as: /usr/bin/s3cmd -c ./s3cfg.conf rm -r s3://test_bucket/test/
Problem: IOError: [Errno 11] Resource temporarily unavailable
S3cmd:   2.0.0
python:   2.6.6 (r266:84292, Aug 18 2016, 15:13:37) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
environment LANG=None

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2996, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2915, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 627, in cmd_object_del
    rc = subcmd_batch_del_iterative(uri_str = uri_str)
  File "/usr/bin/s3cmd", line 655, in subcmd_batch_del_iterative
    output('\n'.join(u"delete: '%s'" % uri.compose_uri(bucket, p['Key']) for p in to_delete))
  File "/usr/bin/s3cmd", line 66, in output
    sys.stdout.write(message + "\n")
  File "/usr/lib64/python2.6/codecs.py", line 352, in write
    self.stream.write(data)
IOError: [Errno 11] Resource temporarily unavailable

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by fviard** [comment]
Probably a local configuration issue? Maybe you need to set the language of your console, to something like en_US.utf8?

If you still have the issue, you  can try to update s3cmd to the last MASTER version, and update python.
Otherwise, if that does not resolve your issue, please reopen.
