### ISSUE TITLE
About s3cmd upload rate

### ISSUE THREAD

**Issue by Beau-Chen** [s3tools/s3cmd#1224]
Dear developers，

When I upload Minio through s3cmd, I find that the actual rate is inconsistent with the displayed rate. As shown below, "real" is the time actually perceived by the user, which is much greater than "user + sys".

S3cmd shows that the rate of uploading 1g files is 94MB / s, which is true if I calculate according to the time of "user + sys", but if I calculate according to the time actually perceived by the user of "real", the rate becomes more than 60 MB / s, which is too much difference.

Why is this? Is there any way to solve this difference so that my actual speed can reach more than 90 MB / S?

I’m looking forward to your reply. 🙏🙏🙏

Yours sincerely.

```
linux:~/cby # time s3cmd put 1g.txt s3://cby/16.txt
upload: '1g.txt' -> 's3://cby/16.txt'  [part 1 of 3, 500MB] [1 of 1]
 524288000 of 524288000   100% in    5s    96.16 MB/s  done
upload: '1g.txt' -> 's3://cby/16.txt'  [part 2 of 3, 500MB] [1 of 1]
 524288000 of 524288000   100% in    5s    94.57 MB/s  done
upload: '1g.txt' -> 's3://cby/16.txt'  [part 3 of 3, 24MB] [1 of 1]
 25165824 of 25165824   100% in    0s    41.01 MB/s  done

real	0m15.902s
user	0m10.129s
sys	0m0.991s
```

**Comment by fviard** [comment]
Hi,
I think that the reason for this discrepancy is that, the speed that you see in your output is just the "upload" speed of the file or its chunks.
But, in addition, and not accounted for, there are other operations running, like listing files in the bucket, or calculating the hash checksum of each chunk.

You can use the -v flag to see a little bit more details of what is going in on and to understand better where the extra time is spent.

**Comment by Beau-Chen** [comment]
Thank you for your reply :)
