### ISSUE TITLE
LifecycleConfiguration uses obsolete field Prefix

### ISSUE THREAD

**Issue by LadMartin** [s3tools/s3cmd#1247]
Calling
`s3cmd expire s3://bkt/ --expiry-days 1`
Produces
`<LifecycleConfiguration>  <Rule>    <Prefix></Prefix>    <Status>Enabled</Status>    <Expiration>    <Days>1</Days>    </Expiration>  </Rule></LifecycleConfiguration>`
Which uses obsolete field Rule/Prefix and it shall be replaced with Rule/Filter/Prefix
from [doc](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/put-bucket-lifecycle-configuration.html):
`Prefix identifying one or more objects to which the rule applies. This is no longer used; use Filter instead.`

AWS still support the obsolete version, but others may not. The AWS [examples](https://docs.aws.amazon.com/AmazonS3/latest/userguide/lifecycle-configuration-examples.html) only use the new version.

**Comment by fviard** [comment]
This is now fixed in MASTER, thank you for your detailed report!
