### ISSUE TITLE
The CORS config does not take effect

### ISSUE THREAD

**Issue by 277801235** [s3tools/s3cmd#1251]
```
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <AllowedHeader>*</AllowedHeader>
        <ExposeHeader>ETag</ExposeHeader>
    </CORSRule>
</CORSConfiguration>
```

![image](https://user-images.githubusercontent.com/17825710/163993217-df7ede61-5da2-4628-ab53-8c6bad2b410a.png)

I use the AWS SDK for JavaScript V3 on my browser

![image](https://user-images.githubusercontent.com/17825710/164130585-5ae5bd46-d9da-43b3-8ffb-b09f122f5d64.png)

**Comment by fviard** [comment]
I see that you use Ceph. Isn't it a problem with your Ceph instance/ server setup?

If you set allowed origin with an explicit domain name value, is the header given well by the server in case of request?

**Comment by fviard** [comment]
Also, I'm not expert of policies, but you need maybe to use lists for values like:
["*"]

**Comment by fviard** [comment]
Closed as I don't think it is not an issue on s3cmd side and no feedback, don't hesitate to reopen if this is relevant.
