### ISSUE TITLE
s3cmd can't support multi-language

### ISSUE THREAD

**Issue by lambertwang-cn-star** [s3tools/s3cmd#1252]
In linux OS, I have used the apache common to upload the file name like /work/ra/nég.mp4. The file name is used in Portuguese. 
The uploading code is like the below:
           map.put("file", file);
          commandline = new CommandLine("s3cmd");
          commandline.addArguments(S3CmdBuilder.putArgumentsHasBlank(cmdContext.getCmdRequest()), false);
          commandline.setSubstitutionMap(map);
          exec.execute(commandline, environment, handler);
I always get the following error: Access S3 fail. ERROR: Parameter problem: Nothing to upload.
Also I have configured the file .s3cfg and set the encoding to be UTF-8. But it's failed also.
I think it could be located to the linux locale set reason, also set the system locale to be en_US.utf8. But there is not any effect on it.
Could you pls help to give me any feedback for this issue? Thanks very much!

**Comment by fviard** [comment]
Hi, if you still have the problem, can you "dump" the command that your script generate? As a text so we can see what is wrong with it?

Otherwise, you can try to run s3cmd with the "-v" flag also, so you would have more logs including the command you are using.
