### ISSUE TITLE
Plans for the next release?

### ISSUE THREAD

**Issue by dougforster-at** [s3tools/s3cmd#1260]
Hi @fviard, firstly, thank you for your heroic work of maintaining this project. I was wondering: what are your plans for releasing the next version to pip? 

There are some great fixes since the release of 2.2.0 that we are eager to take advantage of!

**Comment by fviard** [comment]
There are a few issues and PR that I want to go over first, but it should come soon I hope.
Maybe in around 1 or 2 weeks.

**Comment by sbason** [comment]
Any news on this? We too are super eager to get those great new fixes :)

**Comment by fviard** [comment]
Released today with 2.3.0 :-)
