### ISSUE TITLE
NameError: global name 'formatDateTime' is not defined

### ISSUE THREAD

**Issue by GuaGuaTai** [s3tools/s3cmd#1262]
Invoked as: /usr/bin/s3cmd ls
Problem: NameError: global name 'formatDateTime' is not defined
S3cmd:   2.2.0
python:   2.6.6 (r266:84292, May  1 2012, 13:52:17) 
[GCC 4.4.6 20110731 (Red Hat 4.4.6-3)]
environment LANG=zh_CN.GB18030

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3121, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 3030, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 156, in cmd_ls
    subcmd_all_buckets_list(s3)
  File "/usr/bin/s3cmd", line 164, in subcmd_all_buckets_list
    output(u"%s  s3://%s" % (formatDateTime(bucket["CreationDate"]),
NameError: global name 'formatDateTime' is not defined

**Comment by fviard** [comment]
Hi, this error does not make sense to me, but you are using a very very old version of python that is unsupported (2.6).
Can you update to python 2.7 at least?
Otherwise, you could try to complete uninstall and reinstall s3cmd, or try to install the master version here.

**Comment by fviard** [comment]
Closing as no update, please don't hesitate to reopen if you are still encountering the issue and can get more details.
