### ISSUE TITLE
too many values to unpack

### ISSUE THREAD

**Issue by alyabievgy** [s3tools/s3cmd#1265]
Trying to sync backups from remote S3 to lockal host with cron job and catch error:

Invoked as: /usr/bin/s3cmd --config=/root/.s3cfg --delete-removed --check-md5 --human-readable-sizes --no-check-certificate --no-progress --quiet sync s3://backup/couchbase /data/backup_from_bucket
Problem: <class 'ValueError: too many values to unpack (expected 3)
S3cmd:   2.2.0
python:   3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3092, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 3001, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1887, in cmd_sync
    return cmd_sync_remote2local(args)
  File "/usr/bin/s3cmd", line 1480, in cmd_sync_remote2local
    n_copies, size_copies, failed_copy_list = local_copy(copy_pairs, destination_base)
  File "/usr/bin/s3cmd", line 1519, in local_copy
    for (src_obj, dst1, relative_file) in copy_pairs:
ValueError: too many values to unpack (expected 3)

**Comment by fviard** [comment]
Your issue looks curious, is it still reproducible for you?
If yes, could you run your command with the additional "-d" flag to have more details? thanks

**Comment by alyabievgy** [comment]
DEBUG: CHECK: couchbase/logs/stats/net/5cc35b3e-82ff-4459-9409-fcf7089ccc1b-backup-1663106423
DEBUG: IGNR: couchbase/logs/stats/net/5cc35b3e-82ff-4459-9409-fcf7089ccc1b-backup-1663106423 (transfer not needed)
DEBUG: CHECK: couchbase/logs/stats/net/5cc35b3e-82ff-4459-9409-fcf7089ccc1b-backup-1663192890
DEBUG: IGNR: couchbase/logs/stats/net/5cc35b3e-82ff-4459-9409-fcf7089ccc1b-backup-1663192890 (transfer not needed)
INFO: Summary: 0 remote files to download, 8332 local files to delete, 101 local files to hardlink

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/bin/s3cmd --delete-removed --check-md5 --no-check-certificate --quiet -d sync s3://akson-backup/couchbase /data/backup_from_bucket
Problem: <class 'ValueError: too many values to unpack (expected 3)
S3cmd:   2.2.0
python:   3.8.10 (default, Jun 22 2022, 20:18:18)
[GCC 9.4.0]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 3092, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 3001, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1887, in cmd_sync
    return cmd_sync_remote2local(args)
  File "/usr/bin/s3cmd", line 1480, in cmd_sync_remote2local
    n_copies, size_copies, failed_copy_list = local_copy(copy_pairs, destination_base)
  File "/usr/bin/s3cmd", line 1519, in local_copy
    for (src_obj, dst1, relative_file) in copy_pairs:
ValueError: too many values to unpack (expected 3)

**Comment by fviard** [comment]
It took me some time to realize, but I think that you have a mixup of versions of s3cmd on your system.
The line in localy_copy should be like that:
`for (src_obj, dst1, relative_file, md5) in copy_pairs:`

And here you have a previous versions that use only 3 arguments in the tuple.

Please check your setup.
- There is one "s3cmd" file in /usr/bin  (that is probably from an older version in your case)
- Library components are in a folder like: /usr/lib/python3/site-packages/S3 (that is probably of a recent version)
