### ISSUE TITLE
What do s3cmd configuration parameters mean

### ISSUE THREAD

**Issue by fantastic2085** [s3tools/s3cmd#1267]
I execute the command(s3cmd --configure), which returns the required configuration parameters what are the meaning, where can I query?

**Comment by fviard** [comment]
There is a readme here:
https://github.com/s3tools/s3cmd/blob/master/README.md

You can also call "s3cmd --help" to have the help about commands and command line arguments.  
Most configs or the configuration file have an equivalent cmdline argument, so you should be able to see what they do.

If some configuration are not explicit, and you don't know what they do, you should probably not use them anyway.

If you use a S3 compatible service different than aws, usually there is documentation somewhere on how to do the configuration to use it.
