### ISSUE TITLE
S3cmd cannot connect to Ceph Ingress

### ISSUE THREAD

**Issue by fantastic2085** [s3tools/s3cmd#1268]
**ceph16.2.7**
![f6232ba6e117094c7f9b6d86fe3c568](https://user-images.githubusercontent.com/4116773/179942427-b762e43f-f22f-4787-9e80-15ae687f0f91.jpg)
![image](https://user-images.githubusercontent.com/4116773/179943213-c4aabce7-e259-45dc-b111-b87e3fb2aa96.png)

**Error message:**
![image](https://user-images.githubusercontent.com/4116773/179943654-335fa9d8-b68a-4993-ac7b-38326ece6faf.png)

s3cmd version
![image](https://user-images.githubusercontent.com/4116773/179943799-c134f4b9-0880-4754-a6d0-29d15400800d.png)

**.s3cfg:**
[default]
access_key = K5JV7S9QMYHN121JBF5P
access_token = 
add_encoding_exts = 
add_headers = 
bucket_location = US
ca_certs_file = 
cache_file = 
check_ssl_certificate = True
check_ssl_hostname = True
cloudfront_host = 10.119.104.222:9443
content_disposition = 
content_type = 
default_mime_type = binary/octet-stream
delay_updates = False
delete_after = False
delete_after_fetch = False
delete_removed = False
dry_run = False
enable_multipart = True
encoding = UTF-8
encrypt = False
expiry_date = 
expiry_days = 
expiry_prefix = 
follow_symlinks = False
force = False
get_continue = False
gpg_command = /usr/bin/gpg
gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_passphrase = 
guess_mime_type = True
host_base = 10.119.104.222:9443
host_bucket = 10.119.104.222:9443/%(bucket)
human_readable_sizes = False
invalidate_default_index_on_cf = False
invalidate_default_index_root_on_cf = True
invalidate_on_cf = False
kms_key = 
limit = -1
limitrate = 0
list_md5 = False
log_target_prefix = 
long_listing = False
max_delete = -1
mime_type = 
multipart_chunk_size_mb = 15
multipart_max_chunks = 10000
preserve_attrs = True
progress_meter = True
proxy_host = 
proxy_port = 0
put_continue = False
recursive = False
recv_chunk = 65536
reduced_redundancy = False
requester_pays = False
restore_days = 1
restore_priority = Standard
secret_key = USn0cSiDC2D8VOhMxXcrnsaINxH7y1yNHlpBj3z2
send_chunk = 65536
server_side_encryption = False
signature_v2 = False
signurl_use_https = False
simpledb_host = 10.119.104.222:9443
skip_existing = False
socket_timeout = 300
stats = False
stop_on_error = False
storage_class = 
throttle_max = 100
upload_id = 
urlencoding_mode = normal
use_http_expect = False
use_https = False
use_mime_magic = True
verbosity = WARNING
website_endpoint = http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
website_error = 
website_index = index.html

**Comment by fviard** [comment]
I think that you have an issue of configuration of your ceph env or you s3cmd settings.
But s3cmd does not have an issue in itself, so i'm closing this but don't hesitate to reopen if you find a real problem.

In your specific case, looking at your config, I think that you might have a typo with your host_bucket:
host_bucket = 10.119.104.222:9443/%(bucket)

There is a "s" that is lacking at the end. Template variables are like "%(...)s".
So you should have:
host_bucket = 10.119.104.222:9443/%(bucket)**s**
