### ISSUE TITLE
Signature v2 issue 

### ISSUE THREAD

**Issue by ppapryczka** [s3tools/s3cmd#1275]
Hi,
I create application which provide S3 interface and I find some differences between s3cmd and aws-cli in representation of canonical string in signature. Examples:

s3cmd:
`GET\n\n\n\nx-amz-date:Tue, 30 Aug 2022 07:54:50 +0000\n/bucket/`

aws-cli:
`GET\nlocalhost:5000\n/bucket\nAWSAccessKeyId=<access_key>&SignatureMethod=HmacSHA256&SignatureVersion=2&Timestamp=2022-08-30T07%3A21%3A32Z`

What is more s3cmd provide access key in headers not in request params. Here I find some information about canonical string in amazon docs: https://docs.aws.amazon.com/general/latest/gr/signature-version-2.html and s3cmd canonical string seems to not follow these concepts.

Function that create canonical string for s3cmd request can be found here: https://github.com/s3tools/s3cmd/blob/d79246c2fe8d48aa876e87809e1f02c46178ebdd/S3/Crypto.py#L96

My question is why s3cmd uses this representation of canonical string? Can I use some configuration options in s3cmd config to create aws-cli like canonical string and access key in headers?

Sorry if I misunderstand some concepts and I know that aws-cli is not s3cmd, but I wonder why this differences occur. 

Greetings, 
Patryk

**Comment by fviard** [comment]
@ppapryczka Good question, in fact, the page you are referencing does looks to be how the signature v2 should be for aws api but not for S3.
For s3, and signature v2, you can find the documentation here:
https://docs.aws.amazon.com/AmazonS3/latest/userguide/RESTAuthentication.html

That matches s3cmd implementation.

Why there are 2 versions of signature v3 with aws apis, I have no idea...

**Comment by fviard** [comment]
But, to be noted, if you create anything nowadays, you should only look at signature version 4.
v2 is deprecated for a very long time and support for it might be removed any day in the future.

**Comment by ppapryczka** [comment]
Thanks for you answer :) I managed to find that for example boto3 uses three versions of signature - v2(the one which I present), s3(which is the same as the one calculated in s3cmd) and v4. It is a bit strange :)

Greetings, 
Patryk
