### ISSUE TITLE
What's the 's' in %(bucket)s.host.x.y for?

### ISSUE THREAD

**Issue by boaks** [s3tools/s3cmd#1328]
I'm wondering, what the 's' in

"%(bucket)s.s3.amazonaws.com" is for? 

e.g.: bucket = data

does this result in:

"datas.s3.amazonaws.com"

or 

"data.s3.amazonaws.com"

**Comment by fviard** [comment]
"%(XXXX)s" is like "%s" but with a named parameter.

So, in your example, the result will be:
"data.s3.amazonaws.com"

See:
https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting

**Comment by boaks** [comment]
Thanks a lot!
For "no-python" people it's not that obvious.
