### ISSUE TITLE
Support for TLS 1.2 +

### ISSUE THREAD

**Issue by activaireadmin** [s3tools/s3cmd#1338]
AWS is no longer supporting TLS 1.0 and TLS 1.1.  How can I update the TLS version on this library?

Ref: https://aws.amazon.com/blogs/security/tls-1-2-required-for-aws-endpoints/

**Comment by activaireadmin** [comment]
Never mind, after looking at the source code I found that its related to Python 2.7 and its SSL dependencies.
Temporarily disabling the HTTPS to transfer non sensitive data did the trick. :)

**Comment by fviard** [comment]
Ok, good to know!
