### ISSUE TITLE
recursive restore fails on first error

### ISSUE THREAD

**Issue by lavigne958** [s3tools/s3cmd#1369]
## Overview

When using the command `s3cmd restore --recursive s3://my-bucket` if an object is not in GLACIER storage class then the whole command fails.

## Details

When restoring object from GLACIER storage class, we can use the `--recursive` to trigger all objects in this bucket.

**What is expected:** When listing the objects in the bucket, when we have mixed objects in the bucket, it is expected to restore all objects in GLACIER and simply skip objects that are already in the right storage class or even failing requests are expected to just keep going sending requests on the rest of the object in the bucket.

I noticed you offer an option to stop on the first error. this should be added and if not set the loop should keep going.

I have a proposal that I could share and open a PR, let me know if you´d rather do it yourself or let me do it.

**Comment by fviard** [comment]
Sorry for the long delay to give you a reply.
Obviously I would appreciate a lot a PR to resolve this issue.

If I'm not wrong, it would make sense to skip files that are already in the right storage without considering that as an error.

**Comment by lavigne958** [comment]
> Sorry for the long delay to give you a reply. Obviously I would appreciate a lot a PR to resolve this issue.

No problem, I'll open a PR with a proposal for a fix.

> 
> If I'm not wrong, it would make sense to skip files that are already in the right storage without considering that as an error.

It would make sense to me too, that's how I expected the tool to work, and that's when I was surprised to see that's it fails fast.

The way I see this issue:
- if the storage class is already the right one -> nothing to do just keep iterating on the next object
- if the request ends in error `RestoreAlreadyInProgress` -> nothing to do just keep iterating on the next object
- if the request ends in error:
  - if the flag `cfg.stop_on_error` is set to True -> stop here with an error
  - if the flag `cfg.stop_on_error` is set to False -> notify the error AND keep iterating on the next object

Would that make sense ?

It does change the behavior, thought I see it as an improvement and not a breaking change. it will ensure command completion whereas before the command could fail and never complete the whole bucket.
