### ISSUE TITLE
abandoned project ? 

### ISSUE THREAD

**Issue by lavigne958** [s3tools/s3cmd#1373]
Hi I am wondering if this project has been abandoned ? 

if so then there is no point trying to bring up issue and fixes etc.

**Comment by fviard** [comment]
Hi @lavigne958 ,

No this project is not abandoned as you can see it is moving even if at slow speed.
Currently, the work on s3cmd is entirely voluntary work and so sadly the support provided is based on best effort.

I'm sorry if it took time to reply to your previous issue, but all help like issues, fixes, support is highly appreciated.

When looking at PR, sometimes we can have the feeling that some fixes are trivial, and should be merged fast, but most of the time they are not that easy if we don't want to break retrocompatibility and existing users on all platforms.
And that takes a lot of time sadly.

**Comment by lavigne958** [comment]
> Hi @lavigne958 ,
> 
> No this project is not abandoned as you can see it is moving even if at slow speed. Currently, the work on s3cmd is entirely voluntary work and so sadly the support provided is based on best effort.
> 
> I'm sorry if it took time to reply to your previous issue, but all help like issues, fixes, support is highly appreciated.
> 
> When looking at PR, sometimes we can have the feeling that some fixes are trivial, and should be merged fast, but most of the time they are not that easy if we don't want to break retrocompatibility and existing users on all platforms. And that takes a lot of time sadly.

Hi I see, I understand , it's time consuming. What you need is more maintainers or some users with some time to spare to help around I suppose ? cleaning some issues, reviewing PRs etc.

I understand breaking changes are the worst and you have a lot of active users handling potentially sensible data.

Let me know If I can help in any way.

**Comment by fviard** [comment]
Exactly ^^
Feel free to get more involved as you see fit.
