### ISSUE TITLE
Using host_bucket is poorly documented

### ISSUE THREAD

**Issue by Downchuck** [s3tools/s3cmd#149]
When trying to debug radosgw running on localhost, I ran into host_base and host_bucket several times and hit some frustrating issues. When host_bucket is not defined, host_base and host_bucket may hit completely different servers. Further, I've not figured out how to get old storage behavior (http://host/bucket) over the current http://bucket.host/ behavior.

**Comment by matt-murdock** [comment]
Is it possible to pass the host_base or host_bucket as a command line option for the sync call? Similar to --access_key and --secret_key

**Comment by fviard** [comment]
@matt-murdock the question is not related to this issue, but yes, here are the options:
  --host=HOSTNAME       HOSTNAME:PORT for S3 endpoint (default:
                        s3.amazonaws.com, alternatives such as s3-eu-
                        west-1.amazonaws.com). You should also set --host-
                        bucket.
  --host-bucket=HOST_BUCKET
                        DNS-style bucket+hostname:port template for accessing
                        a bucket (default: %(bucket)s.s3.amazonaws.com)
