### ISSUE TITLE
Support --access_key and --access_secret as arguments in s3cmb sync

### ISSUE THREAD

**Issue by stevepeak** [s3tools/s3cmd#165]
Nice to do the following `s3cmd sync folder/ s3://my-bucket --access_key $S3_KEY --secret_key $S3_SECRET`

**Comment by fviard** [comment]
Closing obsolete ticket because it is already resolved:
  --access_key=ACCESS_KEY
                        AWS Access Key
  --secret_key=SECRET_KEY
                        AWS Secret Key

NOTE: It is not recommended to provide the secret key like that as it could be exposed publically with any ps as command line arguments of running process are system wide public on linux.
