### ISSUE TITLE
IAM roles not working under Linux cron

### ISSUE THREAD

**Issue by smillerk2** [s3tools/s3cmd#173]
I'm using 1.5.0-alpha3 to take advantage of EC2 IAM roles because this removes the need for a physical *.s3cfg file on the Linux machine. I can successfully run "s3cmd ls" and the buckets are retrieved. However, when running the same shell script, under the ec2-user crontab, it would appear that IAM roles are ignored and the application looks for a config file:

ERROR: /home/ec2-user/.s3cfg: None
ERROR: Configuration file not available.
ERROR: Consider using --configure parameter to create one.

How can this be avoided? I need to have this working in unattended cron mode without a *.s3cfg file. 

I believe this issue is identical to https://github.com/s3tools/s3cmd/issues/180

**Comment by penfold45** [comment]
+1

**Comment by smillerk2** [comment]
@penfold45 please look at issue #180 for a work around for this specific version. I do believe this issue is fixed in a later version of s3cmd.
