### ISSUE TITLE
ValueError related to the format string

### ISSUE THREAD

**Issue by mdomsch** [s3tools/s3cmd#181]
Content-Type: multipart/mixed; boundary="========GMX69531370228045584144"
Date: Mon, 03 Jun 2013 04:54:05 +0200
From: "Isaac" ratel@gmx.co.uk
To: s3tools-bugs@lists.sourceforge.net
Subject: [S3tools-bugs] Patch for Config.py:197 ValueError

--========GMX69531370228045584144
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 8bit

Hi,

On running s3cmd without arguments, I got a ValueError related to the format string. This was most likely because I had a '%' character in my password in the configuration file. Anyway, I have attached a patch to fix it and I have also pasted it here: http://codepad.org/nsinMJmz just in case attachments are stripped.

$ s3cmd 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please report the following lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Problem: ValueError: incomplete format
S3cmd:   1.5.0-alpha1

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 2037, in <module>
    main()
  File "/usr/local/bin/s3cmd", line 1813, in main
    cfg = Config(options.config)
  File "/usr/local/lib/python2.7/dist-packages/S3/Config.py", line 106, in **init**
    self.read_config_file(configfile)
  File "/usr/local/lib/python2.7/dist-packages/S3/Config.py", line 123, in read_config_file
    cp = ConfigParser(configfile)
  File "/usr/local/lib/python2.7/dist-packages/S3/Config.py", line 169, in **init**
    self.parse_file(file, sections)
  File "/usr/local/lib/python2.7/dist-packages/S3/Config.py", line 197, in parse_file
    print_value = (data["value"][:2]+"...%d chars..."+data["value"][-1:]) % (len(data["value"]) - 3)
ValueError: incomplete format

$ python -V
Python 2.7.3
$ uname -a
Linux <hostname> 3.2.0-4-amd64 #1 SMP Debian 3.2.41-2 x86_64 GNU/Linux
## 

Isaac

--========GMX69531370228045584144
Content-Type: text/x-diff; charset="utf-8"; name="Config.py.patch"
Content-Transfer-Encoding: 8bit
Content-Disposition: attachment; filename="Config.py.patch"
Content-Description: Attachment: Config.py.patch

--- Config.py.orig  2013-06-03 03:19:40.076173303 +0100
+++ Config.py   2013-06-03 03:42:23.751029589 +0100
@@ -194,7 +194,9 @@ class ConfigParser(object):
                     data["value"] = data["value"][1:-1]
                 self.**setitem**(data["key"], data["value"])
                 if data["key"] in ("access_key", "secret_key", "gpg_passphrase"):
-                    print_value = (data["value"][:2]+"...%d_chars..."+data["value"][-1:]) % (len(data["value"]) - 3)
-                    print_value = "%s...%d chars...%s" % (data["value"][:2],\
-                                len(data["value"])-3,\
-                             data["value"][-1:])
               else:
                   print_value = data["value"]
               debug("ConfigParser: %s->%s" % (data["key"], print_value))

--========GMX69531370228045584144
Content-Type: text/plain; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit
Content-Disposition: inline

**Comment by fviard** [comment]
Closing old ticket.
Issue already resolved in last versions.
