### ISSUE TITLE
MIME type detection does not work with python-magic (Ubuntu 13.10)

### ISSUE THREAD

**Issue by e-t-u** [s3tools/s3cmd#198]
s3cmd does not work with Ubuntu 13.10 python-magic. I assume that the problem is also in other systems but I have not tried.

The MIME type of uploaded files is random. None of my CSS files gets the right MIME type, big part of HTML files gets also wrong MIME type. Typical wrong HTML MIME is text/x-c++ ja CSS gets MIME text/x-asm or text/troff.

This is naturally a showstopper when uploading large web servers.

As a workaround, if you remove package python-magic, s3cmd falls back to simple detection that seems to work.

**Comment by traviscollins** [comment]
Use the --no-mime-magic option, and s3cmd will not use python-magic to guess a mime type.

**Comment by jamiesonbecker** [comment]
good advice @traviscollins. @mpybkk indicated that this problem seems to persist even with --no-mime-magic set. Maybe just getting import'ed is causing side effects.

**Comment by traviscollins** [comment]
I'm using a Centos 6.6 machine to recursively deploy files from a Jenkins build output to S3 using s3cmd. Without --no-mime-magic, a .css file was being set as text/x-c++. I confirmed the detection using python-magic (simple python script to dump value) and then learned that python-magic is just a wrapper for libmagic, which is exposed through the unix file command. I found that  file -i style.css was the culprit (it returns text/x-css++ for one very long css file, and text/plain for another). 

When use the --no-mime-magic -M flags together, the S3 file is set with the correct text/css mime-type.

**Comment by jamiesonbecker** [comment]
-M, --guess-mime-type, is not available in older versions of s3cmd. There might be some interactions due to recent changes to s3cmd. Perhaps @e-t-u (or @gf3/@mpybkk) can confirm if it's still a problem w/ pip installed s3cmd.

**Comment by monikabhadauria** [comment]
I am also facing this issue as @mpybkk , when I use --no-mime-magic and -M together , it overrides sthe mime type to "binary/octet-stream" for all files except jss and css.

**Comment by gf3** [comment]
@monikabhadauria i've switched to manually setting the mime-type for files. there was a bug related to that, [but it's fixed now](https://github.com/s3tools/s3cmd/issues/401).

**Comment by jamiesonbecker** [comment]
@monikabhadauria @gf3 That seems like it might be a slightly different issue. There's an upstream bug report for libmagic referenced above - please run the tests in that bug report and mention if you see the same behavior.

**Comment by sebcl** [comment]
I'm having this issue too, and haven't been able to solve it with any command suggested here. Also using Ubuntu on AWS. Of 2 CSS files, one gets text/css and the other, text/plain. It's a pain since Chrome doesn't rneder CSS with wrong mime type.

**Comment by idmontie** [comment]
Decided to try to install python-magic on my Docker image so that I would stop getting the warning from s3cmd, but it just marked most of my CSS, HTML, and JS files as plain/text.
