### ISSUE TITLE
Update PyPI to include support for --access-key and --secret-key flags

### ISSUE THREAD

**Issue by sjhitchner** [s3tools/s3cmd#201]
It appears the current version of s3cmd in GitHub has added support to specify the access-key and secret-key using command-line parameters. This enables s3cmd to use the env variables that EC2 automatically setup (although it would be even better if s3cmd read the env variables directly)

Can the version of s3cmd in PyPi be updated to support these flags.  Makes installation much easier on EC2 hosts.

**Comment by fviard** [comment]
Closing obsolete issue.
