### ISSUE TITLE
How to restrict number of files returning by ls command in recursive mode?

### ISSUE THREAD

**Issue by vpoluyaktov** [s3tools/s3cmd#209]
Is any way to restrict number of files returning by ls command? When you list a bucket with --recursive flag ls  command can return billions of files and the command takes minutes for completion or crashes by timeout. I need only 100 first files from the list so having some command line switch to restrict number of files will be very useful.

**Comment by fviard** [comment]
Closing old ticket.
Issue already resolved in current version with option "--limit".
