### ISSUE TITLE
Error when uploading a very large file

### ISSUE THREAD

**Issue by zhm** [s3tools/s3cmd#224]
When trying to upload a 23GB file, I'm getting this error:

```
ERROR: S3 error: 403 (SignatureDoesNotMatch): The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

Here is the command I'm running:

```
s3cmd -c s3cfg-production --add-header='Content-Type: application/zip' --add-header='Content-Disposition: attachment; filename=Export_31717787-a28c-41d6-85de-c255a867b1ff.zip;' put /apps/exports/10807/10807.zip s3://bucketname/exports/31717787-a28c-41d6-85de-c255a867b1ff.zip
```

**Comment by fviard** [comment]
A lot of changed since the v1.5.0 so closing this issue as it is probably obsolete.
Please reopen if you are still encountering it with the last version.

btw, now there are the option --content-type and --content-disposition to be used instead of manually setting headers.
