### ISSUE TITLE
ERROR UPLOADING. NO 32

### ISSUE THREAD

**Issue by jshorwitz** [s3tools/s3cmd#226]
WARNING: Upload failed: /2013-09-01-00.gz ([Errno 104] Connection reset by peer)
WARNING: Retrying on lower speed (throttle=0.01)
WARNING: Waiting 6 sec...
ERROR: Upload of '/media/newdrive/2013-09-01-00.gz' failed too many times. Skipping that file.

**Comment by havramar** [comment]
Had the same issue with ~14MB file. 

Running s3cmd with `--multipart-chunk-size-mb=5` helped.

I'm using s3cmd 1.6.0

**Comment by prurigro** [comment]
Setting mutlipart-chunk-size-mb=5 fixes uploads of files larger than 5mb, but files smaller than 5mb will fail a bunch of times before the upload succeeds, and they upload twice for some reason when they do work
