### ISSUE TITLE
"content-md5" custom headers not working in "put" operation using 1.5a3

### ISSUE THREAD

**Issue by torstenrohlfing** [s3tools/s3cmd#263]
Upgrading s3cmd from 1.10 to 1.5a3, custom headers are no longer working. This has been previously observed for "cp" and "rsync" operations and server-side encryption headers, but the same problem seems to affect also "put" operations and, for example, "content-md5" header field.

The following works fine with 1.1.0, but gives a checksum mismatch error for 1.5a3:

s3cmd --add-header="content-md5: ${md5}" put source s3://bucket/dest

where "md5" is the properly encoded MD5 checksum for file "source" (I know it's correct because for 1.1.0 the put operation succeeds).

I suspect there is some request that's sent to the server prior to the actual "put" that also gets the MD5 checksum included, but of course for that request the checksum isn't a match?

Cheers!

**Comment by rouge8** [comment]
@mdomsch This still fails for me, and it doesn't look like s3cmd 1.5.2 sets the `Content-MD5` header for multipart uploads. I'm also unable to add the header with

```
s3cmd modify --add-header="content-md5: ${MD5SUM}" s3://bucket/path
```

**Comment by mdomsch** [comment]
We don't set Content-MD5 for anything.  With the new signature-v4 method,
it's redundant anyhow, as we send a SHA256 of each chunk with the PUT
request.

Please describe your failure not doing --add-header.

**Comment by rouge8** [comment]
Right, but I was hoping to set it myself, since some of our tools expect to be able to compare the MD5 when downloading. The `s3cmd modify` command above doesn't add the header, although it outputs `File s3://bucket/path modified`.

**Comment by rouge8** [comment]
I misunderstood the purpose of the `Content-MD5` header, never mind.
