### ISSUE TITLE
s3cmd (1.5.0-beta1) on Windows and full file path with drive letter when uploading a file. 

### ISSUE THREAD

**Issue by wmiadmin** [s3tools/s3cmd#269]
Hello!
I tried to use s3cmd (1.5.0-beta1) in Windows based on [this installation instruction.](http://beingshivdatta.blogspot.com/2013/10/aws-s3-s3cmd-tool-setup-on-windows.html)

> python s3cmd -v --no-progress put D:\Backup\DB_20140106.7z s3://bucket/backup/

As a result s3cmd create the following folders in destination bucket:
s3://bucket/backup/D:
s3://bucket/backup/D:/Backup
s3://bucket/backup/D:/Backup/DB_20140106.7z

> Windows 2003 x64
> python-2.7.6.amd64.msi
> s3cmd-1.5.0-beta1

On Ubuntu full file path doesn't added. Maybe I missed something on Windows ?

Thank you!

**Comment by fviard** [comment]
I think that it should be fixed now. Please reopen if you are still able to reproduce the issue with the last master.
