### ISSUE TITLE
s3cmd upload via stdin not working

### ISSUE THREAD

**Issue by freerobby** [s3tools/s3cmd#270]
We're unable to get uploads working through stdin. Here is my test; please advise:

```
$ cd /tmp
$ echo "hello" | /tmp/s3cmd-1.5.0-alpha1/s3cmd -c /etc/mysql_s3_backup_tool/.s3cfg put - s3://my-bucket/folder/hello.txt --verbose
INFO: Compiling list of local files...
INFO: Applying --exclude/--include
INFO: Summary: 0 local files to upload

```

**Comment by atramos** [comment]
Not working for me... Am I doing something wrong?

root@ctcdev:~/root.bin/db-tools# echo test | s3cmd put - s3://ctc.dev/test --verbose
INFO: Compiling list of local files...
INFO: Applying --exclude/--include
INFO: Summary: 0 local files to upload
root@ctcdev:~/root.bin/db-tools# s3cmd --version
s3cmd version 1.1.0-beta3

**Comment by mdomsch** [comment]
You need version 1.5.2 or newer upstream github.com/s3tools/s3cmd master
branch.
