### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'getchildren'

### ISSUE THREAD

**Issue by mdomsch** [s3tools/s3cmd#281]
From: Todd Kirby toddkirby@gmail.com
To: s3tools-bugs@lists.sourceforge.net

First off, thank you for s3cmd.  It's amazing.
I'm using the latest git as of Feb 13th 2014 @ ~10:00
I'm using Python 2.7.2rc1 on an older Redhat EL5.3 box.
Is there anything else I can pass to the command line to get more detail
about where it's blowing up?  Thanks for the help.

Todd Kirby
# my command

/usr/local/bin/python2.7 /usr/local/bin/s3cmd -v --delete-removed
--progress sync /syscon/ s3://syscon/syscon_lnx/

INFO: Compiling list of local files...
INFO: Retrieving list of remote files for s3://syscon/syscon_lnx/ ...
INFO: Found 87608 local files, 193526 remote files
INFO: Applying --exclude/--include
INFO: Applying --exclude/--include
INFO: Verifying attributes...
INFO: Summary: 15 local files to upload, 0 files to remote copy, 105918
remote files to delete

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd -v --delete-removed --progress /syscon/
s3://syscon/syscon_lnx/Problem: AttributeError: 'NoneType' object has no
attribute 'getchildren'
S3cmd:   1.5.0-beta1
python:   2.7.2rc1 (default, Jun  3 2011, 11:35:22)
[GCC 4.1.2 20080704 (Red Hat 4.1.2-44)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 2344, in <module>
    main()
  File "/usr/local/bin/s3cmd", line 2266, in main
    cmd_func(args)
  File "/usr/local/bin/s3cmd", line 1346, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/usr/local/bin/s3cmd", line 1330, in cmd_sync_local2remote
    destination_base_uri = _single_process(local_list)
  File "/usr/local/bin/s3cmd", line 1138, in _single_process
    _child(destination_base, local_list)
  File "/usr/local/bin/s3cmd", line 1266, in _child
    _do_deletes(s3, remote_list)
  File "/usr/local/bin/s3cmd", line 1128, in _do_deletes
    s3.object_delete(uri)
  File "/usr/local/lib/python2.7/site-packages/S3/S3.py", line 491, in
object_delete
    response = self.send_request(request)
  File "/usr/local/lib/python2.7/site-packages/S3/S3.py", line 774, in
send_request
    raise S3Error(response)
  File "/usr/local/lib/python2.7/site-packages/S3/Exceptions.py", line 52,
in __init__
    for child in error_node.getchildren():
AttributeError: 'NoneType' object has no attribute 'getchildren'

**Comment by fviard** [comment]
This issue can be closed, it should already be fixed with:
https://github.com/s3tools/s3cmd/commit/a281515afbe042412ff654c8ca356865c60ddd7e
and then:
https://github.com/s3tools/s3cmd/commit/dd1f7fb8d1747c06399236db48b8b50c7275a8f8
