### ISSUE TITLE
s3cmd sync --preserve s3 -> local doesn't "preserve"

### ISSUE THREAD

**Issue by TTimo** [s3tools/s3cmd#290]
s3cmd 1.5.0-alpha3 on OSX, when I run s3cmd sync from S3 to a local repository, creation/modification times are set to the current time and not preserved.

Another user has identified this problem here also:
http://stackoverflow.com/questions/21104332/s3cmd-put-preserve-flag-does-not-preserve-file-creation-modified-date-when-cop

**Comment by rstacruz** [comment]
hey i'm not sure if this is the place to ask, but I'm running into the issue where a file I'm uploading via `s3cmd --sync` doesn't have the correct `Last-Modified` header.

Here's my local file, showing `Apr 9` as the date:

```
• stat path/file.js
16777220 26293685 -rw-r--r-- 1 rsc staff 0 37842 "Apr  9 19:00:54 2015" "Apr  9 18:13:27 2015" "Apr  9 18:13:27 2015" "Feb 16 20:05:32 2015" 4096 80 0 path/file.js
```

I'll delete it remotely:

```
• s3cmd rm s3://abc-cdn/path/file.js
File s3://abc-cdn/path/file.js deleted
```

Then use `s3cmd sync` to upload it:

```
• s3cmd sync --cf-invalidate --acl-public --preserve --recursive ./path s3://abc-cdn/
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
./path/file.js -> s3://abc-cdn/path/file.js  [1 of 1]
 37842 of 37842   100% in    1s    24.58 kB/s  done
Done. Uploaded 37842 bytes in 3.1 seconds, 12.08 kB/s. Copied 2 files saving 75684 bytes transfer.
Created invalidation request for 1 paths
Check progress with: s3cmd cfinvalinfo cf://xyz/abc
```

Then fetch it via cloudfront, notice the date says `13 Mar 2015`:

```
• http GET "http://cdn.abc.xyz/path/file.js" --print=h
HTTP/1.1 200 OK
Date: Mon, 30 Mar 2015 06:26:24 GMT
Last-Modified: Fri, 13 Mar 2015 10:55:38 GMT
x-amz-meta-s3cmd-attrs: uid:501/gname:staff/uname:rsc/gid:20/mode:33188/mtime:1426244119/atime:1426244124/ctime:1426244119
```

**Comment by mdomsch** [comment]
Amazon S3 itself sets the "Last-Modified" header to match the upload time,
not the file's stat() time.  I know of no way to set this otherwise.

s3cmd does record the stat() times in x-amz-meta-s3cmd-attrs, and on [get]
or [sync] download, will update the resulting file on disk with the time
from that header, or if not present, with the Last-Modified header time.

**Comment by rstacruz** [comment]
@mdomsch I think I got it: `s3cmd ls` reports the correct time so I think this must be a cf invalidation issue (#525).

**Comment by mssmmx** [comment]
$ s3cmd --version
s3cmd version 2.0.1
I am wondering if using (s3cmd sync --preserve --recursive) will keep the original file attributes like mtime after upload to s3. My test showed it was not. Did I miss anything?

original local file
Access: 2017-11-27 14:28:13.718132921 -0500
Modify: 2017-09-23 09:18:17.035790000 -0400
Change: 2017-09-23 09:18:17.035749999 -0400

download from s3
Access: 2017-11-27 20:37:32.000000000 -0500
Modify: 2017-11-27 20:37:32.000000000 -0500
Change: 2017-11-27 15:38:00.562682697 -0500

**Comment by fviard** [comment]
@mssmmx On my side it is working. Can you tell me if you are on linux/windows? and if you are using aws s3 as target?

**Comment by mssmmx** [comment]
@fviard I am on Linux and using aws s3 as target. I tried again on different node and got the same result.
All files in s3 bucket kept the time when they were uploaded.

**Comment by muhammad-fahad2068** [comment]
any update on this?
