### ISSUE TITLE
error in Centos 6.5 x64

### ISSUE THREAD

**Issue by contenidosonline** [s3tools/s3cmd#298]
Hello

when I run s3cmd installed from git repository have this error (In this server an older version worked well )

[root@server4 s3cmd-master]# s3cmd ls

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/bin/s3cmd lsProblem: ImportError: No module named dateutil.parser
S3cmd:   unknown version. Module import problem?
python:   2.6.6 (r266:84292, Jan 22 2014, 09:42:36)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
environment LANG=es_AR.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2402, in <module>
    from S3.Exceptions import *
  File "/usr/lib/python2.6/site-packages/S3/Exceptions.py", line 7, in <module>
    from Utils import getTreeFromXml, unicodise, deunicodise
  File "/usr/lib/python2.6/site-packages/S3/Utils.py", line 19, in <module>
    import dateutil.parser
ImportError: No module named dateutil.parser

Your sys.path contains these entries:
    /usr/bin
    /usr/lib64/python26.zip
    /usr/lib64/python2.6
    /usr/lib64/python2.6/plat-linux2
    /usr/lib64/python2.6/lib-tk
    /usr/lib64/python2.6/lib-old
    /usr/lib64/python2.6/lib-dynload
    /usr/lib64/python2.6/site-packages
    /usr/lib/python2.6/site-packages
    /usr/lib/python2.6/site-packages/setuptools-0.6c11-py2.6.egg-info
Now the question is where have the s3cmd modules been installed?

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

roberto

**Comment by avinashsi** [comment]
It's because you have updated the python version on your machine and its module got installed in the earlier version of python just copy the modules of s3 from /usr/lib/python_2x/site-packages to /usr/lib/python_2.6/site-packages .

Also you can update the python version to be used by the system by default by this command

$ update-alternatives --config python
There are 2 programs which provide 'python'.
  Selection    Command
-----------------------------------------------
*+ 1           /usr/bin/python2.7
   2           /usr/bin/python2.6

**Comment by mdomsch** [comment]
Or use s3cmd from the EPEL repository, which is 1.5.2ish (close enough to
be all sorts of fine).
