### ISSUE TITLE
NameError: global name 'unicodise' is not defined

### ISSUE THREAD

**Issue by jeevanullas** [s3tools/s3cmd#306]
Getting following error while using the latest code in github against Eucalyptus 4.0.0 , looks like this commit breaks the functionality? 

https://github.com/s3tools/s3cmd/commit/ea5451d8e42e79ee5bffb81c6e8cdd9bff4e5f99

% s3cmd -c s3cfg ls

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2426, in <module>
    report_exception(e)
  File "/usr/bin/s3cmd", line 2365, in report_exception
    s = u' '.join([unicodise(a) for a in sys.argv])
NameError: global name 'unicodise' is not defined

Please let me know if you have any questions.

Cheers!
Deependra

**Comment by cwthorpe** [comment]
Just a further comment here.  I got this error when I upgraded Ubuntu server from 10.04 to 12.04 (yes, perhaps a bit late).

apt-get upgrade didn't help even with s3cmd repositories. Eventually fixed it by downloading the 1.6.1 version (from SourceForge) and reinstalling.
