### ISSUE TITLE
DreamHost support missing ACLs, bucket expiration rules

### ISSUE THREAD

**Issue by mdomsch** [s3tools/s3cmd#312]
The test suite runs successfully when pointed at DreamHost DreamObjects service, except for:
- Private/Public ACL setting and getting fails.
- setting, getting, deleting bucket expiration rules all fail.

./run-tests.py 1..20 24..42 44..51 58..
succeeds.

**Comment by fviard** [comment]
There is now run-tests-minio.py  to have a test with a smaller subset of s3.
having tests whitelisted/blacklisted per service could be nice but fit badly with the tendency to run s3 servers on each one own domain.
Also sadly the auto test is currently a lot state-full and so it is hard to randomly skip some tests and still have the auto test working as intended and completing.
