### ISSUE TITLE
Handle remote copies of >5GB objects

### ISSUE THREAD

**Issue by mdomsch** [s3tools/s3cmd#317]
The remote copy code path fails for >5GB objects because that requires using the multi-part upload API, but s3cmd doesn't invoke that API, it only invokes the regular single-part PUT API.

**Comment by gooodmorningopenstack** [comment]
Any update ? #74 seems not to be merged and s3cmd doesn't hande multipart API, which is a problem.

**Comment by fviard** [comment]
@gooodmorningopenstack Thank you for bringing up the issue that was like forgotten :-p
This PR has to be fixed as there are some conflicts, and reviewed and tested.
If you have the resources to help us with some of these points. That would help a lot fix this issue faster as we are currently quite busy and there is other issues that have to be fixed before also. If you can work on that, I can promise to look at it fast for merging.

**Comment by rkeene** [comment]
Implementing this would likely fix #830

**Comment by jamshid** [comment]
FYI if anyone really needs to move or copy >5GB objects you might try https://github.com/bloomreach/s4cmd. It appears to be back in active development and it does support "multipart" for >5GB object copies. The current 2.0.1 version from pip does not support S3-compatible systems, you'll have to install from source and use `--endpoint-url`.

**Comment by fviard** [comment]
Should now be fixed in MASTER and next releases (>=2.2.0)
See: https://github.com/s3tools/s3cmd/issues/830#issuecomment-613207225
