### ISSUE TITLE
s3 bucket files locked out after s3cmd cp, cant add permissions

### ISSUE THREAD

**Issue by xxxazxxx** [s3tools/s3cmd#329]
i recently transferred a couple of s3 buckets to a different account with s3cmd from the master :(

now i cant access any of the files transferred to these buckets since there is no way i can add permissions to these transferred files. when i try to add permissions to these files i get. Sorry! You were denied access to do that even when I'm the admin!

no way to add permissions to files : http://imgur.com/LOPK2dN

I have tried to add everyone permission in the bucket itself but all in vain.

I'll appreciate if anyone can help me to retrieve these files.

http://stackoverflow.com/questions/23455351/aws-s3-bucket-files-locked-out-cant-add-permissions

**Comment by mdomsch** [comment]
we don't deal with bucket permissions in any significant way in s3cmd.
