### ISSUE TITLE
python3 compatibility

### ISSUE THREAD

**Issue by bsdlp** [s3tools/s3cmd#335]
Hey, it would be great if we could make s3cmd py2 and py3 compatible. I've got an environment where I would like to use s3cmd, but don't have py2. I've started working on  py3 compatibility here:

https://github.com/fly/s3cmd/compare/py3ify

any assistance, advice, or decision on mergeability of a py3-compat PR would be greatly appreciated!

**Comment by szepeviktor** [comment]
Are s3cmd users use modern (with Python 3 only) operating systems rarely?

**Comment by szepeviktor** [comment]
Maybe I am wrong https://packages.debian.org/jessie/python points to 2.7.8.

**Comment by alexflint** [comment]
+1, would love to have s3cmd working under python3

**Comment by mikemhenry** [comment]
+1, for python3 support.

**Comment by Keruspe** [comment]
This really should happen.

**Comment by mdomsch** [comment]
I'll be happy to review patches.

**Comment by fviard** [comment]
I think that this could be good to have python 3 support for s3cmd, but the following has to be taken under account:
1) python2 should still be fully supported (and will probably stay the mainly developed version for a long time)
2) Maintainers don't have the time to work on that.
3) (My opinion) is that it is not good, very clear to have mixed python2/3 codes like when using python six. (Otherwise, take care that compatibility changes like the one done by fly, restrain the python 2 support to 2.6 and 2.7 or maybe only 2.7. I don't know if we still want to support older python versions?)

So, as always s3cmd is open to contributions, also for this topic.
My personal opinion of the nice way to go is to do same thing as did some python libraries: have different source folders for python2 and python3 code:
 http://python3porting.com/2to3.html#distributing-packages

**Comment by davidfstr** [comment]
s3cmd already restricts its Python to be >= 2.6:

```
if float("%d.%d" %(sys.version_info[0], sys.version_info[1])) < 2.6:
    sys.stderr.write(u"ERROR: Python 2.6 or higher required, sorry.\n")
    sys.exit(EX_OSFILE)
```

If you further restrict to be Python >= 2.7 then having a mixed 2.7/3.x codebase is not too difficult in my experience.

**Comment by h4ck3rm1k3** [comment]
I have a python3 in the works, basic stuff working, this is focused on archive.org support, not aws, but feel free to help out.  https://github.com/h4ck3rm1k3/s3cmd/tree/python3000

**Comment by ryanfoxsquire** [comment]
Any updates here? As far as I can tell s3cmd still unable to run with Python 3.

**Comment by fviard** [comment]
@ryanfoxsquire There is not official pending work regarding this yet. I think that there was a PR some time ago, but it was too radical to be able to be merged.

@h4ck3rm1k3 I just noticed your previous message with the branch that you have done. Honestly I don't have the time to have a look yet. But I wanted to say that so far we will be gladly open to accept small / incremental PR patch to increase the python3 compatibility, till the point where big changes will be needed. I mean that today, without six or something like that, there is a lot of corrections that can be done I think (like using future imports) to have a code that will be more py 3 compatible, and still be working with python v2.6 and 2.7.

The point of patchs being small is to be able to review them and merge them more easily and fast. Also, I'm a little worried that there is still some interesting PR to be merged that could have hard time being rebased after a very big code change.

**Comment by h4ck3rm1k3** [comment]
Hi, I might have time to look at this again someday.

**Comment by shaform** [comment]
I found an interesting s3 utility that already supports Python 3: https://github.com/bloomreach/s4cmd.
If you are interested in using Python 3, this might be a temporary solution.

**Comment by h4ck3rm1k3** [comment]
I am using boto that works. here is a simple upload script that I threw
together

http://paste.debian.net/894928/

**Comment by fviard** [comment]
I just pushed a lot of patches, and so thanks to the help of @shaform that did an initial work, there should now be basic functions working with python3.
But really with a lot of bugs and things not working yet. But we are on the good path.

@shaform I resolved the issue of the custom httplib that stopped you, so don't hesitate if you want to go on the help for this work.

**Comment by shaform** [comment]
That's great news! Thank you very much. I am in the middle of something right now, but might be able to look at this when I have free time.

**Comment by patfla** [comment]
Florent - what branch would that be?

**Comment by patfla** [comment]
@fviard - I downloaded from your master branch and, after some finagling, was able to get a simple

python s3cmd ls

to work.

Most of the trouble was in getting python-magic to work on my Windows 7 machine although I changed at least one line in your s3cmd sources as well.  Probably a hack as opposed to a fix.

**Comment by fviard** [comment]
@patfla : The python3 support is in the master branch of s3cmd.  (but the version in my personal s3cmd repo should be the same).

Good to know, don't hesitate to post here a diff of the change you did or the traceback that you encountered. It was hard to handle all the python-magic version. And maybe there is something additional to take into account for py 3.
Note: Outside of the python 3 support, there are a few known synchronization issues with windows support. Like files that would be re-uploaded/download when non needed in theory.

**Comment by turicas** [comment]
Are you going to release soon on PyPI a version with Python 3 support? It's very useful to have `s3cmd` installed on the same virtualenv I'm working on (and not globally on the system).

**Comment by fviard** [comment]
@turicas Sadly I was a lot busy lastly, but I hope to have more time to complete the work on python 3 in the middle of may.

**Comment by fviard** [comment]
Version 2.0.0 with python 3 support has been released.

**Comment by turicas** [comment]
@fviard thanks! :)
