### ISSUE TITLE
modify command works incorrectly with globbing

### ISSUE THREAD

**Issue by mdahlstrand** [s3tools/s3cmd#344]
The newly added `modify` command works by (I assume) internally executing the `cp` command with the source and the target set to the same value. When running `modify` with a single file it works perfectly, but when using a filename glob the source is set correctly, but the target is set to the glob pattern, not the "resolved" glob's filename. This is the case no matter if the glob matches one or multiple files.

So, with the following bucket contents:
```
a.pdf
b.pdf
c.pdf
```
Running the following (other options used such as `-P` and `--add-header` excluded for brevity):
`s3cmd modify s3://bucket/*.pdf`
Would set the source list to `a.pdf`, `b.pdf`, and `c.pdf`, but the target for each of them would be `*.pdf` instead of their respective names. This results in the files not being modified, and instead one new file is created - named `*.pdf` and with the content of the last source file.

If the same (incorrect) copy commands would have been run through the s3cmd cli, they would have looked something like this:
```bash
s3cmd cp s3://bucket/a.pdf s3://bucket/*.pdf
s3cmd cp s3://bucket/b.pdf s3://bucket/*.pdf
s3cmd cp s3://bucket/c.pdf s3://bucket/*.pdf
```

This basically renders the command useless if used with globbing, which I would think is quite a normal use case for the modify command.

**Comment by mdomsch** [comment]
Fixed on upstream master.

$ ./s3cmd modify --mime-type="application/octet-stream" s3://s3cmd-test.domsch.com/*.py
File s3://s3cmd-test.domsch.com/ACL.py modified
File s3://s3cmd-test.domsch.com/AccessLog.py modified
File s3://s3cmd-test.domsch.com/BidirMap.py modified
File s3://s3cmd-test.domsch.com/CloudFront.py modified
File s3://s3cmd-test.domsch.com/Config.py modified
File s3://s3cmd-test.domsch.com/ConnMan.py modified
File s3://s3cmd-test.domsch.com/Crypto.py modified
File s3://s3cmd-test.domsch.com/Exceptions.py modified
File s3://s3cmd-test.domsch.com/ExitCodes.py modified
File s3://s3cmd-test.domsch.com/FileDict.py modified
File s3://s3cmd-test.domsch.com/FileLists.py modified
File s3://s3cmd-test.domsch.com/FileObject.py modified
File s3://s3cmd-test.domsch.com/HashCache.py modified
File s3://s3cmd-test.domsch.com/MultiPart.py modified
File s3://s3cmd-test.domsch.com/PkgInfo.py modified
File s3://s3cmd-test.domsch.com/Progress.py modified
File s3://s3cmd-test.domsch.com/S3.py modified
File s3://s3cmd-test.domsch.com/S3Uri.py modified
File s3://s3cmd-test.domsch.com/SortedDict.py modified
File s3://s3cmd-test.domsch.com/Utils.py modified
File s3://s3cmd-test.domsch.com/__init__.py modified
[mdomsch@pws490 s3cmd (upstream-master)]$ ./s3cmd info s3://s3cmd-test.domsch.com/S3.py
s3://s3cmd-test.domsch.com/S3.py (object):
   File size: 58844
   Last mod:  Wed, 04 Feb 2015 14:37:26 GMT
   MIME type: application/octet-stream
   MD5 sum:   6f30b2960acc8df9ceed523a33bc76f7
   SSE:       NONE
   policy: none
   ACL:       matt: FULL_CONTROL
