### ISSUE TITLE
WARNING: Empty object name on S3 found, ignoring.

### ISSUE THREAD

**Issue by aekondratiev** [s3tools/s3cmd#349]
Hello, when I'am sync to S3, s3cmd show's to me this warning sometimes : "WARNING: Empty object name on S3 found, ignoring." is it ok ? can I off such warnings from s3cmd without using --quiet option ? 

s3cmd version 1.5.0-beta1

**Comment by cwc219** [comment]
When I experience this message it is because of the trailing /.  For example: if you leave off the trailing /  # s3://aws3_bucket/Folder  It will complain "ERROR: Parameter problem: Destination S3 URI must end with '/' (ie must refer to a directory on the remote side)."  but at the same time the other message  "WARNING: Empty object name on S3 found, ignoring."  disappears.

This only started when we started putting data into a folder.  When we were dumping data into the root folder, the bucket the message "WARNING: Empty object name on S3 found, ignoring." did not appear.

**Comment by jamiejackson** [comment]
I'm not at my machine now, but it makes me wonder if this is related to the 1-byte "directory" objects that are created when one creates a "directory" in an S3 client (e.g. s3browser, AWS web client, etc.) *before* populating it. (It persists even after populating, unless it's deleted afterwards. That's not possible in most clients, though AWS console can do it.)

https://luceeserver.atlassian.net/plugins/servlet/mobile#issue/LDEV-359

**Comment by mdomsch** [comment]
Yes, quite likely.  If it creates a (tiny) object named path/to/file/ (with
trailing slash) I bet we don't handle that well.

**Comment by dwery** [comment]
it still happens on 1.6.0 with 
```s3cmd --reduced-redundancy sync /my/local/path/ s3://my-bucket/folder/```
the local path has files only and I can't see any strange object on the s3 console

**Comment by babatundebusari** [comment]
still happens even with current version
and even when makes it quiet, it still outputs this message

**Comment by massdest** [comment]
> still happens even with current version

seems I stop backup some folders, witch generate those messages, so I dont saw it anymore. 

ok, reopened.

**Comment by pelegb** [comment]
Hi,
Any news?
Experiencing this warning as well.

Thanks

**Comment by fviard** [comment]
@pelegb Are you experiencing this with the last MASTER of s3cmd? if yes, do you know with which "s3" software you could have "first" created the files on s3 side?

**Comment by pelegb** [comment]
@fviard I'm experiencing this with version 1.6.1 downloaded via pip

**Comment by sagespidy** [comment]
Hi All
AFIAK, this error is due to fact there are no new files in the dir you are trying to sync. I created a new test file and i was able to able to get rid of the error.
Hope it helps

**Comment by pelegb** [comment]
@fviard I'm experiencing this in version 2.0 as well

**Comment by hersche** [comment]
2.1.0 same

**Comment by Kill0p** [comment]
Got it today. 2.1.0

**Comment by minkbear** [comment]
Got the same 2.1.0

**Comment by fviard** [comment]
A lot of changes were pushed to MASTER to be able to support empty directories and so I think that your issue should now be solved.
So far, we consider empty objects as directories, only if the size of the object is 0-byte, as what looks like to be created by any client that creates objects. But I will appreciate your feedback if you are still encountering the warning as it would mean that some clients might create objects with  a final forward slash in the name that can have content inside.

Btw, in addition, there is a new command to allow to backup directories themselves ("--keep-dirs") a little bit like it is done by the aws console. It is still experimental, but I would appreciate a lot feedbacks about it.
