### ISSUE TITLE
RC1:  Problem: ValueError: too many values to unpack

### ISSUE THREAD

**Issue by jboncek** [s3tools/s3cmd#353]
I just started evaluating s3cmd and happened to start with rc1.  I managed to install it on my windows box with python 2.7.7, pip, python-dateutil, etc... but i could not get it to put or sync any files.  It would only give me this python error:  Problem: ValueError: too many values to unpack

So, i reverted to beta1 and it worked just fine.  looks like you might have an issue in the new rc1.

**Comment by mdomsch** [comment]
closing for lack of reproducability.

**Comment by eincs** [comment]
Well, this is run command and  error message of the error:

```s3cmd sync --acl-public ./_site/* s3://xxx.yyy.zzz```

```!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please report the following lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Problem: ValueError: too many values to unpack
S3cmd:   1.6.0

Traceback (most recent call last):
  File "/opt/local/bin/s3cmd", line 2037, in <module>
    main()
  File "/opt/local/bin/s3cmd", line 1978, in main
    cmd_func(args)
  File "/opt/local/bin/s3cmd", line 1162, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/opt/local/bin/s3cmd", line 1139, in cmd_sync_local2remote
    local_list, single_file_local = fetch_local_list(args[:-1], recursive = True)
ValueError: too many values to unpack

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
    Please report the above lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

**Comment by mdomsch** [comment]
You have a mixture of version 1.6.0 and something else.  That line is not
present in v1.6.0.  Please clean your installation in /usr/local/ and try
again.

Thanks,
Matt
