### ISSUE TITLE
Deploy to the PyPI

### ISSUE THREAD

**Issue by ghickman** [s3tools/s3cmd#36]
Deploying to the PyPI should be a trivial thing to do and would benefit many people.

**Comment by mdomsch** [comment]
@ghickman can you add matt.domsch.com as an approved uploader for PyPi please?

**Comment by mdomsch** [comment]
@brandon-rhodes can you add matt.domsch.com as an approved uploader for PyPi please?

**Comment by brandon-rhodes** [comment]
Done!
