### ISSUE TITLE
s3cmd no longer working on CentOS 5.10 python2.4

### ISSUE THREAD

**Issue by rawrkats** [s3tools/s3cmd#365]
I run a cron that runs s3cmd and then emails me a report. I started receiving this report:

`ImportErr: /usr/lib/python2.4/lib-dynload/pyexpat.so: symbol XML_SetHashSalt, version EXPAT_1_95_8_RH not defined in file libexpat.so.0 with link time reference
S3cmd:   unknown version. Module import problem?
python:   2.4.3 (#1, Jan  9 2013, 06:49:54) 
[GCC 4.1.2 20080704 (Red Hat 4.1.2-54)]
environment LANG=None

Traceback (most recent call last):
 File "/usr/bin/s3cmd", line 2407, in ?
   from S3.Exceptions import *
 File "/usr/lib/python2.4/site-packages/S3/Exceptions.py", line 7, in ?
   from Utils import getTreeFromXml, unicodise, deunicodise
 File "/usr/lib/python2.4/site-packages/S3/Utils.py", line 39, in ?
   from xml.parsers.expat import ExpatError
 File "/usr/lib/python2.4/xml/parsers/expat.py", line 4, in ?
   from pyexpat import *
ImportError: /usr/lib/python2.4/lib-dynload/pyexpat.so: symbol XML_SetHashSalt, version EXPAT_1_95_8_RH not defined in file libexpat.so.0 with link time reference`

I logged in, ran yum --enablerepo epel-testing install s3cmd, it updated, but when i run s3cmd I get the following error:
`
Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2527, in ?
    report_exception(e)
  File "/usr/bin/s3cmd", line 2465, in report_exception
    s = u' '.join([unicodise(a) for a in sys.argv])
NameError: global name 'unicodise' is not defined
`

**Comment by mdomsch** [comment]
For 1.5.2 we explicitly set the minimum requirements to be python 2.6.  CentOS 5 has a python26 package available which is functional. Closing.
