### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by multiformeingegno** [s3tools/s3cmd#366]
I installed latest s3cmd rev on my Ubuntu Server 14.04.1.
I tried running `s3cmd --reduced-redundancy put --recursive /var/www s3:/MY_BUCKET/FILES/`date +\%G-\%m-\%d`/`

... but I got:

`s3cmd[10984]: segfault at 24 ip 00000000004c278f sp 00007fff8db6ce50 error 6 in python2.7[400000+2bd000]`

**Comment by eladnava** [comment]
I also received `Segmentation fault` when trying to interact with a huge bucket. I tried with a small bucket (containing a few files) and all my commands worked. It seems that `s3cmd` doesn't scale too well for huge buckets.

If anyone needs s3cmd for huge buckets, I'd recommend checking out https://github.com/bloomreach/s4cmd, it's inspired by `s3cmd`.
