### ISSUE TITLE
s3cmd modify command

### ISSUE THREAD

**Issue by mckamey** [s3tools/s3cmd#37]
It would be super awesome to have something akin to a modify command that allowed changing the settings that are possible to set during upload but which don't seem to have a way to be modified later.

For instance, I'd like to be able to set headers, switch to reduced redundancy, make public, etc. for JPGs that are already uploaded:

```
s3cmd modify \
    --add-header='Cache-Control: public, max-age=31536000' \
    --reduced-redundancy \
    --cf-invalidate \
    --acl-public \
    --recursive \
    --exclude '*' \
    --include '*.jpg' \
    'foo' \
    s3://foo
```

Unless I'm missing something these can be changed manually in the AWS Console, but not via s3cmd without a full delete and re-upload which may not be feasible.

Thanks in advance and keep up the great work!

**Comment by pablolibo** [comment]
+1

**Comment by mdomsch** [comment]
This is on upstream master now.

**Comment by lindleywhite** [comment]
So will modify work, without creating a copy of the file in the same directory? 

Assuming it will, can we use it like this?
```
s3cmd modify --recursive --add-header=Cache-Control:max-age=86400 s3://BUCKET/FOLDER
```

**Comment by lindleywhite** [comment]
I pulled down the latest branch and am getting an error from Python.

```
Invoked as: /usr/local/bin/s3cmd modify --add-header=Cache-Control:max-age=86400 -m image/png s3://blendtec.com/images/Homepage/warranty_mobile.png
Problem: AttributeError: 'S3' object has no attribute 'object_modify'
S3cmd:   1.5.0-rc1
python:   2.7.9 (default, Dec 19 2014, 11:33:50) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 2547, in <module>
    rc = main()
  File "/usr/local/bin/s3cmd", line 2460, in main
    rc = cmd_func(args)
  File "/usr/local/bin/s3cmd", line 761, in cmd_modify
    return subcmd_cp_mv(args, s3.object_modify, "modify", u"File %(src)s modified")
AttributeError: 'S3' object has no attribute 'object_modify'
```

**Comment by mdomsch** [comment]
You have a mix of old and new installed. This isn't github  master branch...

**Comment by ryandurfey** [comment]
Just installed s3cmd/1.6 and the command line modify suggested above worked.  I also included an extra example for pattern matching in the pathname.

Modify everything below a directory:
s3cmd modify --recursive --add-header=Cache-Control:max-age=0 s3://bucketname/directory1/directory2 

Modify everything with "directory4" in the path name:
s3cmd modify --recursive --add-header=Cache-Control:max-age=300 s3://bucketname --exclude '*'  --include '*directory4*'
