### ISSUE TITLE
Mime Type options for s3cmd sync

### ISSUE THREAD

**Issue by cdenneen** [s3tools/s3cmd#376]
When syncing a very large set of files for static website, really need a way to specify content-type overrides as necessary for all .css files, .svg files... etc.
To have to modify content-type on a per file s3cmd put basis renders s3cmd sync or even s3cmd put -r unusable.

**Comment by 3xp0n3nt** [comment]
Can we please re-open this?

I don't want to run a separate s3cmd upload for each file type I want to override.

--guess-mime-type works for most files, but there's always some that need to be overridden. It would be a huge hassle to separate out each file type into a group and run a separate upload for each group vs. allowing some sort of override flag or config file.

>I think a simpler file-extension based MIME mapping would be more reliable

The point is to be able to *customize* the MIME mapping, not find a better one-size-fits all solution. I know this is an old issue, so I have no idea if anything has changed, but it doesn't seem like it.

**Comment by 3xp0n3nt** [comment]
Look at http://stackoverflow.com/questions/20284531/how-to-specify-mime-type-mappings-when-using-s3cmd-sync?rq=1

People hacking s3cmd to override file types.

**Comment by fviard** [comment]
It has been a long time, but, if you are still having the issue, I have created a wiki page related to this topic:
https://github.com/s3tools/s3cmd/wiki/Understand-Content-Type,-Mime-type-guessing-and-Magic

In short, s3cmd just use what is detected by other system components for file extension or magic.
One way to achieve your purpose without hacking is just to add the rules in the /etc/mime.types and /etc/magic files of your system.
