### ISSUE TITLE
Support adding Content-Encoding for compressed files

### ISSUE THREAD

**Issue by mietek** [s3tools/s3cmd#396]
Please take a look at Amazon advice regarding [“Serving Compressed Files from Amazon S3”](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html#CompressedS3):

> Add a `Content-Encoding` header field for each compressed file and set the field value to `gzip`.

It would be nice if `s3cmd sync` had an option to do this automatically, as uploading compressed files is the only way to serve compressed content from S3.

**Comment by kaihendry** [comment]
Instead of s3cmd detecting gzip encoded content as what I think this issue asks for, couldn't it have a filter to gzip the content whilst uploading it and adding the header?

    --gzip-include='*.css' --gzip-include='*.html' --gzip-include='*.js' --gzip-include='*.svg'

I think pretty much all browsers support gzip now. http://webmasters.stackexchange.com/a/22223

**Comment by guss77** [comment]
Pretty much all browsers support gzip, but not all of them, and other useful tools (like curl) don't sorry it or don't support it by default.

The main reason to have s3cmd support content encoding, is to support cloudfront serving of gzip compressed content, and that requires both the original content and the gz files.

**Comment by kaihendry** [comment]
On my test site: http://browserinabox.com/font-awesome/css/font-awesome.min.css I gzipped the CSS (no .gz extension) and uploaded that with the Gzip header by hand. So you don't need two versions of the same file AFAICT.

**Comment by mietek** [comment]
@kaihendry If you don’t care about serving the uncompressed version of the file to user agents which can’t handle the compressed version, then yes, you only need one version…

**Comment by mietek** [comment]
I’m unhappy with my current workaround.  Part of my `Makefile`:
```Make
s3-args := sync out/pub/ s3://$(s3-bucket) --acl-public --no-preserve --exclude='*.git*'

define pub-sync-zip
  s3cmd $(s3-args) --cf-invalidate --add-header='Content-Encoding:gzip' --exclude='*' --include='*.gz' || s3cmd $(s3-args) --add-header='Content-Encoding:gzip' --exclude='*' --include='*.gz'
endef

define pub-sync-all
  s3cmd $(s3-args) --cf-invalidate --delete-removed || s3cmd $(s3-args) --delete-removed
endef
```
The need to call `s3cmd` twice (once for uncompressed files, once for compressed files) means two CloudFront invalidations are generated.  There can be at most three CF invalidations in-flight, which means re-running my `Makefile` too quickly will cause one of the `s3cmd` calls to fail.

There also appears to be a bug with `s3cmd` not invalidating `index.html.gz` properly, but I haven’t pinpointed it yet, because the entire process is so error-prone.

**Comment by kaihendry** [comment]
@mietek Which UAs can't support Gzip decoding?! From what I researched, all browsers support Gzip decoding, so I am not sure it's worth the effort with your dual approach which is confusing because IIUC you have to rewrite paths based on the browser header, which is a huge PITA because you need some dynamic component.

Anyway, back to my proposal, doesn't `--gzip-include` sound reasonable? Since if I compress the files on my local dev disk, it's a PITA to tell my tooling like vim to uncompress & compress them without a .gz extension. So I rather just have s3cmd do it in one step.

**Comment by ahmed1490** [comment]
Any update on this? as to what is the best way to update gzip content.

**Comment by kaihendry** [comment]
I'm using this stop gap: http://s.natalian.org/2015-05-12/compress.sh

**Comment by theUtherSide** [comment]
Bump.  I'd also like to request this feature.  Currently, when I specify `--header Content-Encoding: gzip`, in S3 it sets: `x-amz-meta-content-encoding: gzip` instead.  Chrome still unpacks and renders the file, but FF and Safari display garbled text.

**Comment by mietek** [comment]
@theUtherSide: The correct option to use is not `--header`.

As an example, here’s how I upload a local `json` directory to `my-bucket/json`:
```
s3cmd sync json \
    s3://my-bucket \
    --acl-public \
    --delete-removed \
    --exclude='*' \
    --include='*.json.gz' \
    --add-header="Cache-Control:max-age=3600" \
    --add-header='Content-Type:application/json' \
    --add-header='Content-Encoding:gzip'
```

**Comment by theUtherSide** [comment]
Very helpful!  Thank you!

**Comment by fernandopg** [comment]
In my case I don't need to specify the headers to upload gzip content. I upload everything with s3cmd:

s3cmd sync www/ s3://www.mysite.com  --delete-removed

And then if I go to the Amazon S3 console I can see the gzip files with the correct headers!
