### ISSUE TITLE
--server-side-encryption flag not working.

### ISSUE THREAD

**Issue by chiedojohn** [s3tools/s3cmd#397]
Hey guys, 
My apologies if the misunderstanding is on my end and not an issue on your end. I am running s3cmd version 1.5.0-rc1.

I'm running a command like the following:
s3cmd --server-side-encryption put ./file.txt s3:/{bucket_name}/file.txt

The file is ending up in the S3 bucket but when I check properties, 'Server Side encryption' is set to 'None'.

I get the same results with Python 2.7.3 and 2.7.6 if that matters at all.

Once again my apologies if the issue is in fact my misunderstanding.

**Comment by mdomsch** [comment]
This works on upstream master branch.
$ ./s3cmd put --server-side-encryption README.md s3://s3cmd-test.domsch.com/
README.md -> s3://s3cmd-test.domsch.com/README.md  [1 of 1]
 14137 of 14137   100% in    0s    57.37 kB/s  done

$ ./s3cmd info s3://s3cmd-test.domsch.com/README.md
s3://s3cmd-test.domsch.com/README.md (object):
   File size: 14137
   Last mod:  Wed, 04 Feb 2015 14:17:30 GMT
   MIME type: text/plain
   MD5 sum:   7b8d2b31d18086c7a856732c46d6711e
   SSE:       AES256
   policy: none
   ACL:       matt: FULL_CONTROL

**Comment by chiedojohn** [comment]
Thanks for taking care of this.
