### ISSUE TITLE
WARNING: Empty object name on S3 found, ignoring.

### ISSUE THREAD

**Issue by ezmiller** [s3tools/s3cmd#398]
I'm getting this error message and am not sure exactly how to interpret it:

> WARNING: Empty object name on S3 found, ignoring.

Anyone know what it means? How to fix?

**Comment by silyevsk** [comment]
:+1:

**Comment by rockmyrun** [comment]
I am having this issue now too. Our servers just updated s3cmd from epel to this version:
s3cmd-1.5.1.2-5.el6

And we get this Error now every time s3cmd sync runs. I can output all errors to /dev/null to get rid of the cron job emails but then we miss any actual errors.

Is there any other fix for this?

**Comment by fviard** [comment]
If you are still experiencing such an issue, could you run the last git version with the "--debug" flag?
So we can see what is returned by the server that triggers this?

**Comment by tilghman** [comment]
Is version 1.6.0 sufficient for the debug?
[s3sync-debug-images.gz](https://github.com/s3tools/s3cmd/files/213650/s3sync-debug-images.gz)

**Comment by fviard** [comment]
Closing as duplicate of #349
