### ISSUE TITLE
Cannot sync filenames wit spaces in it

### ISSUE THREAD

**Issue by ncri** [s3tools/s3cmd#400]
I'm doing 

```
s3cmd sync s3://my-bucket/ /my-local-bucket-folder --delete-removed --dry-run
```

What I get is lots of

```
delete: /my-local-bucket-folder/some file with spaces in it.ext
...
```

All of these files exist on S3, in fact they were just copied to my local bucket from there in an initial sync call. Is there a fix for this? I'm also wondering if there are other characters causing issues.

**Comment by verlata** [comment]
s3cmd version 1.6.1 on ubuntu 14.04. Trying to sync remote tree (with spaces in folder names) to local:
$/usr/local/bin/s3cmd sync s3://remotebucket/ /localfolder/s3/

here is the output:
download: 's3://remotebucket/100001/2014-old/Fatture PA/Allegati/118/0000000009/10484.P7M' -> '/localfolder/s3/100001/2014-old/Fatture PA/Allegati/118/0000000009/10484.P7M'  [10 of 11645]

and the warning: WARNING: Remote file ''. S3Error: 404 (Not Found)

in /localfolder/ the folder tree is recreated correctly (even the folder with spaces), but no file is there.

Any idea?
