### ISSUE TITLE
AWS4-HMAC-SHA256 Support

### ISSUE THREAD

**Issue by felixbuenemann** [s3tools/s3cmd#402]
I'm trying to connect a bucket in the new eu-central-1 region (Frankfurt), but it seems it uses a newer authentication scheme that's not supported by 1.5.0-rc1:

```
Please wait, attempting to list bucket: s3://mybucket
WARNING: Redirected to: mybucket.s3.eu-central-1.amazonaws.com
ERROR: Test failed: 400 (InvalidRequest):
The authorization mechanism you have provided is not supported.
Please use AWS4-HMAC-SHA256.
```

Also note that the endpoint is named s3.eu-central-1.amazonaws.com (dot after s3 instead of dash).

**Comment by dsjoerg** [comment]
@mdomsch you wrote "With all the S3 regions switching to AWS4 in January, s3cmd will have to
grow this capability" — do you have a reference for that?  I have been unable to find any official docs that claim that S3 regions are switching to AWS4.

Thanks in advance!

**Comment by mdomsch** [comment]
http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-authenticating-requests.html

"Amazon S3 supports Signature Version 4, a protocol for authenticating
inbound API requests to AWS services, in all AWS regions. At this time,
existing AWS regions continue to support the previous protocol, Signature
Version 2. Any new regions after January 30, 2014 will support only
Signature Version 4 and therefore all requests to those regions must be
made with Signature Version 4."


This includes at least Frankfurt (eu-central-1).

**Comment by dsjoerg** [comment]
Thanks @mdomsch, feel much better now.  If I'm reading this right, no regions are switching per se, and regions that currently support AWS Sig V2 will continue to do so.  (Note they are referring to last January not this upcoming January).

For my own very limited purposes this is great news.  But I certainly understand why software such as s3cmd (thank you it's awesome!) must start supporting AWS Sig V4 now.

**Comment by Ajaxy** [comment]
Has it been finally released? I'm facing the same error.

**Comment by felixbuenemann** [comment]
@Ajaxy According to the merge date, this should be included in v1.5.0 upwards.

**Comment by Ajaxy** [comment]
Seems that it's missed in package from `apt-get`.

**Comment by felixbuenemann** [comment]
The chance that you can anything recent in apt-get is rather slim ;-)

**Comment by mdomsch** [comment]
It's in very new Ubuntu.  Otherwise, install it from pip or from github.

**Comment by JensRantil** [comment]
@Ajaxy @felixbuenemann I can confirm this patch did not make into `1.5.0-alpha1` as I experienced `The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.` with that version. `pip install --upgrade`ing to `1.6.0` fixed it for me.

@mdomsch In the future it would help a lot of you could make sure an issue refers to a GIT commit (or pull request) when closing an issue. It took me 30 minutes of detective work on my side to figure this out. Simply looking up which tags contained a commit would have been so much easier... ;)

**Comment by felixbuenemann** [comment]
@JensRantil Well, I meant v1.5.0 (released in January), not v1.5.0-alpha1 (released in 2013).

**Comment by ustun** [comment]
Still facing this error with v1.6.1

**Comment by felixbuenemann** [comment]
You probably forgot to specify the region, it's mandatory for AWS4 auth.

**Comment by ngtuna** [comment]
> You probably forgot to specify the region, it's mandatory for AWS4 auth.

How to ? I specified region but still facing the error:

```console
$  aws --region us-east-1 s3 cp <src> s3://<dest>

A client error (InvalidRequest) occurred when calling the CreateMultipartUpload operation: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.
```

**Comment by fviard** [comment]
@ngtuna "aws s3" client is another tool, here it is the project "s3cmd" that your run with commands like:
$ s3cmd cp ....

**Comment by ngtuna** [comment]
@fviard ah my mistake. Also I just figured out I install wrong version of aws s3 cli.

**Comment by Gwanghyeon** [comment]
I solved this issue by simply adding my bucket region in my `settings.py file. I used Django and boto3. For example, 
`AWS_S3_REGION_NAME = "ap-northeast-2"`
should work.

**Comment by ponthos** [comment]
+1
