### ISSUE TITLE
Warning: Unable to remote copy

### ISSUE THREAD

**Issue by ezmiller** [s3tools/s3cmd#403]
Hi,
I'm getting an error when using s3cmd sync. The error looks like this:

> WARNING: Unable to remote copy files s3://****/hosting-backups/****/built/fonts/league_gothic/stylesheet.css -> s3://****/hosting-backups/****/assets/fonts/league_gothic/stylesheet.css

(Note: *** are just to protect some info) 

I'm not sure what's causing this error, whether it's some sort of permissions problem, or what have you. Can anyone here shed some light?

**Comment by mdomsch** [comment]
without further detail, closing.  The test suite does invoke remote-to-remote copies.  If you still see failures in upstream master, please reopen and post with --debug.

**Comment by semente** [comment]
I got the same error... Perhaps is because my access key has write access only so remote-to-remote copies won't work due lack of read/listing access.

**Comment by matt-murdock** [comment]
I also get this error, but not for all files, only some. I have turned on debug mode, it does show that it is retying after the failure:
'WARNING: Upload failed:
Retrying on lower speed (throttle=0.00)'

but not sure why it failed to begin with
