### ISSUE TITLE
can s3cmd handle temporary redirect?

### ISSUE THREAD

**Issue by jillesvangurp** [s3tools/s3cmd#404]
I'm trying to make s3 backups work with a bucket that I just created. Using s3cmd.

This doesn't work for me. Basically s3cmd randomly fails on some files with a broken pipe.

    WARNING: Upload failed: /fooo/users.gz ([Errno 104] Connection reset by peer)
    WARNING: Retrying on lower speed (throttle=0.01)
    WARNING: Waiting 6 sec...
    backup-testing.inbot.io-20141027T175655Z/users.gz -> s3://inbot-backups.inbot.io/fooo/users.gz  [1 of 1]
    WARNING: Upload failed: /fooo/users.gz ([Errno 104] Connection reset by peer)

Sometimes it actually goes through and our backup script manages to eventually get some of the files across but not all.

Bucket is in the US (the standard one in California). The files are tiny (well below the 5GB limit). This is happening in our data center (Germany). No proxies are involved. Broken with and without HTTPS. Centos version is 7.0. Python version is 2.7.5 that comes with centos. S3cmd version is 1.5.0-rc1 installed from the epel repository.

In short, I've been pulling my hair out. Then I tried a bash script that I found [here][1]

    #!/bin/bash
    file="$1"
    
    key_id="YOUR-AWS-KEY-ID"
    key_secret="YOUR-AWS-KEY-SECRET"
    path="some-directory/$file"
    bucket="s3-bucket-name"
    content_type="application/octet-stream"
    date="$(LC_ALL=C date -u +"%a, %d %b %Y %X %z")"
    md5="$(openssl md5 -binary < "$file" | base64)"
    
    sig="$(printf "PUT\n$md5\n$content_type\n$date\n/$bucket/$path" | openssl sha1 -binary -hmac "$key_secret" | base64)"
    
    curl -T $file http://$bucket.s3.amazonaws.com/$path \
        -H "Date: $date" \
        -H "Authorization: AWS $key_id:$sig" \
        -H "Content-Type: $content_type" \
        -H "Content-MD5: $md5"

Interestingly, that fails with a 302, temporary redirect (found that oud by adding -v to the curl command). That's easily fixed by adding the -L parameter. And lo and behold: it works. Just like that.

So my analysis is that s3cmd is not handling the temporary redirect as it should. Some other googling seems to confirm that there is some weirdness with dns and s3 and that things should settle down after a few hours/days. Having to wait for that is kind of insane. 

So, I was wondering if there's a way to make s3cmd it not fail on this apparently quite common situation where s3 just needs a few hours until it is ready to reliably receive files sent to it via s3cmd without breaking on 302s?

  [1]: http://geek.co.il/2014/05/26/script-day-upload-files-to-amazon-s3-using-bash

**Comment by mdomsch** [comment]
are you still seeing this?  I've not experienced this.  If you are, please try with upstream master and reopen.

**Comment by fviard** [comment]
This issue should now be fixed in master.
Please give it a try.
