### ISSUE TITLE
Bug Report ascii

### ISSUE THREAD

**Issue by maycson-fonseca-movile** [s3tools/s3cmd#417]
[maycson.fonseca@]$ sudo /teste/s3cmd-1.5.0-rc1/s3cmd -c /etc/s3cmd/testecfg sync -p --check-md5 --no-progress "/opt/graphite/storage/whisper/sbs-engine3dc1/HYBRID/CARRIER_1/skiped/[BR]-Só-para-Maiores---Oi/count.wsp.gz" "s3://opt/graphite/storage/whisper/sbs-engine3dc1/HYBRID/CARRIER_1/skiped/[BR]-Só-para-Maiores---Oi/count.wsp.gz"

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

You have encountered a UnicodeEncodeError.  Your environment
variable LANG=en_US.UTF-8 may not specify a Unicode encoding (e.g. UTF-8).
Please set LANG=en_US.UTF-8 or similar in your environment before
invoking s3cmd.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Problem: UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 114: ordinal not in range(128)
S3cmd:   1.5.0-rc1
python:   2.6.6 (r266:84292, Feb 22 2013, 00:00:18) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-3)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/movile/s3cmd-1.5.0-rc1/s3cmd", line 2523, in <module>
    rc = main()
  File "/movile/s3cmd-1.5.0-rc1/s3cmd", line 2441, in main
    rc = cmd_func(args)
  File "/movile/s3cmd-1.5.0-rc1/s3cmd", line 1472, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/movile/s3cmd-1.5.0-rc1/s3cmd", line 1449, in cmd_sync_local2remote
    any_child_failed = _single_process(local_list)
  File "/movile/s3cmd-1.5.0-rc1/s3cmd", line 1253, in _single_process
    destination_base = str(destination_base_uri)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 114: ordinal not in range(128)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by andreas-venturini** [comment]
using latest s3cmd code from master branch (I know there is an open PR #425)

text```
Invoked as: /usr/bin/s3cmd sync --delete-removed s3://BUCKET/ /BACKUP_DIR/BACKUP_FOLDER/
Problem: UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 91: ordinal not in range(128)
S3cmd:   1.5.0
python:   2.6.8 (unknown, Aug 30 2012, 01:56:38) [C]
environment LANG=None

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2546, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2459, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1481, in cmd_sync
    return cmd_sync_remote2local(args)
  File "/usr/bin/s3cmd", line 1154, in cmd_sync_remote2local
    failed_copy_list = local_copy(copy_pairs, destination_base)
  File "/usr/bin/s3cmd", line 1187, in local_copy
    shutil.copy2(src_file.encode(encoding), dst_file.encode(encoding))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 91: ordinal not in range(128)
```

**Comment by mr-moon** [comment]
Still relevant  ```s3cmd version 1.5.1.2```

```
Problem: UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 42: ordinal not in range(128)
S3cmd:   1.5.1.2
python:   2.6.6 (r266:84292, Nov 22 2013, 12:16:22)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2548, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2460, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1481, in cmd_sync
    return cmd_sync_remote2local(args)
  File "/usr/bin/s3cmd", line 1154, in cmd_sync_remote2local
    failed_copy_list = local_copy(copy_pairs, destination_base)
  File "/usr/bin/s3cmd", line 1187, in local_copy
    shutil.copy2(src_file.encode(encoding), dst_file.encode(encoding))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 42: ordinal not in range(128)
```

Oh, just looks like not yet released.

**Comment by fviard** [comment]
Please try with the release 1.5.2 or even with the current github version of the code.
It is supposed to be fixed now.
