### ISSUE TITLE
s3cmd should not retry getting object if 405 is returned

### ISSUE THREAD

**Issue by hrchu** [s3tools/s3cmd#422]
In AWS S3 spec:
> If an object in reduced redundancy storage has been lost, Amazon S3 will return a 405 error on requests made to that object.

http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingRRS.html

If the scenario is occurred, retry cannot help this. s3cmd should not retry getting object if 405 is returned.

**Comment by mdomsch** [comment]
Added tests for HTTP 405 response, and no longer retrying.

**Comment by hrchu** [comment]
Thanks mdomsch!
