### ISSUE TITLE
SignatureDoesNotMatch error on modify --add-header="Content-Type:image/jpeg"

### ISSUE THREAD

**Issue by mteichtahl** [s3tools/s3cmd#433]
When using the command below

s3cmd modify --exclude '_._' --rinclude '([^\s]+(.(?i)(jpg|jpeg|jpe))$)' --acl-public --recursive --add-header="Content-Type:image/jpeg" s3://syddocuments/Amplifier\ Agency/                                  [15:07:02]

the following error is returned

ERROR: S3 error: 403 (SignatureDoesNotMatch): The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Comment by kyleboon** [comment]
I appear to be running into this after upgrading to 1.5.0

```
s3cmd sync -P public/* s3://kyleboon.org/ --mime-type='text/html; charset=utf-8' --add-header 'content-encoding: gzip' --exclude '*.*' --include '*.html'
```

```
WARNING: Forwarding request to us-east-1
public/instant-messaging-arch.html -> s3://kyleboon.org/instant-messaging-arch.html  [1 of 51]
 8265 of 8265   100% in    0s    38.43 kB/s  done
ERROR: S3 error: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

**Comment by mdomsch** [comment]
Please try with github.com/s3tools/s3cmd master branch. I may have fixed
that since 1.5.0 was released. If not, please send results with --debug
enabled.

**Comment by kyleboon** [comment]
ok it worked from the master branch. any chance of a point release soon? :)

Thanks!
