### ISSUE TITLE
SSL cert failure on buckets with a dot (.)

### ISSUE THREAD

**Issue by yardenac** [s3tools/s3cmd#437]
Since updating Arch Linux, s3cmd fails to connect to any bucket with a dot (`.`) in its name:

```
$ s3cmd info s3://buck.et
WARNING: Retrying failed request: /?location (hostname 'buck.et.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com')
WARNING: Waiting 3 sec...
WARNING: Retrying failed request: /?location (hostname 'buck.et.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com')
WARNING: Waiting 6 sec...
```

This is because python 2.7.9 validates SSL certs by default. It exposes a general problem with Amazon's wildcard cert. Note the certificate failure by visiting anything like this in your browser: https://buck.et.s3.amazonaws.com/

The solution may be to access things using this endpoint instead: https://s3.amazonaws.com/buck.et/

**Comment by doismellburning** [comment]
I'd like to echo the comments from @djmitche about how a release would be much appreciated please.

If there have been breaking changes on master, is there any possibility of a point release of 1.0.x please? It'd be significantly helpful and appreciated. Thanks!

**Comment by doismellburning** [comment]
Ah, I've just seen that the current fix is conditionally disabling SSL hostname checking (i.e. effectively reverting to earlier Python behaviour) - I can totally see why you wouldn't want to backport that

**Comment by mdomsch** [comment]
The problem is, there isn't a better option.  The wildcard cert that AWS S3
presents us allows for *.s3.amazonaws.com hostnames, not *.example.com or
even my.bucket.s3.amazonaws.com.

Another option would be to somehow look up the appropriate S3 endpoint
(e.g. eu-west-1.s3.amazonaws.com) for a given bucket and then rewrite all
s3://mybucket/path/to/file into s3://
eu-west-1.s3.amazonaws.com/mybucket/path/to/file and then use that
endpoint.  That fixes a couple issues: SSL cert checking, and hitting the
region-specific endpoint rather than the generic (s3.amazonaws.com ==
us-east-1) endpoint like we currently do.  The challenge with such rewrites
is it breaks all non-AWS-S3 instances in use (we can't blindly rewrite the
destination host, it could very well be a Walrus, Swift, or even fakes3
instance. whose host names we don't know).

**Comment by djmitche** [comment]
Could we invent a syntax for *users* to supply that form?  Then, rather
than disabling SSL, just fail with a pointer to the documentation for that
syntax.

**Comment by mdomsch** [comment]
To be clear, we're not disabling SSL, we're disabling hostname validation
for SSL - we'll accept any SSL certificate and use SSL encryption, just
without validating the host name we used to contact the server matches the
hostname the server's certificate claims to support.


On Mon, Jan 5, 2015 at 8:11 AM, Dustin J. Mitchell <notifications@github.com

**Comment by djmitche** [comment]
Sorry, yes, I misstated that.

**Comment by muff1nman** [comment]
Thanks @yardenac for packaging that up.

**Comment by wbl** [comment]
Hi: If I understand correctly, someone who has a cert for evil.com will be able to take over any connection your product makes to s3 buckets. I think this is a major security flaw. The "right fix" would be to special-case the handling of only the relevant s3 domain names.

**Comment by mdomsch** [comment]
This is in fact exactly what it does.
            # S3's wildcart certificate doesn't work with DNS-style named buckets.
            if 's3.amazonaws.com' in hostname and http_connection.context:
                http_connection.context.check_hostname = False

The hostname being connected to must be in s3.amazonaws.com (the default).  So the attacker has to both compromise the target's DNS lookup method, and be able to respond as if they were s3.amazonaws.com.

If the python SSL hostname validation code would treat bucket.example.com.s3.amazonaws.com as matching *.s3.amazonaws.com, then we would not need to disable this test.  However, that would then violate RFC 6125 6.4.3  point 2:
2.  If the wildcard character is the only character of the left-most
       label in the presented identifier, the client SHOULD NOT compare
       against anything but the left-most label of the reference
       identifier (e.g., *.example.com would match foo.example.com but
       not bar.foo.example.com or example.com).

But this is exactly the format that Amazon expects the tools to use, and they like bucket names to be formatted like domain names (it helps provide  universal uniqueness of names, and makes their CNAME resolution trivial when serving a bucket as a website).

**Comment by wbl** [comment]
No, it disables hostname verification entirely when connecting to S3. This means anyone else can pretend to be S3, if I understand what the code is doing correctly, and offer any cert they have lying around. You should check the presented cert is in fact a wildcard cert with the offending domain name.

**Comment by mdomsch** [comment]
By the time the connection returns to me, the check has already been
completed in the SSL layer, and failed (if checking is enabled), or passed
(if it was disabled).  There may be a way to add our own validation routine
at this point though.

**Comment by wbl** [comment]
Yeah, I think we were just talking past each other about what's going on. It seems that the ssl library in python will parse and return the cert the other side provided, so implementing a special case for S3 hostnames doesn't look that bad. https://docs.python.org/2/library/ssl.html#ssl.SSLSocket.getpeercert seems to be the key function involved.

**Comment by t-8ch** [comment]
urllib3 would allow you to validate the certificate against a different hostname. (as soon as shazow/urllib3#526 is fixed)

**Comment by mdomsch** [comment]
https://github.com/s3tools/s3cmd/pull/458 has what I believe is a sane fix
for the problem.  Reviews appreciated.

Thanks,
Matt

**Comment by timcreatewell** [comment]
Hi, recently I updated python to 2.7.5 and now I am experiencing this issue (using s3cmd release 1.6.0).  Is there something I can do to rectify this?  Any help would be greatly appreciated!

**Comment by jamshid** [comment]
Not sure, @timcreatewell, but I haven't had problems since I started using a ~/.s3cfg like below, with check_ssl_certificate=False. Also try setting host_bucket the same as host_base -- I think this forces s3cmd to use "bucket in path" rather than "bucket in Host:" style access.

```
$ cat ~/.s3cfg
[default]
access_key = XXX
host_base = mybucket.cloud.example.com
host_bucket = mybucket.cloud.example.com
secret_key = secret
signature_v2=True
check_ssl_certificate = False
use_https = True
```

**Comment by timcreatewell** [comment]
Thanks @jamshid , will give that a go.

**Comment by mdomsch** [comment]
Try master branch please.  There was a fix a few weeks ago needed due to a
2nd python SSL library change in the 2.7.x series. Ugh.

**Comment by timcreatewell** [comment]
Thanks @mdomsch !

**Comment by ksingh7** [comment]
With ``check_ssl_certificate = True``  the following settings works too ( note host_base and host_bucket are same ) . Thanks @jamshid 

```
$ cat ~/.s3cfg
[default]
access_key = XXX
host_base = ceph-s3.ml
host_bucket = ceph-s3.ml
secret_key = secret
check_ssl_certificate = True
use_https = True
```
