### ISSUE TITLE
Add option to support original AWS auth in s3cmd 1.5

### ISSUE THREAD

**Issue by jamshid** [s3tools/s3cmd#445]
Looks like s3cmd 1.5 will switch to AWS4 authentication, which includes the Amazon region in the signature and which requires support of their custom "chunked upload" protocol http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-streaming.html.

Can s3cmd 1.5 provide an option for supporting the old AWS auth? This would be useful for users using s3cmd with S3-compatible storage engines that do not yet support the new protocol [guilty ;-)].

PS: hey can anyone confirm -- the AWS4 chunked upload protocol is redundant if using https, since TLS inherently validates the bits sent by client match what is received, right?

**Comment by mdomsch** [comment]
It should only doube-send for the first file being operated upon, after commit 86ebf0118d53acc81cf8f7070f41cccfa4c20a7b
went in.

I agree it would be nice to do a lightweight probe per endpoint for supported signature versions before doing all other operations.

**Comment by mdomsch** [comment]
I'm going to close this issue as it's fixed now.  We automatically fall back to sig v2 when we get a sane error message, and we have the Config.signature_v2 = True and --signature-v2 options.  Yes, it would be nice to know what signature types a given endpoint supports before we issue the command to it, avoiding a 'double send' for the first object.  But as there are no APIs that tell us this, and I don't really want to hard-code for all known endpoints (which is impossible for all the personally run S3 clones), I'm not going to worry about it.
