### ISSUE TITLE
Access to CloudFront gives "ERROR: [Errno 61] Connection refused"

### ISSUE THREAD

**Issue by nidi3** [s3tools/s3cmd#454]
All commands that access CloudFront fail with the message "ERROR: [Errno 61] Connection refused".
Has this something to do with #402 ?

**Comment by nidi3** [comment]
https://github.com/s3tools/s3cmd/blob/master/S3/CloudFront.py#L547
This does not look like v4 sign.

**Comment by mdomsch** [comment]
CloudFront support in s3cmd is using API version 2010-11-01.   API versions 2013-05-12 and above (including current 2014-11-06) require Signature v4.  Clearly this is in need of some love, and I'd appreciate any help with it.  @nidi3 I would love to see your patch.

**Comment by mdomsch** [comment]
To solve the immediate problem though, we can force CF calls to use HTTPS.  Please see 
https://github.com/mdomsch/s3cmd/tree/bug/cf-ssl
which now does this.  If it works for you, I'll merge this to master.
Thanks,
Matt

**Comment by mdomsch** [comment]
I merged the above into master.  Closing this bug.  Please open a new pull request with your CF v4 signature patch.
