### ISSUE TITLE
s3cmd terminates HTTPS connections without sending "close notify"

### ISSUE THREAD

**Issue by edwintorok** [s3tools/s3cmd#462]
Wishlist bug: please send TLS close notify before shutting down an HTTPS connection.

According to SSL_shutdown(3ssl) "The shutdown procedure consists of 2 steps: the sending of the "close notify" shutdown alert and the reception of the peer's "close notify" shutdown alert. According to the TLS standard, it is acceptable for an application to only send its shutdown alert and then close  the underlying connection without waiting for the peer's response".

But s3cmd doesn't seem to do that it just closes the connection immediately when it is done, which isn't a problem for HTTP, but it is for HTTPS.
This causes "While talking to xx.yy.zz.tt: connection abruptly closed by peer" warnings in LibreS3 for example.

**Comment by mdomsch** [comment]
We're using httplib for this, which seems to call socket.close() directly,
even in latest 2.7.9 on ArchLinux.

**Comment by mdomsch** [comment]
This needs to get taken up with upstream python developers.  Nothing s3cmd can do about it.
