### ISSUE TITLE
put stdin not working

### ISSUE THREAD

**Issue by bertrandom** [s3tools/s3cmd#464]
I've been trying to put data from stdin but it doesn't seem to be working for me. Is this the right syntax?

```
$ echo "Hello" | s3cmd put - s3://testbucket123aaa456/hello.txt
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
WARNING: Forwarding request to us-east-1
<stdin> -> s3://testbucket123aaa456/hello.txt  [part 1, 6B]
ERROR:
Upload of '<stdin>' part 1 failed. Use
  s3://testbucket123aaa456/hello.txt abortmp /usr/local/bin/s3cmd qSSZIkx28g0678FWynEnqg9hDfs0oznI9uY8NJzMz5BEbmcl9o73x0FkAiwXWC1sDiOxmum_f3.QfgAjgwlf9g--
to abort, or
  /usr/local/bin/s3cmd --upload-id qSSZIkx28g0678FWynEnqg9hDfs0oznI9uY8NJzMz5BEbmcl9o73x0FkAiwXWC1sDiOxmum_f3.QfgAjgwlf9g-- put ...
to continue the upload.
ERROR: [Errno 2] No such file or directory: '<stdin>'
```

I'm using s3cmd 1.5.0, I've tried on both Linux and Mac OS X.

**Comment by hamann** [comment]
same here

**Comment by mdomsch** [comment]
I have reproduced this too.  Looks like we need a stdin put test case added
too.

**Comment by mdomsch** [comment]
try with github.com/s3tools/s3cmd master branch please.  I believe this
works now.

Thanks,
Matt

**Comment by bertrandom** [comment]
Thanks for the quick fix, that worked for me!

**Comment by hamann** [comment]
Thanks a lot, works for me, too. But it seems that output is broken with input from stdin

```txt
asking for bucket location
File '-' stored as 's3://x-y-z/d/20150121T000009/wals/00000001000016A5/00000001000016A500000058' (0 bytes in 2.0│ seconds, -1.00 B/s) [1 of 1]
```

The file got transfered, with ~5MB

**Comment by mdomsch** [comment]
Hmm, worked for me with upstream master e64678ae9 now.

$ cat 5mbfile.bin | ./s3cmd put - s3://s3cmd-test.domsch.com/5mbfile.bin
WARNING: Forwarding request to us-east-1
<stdin> -> s3://s3cmd-test.domsch.com/5mbfile.bin  [part 1, 5MB]
 5242880 of 5242880   100% in    2s     2.21 MB/s  done

There is a corner case, trying to put a zero-length file from stdin, which fails, but I think I can live with that...
