### ISSUE TITLE
Utils.sign_url no longer exists

### ISSUE THREAD

**Issue by ataber** [s3tools/s3cmd#469]
Because of [this commit](https://github.com/s3tools/s3cmd/commit/8e4c0d4a4cca9522c731bbaf025f624954f66513), Utils.sign_url no longer exists, but [this line](https://github.com/s3tools/s3cmd/blob/e18c5ff658a7a12c3ecabb601477af31f6e30c85/s3cmd#L1665) requires it.

Thoughts?

**Comment by mdomsch** [comment]
Try master branch now. I think I fixed it.
