### ISSUE TITLE
Problem: ImportError: No module named ExitCodes

### ISSUE THREAD

**Issue by peterski007** [s3tools/s3cmd#471]
Invoking as root runs without any errors but invoking as user apache spits out to the apache error_log, the output below.

I've additionally, tested this by invoking sudo and passing the correct $PATH env in just in case but same problem:
```
sudo PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin -u apache -s bash -c "/usr/bin/php /var/www/html/t.php"
```
```
s3cmd --version
s3cmd version 1.5.0
```
s3cmd was installed by downloading master 'git clone git://github.com/s3tools/s3cmd'
then
python setup.py install

Also tried downloading release tag 1.5.0 & master using the zip file download - all the same!

== Output ==
Invoked as: /usr/bin/s3cmd --rr --progress --delete-removed --preserve --dry-run --config=/var/opt/.s3cfg sync /var/www/html s3://bucket-name.com/
Problem: ImportError: No module named ExitCodes
S3cmd:   unknown version. Module import problem?
python:   2.6.9 (unknown, Sep 13 2014, 00:25:11)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2522, in <module>
    from S3.ExitCodes import *
ImportError: No module named ExitCodes

Your sys.path contains these entries:
	/usr/bin
	/usr/lib64/python26.zip
	/usr/lib64/python2.6
	/usr/lib64/python2.6/plat-linux2
	/usr/lib64/python2.6/lib-tk
	/usr/lib64/python2.6/lib-old
	/usr/lib64/python2.6/lib-dynload
	/usr/lib64/python2.6/site-packages
	/usr/lib64/python2.6/site-packages/PIL
	/usr/lib/python2.6/site-packages
Now the question is where have the s3cmd modules been installed?

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by mdomsch** [comment]
Did you run python setup.py install as root or as a user? Where did it
install the S3/ directory? Why isn't that on apache user's python system
path?

**Comment by peterski007** [comment]
FIXED!!
I'm using php's "passthru()" function to run a s3cmd shell script.

Adding:
 ```putenv('PATH=/usr/bin:/usr/lib:/usr/lib/python2.6/site-packages'); # path to s3cmd```
to my calling php script did the trick!

**Comment by coto2448** [comment]
i have this same issue, following this 3 year old tutorial online messed me up. Noob here attempting to learn how AWS ec2, s3 and other services work. 

my issue:
Your sys.path contains these entries:
        /usr/bin
        /usr/lib64/python27.zip
        /usr/lib64/python2.7
        /usr/lib64/python2.7/plat-linux2
        /usr/lib64/python2.7/lib-tk
        /usr/lib64/python2.7/lib-old
        /usr/lib64/python2.7/lib-dynload
        /usr/local/lib64/python2.7/site-packages
        /usr/local/lib/python2.7/site-packages
        /usr/lib64/python2.7/site-packages
        /usr/lib/python2.7/site-packages
        /usr/lib64/python2.7/dist-packages
        /usr/lib64/python2.7/dist-packages/PIL
        /usr/lib/python2.7/dist-packages
Now the question is where have the s3cmd modules been installed?

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
    Please report the above lines to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

i do have python 3 installed in my windows not sure if that makes a difference??
if not what commands should i try? may need to dumb things down for me a bit, most appreciate it.
