### ISSUE TITLE
Doesn't work with https

### ISSUE THREAD

**Issue by refaelos** [s3tools/s3cmd#472]
Hey,

Nothing works when I enable HTTPS. When I disable it, I can complete the configuration testing and all operations work just fine.

Any ideas why?

**Comment by mdomsch** [comment]
To what  endpoint?

**Comment by refaelos** [comment]
The `s3cmd --configure` doesn't ask me for an endpoint.

**Comment by mdomsch** [comment]
What version?  It works for me from the master branch.


$ ./s3cmd --configure

Enter new values or accept defaults in brackets with Enter.
Refer to user manual for detailed description of all options.

Access key and Secret key are your identifiers for Amazon S3. Leave them
empty for using the env variables.
Access Key: ACCESS_KEY
Secret Key: SECRET_KEY
Default Region [US]:

Encryption password is used to protect your files from reading
by unauthorized persons while in transfer to S3
Encryption password:
Path to GPG program [/usr/bin/gpg]:

When using secure HTTPS protocol all communication with Amazon S3
servers is protected from 3rd party eavesdropping. This method is
slower than plain HTTP, and can only be proxied with Python 2.7 or newer
Use HTTPS protocol [No]: Yes

On some networks all internet access must go through a HTTP proxy.
Try setting it here if you can't connect to S3 directly
HTTP Proxy server name:

New settings:
  Access Key: ACCESS_KEY
  Secret Key: SECRET_KEY
  Default Region: US
  Encryption password:
  Path to GPG program: /usr/bin/gpg
  Use HTTPS protocol: True
  HTTP Proxy server name:
  HTTP Proxy server port: 0

Test access with supplied credentials? [Y/n]
Please wait, attempting to list all buckets...
Success. Your access key and secret key worked fine :-)

Now verifying that encryption works...
Not configured. Never mind.

Save settings? [y/N] y
Configuration saved to '/home/mdomsch/.s3cfg'

**Comment by refaelos** [comment]
Well that's weird... i'm working with the latest 1.5.0

**Comment by mdomsch** [comment]
Run with --debug and maybe that will tell us something.

**Comment by refaelos** [comment]
Here is what i'm getting:
```
WARNING: Retrying failed request: /?prefix=dt=20150202/ (empty or no certificate)
WARNING: Waiting 3 sec...
WARNING: Retrying failed request: /?prefix=dt=20150202/ (empty or no certificate)
WARNING: Waiting 6 sec...
WARNING: Retrying failed request: /?prefix=dt=20150202/ (empty or no certificate)
WARNING: Waiting 9 sec...
WARNING: Retrying failed request: /?prefix=dt=20150202/ (empty or no certificate)
WARNING: Waiting 12 sec...
WARNING: Retrying failed request: /?prefix=dt=20150202/ (empty or no certificate)
WARNING: Waiting 15 sec...
ERROR: S3 Temporary Error: Request failed for: /?prefix=dt=20150202/.  Please try again later.
```
Everything goes well when i'm not using https.

**Comment by mdomsch** [comment]
What OS and version? Seems like a problem with the httplib or ssl library.

**Comment by refaelos** [comment]
Ubuntu 14.04

**Comment by mdomsch** [comment]
I just tried with a new machine:

Welcome to Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-44-generic x86_64)

I installed s3cmd 1.5.0 and python-dateutil into a new virtualenv using
pip, and ran s3cmd --configure, choosing HTTPS = Yes, succeeded, no problem.

**Comment by refaelos** [comment]
Well that's weird ... if you succeeded then I can't say anymore.
Closing.

**Comment by bmurphy1976** [comment]
I'm running into this problem.  It's an issue with 1.5.1.2 but works fine with the previous version (1.5.0alpha3):

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.1 LTS
Release:	14.04
Codename:	trusty
$ uname -a
$ediafly.com 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
$ s3cmd --version
s3cmd version 1.5.0-alpha3
$ s3cmd --config s3cmd.config ls > /dev/null ; echo $?
0
$ pip install --upgrade s3cmd
Collecting s3cmd from https://pypi.python.org/packages/source/s/s3cmd/s3cmd-1.5.1.2.tar.gz#md5=f4cc1b5cb1375f526a4b16f22e22aa9c
  Downloading s3cmd-1.5.1.2.tar.gz (97kB)
    100% |################################| 98kB 2.5MB/s
    Using xml.etree.ElementTree for XML processing
Requirement already up-to-date: python-dateutil in /usr/local/lib/python2.7/dist-packages (from s3cmd)
Requirement already up-to-date: six>=1.5 in /usr/local/lib/python2.7/dist-packages (from python-dateutil->s3cmd)
Installing collected packages: s3cmd
  Found existing installation: s3cmd 1.5.0a3
    Uninstalling s3cmd-1.5.0a3:
      Successfully uninstalled s3cmd-1.5.0a3
  Running setup.py install for s3cmd
    Using xml.etree.ElementTree for XML processing
    changing mode of build/scripts-2.7/s3cmd from 644 to 755
    changing mode of /usr/local/bin/s3cmd to 755
Successfully installed s3cmd-1.5.1.2
$ s3cmd --version
s3cmd version 1.5.1.2
$ s3cmd --config s3cmd.config ls > /dev/null ; echo $?
WARNING: Retrying failed request: / (empty or no certificate)
WARNING: Waiting 3 sec...
WARNING: Retrying failed request: / (empty or no certificate)
WARNING: Waiting 6 sec...
^CSee ya!
130
$
```

**Comment by bmurphy1976** [comment]
Here's my debug output:

```
EBUG: ConfigParser: Reading file 's3cmd.config'
DEBUG: ConfigParser: access_key->AK...17_chars...Q
DEBUG: ConfigParser: access_token->
DEBUG: ConfigParser: add_encoding_exts->
DEBUG: ConfigParser: add_headers->
DEBUG: ConfigParser: bucket_location->US
DEBUG: ConfigParser: cache_file->
DEBUG: ConfigParser: cloudfront_host->cloudfront.amazonaws.com
DEBUG: ConfigParser: default_mime_type->binary/octet-stream
DEBUG: ConfigParser: delay_updates->False
DEBUG: ConfigParser: delete_after->False
DEBUG: ConfigParser: delete_after_fetch->False
DEBUG: ConfigParser: delete_removed->False
DEBUG: ConfigParser: dry_run->False
DEBUG: ConfigParser: enable_multipart->True
DEBUG: ConfigParser: encoding->ANSI_X3.4-1968
DEBUG: ConfigParser: encrypt->False
DEBUG: ConfigParser: follow_symlinks->False
DEBUG: ConfigParser: force->False
DEBUG: ConfigParser: get_continue->False
DEBUG: ConfigParser: gpg_command->/usr/bin/gpg
DEBUG: ConfigParser: gpg_decrypt->%(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_encrypt->%(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_passphrase->...-3_chars...
DEBUG: ConfigParser: guess_mime_type->True
DEBUG: ConfigParser: host_base->s3.amazonaws.com
DEBUG: ConfigParser: host_bucket->%(bucket)s.s3.amazonaws.com
DEBUG: ConfigParser: human_readable_sizes->False
DEBUG: ConfigParser: invalidate_default_index_on_cf->False
DEBUG: ConfigParser: invalidate_default_index_root_on_cf->True
DEBUG: ConfigParser: invalidate_on_cf->False
DEBUG: ConfigParser: list_md5->False
DEBUG: ConfigParser: log_target_prefix->
DEBUG: ConfigParser: mime_type->
DEBUG: ConfigParser: multipart_chunk_size_mb->15
DEBUG: ConfigParser: preserve_attrs->True
DEBUG: ConfigParser: progress_meter->True
DEBUG: ConfigParser: proxy_host->
DEBUG: ConfigParser: proxy_port->0
DEBUG: ConfigParser: recursive->False
DEBUG: ConfigParser: recv_chunk->4096
DEBUG: ConfigParser: reduced_redundancy->False
DEBUG: ConfigParser: secret_key->DM...37_chars...J
DEBUG: ConfigParser: send_chunk->4096
DEBUG: ConfigParser: server_side_encryption->True
DEBUG: ConfigParser: simpledb_host->sdb.amazonaws.com
DEBUG: ConfigParser: skip_existing->False
DEBUG: ConfigParser: socket_timeout->10
DEBUG: ConfigParser: urlencoding_mode->normal
DEBUG: ConfigParser: use_https->True
DEBUG: ConfigParser: verbosity->WARNING
DEBUG: ConfigParser: website_endpoint->http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
DEBUG: ConfigParser: website_error->
DEBUG: ConfigParser: website_index->index.html
DEBUG: Updating Config.Config cache_file ->
DEBUG: Updating Config.Config follow_symlinks -> False
DEBUG: Updating Config.Config verbosity -> 10
DEBUG: Unicodising 'ls' using ANSI_X3.4-1968
DEBUG: Command: ls
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v2
DEBUG: SignHeaders: 'GET\n\n\n\nx-amz-date:Fri, 06 Feb 2015 20:24:17 +0000\n/'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(None): s3.amazonaws.com
DEBUG: ConnMan.get(): creating new connection: https://s3.amazonaws.com
DEBUG: Using ca_certs_file None
DEBUG: non-proxied HTTPSConnection(s3.amazonaws.com)
WARNING: Retrying failed request: / (empty or no certificate)
WARNING: Waiting 3 sec.
```

**Comment by bmurphy1976** [comment]
Also have same problem if I change website_endpoint from http to https.

**Comment by bmurphy1976** [comment]
One final piece of information, 1.5.0 works as well.  It appears to be limited in scope to 1.5.1.2.

**Comment by mdomsch** [comment]
Can you run with --no-check-certificate ?

**Comment by bmurphy1976** [comment]
```
$ s3cmd --version
s3cmd version 1.5.1.2
$ s3cmd --config s3cmd.config ls
WARNING: Retrying failed request: / (empty or no certificate)
WARNING: Waiting 3 sec...
^CSee ya!
$ s3cmd --config s3cmd.config ls --no-check-certificate
WARNING: Retrying failed request: / (empty or no certificate)
WARNING: Waiting 3 sec...
^CSee ya!
```

**Comment by mdomsch** [comment]
I installed a fresh new VM with it (not using the AWS AMI this time), and
have reproduced the failure.
Now to root cause...

**Comment by mdomsch** [comment]
In S3/ConnMan,py:

    def match_hostname(self):
        cert = self.c.sock.getpeercert()

cert is returning as {}.  That fails the validation then.  Now to track
down differences in ssl.py in the main library. :-(

**Comment by mdomsch** [comment]
For the record, between 1.5.0 and 1.5.1.2, I stopped disabling SSL
certificate checking against S3's wildcard cert.  So now we're checking the
certificate again, but for some reason aren't getting the certificate to
check...

**Comment by mdomsch** [comment]
Ah ha.  Ubuntu's ssl library hasn't caught up to python upstream's ssl.py
implementation.  But it has more than Fedora's ssl.py implementation.

Our result from getpeercert() is {}.  Arch (closest to upstream python
2.7.9) says this:

    def getpeercert(self, binary_form=False):
        """Returns a formatted version of the data in
the

        certificate provided by the other end of the SSL
channel.

        Return None if no certificate was provided, {} if
a

        certificate was provided, but not validated."""

In our case, the underlying library didn't do any SSL validation.  So we
shouldn't either.  Patch forthcoming.

**Comment by mdomsch** [comment]
please try master branch.  It's working for me now.

**Comment by mdomsch** [comment]
I've published version 1.5.2 with this fix, and a couple little packaging
fixes.  This is available on 'pip install' now, and is working as expected.

Thanks,
Matt

**Comment by bmurphy1976** [comment]
I can confirm 1.5.2 is working for me.

**Comment by refaelos** [comment]
Thanks @mdomsch  !!
