### ISSUE TITLE
Release 1.5.0 not in PyPi repo?

### ISSUE THREAD

**Issue by feniix** [s3tools/s3cmd#473]
Hi folks,

I tried to install version `1.5.0` of s3cmd and I got this error:

```
pip install -V s3cmd==1.5.0
Collecting s3cmd==1.5.0
  Could not find a version that satisfies the requirement s3cmd==1.5.0 (from versions: 1.0.0, 1.0.1, 1.1.0b2, 1.1.0b3, 1.5.0a1, 1.5.0a2, 1.5.0a3)
  No distributions matching the version for s3cmd==1.5.0
```

Am I doing something wrong?

**Comment by mdomsch** [comment]
I thought I had pushed it there, but apparently I only got the PKG-INFO
updated, but hadn't uploaded the tarball.  I have done so now.  Please give
it a try.

Note that the setup.py file had an incorrect way of specifying installation
requirements, so python-dateutil isn't getting automatically installed.
I've fixed this on upstream master, so it should work on 1.5.1.

Thanks,
Matt
