### ISSUE TITLE
encrypt Secret Key

### ISSUE THREAD

**Issue by toddlahman** [s3tools/s3cmd#475]
Currently the AWS Secret Key is saved as clear text in /root/.s3cfg. Perhaps this value could be encrypted in the event the system is compromised.

**Comment by mdomsch** [comment]
You would then have to get some secret into s3cmd to decrypt the secret key
to make use of it.  :-(  Just as it's rare for SSL certificates to remain
in encrypted form once on the target servers (so you don't have to enter a
secret / password during system startup to start the web server).

You also have the option of somehow getting the secret into the environment
of the program.  Configuration options (e.g. .s3cfg secret_key=$SECRET_KEY)
 will extract the value from the environment variable SECRET_KEY.  That
keeps it off of disk, assuming you have a way to get at the value during
runtime without reading it from disk.
