### ISSUE TITLE
"s3cmd sync" uses excessive requests

### ISSUE THREAD

**Issue by tycho** [s3tools/s3cmd#476]
I was doing an "s3cmd sync &lt;file&gt; &lt;bucket&gt;" (i.e. using it as an as-needed "s3cmd put") I noticed that it was doing hundreds of requests to find the details of all the files in the target bucket, despite the fact that only one transfer could possibly occur, so at most only one metadata fetch would be needed (i.e. if a replacement would happen on the remote end, we need to determine if the replacement is really necessary).

**Comment by mdomsch** [comment]
Yes, for all 'sync' commands, we are retrieving the metadata for each
object.  I agree that test should be moved out of the main execution loop
and be more conditional.  HEAD  S3/FileLists.py lines 449-450 are where
it's getting invoked, which is in the middle of the big "for every object
in the remotelist" loop, and the require_attribs test is always True coming
from one of the top-level sync commands.

I'd be happy to review a patch to improve the behavior.

Thanks,
Matt

**Comment by mdomsch** [comment]
Revise that.  We shouldn't be calling object_info() on all objects during a sync in the 1.5.2 release.  If you put all objects on the command line, then yes, it would; but that's a pretty unusual situation.

It will call object_info on all objects uploaded via multipart upload (so, >15MB by default).  If your tree contains a lot of large objects like that, then yes, it'll call object_info() on each large file to try to retrieve its md5sum (which we can't get from the directory listing ETag for multipart files).

**Comment by tycho** [comment]
Yeah. That is why its doing it. Lots of big objects. But given that the
source is a single file and the destination is a directory I would expect
it to only fetch metadata for any file with the same name. Or perhaps only
fetch the MD5 sums lazily (i.e. when they're actually needed for the sync
operation).

**Comment by mdomsch** [comment]
I've got a start on this.  See github.com/mdomsch/s3cmd branch enhancement/speedups.  It still does calls for multipart-uploaded remote objects.  That can be avoided by using --no-check-md5 but at the cost of not checking md5s anymore.

Also, if you know you only want to push new objects and want to ignore/leave as-is existing objects, you can use --skip-existing.

**Comment by mdomsch** [comment]
#520 may be able to help us here.

**Comment by fviard** [comment]
Closing obsolete issue.
