### ISSUE TITLE
Proxy authentification

### ISSUE THREAD

**Issue by samuelngahane** [s3tools/s3cmd#479]
For security purposes, I must use s3cmd behind a proxy.

s3cmd can be configured with the proxy host and port but is there any way to provide a username and a password for authentification?

**Comment by mdomsch** [comment]
It's more than just username and password.  It would be authentication
method too (e.g. is this an IIS proxy which requires NTLM? Ugh!).

I've had to use apps that talk to a non-authenticating proxy such as cntlm
which then authenticates to an NTLM-authenticing proxy, which then connects
to the outside site.

**Comment by mdomsch** [comment]
httplib gives a way to pass HTTP headers, but then your proxy would have to accept HTTP headers with something in them, and that'll vary by proxy.  We don't send any extra headers when opening a proxy connection right now.  At best, this is a feature request.  My inclination is to close WONTFIX, with the suggestion to use the chain s3cmd -> cntlm -> {proxy} -> S3.

**Comment by samuelngahane** [comment]
Thank you @mdomsch for your suggestion.

**Comment by ernstki** [comment]
@mdomsch Today, good sir, you have changed my life. I was prepared to write off `s3cmd` because I'm behind a corporate HTTP proxy that requires authentication, but `cntlm` fills the gap nicely.
