### ISSUE TITLE
Fatal Python error: GC object already tracked

### ISSUE THREAD

**Issue by dsbcpas** [s3tools/s3cmd#489]
s3cmd version 1.5.2 on compiled version of python-2.7:
Anyone know how to resolve this error? Occurs while running sync command on a local directory.
I found the following searching for this error but I don't understand the fix:

    This usually worked fine but when multiple threads did the same action concurrently it resulted in the Crash with 'GC Object already tracked'.
     Synchronizing the access to python objects for multiple thread does resolve this issue.

**Comment by mdomsch** [comment]
we don't have any multithreading in s3cmd itself, unless somehow it's
coming from a library, but I've never noticed that.

**Comment by dsbcpas** [comment]
Appears to be caused by trickle.

I was also receiving Segmentation faults.
Recompiled `Python-2.7.9, same problems.
Removed trickle from command line; problem solved.  

Any one successfully using trickle?

**Comment by mdomsch** [comment]
upstream github.com/s3tools/s3cmd master branch has a --limit-rate= option
now, so trickle may not be necessary.

**Comment by dsbcpas** [comment]
Sorry to have missed that.

limit_rate = RATE (xxx, xxxk or xxxm seems to also work in .s3cfg

Thank you.
