### ISSUE TITLE
s3cmd 1.5.2 fails for cn-north-1 region

### ISSUE THREAD

**Issue by mdomsch** [s3tools/s3cmd#490]
https://sourceforge.net/p/s3tools/bugs/166/ goes into more detail.  Basically, the several tests for "host.endswith("s3.amazonaws.com")" blow up because cn-north-1 uses <bucket>.s3.cn-north-1.amazonaws.com.cn and you can't direct requests to the US endpoint and have it work.  You have to get the endpoint right, the bucket name right, the canonical_uri right, else signature v4 fails. And we have hard-coded assumptions about host names.

**Comment by mdomsch** [comment]
I have requested a cn-north-1 region account from AWS and await their response.  This will be hard to complete without access to cn-north-1.

**Comment by wbchn** [comment]
@mdomsch 
I am glad to tell you s3cmd 1.5.2 works on cn-north-1 region.

just modify .s3cfg like this, could you put these host settings to command?
```
bucket_location = cn-north-1
host_base = s3.cn-north-1.amazonaws.com.cn
host_bucket = %(bucket)s.s3.cn-north-1.amazonaws.com.cn
website_endpoint = http://%(bucket)s.s3-website-%(location)s.amazonaws.com.cn/
```

Best Regards.

**Comment by sunnycmf** [comment]
@wbchn thanks for sharing the setting,
proved `s3cmd version 1.5.1.2` works as well.

**Comment by fviard** [comment]
@wbchn: Thanks, I have added a new entry in the common issues page with your solution:
https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions#7-problem-s3cmd-not-working-with-a-bucket-in-the-cn-north-1-region
