### ISSUE TITLE
Installing in a non-standard location does not work as well as it did

### ISSUE THREAD

**Issue by tfeb** [s3tools/s3cmd#492]
I install the package (from git) in a non-standard place.  This used to work simply by (after checking out the appropriate release tag):

```
python setup.py install --prefix /path/to/s3cmd
```

That doesn't work in 1.5.2.  I have a workaround which is pretty much as follows:

1. (optionally remove any old `s3cmd` dir so you know it's clean);
2. force the python site library directory to exist with `mkdir -p /path/to/s3cmd/lib/<python>/site-packages/` where `<python>` is, for instance `python-2.7`;
3. install it with `PYTHONPATH=/path/to/s3cmd/lib/<python>/site-packages python setup.py install --prefix /path/to/s3cmd`.

It works fine with this workaround (note you need a wrapper to run it, which I already have).

This may be such an obscure thing that it is not worth supporting or documenting: I do this because I want to be able to run new versions of things without clobbering the old ones.

If it is worth fixing, a sufficient fix is probably to add the above steps to the `INSTALL` (I could do this and submit a pull request if you want).

**Comment by mdomsch** [comment]
use a virtualenv?

**Comment by tfeb** [comment]
I didn't know about those: that's something I'll need to learn about, thanks!

However I can't, because I want to wrap a bunch of other stuff (Perl, native libraries & binaries and so on), and I have a tool which does that (which, itself, I need to put on github in fact!).

But I don't think this is likely worth wasting effort on: I'm probably the only person who has this problem!
