### ISSUE TITLE
Problem with cf-invalidate

### ISSUE THREAD

**Issue by ghost** [s3tools/s3cmd#500]
Hi,

I have a problem.
I have a bucket s3://mycompany.com, in this bucket I have 2 CloudFront CNAMEs.
When I use --cf-invalidate he is creating in the wrong CloudFront invalidate.

I use this command:

/usr/bin/s3cmd -c $S3CMDCFG sync -p --check-md5 --no-progress --region=us-east-1 --add-header="Content-Encoding:gzip" --add-header="Cache-Control: max-age=3600, public" --mime-type="application/json; charset=utf-8" --cf-invalidate $FILE_CF $BUCKET_S3$FILE

regards,

**Comment by maycson-fonseca-movile** [comment]
can someone help me? or has gone through this?
