### ISSUE TITLE
Please add the signature to github too

### ISSUE THREAD

**Issue by LocutusOfBorg** [s3tools/s3cmd#503]
As said, can you please upload the signature here too?

You can attach files in the "releases" page,

thanks

**Comment by LocutusOfBorg** [comment]
closing, seems that it is already there, just debian doesn't pick it up automatically

**Comment by mdomsch** [comment]
I uploaded them last night. The url in the watchfile needs a minor tweak is
all.

**Comment by LocutusOfBorg** [comment]
ough, so you are both upstream and debian? :)

LOL I guess I opened too much pull requests then ;)

**Comment by mdomsch** [comment]
I am not a DD. But I did subscribe to the Debian bugs.
