### ISSUE TITLE
Downloading Objects in Requester Pays Buckets

### ISSUE THREAD

**Issue by andreabedini** [s3tools/s3cmd#511]
From the [developer guide](http://docs.aws.amazon.com/AmazonS3/latest/dev/ObjectsinRequesterPaysBuckets.html):

> Because requesters are charged for downloading data from Requester Pays buckets, the requests must contain a special parameter, `x-amz-request-payer`, which confirms that the requester knows he or she will be charged for the download. 

An example of this usage is documented by [arXiv](http://arxiv.org/help/bulk_data_s3):

    s3cmd ls --add-header="x-amz-request-payer: requester" s3://arxiv/pdf

To support this use case @brendano submitted PR #42, which was reverted on 19 Jan with commit 77f3a1a.

Is there another way to set `x-amz-request-payer` ?

**Comment by mdomsch** [comment]
Try the above branch which has 1 patch beyond master.  use s3cmd get --requester-pays ...

**Comment by andreabedini** [comment]
hi @mdomsch thanks for addressing this so quickly. This now works.

    s3cmd --requester-pays get s3://arxiv/pdf/arXiv_pdf_0001_001.tar

Is there a reason you are passing `x-amz-request-payer` only in `recv_file`? shouldn't it be passed for every call?

**Comment by mdomsch** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/dev/ObjectsinRequesterPaysBuckets.html
indicates it's only useful for GET and POST calls to download an object.  We don't issue any POST calls for an object except for a restore-from-glacier request, or for a batch delete operation.

We could send it for other GET requests such as a bucket listing, I suppose.  Do we need to?  Do you have an example bucket I can try this with?

**Comment by andreabedini** [comment]
`s3://arxiv`. See arXiv's bulk data access [page](http://arxiv.org/help/bulk_data_s3) (at the bottom) for an example.

**Comment by mdomsch** [comment]
ok, a couple patches pushed to that branch.  This moves the setting of that
header into the S3Request() init method for all GET and POST calls where
it's needed.  This also fixes retrieving the object list with [ls] on a
requester-pays bucket.

**Comment by andreabedini** [comment]
works like a charm :thumbsup:

**Comment by mdomsch** [comment]
merged into upstream master.

**Comment by caseybrown89** [comment]
I believe this is also needed on PUT requests when syncing from an S3 bucket that requires requester pays to another S3 bucket.  Using the latest master, --requester-pays doesn't work but you can '--add-header "x-amz-request-payer: requester"' to get it to work.

**Comment by fviard** [comment]
@caseybrown89 The code that was checked in in master was more complete than just the content of this PR.
So, I think that the PUT requests are also covered by what is currently in master. Is there still an issue?

**Comment by caseybrown89** [comment]
Sorry I wasn't very clear.  The point I was trying to make is that "--requester-pays" flag doesn't take effect when syncing from a requester pays bucket to a different S3 bucket.  You can get s3cmd to cover this case by adding the "x-amz-request-payer: requester", but it seems like "--requester-pays" should cover this case as well.

**Comment by fviard** [comment]
Indeed, it looks like that you are right.
I opened the following new issue for this:
https://github.com/s3tools/s3cmd/issues/585

Were you able to validate that this header is taken into account by amazon in the case of the remote copy? and not just ignored?

**Comment by mdomsch** [comment]
Please try with the patch on upstream branch bug/585 and see if that fixes
it.
-Matt

**Comment by caseybrown89** [comment]
That fixed it, thanks!

**Comment by MrChrisRodriguez** [comment]
This still fails for multipart files since s3cmd issues HEAD requests.

### Context
In s3cmd, [multipart file downloads](https://github.com/s3tools/s3cmd/blob/master/S3/FileLists.py#L428) require [HEAD requests](https://github.com/s3tools/s3cmd/blob/master/S3/S3.py#L927) that fail because they [do not include the requester-pays flag](https://github.com/s3tools/s3cmd/blob/master/S3/S3.py#L144).

This requirement is explained in the [AWS docs for RequesterPays buckets](http://docs.aws.amazon.com/AmazonS3/latest/dev/RequesterPaysBuckets.html):

> After you configure a bucket to be a Requester Pays bucket, requesters must include x-amz-request-payer in their requests either in the header, for **POST, GET and HEAD** requests, or as a parameter in a REST request to show that they understand that they will be charged for the request and the data download.

### Solution
Add the requester-pays flag to HEAD requests.
