### ISSUE TITLE
FreeNAS issues

### ISSUE THREAD

**Issue by thejrose1984** [s3tools/s3cmd#514]
Having issues with s3cmd. Originally installed as a plugin on my FreeNAS 9.3 system, but the script kept disappearing and/or not running as instructed in the cron job.

Tried creating a new jail, installing the prerequisites, and pulling fresh code via git clone command.

The following command:
# python2 setup.py install

Yields this output:
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    from setuptools import setup
ImportError: No module named setuptools

I really need a solid way of backup to S3. Any suggestions?

**Comment by mdomsch** [comment]
somehow you need to get setuptools installed (pip install setuptools),
assuming you want to build and install it into /usr/local/bin or somesuch.
Or you can just extract and run it from ./

**Comment by thejrose1984** [comment]
I did and here is the resulting output:

Using xml.etree.ElementTree for XML processing
running install
running bdist_egg
running egg_info
creating s3cmd.egg-info
writing requirements to s3cmd.egg-info/requires.txt
writing s3cmd.egg-info/PKG-INFO
writing top-level names to s3cmd.egg-info/top_level.txt
writing dependency_links to s3cmd.egg-info/dependency_links.txt
writing manifest file 's3cmd.egg-info/SOURCES.txt'
reading manifest file 's3cmd.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 's3cmd.egg-info/SOURCES.txt'
installing library code to build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/S3
copying S3/PkgInfo.py -> build/lib/S3
copying S3/__init__.py -> build/lib/S3
copying S3/SortedDict.py -> build/lib/S3
copying S3/BidirMap.py -> build/lib/S3
copying S3/MultiPart.py -> build/lib/S3
copying S3/Crypto.py -> build/lib/S3
copying S3/FileDict.py -> build/lib/S3
copying S3/HashCache.py -> build/lib/S3
copying S3/Utils.py -> build/lib/S3
copying S3/S3.py -> build/lib/S3
copying S3/CloudFront.py -> build/lib/S3
copying S3/ACL.py -> build/lib/S3
copying S3/FileLists.py -> build/lib/S3
copying S3/AccessLog.py -> build/lib/S3
copying S3/Config.py -> build/lib/S3
copying S3/ConnMan.py -> build/lib/S3
copying S3/ExitCodes.py -> build/lib/S3
copying S3/Progress.py -> build/lib/S3
copying S3/S3Uri.py -> build/lib/S3
copying S3/Exceptions.py -> build/lib/S3
creating build/bdist.freebsd-9.3-RELEASE-p12-amd64
creating build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg
creating build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/Progress.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/AccessLog.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/ExitCodes.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/S3.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/Utils.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/ConnMan.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/SortedDict.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/FileLists.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/Config.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/Crypto.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/HashCache.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/FileDict.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/MultiPart.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/Exceptions.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/PkgInfo.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/BidirMap.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/ACL.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/__init__.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/CloudFront.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
copying build/lib/S3/S3Uri.py -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/Progress.py to Progress.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/AccessLog.py to AccessLog.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/ExitCodes.py to ExitCodes.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/S3.py to S3.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/Utils.py to Utils.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/ConnMan.py to ConnMan.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/SortedDict.py to SortedDict.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/FileLists.py to FileLists.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/Config.py to Config.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/Crypto.py to Crypto.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/HashCache.py to HashCache.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/FileDict.py to FileDict.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/MultiPart.py to MultiPart.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/Exceptions.py to Exceptions.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/PkgInfo.py to PkgInfo.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/BidirMap.py to BidirMap.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/ACL.py to ACL.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/__init__.py to __init__.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/CloudFront.py to CloudFront.pyc
byte-compiling build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/S3/S3Uri.py to S3Uri.pyc
installing package data to build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg
running install_data
creating build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/share
creating build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/share/doc
creating build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/share/doc/packages
creating build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/share/doc/packages/s3cmd
copying README.md -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/share/doc/packages/s3cmd
copying INSTALL -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/share/doc/packages/s3cmd
copying NEWS -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/share/doc/packages/s3cmd
creating build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/share/man
creating build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/share/man/man1
copying s3cmd.1 -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/share/man/man1
creating build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/EGG-INFO
installing scripts to build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/scripts-2.7
copying and adjusting s3cmd -> build/scripts-2.7
changing mode of build/scripts-2.7/s3cmd from 644 to 755
creating build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/EGG-INFO/scripts
copying build/scripts-2.7/s3cmd -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/EGG-INFO/scripts
changing mode of build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/EGG-INFO/scripts/s3cmd to 755
copying s3cmd.egg-info/PKG-INFO -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/EGG-INFO
copying s3cmd.egg-info/SOURCES.txt -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/EGG-INFO
copying s3cmd.egg-info/dependency_links.txt -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/EGG-INFO
copying s3cmd.egg-info/requires.txt -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/EGG-INFO
copying s3cmd.egg-info/top_level.txt -> build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating dist
creating 'dist/s3cmd-1.5.2-py2.7.egg' and adding 'build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg' to it
removing 'build/bdist.freebsd-9.3-RELEASE-p12-amd64/egg' (and everything under it)
Processing s3cmd-1.5.2-py2.7.egg
Copying s3cmd-1.5.2-py2.7.egg to /usr/local/lib/python2.7/site-packages
Adding s3cmd 1.5.2 to easy-install.pth file
Installing s3cmd script to /usr/local/bin

Installed /usr/local/lib/python2.7/site-packages/s3cmd-1.5.2-py2.7.egg
Processing dependencies for s3cmd==1.5.2
Searching for python-magic
Reading https://pypi.python.org/simple/python-magic/
Download error on https://pypi.python.org/simple/python-magic/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581) -- Some packages may not be found!
Couldn't find index page for 'python-magic' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581) -- Some packages may not be found!
No local packages or download links found for python-magic
error: Could not find suitable distribution for Requirement.parse('python-magic')

**Comment by mdomsch** [comment]
It failed https certificate validation downloading the python-magic index
file. The package name and URL is correct otherwise.

**Comment by thejrose1984** [comment]
Any chance you would be willing to update the Free NAS plugin? Or is it something ix systems needs to do?

**Comment by mdomsch** [comment]
I have no way to do it.  Certainly talk to IX Systems and/or their user
group.

**Comment by thejrose1984** [comment]
Got nowhere with FreeNAS plugin and installing via git repository was a major hassle. Was able to install s3cmd in a basic jail using the following commands:

pkg update && pkg upgrade
pkg install net/py-s3cmd

I got the tool install and configured, but, like the original attempt under the version used for the FreeNAS plugin, the schedule task(s) never run! The only difference between the plugin version and the version installed manually as noted above, is that I do not use a SH script to handle the job. Instead, I edit the crontab with the following information (there are no brackets in my actually crontab, those are there for formatting):

[* * * * 7 s3cmd sync /mnt/freenas s3://rosekp]
[* 1 * * * s3cmd sync /mnt/plexhome s3://rosekp]
[* 2 * * * s3cmd sync /mnt/home s3://rosekp]

When the logs found under /var/log/cron show the commands running at their scheduled times, but nothing seems to upload to AWS...

After a couple Google searches, I saw references to specifying the config file in the command, so I updated my cron jobs as follows:

[* * * * 7 s3cmd --config /root/.s3cfg sync /mnt/freenas s3://rosekp]
[* 1 * * * s3cmd --config /root/.s3cfg sync /mnt/plexhome s3://rosekp]
[* 2 * * * s3cmd --config /root/.s3cfg sync /mnt/home s3://rosekp]

If I ran any of those commands manually, they work (mind you it takes a while for the output to show any indicator of upload to the point where I can usually come back in 15 minutes or so before anything shows up). What am I missing???

**Comment by thejrose1984** [comment]
** update **
Running s3cmd manually no longer works. Attempts result in the following error message:
ERROR: Test failed: [Errno 8] hostname nor servname provided, or not known
Reconfiguring doesn't help and neither doesn't blowing out the /root/.s3cfg file and trying again.

**Comment by mdomsch** [comment]
The error you now report is a DNS lookup failure.

**Comment by fviard** [comment]
Legacy bug issue?
Please re-open if you are still encountering issues with latest version.
