### ISSUE TITLE
error Parameter problem:

### ISSUE THREAD

**Issue by sirvon** [s3tools/s3cmd#516]
Thought this was the correct syntax:

```java
creator@creator:~/Downloads/chopped/ogronc$ s3cmd mb s3://radio.myapp.tv/artists/drake
ERROR: Parameter problem: Expecting S3 URI with just the bucket name set instead of 's3://radio.myapp.tv/artists/drake'
```
this is already created:
radio.myapp.tv/artists/
trying to make drake folder under bucket radio.myapp.tv

**Comment by mdomsch** [comment]
The bucket name would be s3://radio.myapp.tv/.

**Comment by sirvon** [comment]
well then how do you create a bucket, I've tried

s3cmd mb s3://radio.app.tv/artists/stylesp/
ERROR
creator@creator:~/Downloads$ s3cmd put *ghost* s3://radio.loqootv.com/artists/stylesp/
ERROR: S3 error: 404 (NoSuchBucket): The specified bucket does not exist

**Comment by mdomsch** [comment]
s3cmd mb s3://radio.app.tv/   creates the bucket named 'radio.app.tv' in
your default region (see your ~/.s3cfg file).

s3cmd uses DNS-hostname-style buckets (S3's recommended naming convention)
to avoid unique bucket name constraint collisions.

**Comment by khurshid-alam** [comment]
@mdomsch How do you create bucket under s3://home/config/ with host name s3.nl-ams.scw.cloud ?
