### ISSUE TITLE
/usr/

### ISSUE THREAD

**Issue by vamitrou** [s3tools/s3cmd#518]
It used to be `/usr/bin/env python` back then. This changed broke my setup. Was there any particular reason for this change?

**Comment by mdomsch** [comment]
Systems (like arch) are starting to make python 3.x the default
/usr/bin/python.  We need to ensure we run with python2.  I've also seen a
failure report when both python 2.6 and 2.7 are installed and available,
and /usr/bin/python2 points at "the wrong one".
