### ISSUE TITLE
v4 signing not working anymore for frankfurt

### ISSUE THREAD

**Issue by vamitrou** [s3tools/s3cmd#519]
v4 signing is not working anymore. Didn't have time to debug yet, if anybody has a clue feel free to share. 

Tried in the frankfurt (eu-central-1) region.

It gets error 400 and falls back to v2 which obviously will not work. 

Tried with an older revision and worked just fine.

( https://github.com/vamitrou/s3cmd/tree/mludvig )

**Comment by mdomsch** [comment]
upstream master does work for me into eu-central-1.  Please post with
--debug and let's figure out what's going on.

There have been a few reports of failures with v4 signatures that I haven't
been able to diagnose and root cause.

**Comment by GlennGeenen** [comment]
DEBUG: ConfigParser: Reading file '/home/glenn/.s3cfg'
DEBUG: ConfigParser: access_key->AK...17_chars...Q
DEBUG: ConfigParser: bucket_location->US
DEBUG: ConfigParser: cloudfront_host->cloudfront.amazonaws.com
DEBUG: ConfigParser: default_mime_type->binary/octet-stream
DEBUG: ConfigParser: delete_removed->False
DEBUG: ConfigParser: dry_run->False
DEBUG: ConfigParser: enable_multipart->True
DEBUG: ConfigParser: encoding->UTF-8
DEBUG: ConfigParser: encrypt->False
DEBUG: ConfigParser: follow_symlinks->False
DEBUG: ConfigParser: force->False
DEBUG: ConfigParser: get_continue->False
DEBUG: ConfigParser: gpg_command->/usr/bin/gpg
DEBUG: ConfigParser: gpg_decrypt->%(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_encrypt->%(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
DEBUG: ConfigParser: gpg_passphrase->AP...33_chars...P
DEBUG: ConfigParser: guess_mime_type->True
DEBUG: ConfigParser: host_base->s3.amazonaws.com
DEBUG: ConfigParser: host_bucket->%(bucket)s.s3.amazonaws.com
DEBUG: ConfigParser: human_readable_sizes->False
DEBUG: ConfigParser: invalidate_on_cf->False
DEBUG: ConfigParser: list_md5->False
DEBUG: ConfigParser: log_target_prefix->
DEBUG: ConfigParser: mime_type->
DEBUG: ConfigParser: multipart_chunk_size_mb->15
DEBUG: ConfigParser: preserve_attrs->True
DEBUG: ConfigParser: progress_meter->True
DEBUG: ConfigParser: proxy_host->
DEBUG: ConfigParser: proxy_port->0
DEBUG: ConfigParser: recursive->False
DEBUG: ConfigParser: recv_chunk->4096
DEBUG: ConfigParser: reduced_redundancy->False
DEBUG: ConfigParser: secret_key->fF...37_chars...g
DEBUG: ConfigParser: send_chunk->4096
DEBUG: ConfigParser: simpledb_host->sdb.amazonaws.com
DEBUG: ConfigParser: skip_existing->False
DEBUG: ConfigParser: socket_timeout->300
DEBUG: ConfigParser: urlencoding_mode->normal
DEBUG: ConfigParser: use_https->True
DEBUG: ConfigParser: verbosity->WARNING
DEBUG: ConfigParser: website_endpoint->http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
DEBUG: ConfigParser: website_error->
DEBUG: ConfigParser: website_index->index.html
DEBUG: Updating Config.Config encoding -> UTF-8
DEBUG: Updating Config.Config follow_symlinks -> False
DEBUG: Updating Config.Config verbosity -> 10
DEBUG: Unicodising 'put' using UTF-8
DEBUG: Unicodising 'backup-2015-05-15-090600.tar.gz' using UTF-8
DEBUG: Unicodising 's3://geenenbackup' using UTF-8
DEBUG: Command: put
INFO: Compiling list of local files...
DEBUG: DeUnicodising u'' using UTF-8
DEBUG: DeUnicodising u'backup-2015-05-15-090600.tar.gz' using UTF-8
DEBUG: Unicodising 'backup-2015-05-15-090600.tar.gz' using UTF-8
DEBUG: Unicodising 'backup-2015-05-15-090600.tar.gz' using UTF-8
INFO: Applying --exclude/--include
DEBUG: CHECK: backup-2015-05-15-090600.tar.gz
DEBUG: PASS: backup-2015-05-15-090600.tar.gz
INFO: Summary: 1 local files to upload
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
DEBUG: Content-Type set to 'application/x-tar'
DEBUG: String 'backup-2015-05-15-090600.tar.gz' encoded to 'backup-2015-05-15-090600.tar.gz'
DEBUG: SignHeaders: 'PUT\n\napplication/x-tar\n\nx-amz-date:Fri, 15 May 2015 09:10:40 +0000\n/geenenbackup/backup-2015-05-15-090600.tar.gz'
DEBUG: CreateRequest: resource[uri]=/backup-2015-05-15-090600.tar.gz
DEBUG: Unicodising 'backup-2015-05-15-090600.tar.gz' using UTF-8
DEBUG: SignHeaders: 'PUT\n\napplication/x-tar\n\nx-amz-date:Fri, 15 May 2015 09:10:40 +0000\n/geenenbackup/backup-2015-05-15-090600.tar.gz'
backup-2015-05-15-090600.tar.gz -> s3://geenenbackup/backup-2015-05-15-090600.tar.gz  [1 of 1]
DEBUG: get_hostname(geenenbackup): geenenbackup.s3.amazonaws.com
DEBUG: format_uri(): /backup-2015-05-15-090600.tar.gz
 37065 of 37065   100% in    0s   109.11 kB/sDEBUG: Response: {'status': 400, 'headers': {'x-amz-region': 'eu-central-1', 'x-amz-id-2': 'o7/T16A9YxyCIklZWOWqUuzCmQxDebKxnr9xEKEd8sFEJqfvbRawuWTOw9ezYK/oucwEnR8cNBY=', 'server': 'AmazonS3', 'transfer-encoding': 'chunked', 'connection': 'close', 'x-amz-request-id': 'E3458AE746A2ED4B', 'date': 'Fri, 15 May 2015 09:10:40 GMT', 'content-type': 'application/xml'}, 'reason': 'Bad Request', 'data': '<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>E3458AE746A2ED4B</RequestId><HostId>o7/T16A9YxyCIklZWOWqUuzCmQxDebKxnr9xEKEd8sFEJqfvbRawuWTOw9ezYK/oucwEnR8cNBY=</HostId></Error>', 'size': 37065}
 37065 of 37065   100% in    0s    96.86 kB/s  done
DEBUG: S3Error: 400 (Bad Request)
DEBUG: HttpHeader: x-amz-region: eu-central-1
DEBUG: HttpHeader: x-amz-id-2: o7/T16A9YxyCIklZWOWqUuzCmQxDebKxnr9xEKEd8sFEJqfvbRawuWTOw9ezYK/oucwEnR8cNBY=
DEBUG: HttpHeader: server: AmazonS3
DEBUG: HttpHeader: transfer-encoding: chunked
DEBUG: HttpHeader: connection: close
DEBUG: HttpHeader: x-amz-request-id: E3458AE746A2ED4B
DEBUG: HttpHeader: etag: 
DEBUG: HttpHeader: date: Fri, 15 May 2015 09:10:40 GMT
DEBUG: HttpHeader: content-type: application/xml
DEBUG: ErrorXML: Code: 'InvalidRequest'
DEBUG: ErrorXML: Message: 'The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.'
DEBUG: ErrorXML: RequestId: 'E3458AE746A2ED4B'
DEBUG: ErrorXML: HostId: 'o7/T16A9YxyCIklZWOWqUuzCmQxDebKxnr9xEKEd8sFEJqfvbRawuWTOw9ezYK/oucwEnR8cNBY='
DEBUG: S3Error: 400 (Bad Request)
DEBUG: HttpHeader: x-amz-region: eu-central-1
DEBUG: HttpHeader: x-amz-id-2: o7/T16A9YxyCIklZWOWqUuzCmQxDebKxnr9xEKEd8sFEJqfvbRawuWTOw9ezYK/oucwEnR8cNBY=
DEBUG: HttpHeader: server: AmazonS3
DEBUG: HttpHeader: transfer-encoding: chunked
DEBUG: HttpHeader: connection: close
DEBUG: HttpHeader: x-amz-request-id: E3458AE746A2ED4B
DEBUG: HttpHeader: etag: 
DEBUG: HttpHeader: date: Fri, 15 May 2015 09:10:40 GMT
DEBUG: HttpHeader: content-type: application/xml
DEBUG: ErrorXML: Code: 'InvalidRequest'
DEBUG: ErrorXML: Message: 'The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.'
DEBUG: ErrorXML: RequestId: 'E3458AE746A2ED4B'
DEBUG: ErrorXML: HostId: 'o7/T16A9YxyCIklZWOWqUuzCmQxDebKxnr9xEKEd8sFEJqfvbRawuWTOw9ezYK/oucwEnR8cNBY='
ERROR: S3 error: 400 (InvalidRequest): The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.

**Comment by mdomsch** [comment]
This is simply using an old version of s3cmd.  You must use v1.5.2 or
thereabouts where that capability was added.

Thanks,
Matt

**Comment by GlennGeenen** [comment]
Thank you. I followed install instructions that link to http://s3tools.org/repo/deb-all/stable/ and that indeed is version 1.0.

**Comment by mdomsch** [comment]
yeah, the repos on s3tools.org are out of date and should probably just be
pulled down.  Debian experimental and unstable, and Ubuntu Wily all have
1.5.2 now.

**Comment by GlennGeenen** [comment]
I just used 1.6 for eu-central-1, everything works fine.
