### ISSUE TITLE
Modify Won't Set Reduced-Redundancy

### ISSUE THREAD

**Issue by jamiejackson** [s3tools/s3cmd#530]
https://github.com/s3tools/s3cmd/blob/e7fad103ca2e485598f67a787c2789eb460dd9cb/S3/S3.py#L728

**Comment by mdomsch** [comment]
https://docs.aws.amazon.com/AmazonS3/latest/dev/ChgStoClsOfObj.html
says you have to do a COPY, not a REPLACE.  Just issue a 's3cmd cp --reduced-redundancy <src> <dest>   where src and dest are identical, to change from STANDARD to RR, or drop the --reduced-redundancy to change from RR to STANDARD.

**Comment by jamiejackson** [comment]
> It is not possible to change the storage class of a specific version of an object. When you copy it, Amazon S3 gives it a new version ID.

The patch in the pull request *seems* to do the right thing, but I guess AWS must be doing a copy under the covers? (Or maybe it's just a quirk of the s3cmd implementation, I didn't dig that much.)

*If* it's AWS that does the copy under the covers, I guess the question is do we allow it or prohibit it? If AWS allows it, I think s3cmd should, too.

(This might all be naive, as I'm very new to both AWS/S3 and s3cmd.)

Thanks for pointing out the `s3cmd cp --reduced-redundancy` alternative, BTW.
