### ISSUE TITLE
global name 'dateutil' is not defined

### ISSUE THREAD

**Issue by m0tter** [s3tools/s3cmd#534]
Hi,
I'm having a problem, here's a copy of the error:

Invoked as: ./s3cmd sync --skip-existing --recursive /shares/data/ s3://ausbucket/backup/
Problem: NameError: global name 'dateutil' is not defined
S3cmd:   1.5.2
python:   2.7.3 (default, May 21 2013, 16:26:58)
[GCC 4.3.2]
environment LANG=None

Traceback (most recent call last):
  File "./s3cmd", line 2550, in <module>
    rc = main()
  File "./s3cmd", line 2462, in main
    rc = cmd_func(args)
  File "./s3cmd", line 1481, in cmd_sync
    return cmd_sync_local2remote(args)
  File "./s3cmd", line 1458, in cmd_sync_local2remote
    any_child_failed = _single_process(local_list)
  File "./s3cmd", line 1263, in _single_process
    rc = _child(destination_base, local_list)
  File "./s3cmd", line 1339, in _child
    remote_list, dst_exclude_list = fetch_remote_list(destination_base, recursive = True, require_attribs = True)
  File "/home/root/s3cmd-1.5.2/S3/FileLists.py", line 419, in fetch_remote_list
    objectlist = _get_filelist_remote(uri, recursive = True)
  File "/home/root/s3cmd-1.5.2/S3/FileLists.py", line 385, in _get_filelist_remote
    'timestamp' : dateS3toUnix(object['LastModified']), ## Sadly it's upload time, not our lastmod time :-(
  File "/home/root/s3cmd-1.5.2/S3/Utils.py", line 160, in dateS3toUnix
    return timegm(dateS3toPython(date).utctimetuple())
  File "/home/root/s3cmd-1.5.2/S3/Utils.py", line 155, in dateS3toPython
    return dateutil.parser.parse(date, fuzzy=True)
NameError: global name 'dateutil' is not defined
## 

I haven't tried debug sorry as it takes about an hour to fail. Was hoping the error above may have enough information. S3cmd has backed up about 35000 of 115000 files OK. Not sure if this is part of the problem, I'm running in a read only file system, the only way to modify the PYTHONPATH (to reference dateutil) is to use sys.path.append at the start of the s3cmd.py file.

I'm using --skip-existing because S3cmd crashed with "error: S3 error: The request signature we calculated does not match the signature you provided. Check your key and signing method". I was trying to restart where the backup had stopped.

Thanks

**Comment by mdomsch** [comment]
Do you have python-dateutil (the RPM or DPKG) installed?  I want to think
so, as startup should have failed if not.

Assuming yes, then why would that fail now and not earlier?  That's really
odd.  I don't have an explanation.

**Comment by m0tter** [comment]
Hi,
Yes python-dateutil is installed. It fails at launch if dateutil is missing. I've installed dateutil from source (no package manager). I'll try to catch a debug output.
Thanks

**Comment by m0tter** [comment]
Here's the debug output (I [removed] some of the identifying data):

<LastModified>2015-04-25T12:35:49.000Z</LastModified><ETag>&quot;15bccefd5cc2e6a85197b4654003068f&quot;</ETag><Size>32339</Size><Owner><ID>[removed]</ID><DisplayName>[removed]</DisplayName></Owner><StorageClass>STANDARD</StorageClass></Contents></ListBucketResult>'}
DEBUG: ConnMan.put(): connection put back to pool (http://[removed].s3.amazonaws.com#1)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

DEBUG: Unicodising './s3cmd' using ANSI_X3.4-1968
DEBUG: Unicodising 'sync' using ANSI_X3.4-1968
DEBUG: Unicodising '--skip-existing' using ANSI_X3.4-1968
DEBUG: Unicodising '--recursive' using ANSI_X3.4-1968
DEBUG: Unicodising '-d' using ANSI_X3.4-1968
DEBUG: Unicodising '/shares/[removed]/' using ANSI_X3.4-1968
DEBUG: Unicodising 's3://[removed]/backup/' using ANSI_X3.4-1968
Invoked as: ./s3cmd sync --skip-existing --recursive -d /shares/[removed]/ s3://[removed]/backup/
Problem: NameError: global name 'dateutil' is not defined
S3cmd:   1.5.2
python:   2.7.3 (default, May 21 2013, 16:26:58)
[GCC 4.3.2]
environment LANG=None

Traceback (most recent call last):
  File "./s3cmd", line 2550, in <module>
    rc = main()
  File "./s3cmd", line 2462, in main
    rc = cmd_func(args)
  File "./s3cmd", line 1481, in cmd_sync
    return cmd_sync_local2remote(args)
  File "./s3cmd", line 1458, in cmd_sync_local2remote
    any_child_failed = _single_process(local_list)
  File "./s3cmd", line 1263, in _single_process
    rc = _child(destination_base, local_list)
  File "./s3cmd", line 1339, in _child
    remote_list, dst_exclude_list = fetch_remote_list(destination_base, recursive = True, require_attribs = True)
  File "/home/root/s3cmd-1.5.2/S3/FileLists.py", line 419, in fetch_remote_list
    objectlist = _get_filelist_remote(uri, recursive = True)
  File "/home/root/s3cmd-1.5.2/S3/FileLists.py", line 385, in _get_filelist_remote
    'timestamp' : dateS3toUnix(object['LastModified']), ## Sadly it's upload time, not our lastmod time :-(
  File "/home/root/s3cmd-1.5.2/S3/Utils.py", line 160, in dateS3toUnix
    return timegm(dateS3toPython(date).utctimetuple())
      File "/home/root/s3cmd-1.5.2/S3/Utils.py", line 155, in dateS3toPython
    return dateutil.parser.parse(date, fuzzy=True)
NameError: global name 'dateutil' is not defined

-----------------

I've fixed the PYTHONPATH so I no longer have sys.path.append statement at the beginning of s3cmd. I added 'print date' to the dateS3toPython function, it printed one date('2015-04-24T05:28:50.000Z') before failing at the parser statement.
Using that output I ran the following manually:

import dateutil.parser
import re
date = 2015-04-24T05:28:50.000Z
date = re.compile('\.[0-9]*(?:[Z\\-\\+]*?)').sub(".000", date)
print dateutil.parser.parse(date, fuzzy=True)
2015-04-24 05:28:50+00:00

I'm not sure what else to check, everything appears to working when ran manually.

Thanks

**Comment by fviard** [comment]
Just in case you are still encountering the issue, that happened for me when testing in virtualenv with python2 and python3.
Try running s3cmd through the same python interpreter as the one you used to "setup.py install" dateutils.
So, instead of doing:
./s3cmd ...
do:
python ./s3cmd ...
