### ISSUE TITLE
option delay-updates is outdate?

### ISSUE THREAD

**Issue by flisky** [s3tools/s3cmd#535]
The commit 1703df700932f08bc99682e5ca4d9b73fd0b9e1b removes the logic of `delay_updates`, so the option `delay-updates` seems redundant.

I'm glad to send a PR if you confirm it:)

**Comment by mdomsch** [comment]
You are correct, --delay-updates no longer exists.  Yes, a patch would be
welcome.  Please leave the optparser.add_option() line, but mark it as
OBSOLETE so as to not break existing scripts, and leave it in Config() but
also mark it as OBSOLETE so as to not break existing config file parsing.

Thanks,
Matt
