### ISSUE TITLE
Cf-invalidate parameter is ignored

### ISSUE THREAD

**Issue by chrisspen** [s3tools/s3cmd#536]
The `--cf-invalidate` option never seems to generate any invalidation requests.

If I run:

```
s3cmd put --progress --acl-public --guess-mime-type --no-mime-magic --cf-invalidate --recursive  --force /local_path/ s3://mybucket/remote_path/
```

and I see N items uploaded, I would expect to see an invalidation request generated for those N files in Cloudfront. However, after running this, no new requests exist for the Cloudfront distribution linked to that S3 bucket.

**Comment by fviard** [comment]
Closing as should already be fixed in recent versions.
