### ISSUE TITLE
setting mime type works in 1.5.0 but not 1.5.2

### ISSUE THREAD

**Issue by jnovotny** [s3tools/s3cmd#541]
We found a bug recently where the command:

/usr/bin/s3cmd put
/home/trizic/accelerator/angular-frontend/dist/scripts/
s3://trizic-qa2/scripts/ -P -r --mime-type='text/javascript;charset=utf-8'

works with 1.5.0 but not 1.5.2 (it does not set the mime type accordingly)

**Comment by fviard** [comment]
Issue should already be fixed as i'm not able to reproduce the issue with 2.0.1.
