### ISSUE TITLE
Problems with encoding french accented characters to s3

### ISSUE THREAD

**Issue by brunobhr** [s3tools/s3cmd#543]
Hello,
I'm having trouble with french-accented characters in filenames when uploading to s3 with s3cmd v1.5.0-rc1

The accented characters get replaced with a video inverted question mark, and then remotely copied:

remote copy: 02 XXXXX/03 MUSIC/05 SINGLE 1 VOLCANO/01 MUSIC/04 PROTOOLS SESSIONS/Volcano/EXPORTS TRACKS SÉPARÉS/Celli 2_01.wav -> 02 XXXXX/03 MUSIC/05 SINGLE 1 VOLCANO/01 MUSIC/04 PROTOOLS SESSIONS/Volcano/EXPORTS TRACKS SE?PARE?S/Celli 2_01.wav

The second time they are uploaded, the question marks are doubled:

remote copy: 02 XXXXX/03 MUSIC/05 SINGLE 1 VOLCANO/01 MUSIC/04 PROTOOLS SESSIONS/Volcano/EXPORTS TRACKS SE?PARE?S/Celli 2_01.wav -> 02 XXXXX/03 MUSIC/05 SINGLE 1 VOLCANO/01 MUSIC/04 PROTOOLS SESSIONS/Volcano/EXPORTS TRACKS SE??PARE??S/Celli 2_01.wav

Any help would be greatly appreciated,
Best regards,
Bruno

**Comment by brunobhr** [comment]
I am using s3cmd via a crontab on Mavericks client 10.9.5.
The computer itself is configured in English language, if this can help.

Any help would be greatly appreciated,
Best regards,
Bruno

**Comment by mdomsch** [comment]
what is in your environment being run by cron?  Specifically, what LANG=
value is set?  Perhaps it's not a UTF-8-enabled LANG?

**Comment by brunobhr** [comment]
Hello Matt,
Thank you very much for your answer.
I edited both root's and my admin account's .bash_profile and added:

LANG="fr_FR.UTF-8"
LC_ALL="fr_FR.UTF-8"

When run manually from bash, the scripts works perfectly, with the correct accents.
But when ran from a crontab, the problem starts again.

I'm not sure what to edit in the root account..

Thank you for your help,
Regards,
Bruno

**Comment by mdomsch** [comment]
Normally .bash_profile is not read for cronjobs.  You would need to
explicitly set these at the top of your crontab file as well.

**Comment by brunobhr** [comment]
Matt, I just added:
* 22 * * * LC_ALL="fr_FR.UTF-8"
to my crontab, and it worked perfectly!
All the accents have been corrected by the new upload.
Thank you very much for your help and for s3cmd.

With my best regards,
Bruno

**Comment by brunobhr** [comment]
Hi Matt,
After installing 1.5.2, I'm again getting errors and bad character encoding.
I'm running this command in a crontab:
" * 22 * * * LC_ALL="fr_FR.UTF-8" s3cmd xxxxxxxxxxx"
And I'm getting:
UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal.
And the accented characters get encoded wrong.

Any help would be greatly appreciated, I'm desperate to have a simple backup task
running with s3cmd, but I've been running into problems for weeks now.

Thank you very much,
Bruno

**Comment by brunobhr** [comment]
Hello,
I'm still trying to run a s3cmd backup from cron.
This time I have this type of errors:
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/S3/S3.py:487: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal

My locale is:
Lun jui 08: 21:17:41 /Volumes:locale
LANG="fr_FR.UTF-8"
LC_COLLATE="fr_FR.UTF-8"
LC_CTYPE="fr_FR.UTF-8"
LC_MESSAGES="fr_FR.UTF-8"
LC_MONETARY="fr_FR.UTF-8"
LC_NUMERIC="fr_FR.UTF-8"
LC_TIME="fr_FR.UTF-8"
LC_ALL="fr_FR.UTF-8"

My crontab starts with " * 22 * * * LC_ALL="fr_FR.UTF-8" s3cmd xxxxxxxxxxx"

I'm really running out of hope.

Any help would be greatly appreciated
Thank you very much

**Comment by fviard** [comment]
Encoding issues should already be fixed I hope. (providing that the cron is well set to utf-8)
