### ISSUE TITLE
Small bug in Makefile

### ISSUE THREAD

**Issue by bprotopopov** [s3tools/s3cmd#544]
Makefile incorrectly lists README file instead of README.md, so the 'make git-tarball' fails.  Here is the diff that fixes it:
$ git diff
diff --git a/Makefile b/Makefile
index 45183d4..b975f7c 100644
--- a/Makefile
+++ b/Makefile
@@ -21,7 +21,7 @@ $(SPEC): $(SPEC).in

 # fixme: python setup.py sdist also generates a PKG-INFO file which we don't have using straight git archive
 git-tarball:
-       git archive --format tar --prefix s3cmd-$(COMMIT)/ HEAD S3/ s3cmd NEWS README INSTALL setup.cfg s3cmd.1 s
- ```
    git archive --format tar --prefix s3cmd-$(COMMIT)/ HEAD S3/ s3cmd NEWS README.md INSTALL setup.cfg s3cmd.
  ```
  # Use older digest algorithms for local rpmbuilds, as EPEL5 and
  # earlier releases need this.  When building using mock for a
  
  (END)

**Comment by mdomsch** [comment]
Patch applied, thanks!
