### ISSUE TITLE
sync should preserve ACL's

### ISSUE THREAD

**Issue by gerryster** [s3tools/s3cmd#547]
I have a production bucket and a staging bucket.  I periodically sync the production bucket to the staging bucket.  My production bucket has some public and private files.  When I sync to staging, I notice that files are copied with only `ACL:       admin: FULL_CONTROL` permission when the source file on production has the following permissions:

```
   ACL:       admin: FULL_CONTROL
   ACL:       *anon*: READ
```

Could there be a preserve ACL option be added to sync?

I am using s3cmd version 1.5.2.

**Comment by mdomsch** [comment]
try with the above patch / branch please.

**Comment by gerryster** [comment]
:+1: that works for me.  I verified with both public and private files and they were both correct.  Thank you!

**Comment by mdomsch** [comment]
Merged in master.

**Comment by mdomsch** [comment]
No, it's not merged yet.
