### ISSUE TITLE
Error when running s3cmd from a crontab

### ISSUE THREAD

**Issue by brunobhr** [s3tools/s3cmd#548]
Hello,
I am having trouble running a s3cmd scripts from a crontab.
When ran 'manually' the scripts run just fine.
But when ran from a crontab I get this error every time:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   An unexpected error has occurreWARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
WARNING: Upload failed: /ALEXANDRE%20XXXSHOP%WARNING: Retrying failed request: /?marker=AUTRES/CHLOE%CC%81/XXXXXXX/POWER%20MASTERED%20261012.mp3 ('')
WARNING: Waiting 3 sec...
WARNING: Retrying failed request: /?marker=AUTRES/CLAM/--MBP_NEPASEFFACER/ETOILE/JOBS/TONIC/2012XXXXtt%20session%20mix%20110312/Elephant%20MXXXFade%20Files/Fade%20pbgfWBWVmpcgFRVW.wav ('')
WARNING: Waiting 3 sec...
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
WARNING: Upload failed: /ALEX/01%2029%20SCH%2030s%20V1.mov ([Errno 32] Broken pipe)
WARNING: Retrying on lower speed (throttle=0.00)
WARNING: Waiting 3 sec...
WARNING: Upload failed: /CLEM_L/clem.sparseimage?partNumber=1111&uploadId=jLA_UQKMgh8chbvjVnDy4YfIOFOa7HmhZr3nisPUuMgTdQUBCU.sw4BGTt6hkw5eRIJIsLNTfQx8VIzE5hmsyA-- ('')
WARNING: Retrying on lower speed (throttle=0.00)
WARNING: Waiting 3 sec...
rgs)
 File "/usr/local/bin/s3cmd", line 1442, in cmd_sync_local2remote
   local_list, single_file_local, src_exclude_list = fetch_local_list(args[:-1], is_src = True, recursive = True)
 File "/Library/Python/2.7/site-packages/S3/FileLists.py", line 318, in fetch_local_list
   _maintain_cache(cache, local_list)
 File "/Library/Python/2.7/site-packages/S3/FileLists.py", line 274, in _maintain_cache
   cache.unmark_for_purge(local_list[i]['dev'], local_list[i]['inode'], local_list[i]['mtime'], local_list[i]['size'])
KeyError: 'dev'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

And here is my s3cmd command ran from cron:
/usr/local/bin/s3cmd sync --progress --server-side-encryption --delete-removed --skip-existing --cache-file=/Users/admin/logs/studio_sh/cache/studio_cache --exclude='@Recycle/*' --exclude='.DS_Store' /Volumes/STUDIO/ s3://studio-bkp/ >/Users/admin/logs/studio_sh/stdout/stdout.log 2>/Users/admin/logs/studio_sh/stderr/stderr.log

Does anybody have an idea?

Thank you for your help.,
Bruno

**Comment by mdomsch** [comment]
Be sure to set your cron environment correctly.  Specifically,
LANG=en_US.UTF-8   is a really good thing to have at the top of your
crontab file.

Also, check your s3cmd version.  You aren't running 1.5.2 or upstream
master which has many more bugfixes.

Thanks,
Matt

**Comment by brunobhr** [comment]
Thank you Matt,
I am now running 1.5.2 from a crontab.
I'm still getting errors.
Here is my crontab:
* 21 * * 4	LC_ALL="fr_FR.UTF-8" /Users/admin/scripts/studio.sh
I am using French locale as I have french-accented characters in my filenames.

And here's the error:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd sync --progress --server-side-encryption --delete-removed --skip-existing --cache-file=/Users/admin/logs/studio_sh/cache/studio_cache --exclude=@Recycle/* --exclude=.DS_Store /Volumes/STUDIO/ s3://studio-bkp/
Problem: gaierror: [Errno 8] nodename nor servname provided, or not known
S3cmd:   1.5.2
python:   2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]
environment LANG=None

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2586, in <module>
  File "/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2498, in main
  File "/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1496, in cmd_sync
  File "/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1473, in cmd_sync_local2remote
  File "/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1278, in _single_process
  File "/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1414, in _child
  File "/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1338, in _upload
  File "build/bdist.macosx-10.9-intel/egg/S3/S3.py", line 568, in object_put
    return self.send_file_multipart(file, headers, uri, size)
  File "build/bdist.macosx-10.9-intel/egg/S3/S3.py", line 1233, in send_file_multipart
    upload = MultiPartUpload(self, file, uri, headers)
  File "build/bdist.macosx-10.9-intel/egg/S3/MultiPart.py", line 25, in __init__
    self.upload_id = self.initiate_multipart_upload()
  File "build/bdist.macosx-10.9-intel/egg/S3/MultiPart.py", line 72, in initiate_multipart_upload
    response = self.s3.send_request(request)
  File "build/bdist.macosx-10.9-intel/egg/S3/S3.py", line 998, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "build/bdist.macosx-10.9-intel/egg/S3/ConnMan.py", line 161, in get
    conn.c.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1172, in connect
    self.timeout, self.source_address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 553, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno 8] nodename nor servname provided, or not known

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


Any help would be greatly appreciated,
Bruno

**Comment by mdomsch** [comment]
This failure is DNS-related - it cannot look up the hostname you have given
it.  Verify it is finding the right config file, and that your config file
has valid values for:

host_base = s3.amazonaws.com
host_bucket = %(bucket)s.s3.amazonaws.com

**Comment by brunobhr** [comment]
Hi Matt,
My ~/.s3cfg file has:
host_base = s3.amazonaws.com
host_bucket = %(bucket)s.s3.amazonaws.com

But as s3cmd runs from a crontab, is it the one that is read?

Should I have a copy of my ~/.s3cfg somewhere else?
In the root account maybe?

Thanks for your help,
Bruno

**Comment by mdomsch** [comment]
Is this running as root?  If so, then yes you need to put it in
/root/.s3cfg.   Or pass -c /path/to/s3cfg

**Comment by brunobhr** [comment]
According to this post, yes:
http://www.codeadventures.com/using-s3cmd-in-a-cron-job/

I just did a cp -i ~/.s3cfg /private/var/root/.s3cfg and will give it a go.

**Comment by brunobhr** [comment]
The script is running as ROOT as it is launched from a CRON job.
But then, how come did the script found the AWS key if it didn't read the .s3cfg in my user account?
There was no .s3cfg in /private/var/root/ and still the script manage to connect and upload..
I am very confused.
Thank you for your help.

**Comment by mdomsch** [comment]
if it's running inside an EC2 instance it may have picked it up
automatically from self discovery service.

**Comment by brunobhr** [comment]
No, it's running on a Mac mini OSX 10.9 Mavericks

**Comment by brunobhr** [comment]
I'm really starting to be desperate.
s3cmd looks impossible to run from a crontab.
I've tried for weeks now and I can't get it to work.


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd sync --progress --server-side-encryption --delete-removed --skip-existing --cache-file=/Users/admin/logs/dropbox_sh/cache/dropbox_cache --exclude=@Recycle/* --exclude=.DS_Store /Volumes/DROPBOX/ s3://dropbox-bkp/
Problem: KeyError: 'dev'
S3cmd:   1.5.2
python:   2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]
environment LANG=None

Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2586, in <module>
  File "/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2498, in main
  File "/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1496, in cmd_sync
  File "/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1466, in cmd_sync_local2remote
  File "build/bdist.macosx-10.9-intel/egg/S3/FileLists.py", line 342, in fetch_local_list
    _maintain_cache(cache, local_list)
  File "build/bdist.macosx-10.9-intel/egg/S3/FileLists.py", line 298, in _maintain_cache
    cache.unmark_for_purge(local_list[i]['dev'], local_list[i]['inode'], local_list[i]['mtime'], local_list[i]['size'])
KeyError: 'dev'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

I would to have to ditch s3cmd, as I've spent so many hours trying to
put up a simple backup routine.

Any help would be very appreciated.

**Comment by mdomsch** [comment]
You have a mix of s3cmd 1.5.2 and some other version installed somehow.  I
know this because S3/FileLists line 289 in v1.5.2 is not the lines you are
showing here.  Please ensure you have removed all vestages of previous
installs and then re-install v1.5.2.

**Comment by brunobhr** [comment]
Thank you Matt,
Do you mean line 298 ?

**Comment by mdomsch** [comment]
yes.

**Comment by brunobhr** [comment]
Thanks Matt,
And is there a procedure to remove every file of my install?
Or a list of files I can fide somehow?
Should I also remove the config files?

Thank you

**Comment by brunobhr** [comment]
Hello,
I completely deleted all files s3cmd, the reinstalled a clean 1.5.2.
I still can't run s3cmd as a cronjob on my Mavericks Mac mini.
This time I'm getting this:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   An unexpected error has occurred.
 Please try reproducing the error using
 the latest s3cmd code from the git master
 branch found at:
   https://github.com/s3tools/s3cmd
 If the error persists, please report the
 following lines (removing any private
 info as necessary) to:
  s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd sync --progress --server-side-encryption --delete-removed --skip-existing --cache-file=/Users/admin/logs/protools_sh/cache/protools_cache --exclude=@Recycle/* --exclude=.DS_Store --exclude=__SESSIONS A EFFACER/* /Volumes/XXXXXXXX/ s3://xxxxxxx-bkp/
Problem: KeyError: 'dev'
S3cmd:   1.5.2
python:   2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]
environment LANG=None

Traceback (most recent call last):
 File "/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2548, in <module>
 File "/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2460, in main
 File "/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1479, in cmd_sync
 File "/Library/Python/2.7/site-packages/s3cmd-1.5.2-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1449, in cmd_sync_local2remote
 File "build/bdist.macosx-10.9-intel/egg/S3/FileLists.py", line 320, in fetch_local_list
   _maintain_cache(cache, local_list)
 File "build/bdist.macosx-10.9-intel/egg/S3/FileLists.py", line 276, in _maintain_cache
   cache.unmark_for_purge(local_list[i]['dev'], local_list[i]['inode'], local_list[i]['mtime'], local_list[i]['size'])
KeyError: 'dev'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   An unexpected error has occurred.
 Please try reproducing the error using
 the latest s3cmd code from the git master
 branch found at:
   https://github.com/s3tools/s3cmd
 If the error persists, please report the
 above lines (removing any private
 info as necessary) to:
  s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Any idea?
Thanks a lot for your help,
Bruno

**Comment by ewoks** [comment]
> Is this running as root? If so, then yes you need to put it in
> /root/.s3cfg. Or pass -c /path/to/s3cfg
> 
> > —
> > Reply to this email directly or view it on GitHub
> > [#548 (comment)](https://github.com/s3tools/s3cmd/issues/548#issuecomment-104742790).

Hey Matt, would relative path to s3cfg fail if passed with -c? e.g. if I am running s3cmd from the same folder where s3cfg is would it pick it up correctly with: `s3cmd -c s3cfg ls`?

**Comment by fviard** [comment]
@ewoks if you are in a cron, it is better to put absolute path as cron completely clear the shell environment for running commands
