### ISSUE TITLE
Suppress error message on SIGPIPE

### ISSUE THREAD

**Issue by iceboundflame** [s3tools/s3cmd#549]
Hi, I often like to pipe the output of s3cmd ls and get - into programs like head or less. After these programs terminate, I get an unsightly page full of exclamation marks, a traceback, and error messages, pushing the desired content off my screen. This goes against the "Rule of Silence" of Unix philosophy. Is there an option to disable this error message?

**Comment by mdomsch** [comment]
Merged #550 thanks.
