### ISSUE TITLE
S3 wildcard certificate checking (again)

### ISSUE THREAD

**Issue by schu** [s3tools/s3cmd#555]
With #458 S3 wildcard certificate checking was fixed specifically for AWS. exoscale S3 (via http://pithos.io) also offers "virtual hosted-style buckets", i.e. it's not possible to use s3cmd for their buckets that contain periods under Python >= 2.7.9.

**Comment by mdomsch** [comment]
You can use --no-check-certificate to bypass that check.  I'd be open to a
patch that works for additional service providers - it would have to be
made "generic" such that the certificate validation checks would walk a
list of commercial domains supporting https wildcards and virtual
hosted-style buckets.

**Comment by maikzumstrull** [comment]
How about deriving the "base hostname" for the S3 instance in use, which might be, for example:
s3.amazonaws.com
s3.amazonaws.com.cn
s3-us-west-2.amazonaws.com
s3.someotherprovider.example.com
cloudstorage.yetanotherprovider.example.net

Basically, this would be either host_base from config or host_base modified with a region inserted.

You would then accept the cert if the cert is valid for any of:
- The full bucket hostname
- *.base
- base

This could be implemented as either looking into the SAN list or three calls to match_hostname.

Happy to come up with a patch if you think this approach is valid.

**Comment by mdomsch** [comment]
The code does essentially the first two, but presently fails for
region-specific, or DNS-style named buckets, which are only known after a
CNAME lookup.  I'm definitely open to a better solution than what is in
1.6.0.

**Comment by maikzumstrull** [comment]
Drafted in https://github.com/maikzumstrull/s3cmd/commits/master.

This does not attempt to fix the CNAME issue, but I'm not sure that affects s3cmd in the first place? https to CNAMES to S3 will continue to break in browsers, but that's not something that can be fixed in s3cmd.

**Comment by fviard** [comment]
Already fixed in last versions.
