### ISSUE TITLE
Issue with --no-preserve in multi-parts transfer

### ISSUE THREAD

**Issue by wenjunche** [s3tools/s3cmd#561]
Hello 

I am having an issue with -no-preserve:  it looks like it is being ignored if a file is put to s3 as multi-parts.  

Here is how I reproduce it: put a file of 49M to S3 with --no-preserve.  I see x-amz-meta-s3cmd-attrs being set on S3.  If I pass --multipart-chunk-size-mb=50, x-amz-meta-s3cmd-attrs is not set on S3.

Thanks

**Comment by wenjunche** [comment]
I am using 1.5.2.

Thanks

**Comment by mdomsch** [comment]
Correct.  We are preserving the original md5sum of the file before
uploading it, because we can't get it back from a BUCKET_LIST command later.
