### ISSUE TITLE
xxxxx.xxx is not a regular file

### ISSUE THREAD

**Issue by brunobhr** [s3tools/s3cmd#563]
Hello,
On my quest to get a s3cmd backup using cron working,
I just got that error, which I never had before:
"xxxxx.xxx is not a regular file", on hundreds of normal files
on a QNAP server mounted on a Mac mini via afp.

Any ideas?
Thanks!

**Comment by fviard** [comment]
Closing old issue, that was probably a QNAP temporary file.
Please reopen if you ever encounter this issue again.
