### ISSUE TITLE
In dire need for help running a backup task on OSX with cron

### ISSUE THREAD

**Issue by brunobhr** [s3tools/s3cmd#564]
Hello,
I've been trying literally for month to run a backup task on OSX with cron.
I'm using s3cmd version 1.5.2 and OSX 10.9.5.
I used to run my scripts manually without any problems, but when ran
from a crontab, disaster strikes every time.

Error ranges from UTF errors (we have accentuated characters),
s3cmd duplicated to dozens of instances, various crashes..
Once it even deleted 2TB of data from our bucket.

I can't figure out how a simple script that runs perfectly well in a shell
can become so erratic when ran from a crontab.

My .s3cfg file is copied in /private/var/root, my locale is set system-wide,
Has someone any idea of what I'm doing wrong?

Here are some links to the details of some of my issues so far:
https://github.com/s3tools/s3cmd/issues/441
https://github.com/s3tools/s3cmd/issues/543
https://github.com/s3tools/s3cmd/issues/548

I will supply any config file, logs or precision upon request.

I'm begging for help, I desperately need to get this thing going...

Thank you very much in advance,
Bruno

**Comment by brunobhr** [comment]
AS s3cmd looks impossible to run from cron, I'm switching to launched
for my automation process.
I am currently testing using Agents (so non-root), and it seems that so far so good.
I will post my results here.

**Comment by fviard** [comment]
Closing this old issue, as sub issues are individually addressed.
