### ISSUE TITLE
Support ~/.aws/credentials

### ISSUE THREAD

**Issue by jjshoe** [s3tools/s3cmd#570]
It would be great if s3cmd would check ~/.aws/credentials (http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html) for just the credentials to use.

**Comment by mdomsch** [comment]
Export AWS_CREDENTIAL_FILE=~/.aws/credentials, and then run s3cmd.  This is
in upstream master branch and v1.5.2.

commit dc590d62a12f309802a9865d34204117a8defebe
Author: David Kohen <kohen.d@gmail.com>
Date:   Wed Feb 13 15:57:11 2013 +0200

    Add support for IAM roles and temp tokens

    Including:
    Refresh temp tokens on every request.
    Add support for roles in S3, CloudFront and SimpleDB.
    Add support for AWS_CREDENTIALS_FILE env variable and the file it
references

**Comment by jjshoe** [comment]
@mdomsch very handy, though not the same thing by any means. The point was to check the location that AWS recommends for you to store your credentials.

**Comment by mdomsch** [comment]
I'm not sure why the location was defined in an environment variable
instead of simply looked at.  David?

**Comment by jjshoe** [comment]
http://blogs.aws.amazon.com/security/post/Tx3D6U6WSFGOK2H/A-New-and-Standardized-Way-to-Manage-Credentials-in-the-AWS-SDKs
