### ISSUE TITLE
Add "request-payer" header when needed for PUT requests (for remote copy cases)

### ISSUE THREAD

**Issue by fviard** [s3tools/s3cmd#585]
Following:
https://github.com/s3tools/s3cmd/issues/511#issuecomment-122669706

caseybrown89 commented:
> I believe this is also needed on PUT requests when syncing from an S3 bucket that requires  requester pays to another S3 bucket. Using the latest master, --requester-pays doesn't work but you can '--add-header "x-amz-request-payer: requester"' to get it to work.

>Sorry I wasn't very clear. The point I was trying to make is that "--requester-pays" flag doesn't take effect when syncing from a requester pays bucket to a different S3 bucket. You can get s3cmd to cover this case by adding the "x-amz-request-payer: requester", but it seems like "--requester-pays" should cover this case as well.

That looks right, we need to also add this flag for "PUT" to be able to support remote copy of buckets that are in request payer mode.

Adding the header for normal PUT operations doesn't look to have any side effect.

**Comment by mdomsch** [comment]
I have filed a bug report with AWS to update their documentation to reflect
that PUTs (as well as POST and GET) support x-amz-request-payer header.
