### ISSUE TITLE
[Errno] 32 - Broken pipe while calling s3cmd put / get from Python

### ISSUE THREAD

**Issue by andreiscorus** [s3tools/s3cmd#588]
After upgrading to version 1.5.2 of s3cmd, os.popen calls to s3cmd put and issued errors of broken pipes. Despite the errors, the commands were being executed. 

After changing call to os.system the errors disappeared.

**Comment by mdomsch** [comment]
are the broken pipe errors being seen and reported by s3cmd (therefore the
pipes that s3cmd are using are closing prematurely), or being seen and
reported by your app (s3cmd is closing its pipes prematurely) ?  The
tracebacks you are getting should show that.  I believe from your
description it may be the latter.

**Comment by andreiscorus** [comment]
Thank you for your reply!

The errors are being displayed by the application, which runs on Python 2.7.6. Executing the commands from the command line on the machine (Ubuntu 14.04 LTS) does not show any errors. Thinking about it, this might be more on an issue on Python than s3cmd.

**Comment by fviard** [comment]
This issue should now be fixed in master.
Please give it a try.
