### ISSUE TITLE
s3cmd QUIETLY ignores the names of non-existent files

### ISSUE THREAD

**Issue by UnitedMarsupials** [s3tools/s3cmd#594]
ss3cmd put /nonexistent1 /correct /nonexisten2 s3://foo/bar
will quietly ignore the absent file(s) instead of properly alerting the user.

Something as simple as below would help debug things immensely, but, of course, the message can be more elaborate and/or use error/warning instead of debug:

````diff
--- FileLists.py
+++ FileLists.py    2015-07-31 19:02:32.000000000 -0400
@@ -248,4 +248,5 @@
                 full_name = os.path.join(root, f)
                 if not os.path.isfile(full_name):
+                    debug("Skipping %s" % full_name)
                     continue
                 if os.path.islink(full_name):
````

**Comment by fviard** [comment]
Fixed with https://github.com/s3tools/s3cmd/pull/599
