### ISSUE TITLE
"ERROR: S3 error: Part number must be an integer between 1 and 10000, inclusive"

### ISSUE THREAD

**Issue by r00t-** [s3tools/s3cmd#613]
tried to upload a rather large file, apparently chose a too small segment size...
s3cmd should either know about s3's limit on the segment count and refuse the operation,
or detect this beforehand, i.e. by checking if the last segment is accepted before uploading the others.

```
$ s3cmd put --multipart-chunk-size-mb=10 250_gig_file s3://bucket/
250_gig_file -> s3://bucket/250_gig_file  [part 10001 of 28482, 10MB]
 10485760 of 10485760   100% in    0s    21.40 MB/s  done
ERROR: S3 error: Part number must be an integer between 1 and 10000, inclusive
```

=> 100gb of traffic wasted

**Comment by omederos** [comment]
Any news about this? I got the same when uploading a file of 160GB :\

**Comment by mdomsch** [comment]
The default chunk size is 15MB.  You should set your
--multipart-chunk-size-mb to a larger value (e.g. 50MB)

I believe a check was added very recently to prevent this kind of failure.
You should check github master branch.

Thanks,
Matt

**Comment by fviard** [comment]
Closing issue that was already fixed a long time ago.
