### ISSUE TITLE
ERROR: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by jamieburchell** [s3tools/s3cmd#622]
Hey

I'm getting ERROR: [Errno 32] Broken pipe when trying to delete a large number of files from my S3 bucket (see log link).

The files are lifecycled in Glacier storage, but this hasn't stopped deletes working previously. I've not seen this fatal issue before.

s3cmd version 1.5.2

http://pastebin.com/n7wbhfTg

Regards
Jamie

**Comment by jamieburchell** [comment]
Seems to have been resolved in the trunk version

**Comment by fviard** [comment]
This issue should now be fixed in master.
Please give it a try.
