### ISSUE TITLE
Support IAM roles / instance profiles

### ISSUE THREAD

**Issue by meonkeys** [s3tools/s3cmd#63]
"roles" (aka "instance profiles"?) allow, among other things, an admin to give an EC2 instance read/write access to a particular S3 bucket. On an instance with the proper roles/permissions, an s3cmd configuration file is not necessary.
- http://aws.typepad.com/aws/2012/06/iam-roles-for-ec2-instances-simplified-secure-access-to-aws-service-apis-from-ec2.html
- https://forums.aws.amazon.com/thread.jspa?messageID=353318&tstart=0

**Comment by excalq** [comment]
So how does one actually use this feature? There seems to be a lack of supporting documentation. Thanks for such a great tool otherwise!

**Comment by jelder** [comment]
@excalq The official AWS CLI has made this tool obsolete anyway.

**Comment by slavafomin** [comment]
@jelder and how do you invalidate the CloudFront cache after syncing the S3 bucket (only changed and deleted files) using only AWS CLI?

**Comment by slavafomin** [comment]
@mdomsch could you elaborate please on how this feature could be used? The AWS CLI works out of the box without specifying any credentials, but `s3cmd` gives me the `Configuration file not available` error.
