### ISSUE TITLE
empty directory remains after failed downloads

### ISSUE THREAD

**Issue by mdomsch** [s3tools/s3cmd#636]
Conrad J.C. Hughes (for Debian package stuff) debbugs@xrad.org via tracker.debian.org 
6:10 AM (3 hours ago)

to Debian 
Package: s3cmd
Version: 1.5.0~rc1-2
Severity: normal
Tags: upstream

Dear Maintainer,

On receipt of a permission error during s3cmd sync, a local empty temporary
file is
left.  Would be nice if it was deleted.

The particular remote error I'm getting is this one:

  WARNING: Remote file  S3Error: 403 (Forbidden):
  s3://[blahblahblah] -> <fdopen>  [1 of 136]
  etc.

After this, all files which failed to sync because of permission errors seem to
have an associated empty temp file left behind, e.g. ".s3cmd.MJ8Peb.tmp".  Over
repeated syncs, the numbers rapidly mount...

Best regards,
Conrad

-- System Information:
Debian Release: 8.2
  APT prefers stable-updates
  APT policy: (500, 'stable-updates'), (500, 'stable'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 3.16.0-4-amd64 (SMP w/8 CPU cores)
Locale: LANG=en_GB.UTF-8, LC_CTYPE=en_GB.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)

Versions of packages s3cmd depends on:
ii  python-dateutil  2.2-2
pn  python:any       <none>

Versions of packages s3cmd recommends:
ii  python-magic  1:5.22+15-2

s3cmd suggests no packages.

-- debconf-show failed

Gianfranco Costamagna	
Hi Conrad, can you please try 1.5.2 from Stretch? thanks
6:30 AM (2 hours ago)

Conrad Hughes debbugs@xrad.org via buxtehude.debian.org 
7:17 AM (2 hours ago)

to Gianfranco, 800018 
Hi Gianfranco,

Thanks for the fast response.

> can you please try 1.5.2 from Stretch?

I tried 1.5.2-3~bpo8+1 from jessie-backports; hope that's good enough.

It's a substantial regression: not only does it still leave empty temp
files, but it terminates on the first permission error, so I can no
longer sync at all (there are some files there that I don't have
permission to read, but many that I do).  The '--ignore-failed-copy'
flag, which is the only "ignore" in the documentation, doesn't prevent
this behaviour either.

The error reported has changed too: where previously I got a "403
Forbidden", now I get this:

  s3://[blahblahblah] -> <fdopen>  [1 of 134]
  ERROR: S3 error: Unknown error

Regards,
Conrad

Gianfranco Costamagna	
Well, while we are waiting for an official answer from upstream, I just uploa...
7:25 AM (1 hour ago)

Conrad Hughes debbugs@xrad.org via packages.qa.debian.org 
8:09 AM (1 hour ago)

to Gianfranco, Matt, 800018 
Hi Gianfranco,

Thanks again for such a rapid turnaround!  So 1.6.0-1 returns to the
behaviour of 1.5.0~rc1-2: it can run the whole sync despite the 403
errors, but it still leaves an empty temporary file for every failure..

Regards,
Conrad

**Comment by fviard** [comment]
This should already be fixed in 1.6.0 with:
https://github.com/s3tools/s3cmd/commit/69bb35dff0f4120913a3c5278279d476ab72f496

:-)

**Comment by LocutusOfBorg** [comment]
well, the original reporter seems to have this problem on 1.6.0 too

" So 1.6.0-1 returns to the
behaviour of 1.5.0~rc1-2: it can run the whole sync despite the 403
errors, but it still leaves an empty temporary file for every failure.."

**Comment by fviard** [comment]
@LocutusOfBorg Thanks for the notice, I missed the last part.
Indeed looking at the code it looks like that the reporter is right.
We forgot to delete the temp folder in the case of a S3Error.
I will fix that.

**Comment by mdomsch** [comment]
diff --git a/s3cmd b/s3cmd
index 195a2a7..d2722fb 100755
--- a/s3cmd
+++ b/s3cmd
@@ -1204,7 +1204,12 @@ def cmd_sync_remote2local(args):
                 error(u"Download of '%s' failed too many times (Last Reason: %s). "
                       "This is usually a transient error, please try again "
                       "later." % (file, exc))
-                os.unlink(deunicodise(chkptfname))
+                try:
+                    # Try to remove the temp file if it exists
+                    if chkptfname:
+                        os.unlink(deunicodise(chkptfname))
+                except:
+                    pass
                 if cfg.stop_on_error:
                     ret = EX_DATAERR
                     error(u"Exiting now because of --stop-on-error")
@@ -1213,6 +1218,12 @@ def cmd_sync_remote2local(args):
                 continue
             except S3Error, exc:
                 warning(u"Remote file '%s'. S3Error: %s" % (exc.resource, exc))
+                try:
+                    # Try to remove the temp file if it exists
+                    if chkptfname:
+                        os.unlink(deunicodise(chkptfname))
+                except:
+                    pass
                 if cfg.stop_on_error:
                     raise
                 ret = EX_PARTIAL

**Comment by fviard** [comment]
@mdomsch : the diff is broken here, but I think that you got it right.
The only point is that you can avoid the check "if chkptfname" in these 2 cases as there errors can only be encountered when we call the s3 command, and so after the creation of this temp folder.

**Comment by mdomsch** [comment]
```
diff --git a/s3cmd b/s3cmd
index 195a2a7..c3097b4 100755
--- a/s3cmd
+++ b/s3cmd
@@ -1213,6 +1213,7 @@ def cmd_sync_remote2local(args):
                 continue
             except S3Error, exc:
                 warning(u"Remote file '%s'. S3Error: %s" % (exc.resource, exc))
+                os.unlink(deunicodise(chkptfname))
                 if cfg.stop_on_error:
                     raise
                 ret = EX_PARTIAL
```

**Comment by fviard** [comment]
@mdomsch : but still try:catching this call and the one in S3DownloadError could be good, because who knows what could happened when you try to remove a file :p

**Comment by mdomsch** [comment]
but if we don't catch and do something, just pass, wouldn't it be better to let it crash and raise rather than leave the tmpfiles behind?

**Comment by fviard** [comment]
I don't think so, because that would be for rather special situations, like disk issues, strange permissions, file already removed by another process or so i think, and users will probably prefer that the backup be able to continue if what they want is the ignore-errors.

**Comment by mdomsch** [comment]
ok. have at it please. :-)

**Comment by LocutusOfBorg** [comment]
ping, I would like to fix it in Debian too, to be able to backport it soon :)

**Comment by fviard** [comment]
@LocutusOfBorg I will test and checkin that before the end of the day. thanks

**Comment by LocutusOfBorg** [comment]
Actually the new version will migrate in testing tonight
https://packages.qa.debian.org/s/s3cmd.html

so I plan to add the patch tomorrow or after :)
