### ISSUE TITLE
Not a Bug but a request for more informations…

### ISSUE THREAD

**Issue by ytrezq** [s3tools/s3cmd#638]
I don’t know about your tool, and never used it, but I have problems elsewhere.

Hello, as far I understand signatures *(like`vCfS727jYF60BmM5nmy4/D9puRk=`)* for ᴘᴏꜱᴛ/upload requests don’t use the Secret keys in order to get generated. Isn’t it ?

This is because of “[Using your credentials create a signature, for example 0RavWzkygo6QX9caELEqKi9kDbU= is the signature for the preceding policy document](http://docs.aws.amazon.com/AmazonS3/latest/dev/HTTPPOSTExamples.html).” But this doesn’t tell which exact credentials to use, nor how to do it.

The goal is for file upload by users with exactly those fields inside ᴘᴏꜱᴛ requests`key` `AWSAccessKeyId` `acl` `policy` `signature` `Content-Type` `Cache-Control` `x-amz-meta-Surrogate-Control` `x-amz-meta-Surrogate-Key` which is user account id. The last one is the file itself.

**Comment by fviard** [comment]
I think that the documentation that you are looking at is too old, have a look at this one:
http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-UsingHTTPPOST.html

**Comment by ytrezq** [comment]
@fviard : No, the form doesn’t include a policy.

**Comment by fviard** [comment]
In the linked article you have what you want I think:
http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-HTTPPOSTForms.html
The point is that the secret is used to generate the signature if there is a policy otherwise you can only write to a public bucket, but so no key needed.
