### ISSUE TITLE
Give a clearer response if the verb (e.g. get, put) is missing

### ISSUE THREAD

**Issue by eherot** [s3tools/s3cmd#644]
This was caused by my own stupidity but I feel like s3cmd's reaction could have been more useful.  Basically I did this:
```
s3cmd --access_key NOTSOSECRETSTRING --secret_key SUPERSECRETSTRING --server-side-encryption /mnt/dev0/long/path/to/tarball.tar.gz s3://s3_bucket/even/longer/and/more/convoluted/path_name/to/tarball.tar.gz
```
and what I got back was:
```
ERROR: Invalid command: u'/mnt/dev0/long/path/to/tarball.tar.gz'
```

Again, totally my own fault but I thought perhaps it might just have been clearer what I was doing wrong if it weren't for the "u" (which I found misleading) preceding the erroneous input string.

**Comment by fviard** [comment]
Thank you for your report, but I don't really see what more can be done?
"invalid command" is explicit, and I don't think that it is doable to put the complete list of all the possible commands in this error message.

**Comment by eherot** [comment]
Basically I was just thinking it would make sense to remove the 'u':
```
u'/mnt/dev0/long/path/to/tarball.tar.gz'
^
```
For some reason it being there caused me to completely misinterpret what this message was telling me (and assume that I had some much deeper problem than the missing verb.

**Comment by fviard** [comment]
You are right, I missed the important bit in your message ^^.
It should be fixed now, thanks for the report.

**Comment by eherot** [comment]
:+1: Thanks!
