### ISSUE TITLE
s3cmd sync finds the expected differences, but then reports 0 source files to copy

### ISSUE THREAD

**Issue by Saeven** [s3tools/s3cmd#646]
When I run the sync command with -d, I see this in the log, which is the file I expect it to upload

```
DEBUG: CHECK: vendor/launchfire/core/src/LDP/Factory/AbstractTableFactory.php
DEBUG: xfer: vendor/launchfire/core/src/LDP/Factory/AbstractTableFactory.php (size mismatch: src=2634 dst=2455)
```

However, when the execution concludes, it reports that there are no files to change:

```
Saeven:code Saeven$ s3cmd --version
s3cmd version 1.6.0
```

```
Saeven:code Saeven$ s3cmd sync -v --dry-run --delete-removed  s3://devbucket/STAGE2/ s3://devbucket/LIVE2/
INFO: Retrieving list of remote files for s3://devbucket/STAGE2/ ...
INFO: Forwarding request to us-east-1
INFO: Retrieving list of remote files for s3://devbucket/LIVE2/ ...
INFO: Found 15141 source files, 15141 destination files
INFO: Verifying attributes...
Summary: 0 source files to copy, 0 files at destination to delete
WARNING: Exiting now because of --dry-run
```

Have you seen something like this before?

If I mangle the name on the target (LIVE2) then the file makes it to the transfer list.  Looks to be that it won't transfer otherwise.  For the record, there are changes within the file - their contents are different.

**Comment by Saeven** [comment]
Indeed it looks as though dry runs are to blame. When the dry run is issued, nothing is reported.

**Comment by Saeven** [comment]
Reverting to version 1.0.1 solves the problem.  Looks like this was a bug introduced between then, and 1.6.0.

**Comment by mdomsch** [comment]
There's about 5 years of work between those two versions. :-(

**Comment by fviard** [comment]
@Saeven I think that it should be fixed in master now. For your information, it was only an error of reporting of the summary and in dry-run mode, but the real operation should have been done correctly.
