### ISSUE TITLE
s3cmd sync should exit with non 0 on error

### ISSUE THREAD

**Issue by levithomason** [s3tools/s3cmd#649]
This command is being used by [Wercker](http://www.wercker.com), a popular CD solution.   See [here](https://github.com/wercker/step-s3sync/blob/master/run.sh#L57).

Currently, a failed sync results in "successful" deployments to S3 as the command does not seem to exit non 0. The sync command should exit with a non 0 on errors so it can be captured and used correctly by other systems.

Here are the Wercker issues and corresponding `s3cmd sync` errors that should have exited non 0.

wercker/step-s3sync#20
 - `ERROR: S3 error: Access Denied` 

wercker/step-s3sync#21
 - `ERROR: Parameter problem: Invalid character(s) in header name '"Content-Encoding': """`
 - `ERROR: S3 error: Access Denied`

**Comment by mdomsch** [comment]
Many of these were addressed in v1.6.0, and it now exits non-zero in many
more cases.

**Comment by levithomason** [comment]
Looks like they are running `1.5.1.2`, will submit a PR for the update and see how it goes.  Closing this preemptively, will reopen if we hit issues again.  Thanks for the quick reply.
