### ISSUE TITLE
s3cmd can't import crypto and lists incorrect version number?

### ISSUE THREAD

**Issue by denisemauldin** [s3tools/s3cmd#653]
I'm running on linux 3.8.13-68.1.2.el7uek.x86_64 and python 2.7.10 and attempting to use s3cmd.  Installing from pip, from downloading the file from the github site, or from cloning from the s3cmd git results in s3cmd erring with 'ImportError: cannot import name Crypto'.  The path where crypto is installed is included in the list of sys.path entries.  

Invoked as: /local/bin/s3cmd
Problem: ImportError: cannot import name Crypto
S3cmd:   1.5.0-rc1
python:   2.7.10 (default, Jun 30 2015, 16:50:14) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/local/bin/s3cmd", line 2792, in <module>
    from S3 import Crypto
ImportError: cannot import name Crypto

**Comment by fviard** [comment]
Please check that you have pycrypto installed:
https://pypi.python.org/pypi/pycrypto
(or maybe you simply need to update it)

**Comment by denisemauldin** [comment]
Hi fviard,

I installed pycrypto using pip and the error remains the same.  

> pip install pycrypto
Collecting pycrypto
  Downloading pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 446kB 303kB/s 
Installing collected packages: pycrypto
  Running setup.py install for pycrypto
Successfully installed pycrypto-2.6.1
> s3cmd
Invoked as: /local/bin/s3cmd
Problem: ImportError: cannot import name Crypto
S3cmd:   1.5.0-rc1
python:   2.7.10 (default, Jun 30 2015, 16:50:14) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/local/bin/s3cmd", line 2792, in <module>
    from S3 import Crypto
ImportError: cannot import name Crypto

Thanks for your help!
Denise

**Comment by fviard** [comment]
Hi Denise,
I'm sorry, I just realize that the "Crypto" module that you are not able to load is the one of S3 and not pycrypto. So, something is not loading on your system but sadly the error message doesn't say what.

As I'm suppose that it is still a dependency, can you launch a python interpreter (with the "python" command alone), and then type the following things inside:
```
import sys
import hmac
import base64

import Config
from logging import debug

from calendar import timegm
import datetime
import urllib

from hashlib import sha1, sha256
```

Please tell me if everything goes well or if you encounter an error / backtrace.

**Comment by denisemauldin** [comment]
Hi fviard,

Thanks for the further troubleshooting.  All of these modules imported properly, except for 'Config', but I could 'import config'.  I did a pip install Config and that installed a module, but still 'import Config' didn't work and 'import config' does.  s3cmd gives the same error as previously.

>Python 2.7.10 (default, Jun 30 2015, 16:50:14) 
>[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2
>Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import hmac
>>> import base64
>>> 
>>> import Config
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named Config
>>> from logging import debug
>>> 
>>> from calendar import timegm
>>> import datetime
>>> import urllib
>>> 
>>> from hashlib import sha1, sha256
>>> import config
>>> 


Thanks!
Denise

**Comment by denisemauldin** [comment]
>>> from S3 import Utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/u5/tools/lib/python2.7/site-packages/S3/Utils.py", line 37, in <module>
    import Exceptions
  File "/u5/tools/lib/python2.7/site-packages/S3/Exceptions.py", line 9, in <module>
    from Utils import getTreeFromXml, unicodise, deunicodise
ImportError: cannot import name getTreeFromXml

**Comment by fviard** [comment]
It is very strange, it looks like that you are unable to import any file of s3cmd.
Are you sure to have your python path correctly set?

What is your linux distribution exactly?

**Comment by denisemauldin** [comment]
CENTOS 6 I believe?  3.8.13-68.1.2.el7uek.x86_64  I can run analyses in this python distribution using impyla with my current PYTHONPATH, which is in the same directory (/u5/tools/lib/python2.7/site-packages).  

I have the git repository checked out into /u5/tools/src/s3cmd.  I do python setup.py build then python setup.py install --prefix=/u5/tools.  The s3cmd that's built in the /u5/tools/src/s3cmd directory works.  The s3cmd that gets installed into /u5/tools/bin can't find the S3 directory and, indeed, if I look at the /u5/tools/lib/python2.7/site-packages, it doesn't contain an S3 directory (and copying the /u5/tools/src/s3cmd/S3 directory doesn't fix it).  The /u5/tools/lib/python2.7/site-packages directory only contains s3cmd-1.6.0_-py2.7.egg.  I've included the output from setup.py install --prefix=/u5/tools below in case that's where the error is happening.

> python setup.py install --prefix=/u5/tools
Using xml.etree.ElementTree for XML processing
/u5/tools/lib/python2.7/site-packages/setuptools/dist.py:294: UserWarning: The version specified ('1.6.0+') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
  "details." % self.metadata.version
running install
running bdist_egg
running egg_info
writing requirements to s3cmd.egg-info/requires.txt
writing s3cmd.egg-info/PKG-INFO
writing top-level names to s3cmd.egg-info/top_level.txt
writing dependency_links to s3cmd.egg-info/dependency_links.txt
reading manifest file 's3cmd.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 's3cmd.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/ACL.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/AccessLog.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/BidirMap.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/CloudFront.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/Config.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/Crypto.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/Exceptions.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/ExitCodes.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/FileDict.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/HashCache.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/MultiPart.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/PkgInfo.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/Progress.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/S3Uri.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/SortedDict.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/Utils.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/__init__.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/ConnMan.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/FileLists.py -> build/bdist.linux-x86_64/egg/S3
copying build/lib/S3/S3.py -> build/bdist.linux-x86_64/egg/S3
byte-compiling build/bdist.linux-x86_64/egg/S3/ACL.py to ACL.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/AccessLog.py to AccessLog.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/BidirMap.py to BidirMap.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/CloudFront.py to CloudFront.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/Config.py to Config.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/Crypto.py to Crypto.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/Exceptions.py to Exceptions.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/ExitCodes.py to ExitCodes.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/FileDict.py to FileDict.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/HashCache.py to HashCache.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/MultiPart.py to MultiPart.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/PkgInfo.py to PkgInfo.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/Progress.py to Progress.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/S3Uri.py to S3Uri.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/SortedDict.py to SortedDict.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/Utils.py to Utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/ConnMan.py to ConnMan.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/FileLists.py to FileLists.pyc
byte-compiling build/bdist.linux-x86_64/egg/S3/S3.py to S3.pyc
installing package data to build/bdist.linux-x86_64/egg
running install_data
creating build/bdist.linux-x86_64/egg/share
creating build/bdist.linux-x86_64/egg/share/doc
creating build/bdist.linux-x86_64/egg/share/doc/packages
creating build/bdist.linux-x86_64/egg/share/doc/packages/s3cmd
copying README.md -> build/bdist.linux-x86_64/egg/share/doc/packages/s3cmd
copying INSTALL -> build/bdist.linux-x86_64/egg/share/doc/packages/s3cmd
copying NEWS -> build/bdist.linux-x86_64/egg/share/doc/packages/s3cmd
creating build/bdist.linux-x86_64/egg/share/man
creating build/bdist.linux-x86_64/egg/share/man/man1
copying s3cmd.1 -> build/bdist.linux-x86_64/egg/share/man/man1
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-2.7/s3cmd -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/s3cmd to 755
copying s3cmd.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying s3cmd.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying s3cmd.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying s3cmd.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying s3cmd.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/s3cmd-1.6.0_-py2.7.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing s3cmd-1.6.0_-py2.7.egg
Removing /u5/tools/lib/python2.7/site-packages/s3cmd-1.6.0_-py2.7.egg
Copying s3cmd-1.6.0_-py2.7.egg to /u5/tools/lib/python2.7/site-packages
s3cmd 1.6.0- is already the active version in easy-install.pth
Installing s3cmd script to /u5/tools/bin

Installed /u5/tools/lib/python2.7/site-packages/s3cmd-1.6.0_-py2.7.egg
Processing dependencies for s3cmd===1.6.0-
Searching for python-magic==0.4.10
Best match: python-magic 0.4.10
Adding python-magic 0.4.10 to easy-install.pth file

Using /u5/tools/lib/python2.7/site-packages
Searching for python-dateutil==2.4.2
Best match: python-dateutil 2.4.2
Processing python_dateutil-2.4.2-py2.7.egg
python-dateutil 2.4.2 is already the active version in easy-install.pth

Using /u5/tools/lib/python2.7/site-packages/python_dateutil-2.4.2-py2.7.egg
Searching for six==1.10.0
Best match: six 1.10.0
Adding six 1.10.0 to easy-install.pth file

Using /u5/tools/lib/python2.7/site-packages
Finished processing dependencies for s3cmd===1.6.0-

**Comment by mdomsch** [comment]
You can fix the 'incorrect version number" error by changing S3/PkgInfo.py,
removing the "+".  I added that right after we cut 1.6.0 to show it was
newer.  I didn't realized setuptools would complain.  If it's just a
warning, just ignore it.

I use virtualenv to install this into, which is sure to fix up the paths.
Are you using virtualenv?

**Comment by denisemauldin** [comment]
Hi Matt,

I changed the S3/PkgInfo.py and the warning goes away for the install command.  I am not using virtualenv.

Thanks,
Denise

**Comment by denisemauldin** [comment]
I was incorrect earlier.  The machine is Oracle Linux 7.  If I go into the source directory and go into python, then if I import Exceptions before I import Utils then it works, but it errors if I import Utils without first importing Exceptions.

```
>>> from S3 import Utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "S3/Utils.py", line 37, in <module>
    import Exceptions
  File "S3/Exceptions.py", line 9, in <module>
    from Utils import getTreeFromXml, unicodise, deunicodise
ImportError: cannot import name getTreeFromXml
>>> from S3 import Exceptions
>>> from S3 import Utils
```

**Comment by denisemauldin** [comment]
This error is still occurring with the latest pull from the git repository.  

```
Error loading some components of s3cmd (Import Error)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /local/bin/s3cmd
Problem: ImportError: cannot import name Crypto
S3cmd:   1.5.0-rc1
python:   2.7.10 (default, Jun 30 2015, 16:50:14) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/u5/tools/lib/python2.7/site-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2906, in <module>
ImportError: cannot import name Crypto

Your sys.path contains these entries:
       /u5/tools/lib/python2.7/site-packages
```

```
Copying s3cmd-1.6.1-py2.7.egg to /local/lib/python2.7/site-packages
```

/u5/tools/ is a softlink to /local.  Any other ideas on how to fix this?  It seems like dependencies are being imported in an odd order on Oracle Linux 7?

**Comment by mdomsch** [comment]
You have old bits installed somewhere in your site path still.

**Comment by denisemauldin** [comment]
How do I find them? :\

**Comment by denisemauldin** [comment]
Aha.  Found it! :)  I mucked around with the order of the import statements in the s3cmd script (2897 to 2912) and it ended up giving me a larger Traceback that showed me the path that it was trying to import from (and failing).  :D

**Comment by denisemauldin** [comment]
One thing that would have been helpful in addressing this issue would have been if the traceback was printed for ImportError as well as for NameError.
