### ISSUE TITLE
Problem: Error: `/backup...../l1_b.jpg` and `/backup...../l1_b.jpg` are the same file

### ISSUE THREAD

**Issue by richardrasu** [s3tools/s3cmd#656]
Hi, trying to do a sync from amazon s3 to local machine (for backup) fails on particular files.
e.g.
Invoked as: /usr/bin/s3cmd -c /root/.s3cfg sync --delete-removed --exclude=cf-logs/\* s3://360-binaries/ /backup/amazon_s3_backup/360-binaries/
Problem: Error: `/backup/amazon_s3_backup/360-binaries/pano/AvenidaDelPuerto/panoramas/Pano/l1_b.jpg` and `/backup/amazon_s3_backup/360-binaries/pano/AvenidaDelPuerto/panoramas/Pano/l1_b.jpg` are the same file
S3cmd:   1.6.0+
python:   2.7.3 (default, Mar 13 2014, 11:03:55)
[GCC 4.7.2]
environment LANG=C

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2841, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2749, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 1703, in cmd_sync
    return cmd_sync_remote2local(args)
  File "/usr/bin/s3cmd", line 1342, in cmd_sync_remote2local
    failed_copy_list = local_copy(copy_pairs, destination_base)
  File "/usr/bin/s3cmd", line 1376, in local_copy
    shutil.copy2(deunicodise(src_file), deunicodise(dst_file))
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 69, in copyfile
    raise Error("`%s` and `%s` are the same file" % (src, dst))
Error: `/backup/amazon_s3_backup/360-binaries/pano/AvenidaDelPuerto/panoramas/Pano/l1_b.jpg` and `/backup/amazon_s3_backup/360-binaries/pano/AvenidaDelPuerto/panoramas/Pano/l1_b.jpg` are the same file

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Here's our config file (as referred by the command above) with keys redacted:

[default]
access_key = [secret]
bucket_location = US
cloudfront_host = cloudfront.amazonaws.com
cloudfront_resource = /2010-07-15/distribution
default_mime_type = binary/octet-stream
delete_removed = False
dry_run = False
encoding = UTF-8
encrypt = False
follow_symlinks = False
force = False
get_continue = False
gpg_command = None
gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_passphrase =
guess_mime_type = True
host_base = s3.amazonaws.com
host_bucket = %(bucket)s.s3.amazonaws.com
human_readable_sizes = False
list_md5 = False
log_target_prefix =
preserve_attrs = True
progress_meter = True
proxy_host =
proxy_port = 0
recursive = False
recv_chunk = 4096
reduced_redundancy = False
secret_key = [secret]
send_chunk = 4096
simpledb_host = sdb.amazonaws.com
skip_existing = False
socket_timeout = 300
urlencoding_mode = normal
use_https = False
verbosity = WARNING

Any idea why the sync is failing? The file seems to be ok, as far as I can tell. We're not doing anything special.

**Comment by fviard** [comment]
Indeed, this is strange. Is there a chance that this file 1) is a symbolic link, 2) has a symbolic link targeting it, 3) another file with the same name with different case?

**Comment by richardrasu** [comment]
You mean on the origin file? Not sure. More likely on the destination but I will check and come back to you on this, hopefully even today! ;)

**Comment by richardrasu** [comment]
Hi, sorry for the delay in replying..

Answers to your questions:

1) No, not a symlink
2) No, not a target of other symlinks
3) over 10K with the same name (same casing) but in various other directories outside of the afftected files' directory - this name is generated via templating system. No other clashes on same name in different directories, only this one. I can delete the target directory and run sync fresh and again only this file is affected. The file is not corrupt or AFAICS otherwise special :(

Hope that helps. Am happy to provide as much info as you need. Thanks for your help!

R.

**Comment by aolchik** [comment]
Hi!

@richardrasu could you solve this problem?
I'm facing the same issue.

**Comment by richardrasu** [comment]
@aolchik no sadly not.

**Comment by aripringle** [comment]
FWIW, I was experiencing this same error, and upgrading to s3cmd 2.0.0 resolved it.

I did find the cause of the issue in my case though - it turned out that our S3 bucket had a file that had the exact same name as a directory. I was getting this error:

Error: `/test/sites/global/img/test-01.jpg` and `/test/sites/global/img/test-01.jpg` are the same file

In the above example, the `sites/global` folder in S3 had a folder named "img" AND (mistakenly) a file named "img", which seemed to be confusing things for s3cmd 1.6.1, but it worked fine in s3cmd 2.0.0.
