### ISSUE TITLE
feature request: handle multipart parts with names starting with dash "-"

### ISSUE THREAD

**Issue by carsten-langer** [s3tools/s3cmd#657]
Our internal S3 compatible server sometimes creates multipart upload part ids starting with a dash "-idabc123...". I think this is allowed from Amazon's API.
However, there seems no way currently to operate on such id using s3cmd.

Imagine you want to list the existing parts of an uncomplete multipart upload with such id:
`./s3cmd listmp s3://bucket/key -idabc123`
This will fail with
`s3cmd: error: no such option: -i`

I found no way to make s3cmd to interpret the `-idabc123` as `id` and not as option.

Maybe an option `--` like in other GNU programs, to separate options from other parameters would help.

**Comment by mdomsch** [comment]
we are using OptionParser, so -- should work.  ./s3cmd -- listmp s3://bucket/key -idabc123

I've tried this and proven that s3cmd ignores options after the --.

**Comment by carsten-langer** [comment]
oh, I did not know the -- is implemented already. Yes, works for me. Could that be written explicitly in the help or man?
