### ISSUE TITLE
Unhandled KeyError when fetching MIMEType from file in Eucalyptus 4.1.2

### ISSUE THREAD

**Issue by mastier** [s3tools/s3cmd#659]
$ ./s3cmd -c ~/.s3cfg_walrus info s3://images/rh6.7_05-11-15_1635.img.manifest.xml
s3://images/rh6.7_05-11-15_1635.img.manifest.xml (object):
   File size: 13002
   Last mod:  Fri, 06 Nov 2015 11:05:39 GMT

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: ./s3cmd -c ~/.s3cfg_walrus info s3://images/rh6.7_05-11-15_1635.img.manifest.xml
Problem: KeyError: 'content-type'
S3cmd:   1.6.0+
python:   2.7.10 (default, Oct 14 2015, 16:09:02) 
[GCC 5.2.1 20151010]
environment LANG=en_GB.UTF-8

Traceback (most recent call last):
  File "./s3cmd", line 2841, in <module>
    rc = main()
  File "./s3cmd", line 2749, in main
    rc = cmd_func(args)
  File "./s3cmd", line 841, in cmd_info
    output(u"   MIME type: %s" % info['headers']['content-type'])
KeyError: 'content-type'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by mdomsch** [comment]
oh lovely.  Eucalyptus didn't send us a content type.  Whoops.  That's a
real bug. (well, 2 bugs - one in eucalyptus I bet, and one that s3cmd
didn't check if the header it thought would be there really was).

**Comment by fviard** [comment]
Should be fixed in master even if the behaviour of Walrus is certainly a bug and should also be fixed there I think.
