### ISSUE TITLE
s3cmd del --recursive exits with an error when it does not match any keys

### ISSUE THREAD

**Issue by sheldonkwok** [s3tools/s3cmd#661]
In 1.5.2, s3cmd del --recursive with a prefix  that does not match any files only returns a 
"WARNING: Remote list is empty."

now in 1.6.0 i get a 
"ValueError: Key list is empty" with an exit code 1. 

This was not mentioned in the patch notes and I'm not sure if this was intended. With "rm -rf" you don't get an error if nothing is deleted.

**Comment by fviard** [comment]
Thank you very much for the detailed report. That should now be fixed in master.

**Comment by sheldonkwok** [comment]
Thanks for the quick response!
