### ISSUE TITLE
Is there a way to change the website redirect rules XML using s3cmd?

### ISSUE THREAD

**Issue by pzion** [s3tools/s3cmd#662]
If there is a way to do this, it's not obvious (at least to me) and perhaps something should be added to the docs?

**Comment by fviard** [comment]
I don't think that there is an API provided by s3 to do that.
But, you can use the flag --add-header to set the redirection for one specific file:
 --add-header="x-amz-website-redirect-location: /page1"
See:
http://docs.aws.amazon.com/AmazonS3/latest/dev/how-to-page-redirect.html 

Note: It will only be taken under account for "website" access, and not through S3 Api access like when browsing with s3cmd.
Note 2: Patches are welcome to add an option to s3cmd for supporting directly this feature.

**Comment by pzion** [comment]
Thanks!  I'll look to see if it's easy to add support for this feature.
