### ISSUE TITLE
Combine files from 3 buckets into new bucket with `sync`

### ISSUE THREAD

**Issue by r3wt** [s3tools/s3cmd#663]
i tried with the flag `--skip-existing` but it still displays the warning that remote files will be deleted, however when i ctrl-c'd the job and re ran the first sync, the files from the second bucket were not deleted by a repeat of the initial sync command with `--skip-existing`, though the script reported that 14 files would be deleted from the destination. one might assume this means that the files on remote are not actually deleted, but i don't have the luxury of assuming that. i need a definitive answer.

**If i run sync with --skip-existing flag, will i be able to combine the 3 buckets into the destination bucket without ANY files being deleted.**

**Comment by fviard** [comment]
By default, the sync don't delete files at destination that are not in the source.
It can tell you that in the summary, but it will not do it.
Check that you have the following configuration:
delete_after = False
delete_after_fetch = False
delete_removed = False
and that you don't use a option on the command line like "--delete-removed".

Btw, you are not needed to do things in separated commands. Without the "skip-existing", you can do something like that:
sync s3://source1/ s3://source2/ s3://source3/ s3://mydestination/

**Comment by r3wt** [comment]
@fviard how can i check the config? where is the file at?

**Comment by fviard** [comment]
@r3wt If you don't use another config file, I think that yours will be ~/.s3cfg
It is the same file that stores your aws s3 credentials.

**Comment by r3wt** [comment]
alright, thank you fviard. i am add this to the stackoverflow answer with accreditation to you for your help. thanks so much.
