### ISSUE TITLE
A possible issue when deleting files during a sync? 

### ISSUE THREAD

**Issue by windoverwater** [s3tools/s3cmd#681]
Hi - new to this - apologies in advance for any bad form

After moving a bunch of files around, one (only one of about 10) of my backup crons using s3cmd started to apparently fail in the delete phase of a s3cmd sync.  The sync itself is of about 10G in size over about 95k files.  It was working fine until a chunk of files were moved around.

Could not find a similar bug already opened.  Apologies in advance if this is a repeat or pilot error.

The tail of the debug log is below.  Thanks in advance.
-sandy

[...]
DEBUG: CHECK: releng-private/releng-salt.wiki.git/info/exclude
DEBUG: IGNR: releng-private/releng-salt.wiki.git/info/exclude (transfer not needed)
INFO: Summary: 0 local files to upload, 0 files to remote copy, 2894 remote files to delete
DEBUG: Batch delete 1000, remaining 1894
DEBUG: CreateRequest: resource[uri]=/?delete
DEBUG: Using signature v2
DEBUG: SignHeaders: 'POST\nXXXXX==\napplication/xml\n\nx-amz-date:Mon, 21 Dec 2015 16:09:29 +0000\n/githq-4-backup/?delete'
DEBUG: Processing request, please wait...
DEBUG: get_hostname(XXXXX): XXXXX.YYYYY.verizon.com:443
DEBUG: ConnMan.get(): re-using connection: https://XXXXX.YYYYY.verizon.com:443#134
DEBUG: format_uri(): /?delete
DEBUG: Sending request method_string='POST', uri='/?delete', headers={'content-type': 'application/xml', 'Authorization': 'AWS ZZZZ=', 'x-amz-date': 'Mon, 21 Dec 2015 16:09:29 +0000', 'content-md5': 'XXXXX=='}, body=(141804 bytes)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

DEBUG: Unicodising '/usr/local/bin/s3cmd' using UTF-8
DEBUG: Unicodising '--config=/root/.s3cfg-cloudswitch22' using UTF-8
DEBUG: Unicodising '--human-readable-sizes' using UTF-8
DEBUG: Unicodising '-d' using UTF-8
DEBUG: Unicodising '--delete-removed' using UTF-8
DEBUG: Unicodising 'sync' using UTF-8
DEBUG: Unicodising '/var/opt/gitlab/git-data/repositories/' using UTF-8
DEBUG: Unicodising 's3://XXXXX/var/opt/gitlab/git-data/repositories/' using UTF-8
Invoked as: /usr/local/bin/s3cmd --config=/root/.s3cfg-cloudswitch22 --human-readable-sizes -d --delete-removed sync /var/opt/gitlab/git-data/repositories/ s3://XXXXX/var/opt/gitlab/git-data/repositories/
Problem: error: [Errno 104] Connection reset by peer
S3cmd:   1.6.0
python:   2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 2805, in <module>
    rc = main()
  File "/usr/local/bin/s3cmd", line 2713, in main
    rc = cmd_func(args)
  File "/usr/local/bin/s3cmd", line 1666, in cmd_sync
    return cmd_sync_local2remote(args)
  File "/usr/local/bin/s3cmd", line 1644, in cmd_sync_local2remote
    ret = _single_process(args[:-1], local_list)
  File "/usr/local/bin/s3cmd", line 1422, in _single_process
    return _child(destination_base, source_args, local_list)
  File "/usr/local/bin/s3cmd", line 1576, in _child
    subcmd_batch_del(remote_list = remote_list)
  File "/usr/local/bin/s3cmd", line 673, in subcmd_batch_del
    _batch_del(remote_list)
  File "/usr/local/bin/s3cmd", line 649, in _batch_del
    response = s3.object_batch_delete(to_delete)
  File "/usr/local/lib/python2.7/dist-packages/S3/S3.py", line 643, in object_batch_delete
    self.object_batch_delete_uri_strs(uris)
  File "/usr/local/lib/python2.7/dist-packages/S3/S3.py", line 673, in object_batch_delete_uri_strs
    response = self.send_request(request)
  File "/usr/local/lib/python2.7/dist-packages/S3/S3.py", line 1066, in send_request
    http_response = conn.c.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1051, in getresponse
    response.begin()
  File "/usr/lib/python2.7/httplib.py", line 415, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 371, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
  File "/usr/lib/python2.7/ssl.py", line 341, in recv
    return self.read(buflen)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
error: [Errno 104] Connection reset by peer

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by mdomsch** [comment]
Your S3 server, or a proxy or network device between your S3 server and
your S3cmd client, broke your TCP session in a way s3cmd did not expect. Is
this a frequent occurrence?

**Comment by windoverwater** [comment]
As of Friday after the file refactoring, it is 100% repeatable.  The sync seems to work 100% of the time without the delete option (or perhaps the large # of deletes - TBD) - always fails with the delete option.

**Comment by fviard** [comment]
Hum, do you know what you are using as S3 service? I don't think that it is amazon, no?

Maybe, the service simply doesn't support the "batch delete" function, and so cut the connection the hard way after encountering the error.

If think that you can test this by uploading a folder inside your bucket, and then, you test a "./s3cmd rm --recursive s3://yourbucket/yourfolder" to delete recursively your folder. If I'm true, that should fail in the same way. (WARNING: take care with the arguments of your command to not risk deleting important things in your bucket)

**Comment by mdomsch** [comment]
Please give a try with this branch:
https://github.com/s3tools/s3cmd/tree/bug/unexpected-close

It has a fix which should allow for retries on ECONNRESET errors instead of
crashing with a traceback.  Now, the Verizon server you were using may
still fail due to not supporting batch deletes, at which point the retry
counter will go to zero, but at least you won't crash due to the connection
reset by peer.

Thanks,
Matt

**Comment by fviard** [comment]
@windoverwater If you are still encountering the issue, can you give a try to the latest master with the -d flag?
Now we should be able to see the real server error associated with your issue.
