### ISSUE TITLE
error with s3cmd rm -r

### ISSUE THREAD

**Issue by gfim** [s3tools/s3cmd#687]
s3cmd rm -vr s3://zzz/xxx

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd rm -vr s3://zzz/xxx
Problem: ValueError: Key list is empty
S3cmd:   1.6.0
python:   2.7.11 (default, Dec 23 2015, 10:00:16)
[GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)]
environment LANG=en_AU.UTF-8

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 2805, in <module>
    rc = main()
  File "/usr/local/bin/s3cmd", line 2713, in main
    rc = cmd_func(args)
  File "/usr/local/bin/s3cmd", line 601, in cmd_object_del
    rc = subcmd_batch_del_iterative(uri_str = uri_str)
  File "/usr/local/bin/s3cmd", line 624, in subcmd_batch_del_iterative
    response = s3.object_batch_delete_uri_strs([uri.compose_uri(bucket, item['Key']) for item in to_delete])
  File "/usr/local/lib/python2.7/site-packages/S3/S3.py", line 665, in object_batch_delete_uri_strs
    raise ValueError("Key list is empty")
ValueError: Key list is empty

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by fviard** [comment]
@gfim: Are you able to reproduce this issue with the version 1.6.1? i'm not.

**Comment by gfim** [comment]
Sorry about taking so long to reply.

Yes, it seems to be fixed in 1.1.6.

Thanks,
  Graham
