### ISSUE TITLE
.svg files not recognized by --guess-mime-type

### ISSUE THREAD

**Issue by jtbr** [s3tools/s3cmd#698]
The guess mime type function (unlike python-magic) does a great job guessing file types for web files: html, js, css, png, jpg, gif, etc. But it fails with .svg image files (or at least ones I've tried) which should have the content-type: image/svg+xml.

It would be great if support for this could be added.

**Comment by hneelakantan** [comment]
+1 for that

**Comment by fviard** [comment]
It is not s3cmd that does this mime guessing, it uses either python-magic (or file or filemagic) [depending on your setup] OR python default mimetypes.guess_type [if you asked for --no-mime-magic].
So check the library that you have installed on your system, if you should not update/replace it and if the issue persists contact upstream of these projects for them to update their database.

**Comment by fviard** [comment]
It has been a long time, but, if you are still having the issue, I have created a wiki page related to this topic:
https://github.com/s3tools/s3cmd/wiki/Understand-Content-Type,-Mime-type-guessing-and-Magic

In short, s3cmd just use what is detected by other system components for file extension or magic.
One way to achieve your purpose without hacking is just to add the rules in the /etc/mime.types and /etc/magic files of your system.
