### ISSUE TITLE
Error syncing from S3 bucket: AttributeError: 'module' object has no attribute 'ETXTBSY'

### ISSUE THREAD

**Issue by lruminski** [s3tools/s3cmd#709]
running on Windows with python 2.7.6, on latest master branch of s3cmd

's3cmd get' command works properly downloading files from the bucket
's3cmd sync' errors with the following:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: s3cmd sync -r s3://lexuswheelstand2016 ..\s3test
Problem: AttributeError: 'module' object has no attribute 'ETXTBSY'
S3cmd:   1.6.1
python:   2.7.6 (default, Nov 10 2013, 19:24:24) [MSC v.1500 64 bit (AMD64)]
environment LANG=None

Traceback (most recent call last):
  File "s3cmd", line 2919, in <module>
    rc = main()
  File "s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "s3cmd", line 1791, in cmd_sync
    return cmd_sync_remote2local(args)
  File "s3cmd", line 1392, in cmd_sync_remote2local
    ret, seq, size_transferred = _download(remote_list, seq, remote_count + update_count, size_transferred, dir_cache)
  File "s3cmd", line 1233, in _download
    exc.errno == errno.ETXTBSY or
AttributeError: 'module' object has no attribute 'ETXTBSY'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by fviard** [comment]
Thank you for your report. It is indeed a bug.
I think that I did a change that is not compatible with windows.
I will have a look at that.

**Comment by lruminski** [comment]
would you know which version introduced the bug?

**Comment by fruser** [comment]
I've got the same problem with the 1.6.1 version. 
@lruminski by trial and error I found that 1.5.2 ([pypi_url](https://pypi.python.org/pypi/s3cmd/1.5.2)) works just fine.

**Comment by lruminski** [comment]
@fruser indeed it does. Thanks!

**Comment by fviard** [comment]
I have finally found a windows box to investigate this issue.
It is now fixed in master.

@lruminski @fruser could you give a try to the last master version?
Also I think that it could be in your interest, because I'm not very sure, but I think that when you use the 1.5.2 version, the error is just hidden and so local files are not "overwritten" as they should.
And so it was like if you have keep the old local version of a file after a sync.
