### ISSUE TITLE
ImportError: No module named S3.ExitCodes in abortmp

### ISSUE THREAD

**Issue by sc0rp10** [s3tools/s3cmd#717]
log file here: https://gist.github.com/sc0rp10/eb251f88520b0f29bafd/raw

**Comment by fviard** [comment]
Do you have any other command of s3cmd that works? like a s3cmd ls?
Your installation path looks like to be non standard:
/usr/local/Cellar/s3cmd/1.6.0/libexec/bin/s3cmd
And my intuition tells me that s3cmd modules (a "S3" folder with things like CloudFront.py inside), should be somewhere inside /usr/local/Cellar/s3cmd/1.6.0/???? but i don't see such a path inside your sys.path

**Comment by fviard** [comment]
Closed because of no more feedback.
Please re-open with a debug trace (-d) if still reproducible with latest master
