### ISSUE TITLE
How to Using S3cmd download video dataset (MED2016)

### ISSUE THREAD

**Issue by wangzi8338** [s3tools/s3cmd#721]
Follow this 4 steps , i can not download the dataset succussfully!
1. Download and install s3cmd from http://s3tools.org/download (or using an appropriate package manager for your platform)
2. Run 's3cmd --configure' and enter your access key and secret ( available via https://aws-portal.amazon.com/gp/aws/developer/account/index.html?action=access-key ). Here you can also specify additional options, such as enabling encryption during transfer, and enabling a proxy.
3. Run 's3cmd ls s3://yahoo-webscope/I3set10/' to view the S3 objects for I3 - Yahoo Flickr Creative Commons 100M (14G) (Hosted on AWS)
4. Run 's3cmd get --recursive s3://yahoo-webscope/I3set10/' to download a local copy of I3 - Yahoo Flickr Creative Commons 100M (14G) (Hosted on AWS)

I want ask you how to success download the dataset.
when i input "s3cmd ls" also occur [Erron 10049]

**Comment by MadeInChina** [comment]
@wangzi8338 i just apply from the yahoo labs but didn't get not any email response. how did you apply it?

**Comment by licx265** [comment]
you must get engage in this project of MED2016.
after then you can apply the dataset!

**Comment by MadeInChina** [comment]
i just found http://www.nist.gov/itl/iad/mig/med16.cfm. so did you downloaded  I3set10?

**Comment by vishakhhegde** [comment]
@wangzi8338, did you find a way to download the whole flickr 100M dataset?

**Comment by vishakhhegde** [comment]
@wangzi8338 did you find a way to download the whole of flickr 100M dataset?
