### ISSUE TITLE
Sync cmd on windows re download not modified files

### ISSUE THREAD

**Issue by fviard** [s3tools/s3cmd#722]
In a command like that:
python s3cmd sync -r s3://testwindows localdir/

s3cmd re download the file each time even if the md5 is still the same.

My guess is that it should be because filenames of cloud and local are not compared with the same os separator.
ex: s3//testwindows/test-file1.log vs localdir\test-file1.log

**Comment by MarZab** [comment]
I think im seeing the same thing on MacOS as well

**Comment by fviard** [comment]
Another report for windows  that is has the similar root cause:

`Hello,

Thank you for s3tools, which is useful to me for retrieving website statistics.  I just began using a new up-to-date Windows 10 64-bit computer with the latest s3tools and python.  I had no problems with the download on my earlier computer.  I ran my batch program to call s3tools successfully (I think) the first time earlier today on the new computer. A few minutes ago I ran it a second time. On this run I got these messages:

 

0688' (300 bytes in 0.1 seconds, 4.65 kB/s) [25 of 28]

download: 's3://logs.htptu.com/root/2016-09-07-22-22-49-DB57154DF1381327' -> 'c:\s3Logs\2016-09-07-22-22-49-DB57154DF1381327' (290 bytes in 0.1 seconds, 5.45 kB/s) [26 of 28]

download: 's3://logs.htptu.com/root/2016-09-07-22-22-58-025FCEAC9A5FF720' -> 'c:\s3Logs\2016-09-07-22-22-58-025FCEAC9A5FF720' (381 bytes in 0.1 seconds, 3.88 kB/s) [27 of 28]

download: 's3://logs.htptu.com/root/2016-10-17-23-46-04-5A74B4EB7FA0BD51' -> 'c:\s3Logs\2016-10-17-23-46-04-5A74B4EB7FA0BD51' (290 bytes in 0.1 seconds, 4.72 kB/s) [28 of 28]

 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    An unexpected error has occurred.

  Please try reproducing the error using

  the latest s3cmd code from the git master

  branch found at:

    https://github.com/s3tools/s3cmd

  and have a look at the known issues list:

    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions

  If the error persists, please report the

  following lines (removing any private

  info as necessary) to:

   s3tools-bugs@lists.sourceforge.net

 

 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

 

Invoked as: s3cmd sync --skip-existing s3://logs.htptu.com/root/ c:\s3Logs\

Problem: Error: `c:/s3Logs/2016-09-08-00-35-25-57579332709A5C55` and `c:\s3Logs\2016-09-08-00-35-25-57579332709A5C55` are the same file

S3cmd:   1.6.1

python:   2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]

environment LANG=None

 

Traceback (most recent call last):

  File "s3cmd", line 2919, in <module>

    rc = main()

  File "s3cmd", line 2841, in main

    rc = cmd_func(args)

  File "s3cmd", line 1791, in cmd_sync

    return cmd_sync_remote2local(args)

  File "s3cmd", line 1397, in cmd_sync_remote2local

    n_copies, size_copies, failed_copy_list = local_copy(copy_pairs, destination_base)

  File "s3cmd", line 1445, in local_copy

    shutil.copy2(deunicodise(src_file), deunicodise(dst_file))

  File "c:\Python27\lib\shutil.py", line 130, in copy2

    copyfile(src, dst)

  File "c:\Python27\lib\shutil.py", line 69, in copyfile

    raise Error("`%s` and `%s` are the same file" % (src, dst))

Error: `c:/s3Logs/2016-09-08-00-35-25-57579332709A5C55` and `c:\s3Logs\2016-09-08-00-35-25-57579332709A5C55` are the same file

 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    An unexpected error has occurred.

  Please try reproducing the error using

  the latest s3cmd code from the git master

  branch found at:

    https://github.com/s3tools/s3cmd

  and have a look at the known issues list:

    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions

  If the error persists, please report the

  above lines (removing any private

  info as necessary) to:

   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Note that the problem occurred after downloading the last of the 28 files.
Would I be better off running the 64-bit version of Python?
I ran the program again, and got the same problem, after the last of the files had been downloaded.
Thanks for your help,

Don Macnaughton`
