### ISSUE TITLE
How to Instruct s3cmd to Issue Multipart Abort Instruction

### ISSUE THREAD

**Issue by amitsidhim** [s3tools/s3cmd#727]
Team, 

I have a query , incase if there situation if the Mulipart upload fails due to Network issue, is there a way I can send abort signal, so that at  client end it can cleanup the data that has been accumulated.

Thanks

**Comment by mdomsch** [comment]
Yes.  Use the 'multipart' command to find such, and the 'abortmp' command
to abort it and clean up.

$ s3cmd multipart s3://s3cmd-test.domsch.com/

s3://s3cmd-test.domsch.com/
Initiated Path Id
2015-02-18T22:01:25.000Z s3://s3cmd-test.domsch.com/bigfile
UNKLP86LDlu4GZJJb0j2oZ92Z0HRDkabdne7dkMxQgUXbBrmF_xu8wSENfhnv0QnQEwqYp84a7yPf6WBAm2_Vg--

$ s3cmd abortmp s3://s3cmd-test.domsch.com/bigfile
UNKLP86LDlu4GZJJb0j2oZ92Z0HRDkabdne7dkMxQgUXbBrmF_xu8wSENfhnv0QnQEwqYp84a7yPf6WBAm2_Vg--
s3cmd-test.domsch.com/bigfile

**Comment by amitsidhim** [comment]
Thanks  a lot team, I was struggling to find the examples in this.
