### ISSUE TITLE
Does S3cmd Supports Multipart Download

### ISSUE THREAD

**Issue by amitsidhim** [s3tools/s3cmd#728]
Hello Team, 

I can very well upload a data using multipart upload . I wanted to  know  is there a way to even download data using multipart download and using the chuck size in s3cmd. Appreciate with some command line examples. 

Thanks in Advance

**Comment by mdomsch** [comment]
No, it does not support multipart downloads, or for that matter, any
parallel actions, at this point in time.

Thanks,
Matt

**Comment by amitsidhim** [comment]
Thanks, Team for the prompt reply.
