### ISSUE TITLE
Getting error message "Problem: ValueError: incomplete format"

### ISSUE THREAD

**Issue by phil2508** [s3tools/s3cmd#73]
I'd love to use this tool but I'm getting the following error message. Anybody here who can help?

> Problem: ValueError: incomplete format
> S3cmd:   0.9.9.91
>  
> Traceback (most recent call last):
>   File "/usr/bin/s3cmd", line 1736, in <module>
>     main()
>   File "/usr/bin/s3cmd", line 1557, in main
>     cfg = Config(options.config)
>   File "/usr/share/s3cmd/S3/Config.py", line 81, in **init**
>     self.read_config_file(configfile)
>   File "/usr/share/s3cmd/S3/Config.py", line 98, in read_config_file
>     cp = ConfigParser(configfile)
>   File "/usr/share/s3cmd/S3/Config.py", line 135, in **init**
>     self.parse_file(file, sections)
>   File "/usr/share/s3cmd/S3/Config.py", line 163, in parse_file
>     print_value = (data["value"][:2]+"...%d_chars..."+data["value"][-1:]) % (len(data["value"]) - 3)
> ValueError: incomplete format

**Comment by matthewlboyd** [comment]
Way late to this party, but I was running into the same error. Removing the % in my gpg password resolved the problem.

**Comment by fviard** [comment]
Closing as should already be fixed in last versions.
