### ISSUE TITLE
Errno 2: Name or service not known: on this command: s3cmd mb s3://mybucket --debug

### ISSUE THREAD

**Issue by antonleshkevich** [s3tools/s3cmd#748]
DEBUG: s3cmd version 1.6.1
DEBUG: ConfigParser: Reading file '/home/anton/.s3cfg'
DEBUG: ConfigParser: host_base->https://play.minio.io:9000
DEBUG: ConfigParser: host_bucket->https://play.minio.io:9000
DEBUG: ConfigParser: bucket_location->us-east-1
DEBUG: ConfigParser: access_key->Q3...17_chars...F
DEBUG: ConfigParser: secret_key->zu...37_chars...G
DEBUG: ConfigParser: signature_v2->False
DEBUG: Updating Config.Config cache_file ->
DEBUG: Updating Config.Config follow_symlinks -> False
DEBUG: Updating Config.Config verbosity -> 10
DEBUG: Unicodising 'mb' using UTF-8
DEBUG: Unicodising 's3://mybucket' using UTF-8
DEBUG: Command: mb
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v4
DEBUG: get_hostname(mybucket): https://play.minio.io:9000
DEBUG: canonical_headers = host:https://play.minio.io:9000
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20160604T220451Z

DEBUG: Canonical Request:
PUT
/mybucket/

host:https://play.minio.io:9000
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20160604T220451Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
----------------------
DEBUG: signature-v4 headers: {'x-amz-content-sha256': 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': 'AWS4-HMAC-SHA256 Credential=Q3AM3UQ867SPQQA43P2F/20160604/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=538522d34c843e38177385cb9fda5f1cbea76f12abf4333dbbe733e29bfe8b7f', 'x-amz-date': '20160604T220451Z'}
DEBUG: Processing request, please wait...
DEBUG: get_hostname(mybucket): https://play.minio.io:9000
DEBUG: ConnMan.get(): creating new connection: https://https://play.minio.io:9000
DEBUG: Using ca_certs_file None
DEBUG: httplib.HTTPSConnection() has only context
DEBUG: non-proxied HTTPSConnection(https://play.minio.io:9000)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

DEBUG: Unicodising '/usr/bin/s3cmd' using UTF-8
DEBUG: Unicodising 'mb' using UTF-8
DEBUG: Unicodising 's3://mybucket' using UTF-8
DEBUG: Unicodising '--debug' using UTF-8
Invoked as: /usr/bin/s3cmd mb s3://mybucket --debug
Problem: gaierror: [Errno -2] Name or service not known
S3cmd:   1.6.1
python:   2.7.11+ (default, Apr 17 2016, 14:00:29)
[GCC 5.3.1 20160413]
environment LANG=ru_RU.UTF-8

Traceback (most recent call last):
  File "/usr/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/usr/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/usr/bin/s3cmd", line 205, in cmd_bucket_create
    response = s3.bucket_create(uri.bucket(), cfg.bucket_location)
  File "/usr/lib/python2.7/dist-packages/S3/S3.py", line 367, in bucket_create
    response = self.send_request(request)
  File "/usr/lib/python2.7/dist-packages/S3/S3.py", line 1081, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "/usr/lib/python2.7/dist-packages/S3/ConnMan.py", line 192, in get
    conn.c.connect()
  File "/usr/lib/python2.7/httplib.py", line 1270, in connect
    HTTPConnection.connect(self)
  File "/usr/lib/python2.7/httplib.py", line 836, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 557, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
gaierror: [Errno -2] Name or service not known

**Comment by fviard** [comment]
You need to remove the "https://" string of the two following configs:
```
host_base = https://play.minio.io:9000
host_bucket =https://play.minio.io:9000
```
So the right config are:
```
host_base = play.minio.io:9000
host_bucket = play.minio.io:9000
```

Please also ensure to have the following setting:
use_https = True

**Comment by fviard** [comment]
With the right configuration (and the last master when using github master version), that should work now.
Configuration should have been updated in minio documentation also.
