### ISSUE TITLE
Sync error directory with space in name

### ISSUE THREAD

**Issue by verlata** [s3tools/s3cmd#751]
Hello all,
s3cmd version 1.6.1 on ubuntu 14.04. Trying to sync remote tree (with spaces in folder names) to local:
$/usr/local/bin/s3cmd sync s3://remotebucket/ /localfolder/s3/

here is the output:
download: 's3://remotebucket/100001/2014-old/Fatture PA/Allegati/118/0000000009/10484.P7M' -> '/localfolder/s3/100001/2014-old/Fatture PA/Allegati/118/0000000009/10484.P7M' [10 of 11645]

and the warning: WARNING: Remote file ''. S3Error: 404 (Not Found)

in /localfolder/ the folder tree is recreated correctly (even the folder with spaces), but no file is there.

Any idea?
TIA, Giuseppe

**Comment by fviard** [comment]
Can you try with the last github version (master) ?
I can't reproduce this. If you are still encountering this issue with the last version, you can generate a more detailed log with the "-d" option.

**Comment by verlata** [comment]
Using github master and debug flag:

DEBUG: DeUnicodising u'/localfolder/s3/100001/2015/Fatture PA/Allegati/354/0000000011/14979.P7M' using UTF-8
DEBUG: Unicodising '/localfolder/s3/100001/2015/Fatture PA/Allegati/354/0000000011' using UTF-8
DEBUG: dst_file=/localfolder/s3/100001/2015/Fatture PA/Allegati/354/0000000011/14979.P7M
DEBUG: DeUnicodising u'/localfolder/s3/100001/2015/Fatture PA/Allegati/354/0000000011/14979.P7M' using UTF-8
DEBUG: Unicodising '/localfolder/s3/100001/2015/Fatture PA/Allegati/354/0000000011/.s3cmd._AcSx0.tmp' using UTF-8
DEBUG: created chkptfname=/localfolder/s3/100001/2015/Fatture PA/Allegati/354/0000000011/.s3cmd._AcSx0.tmp
DEBUG: String '100001/2015/Fatture PA/Allegati/354/0000000011/14979.P7M' encoded to '100001/2015/Fatture+PA/Allegati/354/0000000011/14979.P7M'
DEBUG: CreateRequest: resource[uri]=/100001/2015/Fatture+PA/Allegati/354/0000000011/14979.P7M
DEBUG: Unicodising "Bucket name 'remotebucket' contains disallowed character 'C'. The only supported ones are: lowercase us-ascii letters (a-z), digits (0-9), dot (.) and hyphen (-)." using UTF-8
DEBUG: Using signature v2
DEBUG: SignHeaders: 'GET\n\n\n\nx-amz-date:Wed, 15 Jun 2016 12:17:43 +0000\n/remotebucket/100001/2015/Fatture+PA/Allegati/354/0000000011/14979.P7M'
DEBUG: Unicodising '<fdopen>' using UTF-8
download: 's3://remotebucket/100001/2015/Fatture PA/Allegati/354/0000000011/14979.P7M' -> '/localfolder/s3/100001/2015/Fatture PA/Allegati/354/0000000011/14979.P7M'  [121 of 11645]
DEBUG: Unicodising "Bucket name 'remotebucket' contains disallowed character 'C'. The only supported ones are: lowercase us-ascii letters (a-z), digits (0-9), dot (.) and hyphen (-)." using UTF-8
DEBUG: get_hostname(remotebucket): s3.ns3.it
DEBUG: ConnMan.get(): creating new connection: http://s3.ns3.it
DEBUG: non-proxied HTTPConnection(s3.ns3.it)
DEBUG: Unicodising "Bucket name 'remotebucket' contains disallowed character 'C'. The only supported ones are: lowercase us-ascii letters (a-z), digits (0-9), dot (.) and hyphen (-)." using UTF-8
DEBUG: format_uri(): /remotebucket/100001/2015/Fatture+PA/Allegati/354/0000000011/14979.P7M
DEBUG: Response: {'status': 404, 'headers': {'content-length': '75', 'accept-ranges': 'bytes', 'server': 'Apache/2.2.22 (Ubuntu)', 'x-amz-request-id': 'tx000000000000000241839-0057614769-34bad7-default', 'date': 'Wed, 15 Jun 2016 12:17:45 GMT', 'content-type': 'application/xml'}, 'reason': 'Not Found'}
DEBUG: S3Error: 404 (Not Found)
DEBUG: HttpHeader: content-length: 75
DEBUG: HttpHeader: accept-ranges: bytes
DEBUG: HttpHeader: server: Apache/2.2.22 (Ubuntu)
DEBUG: HttpHeader: x-amz-request-id: tx000000000000000241839-0057614769-34bad7-default
DEBUG: HttpHeader: date: Wed, 15 Jun 2016 12:17:45 GMT
DEBUG: HttpHeader: content-type: application/xml
WARNING: Remote file ''. S3Error: 404 (Not Found)
DEBUG: DeUnicodising u'/localfolder/s3/100001/2015/Fatture PA/Allegati/354/0000000011/.s3cmd._AcSx0.tmp' using UTF-8

What I see is the "disallowed character 'C' " warning, so I tried creating a new bucket with low-case characters and syncing from that bucket: same result: WARNING: Remote file ''. S3Error: 404 (Not Found).
So I think this problem has to do with the presence of spaces in folder names...

**Comment by fviard** [comment]
Ok, I understand, you are using a custom server and not amazon s3?
In that case, it is probably the server that is not handling correctly files with spaces in names.
On point that is complicated with the protocol is that "path" are urlencoded using the "quoteplus" method, meaning that "space" char are replaced by "+" chars.

There is probably an issue of the server using "unquote" like function instead of a "unquote_plus".
So, in my opinion you should report this issue to the service that you are using.

**Comment by fviard** [comment]
@verlata In version 2.0.0 we have changed the encoding mode so that should now be compatible with your provider.
