### ISSUE TITLE
Cannot run at crontab in freebsd

### ISSUE THREAD

**Issue by zyzhang6** [s3tools/s3cmd#752]
I used s3cmd to do backup at freebsd system.

At beginning, I used cmd **"s3cmd sync --recursive --ssl /backup to s3://jzbackup"**. This command runs successfully. Then I want to set up schedule job for this backup.

First, I created a shell script .s3backup.sh at /home/jail. The above command line input at .s3backup.sh file. Then I run command **"sh /home/jail/.s3backup.sh"**. It also runs successfully.

Finally, I use "crontab -e" to add cron job. The crontab setting is as following:
```
SHELL=/bin/sh
MAILTO=""
PATH=/etc:/bin:/sbin:/usr/bin:/user/sbin:/root:/home/jail:/usr/local/sbin:/backup
*/5 * * * * sh /home/jail/.s3backup.sh

```

However, the script cannot be executed (i.e. no file uploaded to S3). And in cron log file, I can find 
**Jul 15 23:50:00 amazone /user/sbin/cron[85256]: (root) CMD (sh /home/jail/.s3backup.sh)**

**Comment by mdomsch** [comment]
typo in PATH "user" not "usr"

**Comment by zyzhang6** [comment]
Hi mdomsch,

I am using freebsd. It seems freebsd does not have "user".

**Comment by zyzhang6** [comment]
I got it soleved. I need to use full path for s3cmd (i.e. /usr/bin/s3cmdZ).
