### ISSUE TITLE
s3cmd cannot sync file/folder with space or Chinese character in the file/folder name

### ISSUE THREAD

**Issue by zyzhang6** [s3tools/s3cmd#754]
s3cmd cannot sync file/folder with space or Chinese character in the file/folder name. Those files or folders will be ignored.

**Comment by mdomsch** [comment]
Please provide an example run with --debug.

**Comment by fviard** [comment]
In theory, this should work. With the debug, can you confirm that you are using "amazon" servers?

**Comment by zyzhang6** [comment]
After some more tests, I think the problem is freebsd system cannot identify Chinese characters (including Chinese space). When I run ls command, it shows name with "????" and this kind of folder or file will not be sync to Amazon
![2016-06-20_113145](https://cloud.githubusercontent.com/assets/19955823/16182627/e03310a6-36da-11e6-8dfd-c2d70269c56f.JPG)
![2016-06-20_113156](https://cloud.githubusercontent.com/assets/19955823/16182629/e2f60564-36da-11e6-8217-235e92b37b2d.JPG)

.

**Comment by fviard** [comment]
Can't you extract the complete log? I think earlier there should be some info about the file that is at issue. Because the last lines are only about the good one.
Also, you can maybe check that your system is setup with an "UTF8" locale.

**Comment by zyzhang6** [comment]
Hi, I changed the freebsd to UTF-8 for language and character set. After that, the folder name with Chinese can show at console. However, when I use s3cmd to sync the folders with Chinese to Amazon. It is still not success. Please see the full log file attached. 
[s3cmd.txt](https://github.com/s3tools/s3cmd/files/329354/s3cmd.txt)

**Comment by mdomsch** [comment]
Your .s3cfg value for encoding needs to be not US-ASCII, but UTF-8.

**Comment by zyzhang6** [comment]
Thanks. The issue fixed. I changed encoding at .s3cfg to UTF-8. Why the default setting is not UTF-8? I think UTF-8 covers more scenarios.

**Comment by fviard** [comment]
The default setting should be based on your system settings.
So I guess that you created the config file when you had your system in us-ascii, that's why you had it like that in the end.

**Comment by zyzhang6** [comment]
I see. Thanks for the explaintion.
