### ISSUE TITLE
ParseError: reference to invalid character number: line 2, column 138022

### ISSUE THREAD

**Issue by angeloc** [s3tools/s3cmd#758]
Invoked as: /usr/local/bin/s3cmd sync -v --dry-run --recursive --progress s3://xxx-prod/ s3://xxx-prod-backup
Problem: ParseError: reference to invalid character number: line 2, column 138022
S3cmd:   1.6.1
python:   2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2]
environment LANG=it_IT.UTF-8

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/usr/local/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/usr/local/bin/s3cmd", line 1793, in cmd_sync
    return cmd_sync_remote2remote(args)
  File "/usr/local/bin/s3cmd", line 942, in cmd_sync_remote2remote
    src_list, src_exclude_list, remote_total_size = fetch_remote_list(args[:-1], recursive = True, require_attribs = True)
  File "/usr/local/lib/python2.7/dist-packages/S3/FileLists.py", line 455, in fetch_remote_list
    objectlist, tmp_total_size = _get_filelist_remote(uri, recursive = True)
  File "/usr/local/lib/python2.7/dist-packages/S3/FileLists.py", line 392, in _get_filelist_remote
    recursive = recursive, uri_params = uri_params)
  File "/usr/local/lib/python2.7/dist-packages/S3/S3.py", line 297, in bucket_list
    for dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params):
  File "/usr/local/lib/python2.7/dist-packages/S3/S3.py", line 325, in bucket_list_streaming
    current_list = _get_contents(response["data"])
  File "/usr/local/lib/python2.7/dist-packages/S3/S3.py", line 314, in _get_contents
    return getListFromXml(data, "Contents")
  File "/usr/local/lib/python2.7/dist-packages/S3/Utils.py", line 101, in getListFromXml
    tree = getTreeFromXml(xml)
  File "/usr/local/lib/python2.7/dist-packages/S3/Utils.py", line 89, in getTreeFromXml
    tree = ET.fromstring(xml)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: reference to invalid character number: line 2, column 138022

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by fviard** [comment]
Are you using amazon S3 or a third party service?
If you run the command with the "--debug" flag, that could give us more details.

**Comment by angeloc** [comment]
@fviard 
I'm using a plain simple s3 bucket with various subfolders inside and a very high number of files.
--debug produces tons of output and includes too many sensitive informations, I try to upload only the relevant parts.

**Comment by fviard** [comment]
Ok, the debug will probably allows us to understand more.
To help the work,  I think that you need to post only the last 20/30 lines I think. around where there was the issue.

**Comment by angeloc** [comment]
This is the debug output:

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

DEBUG: Unicodising './s3cmd' using UTF-8
DEBUG: Unicodising 'sync' using UTF-8
DEBUG: Unicodising '--dry-run' using UTF-8
DEBUG: Unicodising '--recursive' using UTF-8
DEBUG: Unicodising '--progress' using UTF-8
DEBUG: Unicodising '--debug' using UTF-8
DEBUG: Unicodising 's3://nuvola-prod/' using UTF-8
DEBUG: Unicodising 's3://nuvola-prod-backup' using UTF-8
Invoked as: ./s3cmd sync --dry-run --recursive --progress --debug
s3://nuvola-prod/ s3://nuvola-prod-backup
Problem: ParseError: reference to invalid character number: line 2, column
170349
S3cmd:   1.6.1
python:   2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2]
environment LANG=it_IT.UTF-8

Traceback (most recent call last):
  File "./s3cmd", line 2919, in <module>
    rc = main()
  File "./s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "./s3cmd", line 1793, in cmd_sync
    return cmd_sync_remote2remote(args)
  File "./s3cmd", line 942, in cmd_sync_remote2remote
    src_list, src_exclude_list, remote_total_size =
fetch_remote_list(args[:-1], recursive = True, require_attribs = True)
  File "/home/ubuntu/s3cmd/S3/FileLists.py", line 455, in fetch_remote_list
    objectlist, tmp_total_size = _get_filelist_remote(uri, recursive = True)
  File "/home/ubuntu/s3cmd/S3/FileLists.py", line 392, in
_get_filelist_remote
    recursive = recursive, uri_params = uri_params)
  File "/home/ubuntu/s3cmd/S3/S3.py", line 298, in bucket_list
    for dirs, objects in self.bucket_list_streaming(bucket, prefix,
recursive, uri_params):
  File "/home/ubuntu/s3cmd/S3/S3.py", line 326, in bucket_list_streaming
    current_list = _get_contents(response["data"])
  File "/home/ubuntu/s3cmd/S3/S3.py", line 315, in _get_contents
    return getListFromXml(data, "Contents")
  File "/home/ubuntu/s3cmd/S3/Utils.py", line 101, in getListFromXml
    tree = getTreeFromXml(xml)
  File "/home/ubuntu/s3cmd/S3/Utils.py", line 89, in getTreeFromXml
    tree = ET.fromstring(xml)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1506, in
_raiseerror
    raise err
ParseError: reference to invalid character number: line 2, column 170349

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:

https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!


2016-06-28 10:45 GMT+02:00 Florent Viard <notifications@github.com>:

> Ok, the debug will probably allows us to understand more.
> To help the work, I think that you need to post only the last 20/30 lines
> I think. around where there was the issue.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/s3tools/s3cmd/issues/758#issuecomment-228989004>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AA0RWY7fe12YC05xzyysOSNWLj3BP7uxks5qQN85gaJpZM4I_2gi>
> .
>



-- 
Profile: http://it.linkedin.com/in/compagnucciangelo

**Comment by fviard** [comment]
i did try a few things, but I was not able to reproduce your issue.
Is it still reproducible for you? Can you try with the last git master version of s3cmd?

**Comment by jaredmoody** [comment]
I'm having this same error when trying to work with a file with invalid UTF-8 characters in the file name. One of my objects has `\u0019` in the name which s3cmd doesn't like.

**Comment by fviard** [comment]
Ok, I was able to reproduce the issue and now I understand.
The issue is when files with invalid characters are uploaded with aws cli  instead of s3cmd.

WIth aws all utf-8 characters are valid to manipulate and upload through rest requests, but when listing files, the listing is sent through xml. And xml has a largest list of forbidden characters than utf-8.
Normally s3cmd replace/escape invalid characters in filenames before uploading the files. But aws cli doesn't look like to do that.

aws cli doesn't have an issue to retrieve the xml after because it use an option "encoding_type =url" when requesting the listing. This will url encode all the file names in the returned list.
The issue to use this option is that it will give file names different of what we upload, i'm not sure if a lot of s3-compatible servers implement it, and so I might risk to "url decode" what was not url encoded.
