### ISSUE TITLE
SSL certificate verification failure: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol

### ISSUE THREAD

**Issue by UriShohet** [s3tools/s3cmd#761]
Hi, I'm sometimes getting 
```
SSL certificate verification failure: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
```
while executing commands (get, del, put).

Any idea what could be the problem?

Ubuntu 14.04.4 LTS
Python 2.7.6

**Comment by fviard** [comment]
Check that you have the correct "host" url set in your configuration file.
And also, if you don't have any firewall or "proxy" in between you and the amazon server.
Such error occurs when you are trying to talk "https" to a server that is not a "https" server.
