### ISSUE TITLE
S3 error: 403 (AccessDenied): Access Denied

### ISSUE THREAD

**Issue by komalsrathi** [s3tools/s3cmd#762]
Hi,
 
I am trying to perform ls/get operations on a publicly accessible s3 bucket: s3://cgl-rnaseq-recompute-fixed
 
```
$ s3cmd --configure
# I put my access key and secret key and the configuration worked because I got this message at the end:
Test access with supplied credentials? [Y/n] Y
Please wait, attempting to list all buckets...
Success. Your access key and secret key worked fine :-)
​
Now verifying that encryption works...
Success. Encryption and decryption worked fine :-)
​
# When I try to list the contents of the bucket, it says access denied
$ s3cmd --requester-pays ls s3://cgl-rnaseq-recompute-fixed
ERROR: Access to bucket 'cgl-rnaseq-recompute-fixed' was denied
ERROR: S3 error: 403 (AccessDenied): Access Denied

# I got this using --debug parameter
DEBUG: Sending request method_string='GET', uri='/?delimiter=/', headers={'x-amz-content-sha256': 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'x-amz-request-payer': 'requester', 'Authorization': 'AWS4-HMAC-SHA256 Credential=**************/20160714/us-west-2/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date;x-amz-request-payer,Signature=f5d55ac903eb2a968007653f3f4d28beac8fe0d920da0e629a4fd5c44ccd2f66', 'x-amz-date': '20160714T170216Z'}, body=(0 bytes)
DEBUG: Response: {'status': 403, 'headers': {'x-amz-bucket-region': 'us-west-2', 'x-amz-request-charged': 'requester', 'x-amz-id-2': 'YcGsGclBPXIUWUNWG1CS3xiyXvbKuUzIvaSXfIqCW7W56AvqZPryPLvYJiNJiI4GnJc5M0W1AcE=', 'server': 'AmazonS3', 'transfer-encoding': 'chunked', 'x-amz-request-id': '77B29892B083D287', 'date': 'Thu, 14 Jul 2016 17:02:15 GMT', 'content-type': 'application/xml'}, 'reason': 'Forbidden', 'data': '<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>77B29892B083D287</RequestId><HostId>YcGsGclBPXIUWUNWG1CS3xiyXvbKuUzIvaSXfIqCW7W56AvqZPryPLvYJiNJiI4GnJc5M0W1AcE=</HostId></Error>'}
```

Just an FYI, I can list/get the contents of a bunch of buckets that I have access to.
 
Any help would be much appreciated!

**Comment by mdomsch** [comment]
What version?  Works for me on github master branch.

$ ./s3cmd --requester-pays ls s3://cgl-rnaseq-recompute-fixed
                       DIR   s3://cgl-rnaseq-recompute-fixed/gtex/
                       DIR   s3://cgl-rnaseq-recompute-fixed/pnoc/
                       DIR   s3://cgl-rnaseq-recompute-fixed/target/
                       DIR   s3://cgl-rnaseq-recompute-fixed/tcga/
2016-07-08 19:02 314918856
s3://cgl-rnaseq-recompute-fixed/cwl-example.tar.gz
2016-06-03 17:02    435553   s3://cgl-rnaseq-recompute-fixed/gtex-manifest
2016-06-03 17:01      1534   s3://cgl-rnaseq-recompute-fixed/pnoc-manifest
2016-06-03 16:58     60922   s3://cgl-rnaseq-recompute-fixed/target-manifest
2016-06-03 17:01    923545   s3://cgl-rnaseq-recompute-fixed/tcga-manifest

**Comment by komalsrathi** [comment]
I am using the latest v1.6.1. This could be something related to the billing? Because the credentials were authenticated, what else could be the reason?

**Comment by komalsrathi** [comment]
Ok, I did not have the correct permissions for the AWS account. Closing it here.
