### ISSUE TITLE
Run s3cmd get in background

### ISSUE THREAD

**Issue by komalsrathi** [s3tools/s3cmd#764]
I am using `s3cmd` to get around ~11000 files from a publicly accessible s3 bucket (`s3://cgl-rnaseq-recompute-fixed`) to my EC2 container. I am using the following command:

`for i in $(cat tcga-manifest); do s3cmd get --requester-pays $i; done`

where `tcga-manifest` is a file with a list of files to get:

    head -n3 tcga-manifest

    s3://cgl-rnaseq-recompute-fixed/tcga/00065a62-5e18-4223-a884-12fca053a109.tar.gz
    s3://cgl-rnaseq-recompute-fixed/tcga/0009f27d-a053-49b0-a030-ba9c1469224f.tar.gz
    s3://cgl-rnaseq-recompute-fixed/tcga/000f476b-7d55-4fd1-8f72-622ab00e009b.tar.gz
    s3://cgl-rnaseq-recompute-fixed/tcga/001313a7-fbd7-4a9a-a961-50c7433338e7.tar.gz

However, I want to run the get command in the background so that when I log out of the EC2 container, it still keeps running. Also, because I am downloading a large number of files, the ssh connection breaks. I tried using `&` which did not work:

`for i in $(cat tcga-manifest); do s3cmd get --requester-pays $i; done &` 

How can I run the s3cmd get command in the background and logout of the EC2 container?

Thanks!

**Comment by fviard** [comment]
Have you tried running the command alone and see if there are some error?
At least, I think that you will need a "destination folder" for your get command.
like:  s3cmd get MY_Source_File somedestination/

**Comment by komalsrathi** [comment]
Actually, I do not get any error. I am just asking if I could run the s3cmd command in the background.

**Comment by mdomsch** [comment]
Put your commands in a shell script (e.g. get-all-files.sh).  Execute it
with 'nohup bash ./get-all-files.sh'​.  The 'nohup'. causes it to ignore
the usual SIGHUP (hangup) signal that occurs during logout, so continues
running.

Alternately, install screen, and execute it inside a screen session.

**Comment by komalsrathi** [comment]
Thanks! That works!
