### ISSUE TITLE
s3cmd fails with SSL Certificate error for buckets with '.' in the name

### ISSUE THREAD

**Issue by steevmi1** [s3tools/s3cmd#766]
If I try to create a bucket with a '.' in the name, s3cmd throws an SSL certificate error.

`$ s3cmd mb s3://test.bucket

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /opt/local/bin/s3cmd mb s3://test.bucket
Problem: CertificateError: hostname 'test.bucket.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
S3cmd:   1.6.1
python:   2.7.12 (default, Jun 29 2016, 12:52:38)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/opt/local/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/opt/local/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/opt/local/bin/s3cmd", line 205, in cmd_bucket_create
    response = s3.bucket_create(uri.bucket(), cfg.bucket_location)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/S3/S3.py", line 367, in bucket_create
    response = self.send_request(request)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/S3/S3.py", line 1081, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/S3/ConnMan.py", line 192, in get
    conn.c.connect()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 838, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 272, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
CertificateError: hostname 'test.bucket.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!`

Apologies if this is a known issue or if I've missed a config option for this.

**Comment by mdomsch** [comment]
Try with the master branch please.  This should be fixed there.

**Comment by fviard** [comment]
@steevmi1 That should work now, could you confirm?

**Comment by retostockli** [comment]
Nope. Does not work with 2.0.1 (worked with 1.6.0 for me):

./s3cmd ls s3://data.geo.admin.ch/ch.meteoschweiz.globalstrahlung-monatlich 

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: ./s3cmd ls s3://data.geo.admin.ch/ch.meteoschweiz.globalstrahlung-monatlich
Problem: CertificateError: hostname u'data.geo.admin.ch.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'
S3cmd:   2.0.1
python:   2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609]
environment LANG=en_US.ISO-8859-1

Traceback (most recent call last):
  File "./s3cmd", line 3073, in <module>
    rc = main()
  File "./s3cmd", line 2989, in main
    rc = cmd_func(args)
  File "./s3cmd", line 140, in cmd_ls
    subcmd_bucket_list(s3, uri, cfg.limit)
  File "./s3cmd", line 176, in subcmd_bucket_list
    response = s3.bucket_list(bucket, prefix = prefix, limit = limit)
  File "/prod/zue/climate/others/res/src/s3cmd-2.0.1/S3/S3.py", line 308, in bucket_list
    for truncated, dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params, limit):
  File "/prod/zue/climate/others/res/src/s3cmd-2.0.1/S3/S3.py", line 342, in bucket_list_streaming
    response = self.bucket_list_noparse(bucket, prefix, recursive, uri_params, max_keys)
  File "/prod/zue/climate/others/res/src/s3cmd-2.0.1/S3/S3.py", line 373, in bucket_list_noparse
    response = self.send_request(request)
  File "/prod/zue/climate/others/res/src/s3cmd-2.0.1/S3/S3.py", line 1249, in send_request
    conn = ConnMan.get(self.get_hostname(resource['bucket']))
  File "/prod/zue/climate/others/res/src/s3cmd-2.0.1/S3/ConnMan.py", line 253, in get
    conn.c.connect()
  File "/usr/lib/python2.7/httplib.py", line 1278, in connect
    server_hostname=server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 353, in wrap_socket
    _context=self)
  File "/usr/lib/python2.7/ssl.py", line 601, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 838, in do_handshake
    match_hostname(self.getpeercert(), self.server_hostname)
  File "/usr/lib/python2.7/ssl.py", line 272, in match_hostname
    % (hostname, ', '.join(map(repr, dnsnames))))
CertificateError: hostname u'data.geo.admin.ch.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com'

**Comment by retostockli** [comment]
And it does not work with the current master branch either:

./s3cmd ls s3://data.geo.admin.ch/ch.meteoschweiz.globalstrahlung-monatlich
WARNING: Retrying failed request: /?delimiter=%2F&prefix=ch.meteoschweiz.globalstrahlung-monatlich (hostname u'data.geo.admin.ch.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com')
WARNING: Waiting 3 sec...
WARNING: Retrying failed request: /?delimiter=%2F&prefix=ch.meteoschweiz.globalstrahlung-monatlich (hostname u'data.geo.admin.ch.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com')
WARNING: Waiting 6 sec...
WARNING: Retrying failed request: /?delimiter=%2F&prefix=ch.meteoschweiz.globalstrahlung-monatlich (hostname u'data.geo.admin.ch.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com')

**Comment by fviard** [comment]
@retostockli What is the value of host_base and host_bucket in your configuration file?

If you use your own domain name, and so that it is the certificate of this domain (not the one of amazon) that will be check, that should be setup in host_base / bucket also.

**Comment by retostockli** [comment]
Good Point. It was set to the Default Amazon naming. That worked well with 1.6.0 but seems to break in 2.0.1.

I've now changed values to:
host_base = data.geo.admin.ch
host_bucket = %(bucket)

Is that correct?
But now get this error:

./s3cmd ls s3://data.geo.admin.ch/ch.meteoschweiz.globalstrahlung-monatlich
ERROR: Error parsing xml: Malformed error XML returned from remote server..  ErrorXML: <html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
<ul>
<li>Code: NoSuchKey</li>
<li>Message: The specified key does not exist.</li>
<li>Key: data.geo.admin.ch/index.html</li>
<li>RequestId: 2D92B036837DA8A9</li>
<li>HostId: M5ZQYyqXfl+7toznaUCS0Mxmw5ZmXSE7VqNhnzp7n4OY03b9vBMGabx1STPN+gqx7SQ+loZirHQ=</li>
</ul>
<hr/>
</body>
</html>

ERROR: Error parsing xml: Malformed error XML returned from remote server..  ErrorXML: <html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
<ul>
<li>Code: NoSuchKey</li>
<li>Message: The specified key does not exist.</li>
<li>Key: data.geo.admin.ch/index.html</li>
<li>RequestId: 2D92B036837DA8A9</li>
<li>HostId: M5ZQYyqXfl+7toznaUCS0Mxmw5ZmXSE7VqNhnzp7n4OY03b9vBMGabx1STPN+gqx7SQ+loZirHQ=</li>
</ul>
<hr/>
</body>
</html>

ERROR: S3 error: 404 (Not Found)
res@zueub416 s3cmd-2.0.1> ./s3cmd ls s3://data.geo.admin.ch/ch.meteoschweiz.globalstrahlung-monatlich/
ERROR: Error parsing xml: Malformed error XML returned from remote server..  ErrorXML: <html>
<head><title>404 Not Found</title></head>
<body>
<h1>404 Not Found</h1>
<ul>
<li>Code: NoSuchKey</li>
<li>Message: The specified key does not exist.</li>
<li>Key: data.geo.admin.ch/index.html</li>
<li>RequestId: 2D92B036837DA8A9</li>
<li>HostId: M5ZQYyqXfl+7toznaUCS0Mxmw5ZmXSE7VqNhnzp7n4OY03b9vBMGabx1STPN+gqx7SQ+loZirHQ=</li>
</ul>
<hr/>
</body>
</html>

**Comment by fviard** [comment]
Your new configuration is not good, it should be that i think:
host_base = data.geo.admin.ch
host_bucket = %(bucket).data.geo.admin.ch

Host_base is the basic url for requests without buckets like if you try to create a new bucket, or list them.
Host_bucket is the url with the backet name inside, for all the requests on the specifc bucket, like listing objects inside.

**Comment by retostockli** [comment]
Solved, but not through the host_base and host_bucket entries. Instead the Switch from https to http did the Job:

< use_https = False
---
> use_https = True

Thanks for motivating!

**Comment by fviard** [comment]
@retostockli Sad, but thank you for the update.
Please take care that the data you transfer will be in plain text.
BTW, if you want to give it a last try, i noticed a small typo in the example i gave to you as i copy pasted.
Instead of : 
host_bucket = %(bucket).data.geo.admin.ch
it SHOULD BE:
host_bucket = %(bucket)s.data.geo.admin.ch

There is a small "s" after the parenthesis. Otherwise it will not replace bucket by the bucket name.

**Comment by retostockli** [comment]
The new host_bucket Name does not make a difference. The only difference is with the protocol. Interestingly https did work in 1.6.0 ...

**Comment by fviard** [comment]
@retostockli ok, in fact after looking more closely, i think that there is a mixup in your config or my understanding of your setup.

At the basis there is amazon, something like:
s3.amazonaws.com

So you probably created a bucket named: "data.geo.admin.ch".
So, if you go through amazon, you would use the following urls:
bucket less requests: s3.amazonaws.com
with bucket requests: data.geo.admin.ch.s3.amazonaws.com

Then you used your custom dns record, that you did setup like that:
https://data.geo.admin.ch  -> https://data.geo.admin.ch.s3.amazonaws.com

So your own domain is pointing directly at the amazon bucket url.
(sending bucket less requests to a bucket url, is supported by aws, so no issue reported).

in that case, your host_bucket should be fixed and not try to used the cmdline specified bucket.

So, in the end, with https on, you should have these 2 values like that:
host_bucket = data.geo.admin.ch
host_bucket = data.geo.admin.ch
(no more "bucket" templating).
