### ISSUE TITLE
Sync: incorrect remote filename generation?

### ISSUE THREAD

**Issue by michaeltyson** [s3tools/s3cmd#768]
s3cmd's sync facility seems to be generating incorrect remote filenames if more than one file have roughly similar names. The issue may be correlated with filenames having duplicate file extensions (.jpg.jpg). 

For example, a local filename "BIGsarah-dau.jpg.jpg" is being mapped to the remote filename "sarah-dau.jpg", which already exists and is associated with a different file ("sarah-dau.jpg"). Consequently, I see the error:

```
WARNING: Unable to remote copy files 's3://aoeuaoeuaoeu-backups/Sun/www/aoeuaoeuaoeu.com/public_html/files/BIGsarah-dau.jpg.jpg' -> 's3://aoeuaoeuaoeu-backups/Sun/www/aoeuaoeuaoeu.com/public_html/files/sarah-dau.jpg'
```

The original files:

```
$ ls /var/www/aoeuaoeuaoeu.com/public_html/files/*sarah-dau*
/var/www/aoeuaoeuaoeu.com/public_html/files/BIGsarah-dau.jpg.jpg
/var/www/aoeuaoeuaoeu.com/public_html/files/sarah-dau.jpg
```

Another example:

```
WARNING: Unable to remote copy files 's3://aoeuaoeuaoeu-backups/Sun/www/aoeuaoeuaoeu.com/public_html/files/BIGdow-sisters-1870s-copy.jpg.jpg' -> 's3://aoeuaoeuaoeu-backups/Sun/www/aoeuaoeuaoeu.com/public_html/files/dow-sisters-1870s-copy.jpg'
```

The original files:

```
$ ls /var/www/aoeuaoeuaoeu.com/public_html/files/*dow-sisters*
/var/www/aoeuaoeuaoeu.com/public_html/files/BIGdow-sisters-1870s-copy.jpg.jpg
/var/www/aoeuaoeuaoeu.com/public_html/files/dow-sisters-1870s-copy.jpg
```

Currently using:

```
$ s3cmd --version
s3cmd version 1.6.1
```

**Comment by mdomsch** [comment]
it believes the local files are identical, so it's attempting to save you
time and bandwidth by using remote copies instead of uploading the same
file a 2nd time.

**Comment by michaeltyson** [comment]
Okay, but it seems to consider it an error, though =)

**Comment by nawa** [comment]
I have the same problem. 
@mdomsch Can I turn off this optimization?

**Comment by nawa** [comment]
But it seems that both files are copied successfully. It can be that second file was copied from another source

**Comment by semente** [comment]
I got the same error... Perhaps it is because my access key has write access only so remote-to-remote copies won't work due lack of read/listing access.

**Comment by fviard** [comment]
Can both of you provide the exact command that you use?
And eventually the debug log. (generated by running with -d s3cmd).
Also, are you absolutely sure that the files are different?

**Comment by semente** [comment]
@fviard the files are the **same**... The s3cmd used was the "sync", I send you the debug log later. Thanks

**Comment by fviard** [comment]
I can't reproduce the issue so far, so it will help a lot the exact command and debug log :-)

**Comment by nawa** [comment]
@fviard Sorry, I have no time to try to reproduce it. But I have suggestion: could you try to sync 3 different files with different names and locations inside the synced folder?

**Comment by fviard** [comment]
I'm not really sure tu understand you suggestion? I did try big sync with lot of different files similar or not, with names similar or not also.
At least, would you still have the commandline that you have run?

**Comment by semente** [comment]
@fviard, this warning message appears for me when I'm trying to sync a folder with multiple identical files using a user/access key with write only access. Following is the policy I use for this user:

```
{
    "Statement": [
        {
            "Action": [
                "s3:ListAllMyBuckets"
            ],
            "Effect": "Allow",
            "Resource": "arn:aws:s3:::*"
        },
        {
            "Action": [
                "s3:ListBucket",
                "s3:PutObject"
            ],
            "Effect": "Allow",
            "Resource": [
                "arn:aws:s3:::BUCKET",
                "arn:aws:s3:::BUCKET/*"
            ]
        }
    ]
}
```

(attached a file with the debug output reproducing this)

[debug.txt](https://github.com/s3tools/s3cmd/files/563895/debug.txt)

**Comment by fviard** [comment]
@semente Ok, but in fact you don't have the same issue as the one reported initially in this issue.
That report was that, in the end, files that were remote copied were not supposed to be similar.

In your case, it is just a issue with your policy, s3cmd first try to do a remote copy of similar files, but as you don't have the "getobject" permission, s3cmd is not allowed by s3 to do the remote copy. And so is the origin of the warning. But, s3cmd will perform a full upload in the end for files that it is not able to remote copy. So the result for you should be good, just that the upload is slower.
So I would suggest you to fix your policy, here is the list of all the available s3 policies:
http://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html

**Comment by dxdc** [comment]
@fviard you are 100% correct. I found another report here, and also tested it.

http://stackoverflow.com/questions/26609528/correct-permissions-for-aws-remote-copy

Strangely, I have a version-enabled bucket, and this is not a sufficient amount of permissions for some reason (not sure which one is missing). When I tried:

```
            "Effect": "Allow",
            "Action": [
                "s3:*"
            ],
            "Resource": "arn:aws:s3:::mybucket/*",
```

this was successful, but if I specified several individual s3 permissions (GetObject, etc.) this failed. Any idea which permission is missing for the version enabled buckets?

**Comment by fviard** [comment]
It is just a guess but i think that you need:
Source:
- listobjects
- getobject
- getobjectacl

Destination
- list objects
- putobject
- putobject acl

**Comment by dxdc** [comment]
Thanks @fviard -- I don't think `listobjects` is an available option?

http://docs.aws.amazon.com/AmazonS3/latest/dev/using-with-s3-actions.html

This doesn't work for me, but if I use `"s3:*"` instead, it is no problem.

```
            "Effect": "Allow",
            "Action": [
                "s3:PutObject",
                "s3:PutObjectAcl",
                "s3:GetObject",
                "s3:GetObjectAcl",
                "s3:GetObjectVersion",
                "s3:DeleteObject",
                "s3:DeleteObjectVersion"
            ],
            "Resource": "arn:aws:s3:::mybucket/*",
```

**Comment by fviard** [comment]
@dxdc Sorry, the one you need is: "s3:ListBucket" that allows to list objects inside a bucket.

**Comment by dxdc** [comment]
@fviard had that one in there too, didn't list it. Was specified as:

```
            "Effect": "Allow",
            "Action": "s3:ListAllMyBuckets",
            "Resource": "arn:aws:s3:::*"
```

and

```
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket",
                "s3:GetBucketPolicy",
                "s3:GetBucketLocation"
            ],
            "Resource": "arn:aws:s3:::mybucket"
```
