### ISSUE TITLE
s3cmd 1.6.1 fails when using a proxy server

### ISSUE THREAD

**Issue by zstrzempa** [s3tools/s3cmd#770]
Hi 

I’m trying to configure s3cmd (1.6.1) to access an S3-like volume
hosted by our PaaS provider. Using V2 signature type I can access the service from an Ubuntu
server. Same release of Ubuntu but with internet access only over a proxy fails to access
the S3 service. The error shown is:

S3 error: 403 (SignatureDoesNotMatch): (please check the uploaded logfile for more details)

… and I do believe that it is the case, only it is not the problem of the key or secret strings as I use pretty much the same .s3cfg file (with the exception of the proxy config) and clearly the same key / secret on both servers. An attempt to access the S3 bucket with a "curl" from the
server connecting over the proxy works just fine.

Looking at the logs I have noticed, that “format_uri()” does look different for both calls but frankly I do not know if I can manipulate it in any way, nor if it would change anything.

I’ve attached a text file with both failing and working request logs, if you see any obvious error in
configuration that causes the trouble I would appreciate a hint very much. I’ve spent already
number of hours on the problem and I’m starring at the wall now ...

Cheers from Switzerland
Max

[s3cmd_logs.txt](https://github.com/s3tools/s3cmd/files/412663/s3cmd_logs.txt)

**Comment by fviard** [comment]
It is probably that the server that you are using is not compliant with the http specification.
But I have just merged a PR, that should take care of that:
https://github.com/s3tools/s3cmd/pull/779
That could be great if you can test this PR or the last master to see if that fixes your issue. Otherwise, don't hesitate to re-open the issue.
