### ISSUE TITLE
s3cmd 1.6.1 always resyncing everything

### ISSUE THREAD

**Issue by hymie0** [s3tools/s3cmd#771]
s3cmd version 1.6.1
Linux  2.6.33.4 (slackware)

I have a collection of music files that I backup to Amazon S3.  They change rarely if ever.  Some of them have timestamps dating 2007.

But every time I run this command

`s3cmd sync . s3://hymie.music/`

it tries to re-upload every single song.

I assume it's something I'm doing wrong, but I can't figure out what.  These files are emphatically not changing.

Here's something I noticed:  if I try to sync a specific directory

`s3cmd sync beatles s3://hymie.music/`

then I get the behavior I expect, where only new/changed songs get uploaded.  So perhaps the problem involves me using the `.` in my sync command?

**Comment by mdomsch** [comment]
Try sync ./ s3://...

**Comment by hymie0** [comment]
That indeed resolved the problem.  This still appears to be a change, because I know that just using `.` worked for me in the past.

Anyway, yes, that resolved my issue.  Thanks.

**Comment by mdomsch** [comment]
@fviard?

**Comment by fviard** [comment]
I will fix this issue soon
