### ISSUE TITLE
S3cmd sync exit when get bad file descriptor

### ISSUE THREAD

**Issue by xuanzhaopeng** [s3tools/s3cmd#773]
Could we add feature , just to ignore the error? cause if I sync a lot of things, just failed by one small file, I need to restart ....

**Comment by richardrasu** [comment]
I get this behaviour also, which is inconvenient when dealing with large amounts of data. I +1 this request.

**Comment by fviard** [comment]
Can you clarify exactly how/why you get bad file descriptors? maybe post a debug trace (-d option)
