### ISSUE TITLE
sync and cp ignore --add-headers when copying between buckets remote2remote

### ISSUE THREAD

**Issue by aubergene** [s3tools/s3cmd#78]
```
# Adds header correctly
s3cmd sync --add-header=Expires:60 local/ s3://bucket2  

# Doesn't add header
s3cmd sync --add-header=Expires:60 s3://bucket1 s3://bucket2  -
```

Seems this is the same problem

https://github.com/s3tools/s3cmd/issues/37#issuecomment-4409761

I'm not familiar with Python but it looks like perhaps the bug is here, that extra_headers needs to be merged with headers

https://github.com/s3tools/s3cmd/blob/master/S3/S3.py#L411

**Comment by fviard** [comment]
Hi,
I have pushed a few fixes in MASTER, and the issue should now be fixed I think.
(Will be in releases >= 2.2.0)
