### ISSUE TITLE
SignatureMismatchError with space in canonical uri

### ISSUE THREAD

**Issue by pritha-srivastava** [s3tools/s3cmd#780]
I am using s3cmd to upload objects in a bucket in a Ceph backend. The canonical uri contains a space, which results in a Signature Mismatch Error. Upon analysing this further, I see that the signature is computed with space converted to '%20', whereas when the canonical uri is sent to the server (ceph here), space is encoded as '+'. This is resulting in a SignatureMismatch, because on the server side (Ceph), the signature is computed based on the received canonical URI which contains space as '+'. 

Is this a bug - to compute signature with space encoded as '%20' and to send the request with space encoded as '+'?

More details:

The version of s3cmd is s3cmd version 1.6.1

A snippet of output with --debug enabled: s3cmd -c .s3cfg put sample-objects/@sample\ 16.txt s3://mybucket --debug

DEBUG: Canonical Request:
POST
/%40sample%2016.txt
uploadId=2~jyZszEoDF4u8dgSDef4oyftCyz-QpQa
content-length:223
host:mybucket.localhost
x-amz-content-sha256:5aca76b6b5bb22e8aa87d2868f3f0e83ab57f73db7a9a9dba378c8566d57b51a
x-amz-date:20160830T050105Z

content-length;host;x-amz-content-sha256;x-amz-date
## 5aca76b6b5bb22e8aa87d2868f3f0e83ab57f73db7a9a9dba378c8566d57b51a

DEBUG: signature-v4 headers: {'x-amz-content-sha256': '5aca76b6b5bb22e8aa87d2868f3f0e83ab57f73db7a9a9dba378c8566d57b51a', 'content-length': '223', 'Authorization': 'AWS4-HMAC-SHA256 Credential=xxx,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=24da43cd1b1779cda05f16e2406a1fe08e8be5b33ef1b279912ebba27afab6c7', 'x-amz-date': '20160830T050105Z'}
DEBUG: Processing request, please wait...
DEBUG: get_hostname(mybucket): mybucket.localhost
DEBUG: ConnMan.get(): re-using connection: http://mybucket.localhost#3
DEBUG: format_uri(): /%40sample+16.txt?uploadId=2~jyZszEoDF4u8dgSDef4oyftCyz-QpQa
DEBUG: Sending request method_string='POST', uri='/%40sample+16.txt?uploadId=2~jyZszEoDF4u8dgSDef4oyftCyz-QpQa', headers={'x-amz-content-sha256': '5aca76b6b5bb22e8aa87d2868f3f0e83ab57f73db7a9a9dba378c8566d57b51a', 'content-length': '223', 'Authorization': 'AWS4-HMAC-SHA256 ...

**Comment by fviard** [comment]
In amazon documentation, it is indicated that for the signature, the uri part should be encoded with %20 for spaces instead of "+" for the signature_v4 calculation.
Maybe it is "ceph" that is not compliant with this specification?

If you want to test this, you can try to remove the ".replace('+', '%20')", in S3/Crypto.py file, "quote_param" function and re-run your test.

**Comment by pritha-srivastava** [comment]
Yes I know that the amazon documentation says that the canonical uri should have space as %20.

As stated above, when I append --debug to s3cmd PUT operation, the signature is calculated correctly with space encoded as "%20" in s3cmd. But the canonical URI that is sent by s3cmd has space encoded as "+". Please look at the snippet of the console output below (with --debug enabled) (uri='/%40sample+16.txt)

DEBUG: format_uri(): /%40sample+16.txt?uploadId=2~jyZszEoDF4u8dgSDef4oyftCyz-QpQa
DEBUG: Sending request method_string='POST', uri='/%40sample+16.txt?uploadId=2~jyZszEoDF4u8dgSDef4oyftCyz-QpQa', headers={'x-amz-content-sha256': '5aca76b6b5bb22e8aa87d2868f3f0e83ab57f73db7a9a9dba378c8566d57b51a', 'content-length': '223', 'Authorization': 'AWS4-HMAC-SHA256 

Ceph at its end doesn't do anything special to the space characters. It just takes the canonical URI sent by the s3cmd, calculates signature based on that and matches the signature with the one sent by s3cmd. Since the uri sent by s3cmd has "+" whereas the signature that was sent was based off the uri having "%20", the signatures at our end do not match.

My question is: is there a reason why the signature that is getting calculated using space as "%20", whereas the canonical URI that is sent has "+", in s3cmd?

**Comment by fviard** [comment]
The + in the canonical url, is because before it looks like that it is the encoding that was to be used.
Maybe this can be changed. (#554)

**Comment by fviard** [comment]
Should already be fixed in 2.0.2.
