### ISSUE TITLE
s3cmd info fails with DreamObjects

### ISSUE THREAD

**Issue by gbenson** [s3tools/s3cmd#782]
I have a backup of my music collection on DreamObjects made with an older version of s3cmd. "s3cmd info" is failing with latest git s3cmd on files that exist in that bucket, and I'm struggling to debug it.  As background, the files used to be synced nightly with cron but it's been failing for a while--I've no idea how long, I only found out after a reinstall--so I can't say what version of s3cmd I was using or whether this issue would have occurred with the older s3cmd I was using.

Looking at the debug output it's failing on a HEAD request. It tries with signature v4, gets a 400, then retries with signature v2 and gets a 404 back.

Any help debugging this would be much appreciated!

**Comment by fviard** [comment]
Hi,
Try to run it with the "-d" debug option switch then we should have more details.

**Comment by gbenson** [comment]
[s3cmd info -d output](https://github.com/s3tools/s3cmd/files/446947/log.txt)

**Comment by mdomsch** [comment]
I've got a DO setup that also fails now, where at one point it worked (I
haven't tried in quite a while I admit).

I had success setting signature_v2 = True  in the config file, with no
other changes.  It seems to fail with v2 only after failing with a  v4
signature.

Thanks,
Matt

**Comment by fviard** [comment]
Shoud already be fixed I think.
