### ISSUE TITLE
S3cmd should not require $HOME/.s3cfg 

### ISSUE THREAD

**Issue by sario120** [s3tools/s3cmd#783]
Hi everyone,

I successfully synced data with s3cmd then I wanted to automate it with cron. When I did, error occurred. Like this;
ERROR: ~/.s3cfg: None
ERROR: Configuration file not available.
ERROR: Consider using --configure parameter to create one.  

I learnt from here that s3cmd doesn't requie this, so I removed this from home and again run cron. It didn't give any error and executed well. But now when I use s3cmd on command line, it gives same error.
ERROR: ~/.s3cfg: None
ERROR: Configuration file not available.
ERROR: Consider using --configure parameter to create one.  

Is there any way to use s3cmd both ways (through cron and CLI).

Thanks

**Comment by fviard** [comment]
you have "-c my_configuration" to set the configuration to a specific file.
Take care that when run with cron, you need to use absolute paths, you don't have an env, with a "/home" and so.
