### ISSUE TITLE
s3cmd sync doesn't work as expected with empty ETags

### ISSUE THREAD

**Issue by Abhishekvrshny** [s3tools/s3cmd#788]
`s3cmd sync` was found to be misbehaving with ceph v0.94.2. It was due to a bug in radosgw that returned empty ETags. http://tracker.ceph.com/issues/12955. Here is the fix to handle empty ETags : https://github.com/s3tools/s3cmd/pull/787

**Comment by fviard** [comment]
Proposed fix is merged, so i expect the issue to be resolved now.
