### ISSUE TITLE
How to invalidate a already uploaded file

### ISSUE THREAD

**Issue by saltarob** [s3tools/s3cmd#790]
Hi,

is there a way to invalidate files which are already uploaded to the s3 bucket?
`s3cmd modify --cf-invalidate s3://mybucket/myvideo.mp4` seems not to work.

Thank you.

**Comment by mdomsch** [comment]
Looks like the cfinval command was never implemented, though it's
referenced.

**Comment by AbdulHadiParsdorfer** [comment]
I was already wondering what and where this cfinval is. Are you still planing to implement it?
Thank you.

**Comment by fviard** [comment]
Closing as cfinval is now correctly implemented.
