### ISSUE TITLE
custom mime-types on upload?

### ISSUE THREAD

**Issue by stevenvachon** [s3tools/s3cmd#791]
I'm trying to upload *.woff2 files that require a `font/woff2` content-type header to work correctly. Unfortunately, I've been unable to find a way to have this action performed automatically on upload. Doing so manually per file post-upload is annoying.

The [Bucket Exporer](http://www.bucketexporer.com) app mentions this in its [FAQ](http://www.bucketexplorer.com/faq/how-to-manage-mime-types.html):
>### How to manage mime types?
>
Bucket Explorer provides facility to Add/Edit/Remove ‘Mime Type’ for files at Amazon S3. Similar to file extensions but more universally accepted, "MIME types" are used to identify the type of information that a file contains while uploading.

>### Follow these steps to Edit Mime type:
>
1. Run Bucket Explorer as usual.
2. At menu bar, go to Tools -> Advanced -> Edit Mime Types .
3. It will show a list of mime types where you can perform ADD, EDIT, and REMOVE operations on these mime types.
4. The list contains standard ‘Mime Types’

What would be the hooks they use to accomplish this?

This might be related to #376

**Comment by stevenvachon** [comment]
We ended up excluding the woff2 files and syncing them separately:
```shell
aws s3 sync $S3_DIRECTORY s3://$S3_BUCKET_NAME/ --acl=public-read --delete --exclude '.git/*' --exclude '*.woff2'
```
```shell
aws s3 sync $S3_DIRECTORY s3://$S3_BUCKET_NAME/ --acl=public-read --delete --content-type 'font/woff2' --exclude '*' --include '*.woff2'
```

**Comment by fviard** [comment]
It has been a long time, but, if you are still having the issue, I have created a wiki page related to this topic:
https://github.com/s3tools/s3cmd/wiki/Understand-Content-Type,-Mime-type-guessing-and-Magic

In short, s3cmd just use what is detected by other system components for file extension or magic.
One way to achieve your purpose without hacking is just to add the rules in the /etc/mime.types and /etc/magic files of your system.

**Comment by fviard** [comment]
btw, this project is the  "s3cmd" tool and not (Amazon) "aws s3" cli tool.
But the command is quite similar for simple things.
