### ISSUE TITLE
s3cmd put uploads before checking bucket permissions

### ISSUE THREAD

**Issue by stefanandres** [s3tools/s3cmd#792]
```
$ time s3cmd put zk.tar.gz  s3://sandres-test
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
upload: 'zk.tar.gz' -> 's3://sandres-test/zk.tar.gz'  [1 of 1]
 2481701 of 2481701   100% in    2s   848.45 kB/s  done
ERROR: S3 error: 403 (AccessDenied): Access Denied

real    0m3.026s
```

Comparison to aws s3 cp:

```
$ time aws s3 cp zk.tar.gz s3://sandres-test
upload failed: ./zk.tar.gz to s3://sandres-test/zk.tar.gz An error occurred (InvalidAccessKeyId) when calling the PutObject operation: The AWS Access Key Id you provided does not exist in our records.


real    0m0.936s
```

When using big files this will lead to massive delay of the error message and waste of bandwitdth.

**Comment by fviard** [comment]
True, I think that this is related to the following issue that we have to fix:
https://github.com/s3tools/s3cmd/issues/778

**Comment by fviard** [comment]
This issue should now be fixed in master.
Please give it a try.

If you don't want to send any data before ensuring that you are allowed to upload it.
You can use the "use_http_expect" option. (But this could result in more latency)
