### ISSUE TITLE
can not create an initial config file

### ISSUE THREAD

**Issue by androyamamoto** [s3tools/s3cmd#795]
After trying to run 's3cmd --configure -c s3test.cfg' and after entering 'Access Key', 'Secret Key' etc., to get a file named 's3test.cfg'. 
I this error:

Test access with supplied credentials? [Y/n] y
Please wait, attempting to list all buckets...
WARNING: Retrying failed request: /?delimiter=/ ([Errno -2] Name or service not known)
WARNING: Waiting 3 sec...
WARNING: Retrying failed request: /?delimiter=/ ([Errno -2] Name or service not known)
WARNING: Waiting 6 sec...
WARNING: Retrying failed request: /?delimiter=/ ([Errno -2] Name or service not known)
WARNING: Waiting 9 sec...

if i run:
bosh_e47ufbhe9@0c230caa-861d-45f3-b946-767a9304204b:~$ s3cmd
ERROR: /var/vcap/bosh_ssh/bosh_e47ufbhe9/.s3cfg: No such file or directory
ERROR: Configuration file not available.
ERROR: Consider using --configure parameter to create one.

whats wrong?

**Comment by fviard** [comment]
There is 2 issues in your case:
- If you use "-c" to set a custom configuration file name, you should also use "-c s3test.cfg" in all your s3cmd commands. ~USER/.s3cfg is the configuration file default location. 
- It looks like that your configuration settings were not good as you didn't pass the "configuration" test.
Please check what you have put as "host_base" and "host_bucket" settings, they are probably wrong and not targeting an existing server. Also, in your configuration file, check your use_https setting, as maybe your custom server doesn't support https or the opposite?
