### ISSUE TITLE
ERROR: Test failed: local variable 'conn' referenced before assignment

### ISSUE THREAD

**Issue by baumeist** [s3tools/s3cmd#796]
Hi There,

I had an auto-reply that stated to come here if my problem isn't resolved by installing the latest s3cmd version. I have installed s3cmd version 1.6.1 2016-01-20 and have been trying to connect to my aws s3 bucket but get this error. I have no reason to believe that my answers to the prompts asked for below is inaccurate. Can you please offer any suggestions?

Thank you,
Mark

  Access Key: 
  Secret Key: 
  Default Region: us-east-1
  Encryption password: 
  Path to GPG program: /usr/local/bin/gpg
  Use HTTPS protocol: True
  HTTP Proxy server name: 
  HTTP Proxy server port:

**Comment by fviard** [comment]
Do you have setup your config file with the correct access/secret keys?
Please run the s3cmd with the "-d" flag to output debug logs and paste them here so we can have an idea of the origin of your issue.

**Comment by colin-nolan** [comment]
I suggest this issue is closed in favour of https://github.com/s3tools/s3cmd/issues/826, which is a newer duplicate but with a bit more information.
