### ISSUE TITLE
Temporary redirect to new S3 bucket throws an exception

### ISSUE THREAD

**Issue by jamesremuscat** [s3tools/s3cmd#798]
When a fresh S3 bucket is created in a non-default region, requests to the bucket via the default URL (`https://bucketname.s3.amazonaws.com`) are given an HTTP 307 temporary redirect until the bucket is propagated. The `location` header of this response points to the regional bucket URL to use to repeat the current request.

When I try to use `s3cmd info` (current `master`) on paths within the new bucket, it results in a stack trace:

```
Invoked as: ./s3cmd info s3://bucket-name/key
Problem: ParseError: no element found: line 1, column 0
S3cmd:   1.6.1
python:   2.7.12 (default, Jul  1 2016, 15:12:24) 
[GCC 5.4.0 20160609]
environment LANG=en_GB.UTF-8

Traceback (most recent call last):
  File "./s3cmd", line 2954, in <module>
    rc = main()
  File "./s3cmd", line 2876, in main
    rc = cmd_func(args)
  File "./s3cmd", line 858, in cmd_info
    info = s3.object_info(uri)
  File "/home/james/workspace/s3cmd/S3/S3.py", line 871, in object_info
    response = self.send_request(request)
  File "/home/james/workspace/s3cmd/S3/S3.py", line 1179, in send_request
    redir_bucket = getTextFromXml(response['data'], ".//Bucket")
  File "/home/james/workspace/s3cmd/S3/Utils.py", line 133, in getTextFromXml
    tree = getTreeFromXml(xml)
  File "/home/james/workspace/s3cmd/S3/Utils.py", line 97, in getTreeFromXml
    tree = ET.fromstring(xml)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1312, in XML
    return parser.close()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1665, in close
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1517, in _raiseerror
    raise err
ParseError: no element found: line 1, column 0
```

(Steps to reproduce: create a new bucket in a non-default S3 region, add an object to it through the S3 web UI. Run command as shown.)

Interestingly, `s3cmd ls s3://bucket-name/key` does work as expected, as does `s3cmd info s3://bucket-name`.

**Comment by fviard** [comment]
@jamesremuscat Is it possible for you to give a new try with the last master? I think that it should be fixed now.

**Comment by jamesremuscat** [comment]
No change on current master (03970190cb5239d1333f3598a0d1b2069c01dc66).

Debug output gives details of the AWS 307 response:

```
DEBUG: Response:
{'data': '',
 'headers': {'content-type': 'application/xml',
             'date': 'Wed, 16 Nov 2016 12:55:28 GMT',
             'location': 'https://bucket-name.s3-ap-southeast-2.amazonaws.com/key',
             'server': 'AmazonS3',
             'transfer-encoding': 'chunked',
             'x-amz-id-2': 'ye8Lf1qTxopxh1EecGZvBDlcm0o2aXo21HKNV7cl1cUV38t/4yYOg00WJN6ZXBxpi2ddcVNjk0Q=',
             'x-amz-request-id': '0D2E47BE3678A735'},
 'reason': 'Temporary Redirect',
 'status': 307}
ERROR: Error parsing xml: no element found: line 1, column 0
```

**Comment by fviard** [comment]
Thank you for your tests.
In understand better now. (And some other "error parsing xml" reports that we could have received).

Contrary to the ls command, the info use a "HEAD" HTTP method. In that case, we get a reply with the headers but no body. That's the concept of the HEAD method.
But currently, we are looking at the xml in the body to determine where to redirect requests.
That's why it is failing in your case because no body, no xml.
I will add a fix to try to extract this information from the "location" header when there is no body.

**Comment by fviard** [comment]
@jamesremuscat I just pushed a fix that should solve your issue.
That would be great if you were able to give it a try.
