### ISSUE TITLE
feature request: delete multiple files on a single command line

### ISSUE THREAD

**Issue by c0b** [s3tools/s3cmd#800]
I found this tool is so weak (or primitive) that for many tasks I have to write shell to wrap or would rather to write python programs on top of boto library,

can I request a simple feature: delete multiple-files on a single command line?

`s3cmd rm s3://bucket1/file1 s3://bucket1/file2 s3://bucket2/file3`

like the shell `rm file1 file2 file3 ...` to delete multiple files

the current behavior of s3cmd is to delete the first file only, other files got ignored, that I have to wrap it around a line of shell,

```bash
$ generate-the-filelist | while read file; do s3cmd rm $file; done
```

expected behavior s3cmd should support to delete multiple files; that's the basics of shell utilities, like ls, rm, cp, mv, ...

```bash
$ generate-the-filelist | xargs s3cmd rm
```

```console
$ s3cmd --version
s3cmd version 1.6.1
```

**Comment by c0b** [comment]
the full pipeline of this shell is like this:

`$ s3cmd ls -r s3://bucket/prefix | grep 'some-pattern' | while read file; do s3cmd rm $file; done`

I want to find out those files according a regular expression and delete, kind of disappointed either s3cmd ls or rm doesn't have regular expression matching, neither the `--include` or `--rinclude` works

I just suspect is this project out of maintenance ? I checked some other open issues **neither had updates in months**

**Comment by fviard** [comment]
Hi, first, the project is maintained. Open issues give you a limited view, most are long standing issues.
But the man power is very limited, so sometimes some changes or fixes can take a little time.
We are very open to pull requests and contributions.

Both the ideas that you propose are good. Just need to have someone implement them.
The rm for multiple files should be easily doable.
I guess that the "include" will be harder and has to be scalable enough for the big dataset that can be encountered. (Most of the time it is "exclude" that is used).

**Comment by fviard** [comment]
For your first point, "multiple delete", this should already be working in master, I don't remember if we have changed something since 1.6.1, but this is already implemented and working.

For your second point, the "include", it was in fact a regression that it was not working anymore, I just fixed it and it should be working again now. (Not that when you use Include/exclude list, it is not possible to use internally the more memory efficient method of delete)

**Comment by c0b** [comment]
I did a `pip install git+git://github.com/s3tools/s3cmd@master` today and can confirm rm can do multiple delete; however I found `ls` doesn't have support to list multiple files; I hope many other commands support multiple arguments as well, like `s3cmd get s3://bkt1/obj1 s3://bkt2/obj2 ./` to download both obj1 and obj2 to current directory, in the case of no naming conflicts; if with conflict, should do warning, or prompt, or overwrite only when called with `--force`
would you like me to file multiple issues for each of them? @fviard 

```console
  Make bucket
      s3cmd mb s3://BUCKET
  Remove bucket
      s3cmd rb s3://BUCKET
  List objects or buckets
      s3cmd ls [s3://BUCKET[/PREFIX]]
  List all object in all buckets
      s3cmd la 
  Put file into bucket
      s3cmd put FILE [FILE...] s3://BUCKET[/PREFIX]
  Get file from bucket
      s3cmd get s3://BUCKET/OBJECT LOCAL_FILE
  Delete file from bucket
      s3cmd del s3://BUCKET/OBJECT
  Delete file from bucket (alias for del)
      s3cmd rm s3://BUCKET/OBJECT
```

**Comment by es-on-github** [comment]
@c0b, just add an extra layer to your command, so you'll pipe the object name to the "rm" command:

`$ s3cmd ls -r s3://bucket/prefix | grep 'some-pattern' | awk '{print $4}' | while read file; do s3cmd rm $file; done`

Thanks for taking me to the right direction!
