### ISSUE TITLE
s3cmd can not work with http 307 redirection

### ISSUE THREAD

**Issue by vesafb** [s3tools/s3cmd#810]
When a redirection response is received, s3cmd can not get the hostname in the conneciton map correctly if bucket name dns support is not configured.

def get_hostname(self, bucket):
    if bucket and check_bucket_name_dns_support(self.config.host_bucket, bucket):
        if self.redir_map.has_key(bucket):
            host = self.redir_map[bucket]
        else:
            host = getHostnameFromBucket(bucket)
    else:
        host = self.config.host_base

The bucket name dns support is not configured because we use path style access instead of virtual host style.

For example,

curl http://10.32.172.184:9020/bucket1/key

<?xml version="1.0" encoding="UTF-8"?>
 <Error>
 <Code>TemporaryRedirect</Code>
 <Message>Temporary Redirect</Message>
 <Bucket>bucket1</Bucket>
 <Endpoint>10.32.169.214:9020</Endpoint>
 </Error>

s3cmd -d -v ls s3://bucket1/

INFO: bucket bucket1 Redirected to: 10.32.169.213:9020
 INFO: bucket bucket1 Redirected to: 10.32.172.184:9020
 INFO: bucket bucket1 Redirected to: 10.32.169.213:9020
 INFO: bucket bucket1 Redirected to: 10.32.172.184:9020
 INFO: bucket bucket1 Redirected to: 10.32.169.213:9020

**Comment by fviard** [comment]
Thank you very much for reporting this important bug!
To reproduce the issue with amazon:
- Create a bucket with a file in a region.
- Try to access a file in this bucket from a different region with "path style syntax" with a bucket_host like:
host_bucket = s3.eu-central-1.amazonaws.com
(no %{bucket}).

Amazon issue a redirect in such a case as indicated here: http://docs.aws.amazon.com/AmazonS3/latest/dev/VirtualHosting.html
