### ISSUE TITLE
Remote copy problem on file size above almost 5GB (s3cmd cp)

### ISSUE THREAD

**Issue by canerkoroglu** [s3tools/s3cmd#818]
Hello, 
I'm trying to change storage_class of files than backed up with WHM to S3 as Standard_IS with s3cmd.
It is working fine which file size under 5gb but i have 2 tar.gz file abouve 5gb (one of them 7.5GB one of them 17.5GB) s3cmd is ignoring these 2 files.

I'm using this command line 

s3cmd cp --storage-class=STANDARD_IA --recursive s3://mybucketname/ s3://mybucketname/

so s3cmd continue progress but skip automatically this two files, didn't change anything above these 2 files.

i'm using s3cmd v 1.6.1

multipart_chunk_size_mb = 15
multipart_max_chunks = 10000
socket_timeout = 1800
recursive = False
recv_chunk = 65536
send_chunk = 65536

thanks.

**Comment by fviard** [comment]
Should now be fixed in MASTER and next releases (>=2.2.0)
See: https://github.com/s3tools/s3cmd/issues/830#issuecomment-613207225
