### ISSUE TITLE
does s3cmd support hosted–style request?

### ISSUE THREAD

**Issue by tracymacding** [s3tools/s3cmd#824]
if so, how to use?

**Comment by fviard** [comment]
In the config of s3cmd, if you don't use the "%(bucket)s" parameter inside the "host_bucket" configuration, then the "bucket" will be set inside the path of the object, and so you will have "hosted-style" requests.

For example, you will have dns-style requests with the following configuration: 
"host_bucket = %(bucket)s.s3.amazonaws.com"
and hosted-style requests when using that instead:
"host_bucket = s3.amazonaws.com"
