### ISSUE TITLE
Problem: UnboundLocalError: local variable 'conn' referenced before assignment

### ISSUE THREAD

**Issue by VAdamec** [s3tools/s3cmd#826]
Getting this error again with version 1.6.1, Python 2.7.5-48.el7, CentOS Linux release 7.2.1511. Downgrade to 1.5.0 helps. Tested against RiakCS in Docker (https://github.com/ianbytchek/docker-riak-cs)

```
Invoked as: /bin/s3cmd ls
Problem: UnboundLocalError: local variable 'conn' referenced before assignment
S3cmd:   1.6.1
python:   2.7.5 (default, Nov  6 2016, 00:28:07)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/bin/s3cmd", line 124, in cmd_ls
    subcmd_all_buckets_list(s3)
  File "/bin/s3cmd", line 129, in subcmd_all_buckets_list
    response = s3.list_all_buckets()
  File "/usr/lib/python2.7/site-packages/S3/S3.py", line 290, in list_all_buckets
    response = self.send_request(request)
  File "/usr/lib/python2.7/site-packages/S3/S3.py", line 1106, in send_request
    conn.counter = ConnMan.conn_max_counter
UnboundLocalError: local variable 'conn' referenced before assignment
...
```

```
pip install -U s3cmd==1.5.0
Collecting s3cmd==1.5.0
  Using cached s3cmd-1.5.0.tar.gz
Installing collected packages: s3cmd
  Found existing installation: s3cmd 1.6.1
    Uninstalling s3cmd-1.6.1:
      Successfully uninstalled s3cmd-1.6.1
  Running setup.py install for s3cmd ... done
Successfully installed s3cmd-1.5.0
```

```
s3cmd ls
2017-01-18 09:10  s3://s3backup
```

**Comment by danielmotaleite** [comment]
for riak and 1.6.1, i had to set ```use_https = False``` and ``` signature_v2 = true```, but after that it works fine

**Comment by thawkins** [comment]
I have the same problem on Amazon Linux, installed with 

pip install s3cmd 

[ec2-user@ip-172-30-0-227 ~]$ s3cmd ls

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net


!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd ls
Problem: UnboundLocalError: local variable 'conn' referenced before assignment
S3cmd:   1.6.1
python:   2.7.12 (default, Sep  1 2016, 22:14:00) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/bin/s3cmd", line 2919, in <module>
    rc = main()
  File "/usr/local/bin/s3cmd", line 2841, in main
    rc = cmd_func(args)
  File "/usr/local/bin/s3cmd", line 124, in cmd_ls
    subcmd_all_buckets_list(s3)
  File "/usr/local/bin/s3cmd", line 129, in subcmd_all_buckets_list
    response = s3.list_all_buckets()
  File "/usr/local/lib/python2.7/site-packages/S3/S3.py", line 290, in list_all_buckets
    response = self.send_request(request)
  File "/usr/local/lib/python2.7/site-packages/S3/S3.py", line 1106, in send_request
    conn.counter = ConnMan.conn_max_counter
UnboundLocalError: local variable 'conn' referenced before assignment

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by colin-nolan** [comment]
This issue has been fixed in:
https://github.com/s3tools/s3cmd/commit/514c5ed0e2b2413862f1136943f9d19f7b33cd6d

**Comment by fviard** [comment]
Thanks for the reference, yes should be fixed now in master.
