### ISSUE TITLE
s3cmd --configure screws up the s3cfg file

### ISSUE THREAD

**Issue by ptrace** [s3tools/s3cmd#827]
Hey,
After running --configure and giving the access key and secret key (and everything else), the cfg file still has an 'access_token = ...' field, which makes future requests use the access token (which doesn't have enough permissions), so future calls fail.

I have to manually delete this line to make it work. Is this expected behavior?

**Comment by fviard** [comment]
I think that this issue should now be solved as the iam and --configure were reworked.
Please re-open if you can still reproduce this.
