### ISSUE TITLE
S3cmd does not support China s3

### ISSUE THREAD

**Issue by ti-yoyo** [s3tools/s3cmd#833]
Test access with supplied credentials? [Y/n] 
Please wait...
ERROR: Test failed: 403 (InvalidAccessKeyId): The AWS Access Key Id you provided does not exist in our records.

Retry configuration? [Y/n] 

Access Key: 
Secret Key:
The above two parameter values are correct

**Comment by mdomsch** [comment]
See item 7 here:
https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
