### ISSUE TITLE
Convert from AWS Signature Version 2 to Version 4

### ISSUE THREAD

**Issue by dsbcpas** [s3tools/s3cmd#846]
Sorry to trouble you; After upgrading to master s3cmd version 1.6.1, I ran into a ton of "SignatureDoesNotMatch" log errors this morning indicating that my bucket locations, us-east-1, now requires AWS Signature V4. Adding "signature_v2 = True" to configuration file solved the problem, but may be I should migrate to V4?

How do I do that? Tips and links would be welcome!

PS Where might I locate a help/content page on s3cmd's configuration file? It took some scouring to find "signature_v2 = True/False" setting.

Thank you,
Average dumb sys admin.

**Comment by dsbcpas** [comment]
Footnote - "signature_v2 = True" seems to only avoid the error on smaller files, large files are bombing with signature error.
Here is what my configuration file looks like: s3cmd --dump-config
[default]
access_key = [deleted]
access_token =
acl_public = False
add_encoding_exts =
add_headers =
bucket_location = us-east-1
ca_certs_file =
cache_file =
check_ssl_certificate = True
check_ssl_hostname = True
cloudfront_host = cloudfront.amazonaws.com
default_mime_type = binary/octet-stream
delay_updates = False
delete_after = False
delete_after_fetch = False
delete_removed = True
dry_run = False
enable_multipart = True
encoding = UTF-8
encrypt = False
expiry_date =
expiry_days =
expiry_prefix =
follow_symlinks = False
force = False
get_continue = False
gpg_command = /usr/bin/gpg
gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_passphrase = letmein
guess_mime_type = True
host_base = s3.amazonaws.com
host_bucket = %(bucket)s.s3.amazonaws.com
human_readable_sizes = False
invalidate_default_index_on_cf = False
invalidate_default_index_root_on_cf = True
invalidate_on_cf = False
kms_key =
limit = -1
limitrate = 0
list_md5 = False
log_target_prefix =
long_listing = False
max_delete = -1
mime_type =
multipart_chunk_size_mb = 15
multipart_max_chunks = 10000
preserve_attrs = True
progress_meter = True
proxy_host =
proxy_port = 0
put_continue = False
recursive = False
recv_chunk = 4096
reduced_redundancy = True
requester_pays = False
restore_days = 1
restore_priority = Standard
secret_key = [deleted]
send_chunk = 4096
server_side_encryption = True
signature_v2 = True
simpledb_host = sdb.amazonaws.com
skip_existing = False
socket_timeout = 300
stats = False
stop_on_error = False
storage_class =
urlencoding_mode = normal
use_http_expect = False
use_https = True
use_mime_magic = True
verbosity = WARNING
website_endpoint = http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
website_error =
website_index = index.html

**Comment by fviard** [comment]
Hi,
can you run your command with the "-d" flag, that should give a more verbose output that could help you figure out what is going on.

 Regarding the signature: 
- To sign requests, aws used to use a specific format (v2).
- Some years ago, they decided to switch to a more complex signature algorithm (but more secure) that use more parameters. (They said that it was version 4 ie "v4" of the sign algo).

- When they rolled out the v4, they preserved support for v2 signed requests for old endpoints and set the v4 as mandatory for the new ones like frankfurt.

- In theory, if you are sure that your bucket is in us-east-1, v2 and v4 should be supported.
- The "signature_v2=True" is more for non aws s3 compatible servers that could only support the v2 and not v4. But that should not be the case.

Could you run the command one time with v4 and the "-d" flag and post the log here so we can look at what's going on with your setup?

**Comment by dsbcpas** [comment]
-d caused me to update bucket policies, but still have some files with the error below while others others do not. Thank you for looking at this.

HERE IS AN EXCERPT OF output from COMMAND:
/usr/bin/s3cmd -f -v -d --config=/root/.s3cfg sync /home/shared/USR/cli/persA_L/speter/ s3://domain.name-epochbackup/syncclipersA_L:speter/
....................
DEBUG: DeUnicodising u'/home/shared/USR/cli/persA_L/speter/ye2016/strentalprelim.xls' using UTF-8
INFO: Retrieving list of remote files for s3://domain.name-epochbackup/syncclipersA_L:speter/ ...
DEBUG: String 'syncclipersA_L:speter/' encoded to 'syncclipersA_L%3Aspeter/'
DEBUG: CreateRequest: resource[uri]=/
DEBUG: Using signature v4
DEBUG: get_hostname(domain.name-epochbackup): domain.name-epochbackup.s3.amazonaws.com
DEBUG: canonical_headers = host:domain.name-epochbackup.s3.amazonaws.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20170320T223230Z

DEBUG: Canonical Request:
GET
/
prefix=syncclipersA_L%253Aspeter%2F
host:domain.name-epochbackup.s3.amazonaws.com
x-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
x-amz-date:20170320T223230Z

host;x-amz-content-sha256;x-amz-date
e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
----------------------
DEBUG: signature-v4 headers: {'x-amz-content-sha256': u'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': u'AWS4-HMAC-SHA256 Credential=HIDDEN/20170320/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=bd522854beb05a65b5d68c15d399bf22efa5cd190b6e991a10adde4777d28d2c', 'x-amz-date': '20170320T223230Z'}
DEBUG: Processing request, please wait...
DEBUG: get_hostname(domain.name-epochbackup): domain.name-epochbackup.s3.amazonaws.com
DEBUG: ConnMan.get(): creating new connection: https://domain.name-epochbackup.s3.amazonaws.com
DEBUG: Using ca_certs_file None
DEBUG: Bucket name contains "." character, disabling initial SSL hostname check
DEBUG: httplib.HTTPSConnection() has only context
DEBUG: non-proxied HTTPSConnection(domain.name-epochbackup.s3.amazonaws.com, None)
DEBUG: checking SSL subjectAltName as forgiving wildcard cert
DEBUG: format_uri(): /?prefix=syncclipersA_L%3Aspeter/
DEBUG: Sending request method_string='GET', uri=u'/?prefix=syncclipersA_L%3Aspeter/', headers={'x-amz-content-sha256': u'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', 'Authorization': u'AWS4-HMAC-SHA256 Credential=HIDDEN/20170320/us-east-1/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=bd522854beb05a65b5d68c15d399bf22efa5cd190b6e991a10adde4777d28d2c', 'x-amz-date': '20170320T223230Z'}, body=(0 bytes)
DEBUG: ConnMan.put(): connection put back to pool (https://domain.name-epochbackup.s3.amazonaws.com#1)
DEBUG: Response:
{'data': '<?xml version="1.0" encoding="UTF-8"?>\n<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>HIDDEN</AWSAccessKeyId><StringToSign>AWS4-HMAC-SHA256\n20170320T223230Z\n20170320/us-east-1/s3/aws4_request\nd77ceba75cb75ac2e14ff169befdd37d7bcd1300e9f1c8a0c0cef1a31524f899</StringToSign><SignatureProvided>bd522854beb05a65b5d68c15d399bf22efa5cd190b6e991a10adde4777d28d2c</SignatureProvided><StringToSignBytes>41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 0a 32 30 31 37 30 33 32 30 54 32 32 33 32 33 30 5a 0a 32 30 31 37 30 33 32 30 2f 75 73 2d 65 61 73 74 2d 31 2f 73 33 2f 61 77 73 34 5f 72 65 71 75 65 73 74 0a 64 37 37 63 65 62 61 37 35 63 62 37 35 61 63 32 65 31 34 66 66 31 36 39 62 65 66 64 64 33 37 64 37 62 63 64 31 33 30 30 65 39 66 31 63 38 61 30 63 30 63 65 66 31 61 33 31 35 32 34 66 38 39 39</StringToSignBytes><CanonicalRequest>GET\n/\nprefix=syncclipersA_L%3Aspeter%2F\nhost:domain.name-epochbackup.s3.amazonaws.com\nx-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date:20170320T223230Z\n\nhost;x-amz-content-sha256;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855</CanonicalRequest><CanonicalRequestBytes>47 45 54 0a 2f 0a 70 72 65 66 69 78 3d 73 79 6e 63 63 6c 69 70 65 72 73 41 5f 4c 25 33 41 6b 61 72 61 67 69 61 6e 69 73 70 65 74 65 72 31 31 30 31 25 32 46 0a 68 6f 73 74 3a 64 73 62 63 70 61 73 2e 63 6f 6d 2d 65 70 6f 63 68 62 61 63 6b 75 70 2e 73 33 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 0a 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3a 65 33 62 30 63 34 34 32 39 38 66 63 31 63 31 34 39 61 66 62 66 34 63 38 39 39 36 66 62 39 32 34 32 37 61 65 34 31 65 34 36 34 39 62 39 33 34 63 61 34 39 35 39 39 31 62 37 38 35 32 62 38 35 35 0a 78 2d 61 6d 7a 2d 64 61 74 65 3a 32 30 31 37 30 33 32 30 54 32 32 33 32 33 30 5a 0a 0a 68 6f 73 74 3b 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3b 78 2d 61 6d 7a 2d 64 61 74 65 0a 65 33 62 30 63 34 34 32 39 38 66 63 31 63 31 34 39 61 66 62 66 34 63 38 39 39 36 66 62 39 32 34 32 37 61 65 34 31 65 34 36 34 39 62 39 33 34 63 61 34 39 35 39 39 31 62 37 38 35 32 62 38 35 35</CanonicalRequestBytes><RequestId>C8C67B9A8AF44B3B</RequestId><HostId>+TPgeALEcEC91FUVhjXLHgWEzOSxDmFUbCTIlkSMtveyIrjHzatf288fkCIf5L0jSTUhMRM1hU8=</HostId></Error>',
 'headers': {'content-type': 'application/xml',
             'date': 'Mon, 20 Mar 2017 22:33:08 GMT',
             'server': 'AmazonS3',
             'transfer-encoding': 'chunked',
             'x-amz-bucket-region': 'us-east-1',
             'x-amz-id-2': '+TPgeALEcEC91FUVhjXLHgWEzOSxDmFUbCTIlkSMtveyIrjHzatf288fkCIf5L0jSTUhMRM1hU8=',
             'x-amz-request-id': 'C8C67B9A8AF44B3B'},
 'reason': 'Forbidden',
 'status': 403}
DEBUG: S3Error: 403 (Forbidden)
DEBUG: HttpHeader: x-amz-bucket-region: us-east-1
DEBUG: HttpHeader: x-amz-id-2: +TPgeALEcEC91FUVhjXLHgWEzOSxDmFUbCTIlkSMtveyIrjHzatf288fkCIf5L0jSTUhMRM1hU8=
DEBUG: HttpHeader: server: AmazonS3
DEBUG: HttpHeader: transfer-encoding: chunked
DEBUG: HttpHeader: x-amz-request-id: C8C67B9A8AF44B3B
DEBUG: HttpHeader: date: Mon, 20 Mar 2017 22:33:08 GMT
DEBUG: HttpHeader: content-type: application/xml
DEBUG: ErrorXML: Code: 'SignatureDoesNotMatch'
DEBUG: ErrorXML: Message: 'The request signature we calculated does not match the signature you provided. Check your key and signing method.'
DEBUG: ErrorXML: AWSAccessKeyId: 'HIDDEN'
DEBUG: ErrorXML: StringToSign: 'AWS4-HMAC-SHA256\n20170320T223230Z\n20170320/us-east-1/s3/aws4_request\nd77ceba75cb75ac2e14ff169befdd37d7bcd1300e9f1c8a0c0cef1a31524f899'
DEBUG: ErrorXML: SignatureProvided: 'bd522854beb05a65b5d68c15d399bf22efa5cd190b6e991a10adde4777d28d2c'
DEBUG: ErrorXML: StringToSignBytes: '41 57 53 34 2d 48 4d 41 43 2d 53 48 41 32 35 36 0a 32 30 31 37 30 33 32 30 54 32 32 33 32 33 30 5a 0a 32 30 31 37 30 33 32 30 2f 75 73 2d 65 61 73 74 2d 31 2f 73 33 2f 61 77 73 34 5f 72 65 71 75 65 73 74 0a 64 37 37 63 65 62 61 37 35 63 62 37 35 61 63 32 65 31 34 66 66 31 36 39 62 65 66 64 64 33 37 64 37 62 63 64 31 33 30 30 65 39 66 31 63 38 61 30 63 30 63 65 66 31 61 33 31 35 32 34 66 38 39 39'
DEBUG: ErrorXML: CanonicalRequest: 'GET\n/\nprefix=syncclipersA_L%3Aspeter%2F\nhost:domain.name-epochbackup.s3.amazonaws.com\nx-amz-content-sha256:e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855\nx-amz-date:20170320T223230Z\n\nhost;x-amz-content-sha256;x-amz-date\ne3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
DEBUG: ErrorXML: CanonicalRequestBytes: '47 45 54 0a 2f 0a 70 72 65 66 69 78 3d 73 79 6e 63 63 6c 69 70 65 72 73 41 5f 4c 25 33 41 6b 61 72 61 67 69 61 6e 69 73 70 65 74 65 72 31 31 30 31 25 32 46 0a 68 6f 73 74 3a 64 73 62 63 70 61 73 2e 63 6f 6d 2d 65 70 6f 63 68 62 61 63 6b 75 70 2e 73 33 2e 61 6d 61 7a 6f 6e 61 77 73 2e 63 6f 6d 0a 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3a 65 33 62 30 63 34 34 32 39 38 66 63 31 63 31 34 39 61 66 62 66 34 63 38 39 39 36 66 62 39 32 34 32 37 61 65 34 31 65 34 36 34 39 62 39 33 34 63 61 34 39 35 39 39 31 62 37 38 35 32 62 38 35 35 0a 78 2d 61 6d 7a 2d 64 61 74 65 3a 32 30 31 37 30 33 32 30 54 32 32 33 32 33 30 5a 0a 0a 68 6f 73 74 3b 78 2d 61 6d 7a 2d 63 6f 6e 74 65 6e 74 2d 73 68 61 32 35 36 3b 78 2d 61 6d 7a 2d 64 61 74 65 0a 65 33 62 30 63 34 34 32 39 38 66 63 31 63 31 34 39 61 66 62 66 34 63 38 39 39 36 66 62 39 32 34 32 37 61 65 34 31 65 34 36 34 39 62 39 33 34 63 61 34 39 35 39 39 31 62 37 38 35 32 62 38 35 35'
DEBUG: ErrorXML: RequestId: 'C8C67B9A8AF44B3B'
DEBUG: ErrorXML: HostId: '+TPgeALEcEC91FUVhjXLHgWEzOSxDmFUbCTIlkSMtveyIrjHzatf288fkCIf5L0jSTUhMRM1hU8='
ERROR: S3 error: 403 (SignatureDoesNotMatch): The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Comment by dsbcpas** [comment]
Appears the credentials are not matching: root versus IAM user specified in bucket policy statement. How do I specify an AWS IAM user credential with s3cmd?

**Comment by dsbcpas** [comment]
Can s3cmd handle a bucket policy with "Principal" ?
AWS appears to have 3 "Principal" syntax types:
1.  "Principal": { "AWS": "arn:aws:iam::AWS-account-ID:root" } OR
2.  "Principal": { "AWS": "AWS-account-ID" }
3.  "Principal": { "AWS": "arn:aws:iam::AWS-account-ID:user/user-name" }

None appear to be working for me.

**Comment by fviard** [comment]
@dsbcpas It is hard to reply to you because I'm not an IAM or policy expert, and that is not related to the client, but maybe you can find ideas by reading the following page:
https://aws.amazon.com/blogs/security/how-to-restrict-amazon-s3-bucket-access-to-a-specific-iam-role/

Things to check in my opinion:
- "account-id" is specified without HYPHENS as stated in the doc.
- You have granted "s3:*" action to your IAM account.

**Comment by dsbcpas** [comment]
Isolated problem to sync -  "ERROR: S3 error: 403 (SignatureDoesNotMatch)" only occurs when using the sync command.

Commands tested: put, get and del all work fine.

NotPrincipal policy problems resolved and work just fine.

**Comment by dsbcpas** [comment]
Resolved through patch to issue #829
Notation: When securing s3 amazon buckets, after setting up iam user(s) the following NotPrincipal policy example is recommended:
 {
            "Sid": "RestrictAccess",
            "Effect": "Deny",
            "NotPrincipal": {
                "AWS": "arn:aws:iam::############:user/xxxxxxxxxxxxx"
            },
            "Action": "s3:*",
            "Resource": "arn:aws:s3:::nameofbucket/*"
        }
