### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by baiyanchun** [s3tools/s3cmd#847]
I used s3cmd command (the latest s3cmd code I use) to put a file named in Chinese, when I use s3cmd info bucket, An unexpected error has occurred. The following is my operation process and result.

1 Create a bucket
s3cmd mb s3://bucket
Bucket 's3://bucket/' created

2 Create a file named in Chinese
touch 中文.txt

3 Put file to s3://bucket
s3cmd put 中文.txt s3://bucket
upload: '中文.txt' -> 's3://bucket/中文.txt'  [1 of 1]
0 of 0     0% in    0s     0.00 B/s  done

4 Ls this file
s3cmd ls s3://bucket
2017-03-21 02:55         0   s3://bucket/中文.txt

5 Get bucket info
s3cmd info s3://bucket

The error message:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Invoked as: /usr/local/bin/s3cmd info s3://bucket
Problem: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 496: ordinal not in range(128)
S3cmd:   1.6.1
python:   2.7.6 (default, Oct 26 2016, 20:30:19) 
[GCC 4.8.4]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2996, in <module>
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2915, in main
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-1.6.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 918, in cmd_info
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 496: ordinal not in range(128)

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by baiyanchun** [comment]
the detail error log.
[s3cmd.txt](https://github.com/s3tools/s3cmd/files/860924/s3cmd.txt)

**Comment by mdomsch** [comment]
The next output line should be a policy.  By chance does your policy have
unicode characters in it?  That's where it's failing.

**Comment by fviard** [comment]
@baiyanchun Any feedback regarding the idea of mdomsch?

**Comment by fviard** [comment]
@baiyanchun Is it possible for your to confirm that the issue come from having chinese characters somewhere in your policy? and if you paste us an extract here? so I can reproduce and fix?
Thank you

**Comment by jdurand** [comment]
I get this issue when trying to transfer file with accents in the filename (i.e. Capture_d’écran_2015-10-23_à_09.20.45.png)

**Comment by jdurand** [comment]
Commenting out the console output fixes the issue:
https://github.com/s3tools/s3cmd/blob/65b34b73bf17eb3ec7cf96093a53fddbc8b0f898/s3cmd#L1103
Looks like an issue with python incorrectly detecting the filename encoding or something.

**Comment by jdurand** [comment]
Python 2.7.15
s3cmd 2.0.1

I'm not familiar with Python, what command should I run or which config file should I check?
I'm running a Homebrew Python on macOS.

**Comment by fviard** [comment]
What is the "s3cmd" command line with arguments that you run for your transfer that is failing?
you just have to had " -d" at the end of the command line that you run to display the full debug log.

**Comment by jdurand** [comment]
I was running `s3cmd sync s3://SRC s3://DEST` but got into some other issues... I large number of files were missing so I ended up syncing my buckets with [aws-cli](https://aws.amazon.com/cli/).

**Comment by fviard** [comment]
Would it still be possible for you to run that command with the -d and look what is the root cause of the failure?
There could be interesting issues coming from the fact that you are using s3cmd on macOS.
As I'm don't have a macOS device to test.

**Comment by offshore** [comment]
I've submitted a patch which should fix this.

**Comment by vlada-dudr** [comment]
The issue is somehow still around...
```
Invoked as: s3cmd-master/s3cmd sync -P s3://bucket1/ s3://bucket2/somedir/                                                                                                                                               [9/1981]
Problem: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 72: ordinal not in range(128)
S3cmd:   2.0.2                                          
python:   2.7.13 (default, Sep 26 2018, 18:42:22)                                
[GCC 6.3.0 20170516]                      
environment LANG=en_US.UTF-8       
                        
Traceback (most recent call last):   
  File "s3cmd-master/s3cmd", line 3104, in <module>                   
    rc = main()                                                                            
  File "s3cmd-master/s3cmd", line 3013, in main                       
    rc = cmd_func(args)
  File "s3cmd-master/s3cmd", line 1901, in cmd_sync
    return cmd_sync_remote2remote(args)
  File "s3cmd-master/s3cmd", line 1128, in cmd_sync_remote2remote
    ret, seq, nb_files, size = _upload(src_list, seq, src_count + update_count)
  File "s3cmd-master/s3cmd", line 1115, in _upload
    output("remote copy: '%(src)s' -> '%(dst)s'" % { "src" : src_uri, "dst" : dst_uri })
  File "s3cmd-master/s3cmd", line 71, in output
    sys.stdout.write(message + "\n")
  File "/usr/lib/python2.7/codecs.py", line 369, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 72: ordinal not in range(128)
`
```

**Comment by fviard** [comment]
I think that @offshore fixed the original poster error,
and that @jdurand and @vlada-dudr had a different issue that I just pushed a fix for.
Thank you all for your reports and your help.
