### ISSUE TITLE
When uploading tar.gz to S3 - ERROR: S3 error: 403 (SignatureDoesNotMatch)

### ISSUE THREAD

**Issue by jpwalsh1** [s3tools/s3cmd#862]
Getting this error when doing a simple put of a tar.gz file to S3. When I do a put of a text file, it goes just as expected, but the gz file fails.

Not sure what's going on with headers or why I need to do something different for the one type of file over the other.

**Error Command**
`s3cmd put gg_mysql.sql.tgz s3://pez_backup/mysql_backup/weekly/
upload: 'gg_mysql.sql.tgz' -> 's3://pez_backup/mysql_backup/weekly/gg_mysql.sql.tgz'  [part 1 of 24, 15MB] [1 of 1]
 15728640 of 15728640   100% in    0s    24.32 MB/s  done
ERROR:
Upload of 'gg_mysql.sql.tgz' part 1 failed. Use
  /usr/local/bin/s3cmd abortmp s3://pez_backup/mysql_backup/weekly/gg_mysql.sql.tgz rjVo19_YbSAMezU7NdUcUw3osNebuP3tq1x6BWMbMuPtTe6uKvKnlQ1Q2H9xq2Ho996QJbPY2st3.8G.VkJ3X54DAkOl.txSejAFJ6143Djm35x4go0kvkL4o1FE9Blq
to abort the upload, or
  /usr/local/bin/s3cmd --upload-id rjVo19_YbSAMezU7NdUcUw3osNebuP3tq1x6BWMbMuPtTe6uKvKnlQ1Q2H9xq2Ho996QJbPY2st3.8G.VkJ3X54DAkOl.txSejAFJ6143Djm35x4go0kvkL4o1FE9Blq put ...
to continue the upload.
ERROR: S3 error: 403 (SignatureDoesNotMatch): The request signature we calculated does not match the signature you provided. Check your key and signing method.`

**Working Command**
`s3cmd put -f test.txt s3://pez_backup/mysql_backup/weekly/
upload: 'test.txt' -> 's3://pez_backup/mysql_backup/weekly/test.txt'  [1 of 1]
 3 of 3   100% in    0s    54.06 B/s  done`

**Comment by fviard** [comment]
@jpwalsh1 Can you run the non working command with the "-d" flag and post the log here? that would help identify the origin of the issue. Thank you

**Comment by jpwalsh1** [comment]
S3 error: 403 (SignatureDoesNotMatch): The request signature we calculated does not match the signature you provided. Check your key and signing method.

**Comment by sleekweasel** [comment]
I have this error. The configuration file works perfectly on my Mac with s3cmd 2.0.0, but not in a Debian docker container running 1.5.0-rc1.

Oddly, 's3cmd ls' works to get a list of buckets, but not once I give it a bucket to list keys.

Which key and signing method is it talking about?

**Comment by Lusitaniae** [comment]
Its about your access/secret keys. 

The AWS apis require a signature to be computed from your private key and sent with the request.
https://docs.aws.amazon.com/general/latest/gr/sigv4-calculate-signature.html

Master probably already includes the fix wich the distributed version doesn't.

**Comment by ikegentz** [comment]
Sorry to necro this, but wanted to post here in case anybody is coming across this in the future. Make sure your access key / secret key do not contain newlines! I had mine set in environment variables and didn't realize a newline was set in the end there. I was getting this exact issue but making sure there was no newline at the end took care of it
