### ISSUE TITLE
Is it possible to use s3cmd for interaction with single node deployments of OpenStack Swift and what configuration steps do i need to carry out?

### ISSUE THREAD

**Issue by christianbaun** [s3tools/s3cmd#865]
I deployed the storage service OpenStack Swift on a single node. The service is running

```
$ curl -i -H "X-Auth-User: test:tester" -H "X-Auth-Key: testing" http://10.0.0.253:8080/auth/v1.0/
HTTP/1.1 200 OK
X-Storage-Url: http://10.0.0.253:8080/v1/AUTH_test
X-Auth-Token-Expires: 77438
X-Auth-Token: AUTH_tka8fff6782f86486a84e3905daa60f308
Content-Type: text/html; charset=UTF-8
X-Storage-Token: AUTH_tka8fff6782f86486a84e3905daa60f308
Content-Length: 0
X-Trans-Id: txa21566e67e8143b1b32db-005908cf2f
X-Openstack-Request-Id: txa21566e67e8143b1b32db-005908cf2f
Date: Tue, 02 May 2017 18:25:51 GMT
```
I have no additional OpenStack services running. 

I modified inside the `~/.s3cfg` file these values:

```
access_key = tester
host_base = 10.0.0.253:8080
host_bucket = 10.0.0.253:8080
secret_key = testing
signature_v2 = True 
```

But this did not help:

```
$ s3cmd ls
ERROR: Error parsing xml: Malformed error XML returned from remote server..  ErrorXML: <html><h1>Unauthorized</h1><p>This server could not verify that you are authorized to access the document you requested.</p></html>
ERROR: S3 error: 401 (Unauthorized)
```

Is it possible to use s3cmd with Swift and what configuration steps do i need to carry out?

Do I need to insert the content of `X-Auth-Token` into the field `access_token` of the `~/.s3cfg`?

Thanks for any help.

**Comment by fviard** [comment]
It is possible to use Swift, but you have to use "Swift3" that is the "gateway" for S3:

https://wiki.openstack.org/wiki/Swift/APIFeatureComparison#Amazon_S3_REST_API_Compatability
https://docs.openstack.org/kilo/config-reference/content/configuring-openstack-object-storage-with-s3_api.html

To be noted, that there were will be limitations.
