### ISSUE TITLE
ls arg --summarize not supported

### ISSUE THREAD

**Issue by curiousercreative** [s3tools/s3cmd#868]
When attempting to get a summary of a directory using `s3cmd ls --human-readable --summarize s3://SOME_BUCKET/SOME_OBJECT`, error is returned:
>Usage: s3cmd [options] COMMAND [parameters]
>s3cmd: error: no such option: --summarize

**Comment by fviard** [comment]
@curiousercreative Both of your options are not existing options of s3cmd.
You can run a "s3cmd --help" command to see the list of available options with their description.

But I'm not sure of what you would like with a summarize option anyway as ls should already display your the needed infos.

**Comment by curiousercreative** [comment]
@fviard apologies for not being more clear. The use case is getting the size of a directory and all of it's contents recursively. Using the native [S3 CLI](https://docs.aws.amazon.com/cli/latest/reference/s3/ls.html#options) we have `--summarize` which will show the total number of objects and the total size of the objects. Can you suggest a better way to ascertain the size of a directory's contents?

```
aws s3 ls s3://mybucket --recursive --human-readable --summarize
2013-09-02 21:37:53   10 Bytes a.txt
2013-09-02 21:37:53  2.9 MiB foo.zip
2013-09-02 21:32:57   23 Bytes foo/bar/.baz/a
2013-09-02 21:32:58   41 Bytes foo/bar/.baz/b
2013-09-02 21:32:57  281 Bytes foo/bar/.baz/c
2013-09-02 21:32:57   73 Bytes foo/bar/.baz/d
2013-09-02 21:32:57  452 Bytes foo/bar/.baz/e
2013-09-02 21:32:57  896 Bytes foo/bar/.baz/hooks/bar
2013-09-02 21:32:57  189 Bytes foo/bar/.baz/hooks/foo
2013-09-02 21:32:57  398 Bytes z.txt

Total Objects: 10
   Total Size: 2.9 MiB
```

**Comment by loleg** [comment]
The equivalent s3cmd parameter is **du** (disk usage) - for example:

```
s3cmd du s3://blah --human-readable
31G      7187 objects s3://blah/
```
