### ISSUE TITLE
README mislead the naming of bucket's name

### ISSUE THREAD

**Issue by nabito** [s3tools/s3cmd#871]
According to:
http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html
bucket's name should contain no dot (.) in order for SSL (HTTPS) to work.

But the README doc said, s3://my-bucket.s3tools.org is a DNS compatible and FQDN. 

This mislead the understanding to name the bucket as 'my-bucket.s3tools.org'

Please consider revising.

**Comment by dsbcpas** [comment]
I created my buckets before the dot "." rule.  The dot is not creating any error messages or other trouble. But then again, there is no public access, just a backup site.

Should I change my bucket names?

**Comment by fviard** [comment]
@nabito @dsbcpas . When using s3cmd with amazon s3, you don't have to worry about that restriction as we did what was needed to handle this situation.

FYI, amazon s3 doesn't issue a "https" certificate per bucket/user but use a general one for their services looking like that:
*.s3.amazonaws.com
In theory, for certificates, the * is a wildcard only for a level but not for all the sub-folders.
So:
mybucket.s3.amazonaws.com
hello.s3.amazonaws.com
Will be validated with this cert.
But the following one will not be valid for standard https libraries:
sub.hello.s3.amazonaws.com
another.sub.hello.s3.amazonaws.com

In s3cmd we implemented our own verification for the validity of "host names" to be able to have a behavior where "*" also cover subdomains.

So as long as you only use s3cmd, you will not have issues.
If you use something else or try to get files through a web browser https request, you could encounter a ssl warning or error. But then, it will not be fatal and you could decide to not do that if that was your usage.

But it has to be noted that in the readme, it is not what is advertised. It says that this is ok if you own your own domain and so can do redirections.
IE my-bucket.s3tools.org -> my-bucket.s3tools.org.s3.amazonaws.com.
In that case, the public facing url would be my-bucket.s3tools.org, and you can provide an adequate ssl certificate for that to amazon.

**Comment by nabito** [comment]
Thank you for your clarification. This makes it very clear, at least to know that s3cmd aware of such issue.
