### ISSUE TITLE
BUCKETNAME.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com')

### ISSUE THREAD

**Issue by Manuel5cc** [s3tools/s3cmd#873]
I can run other functions (like listing) but not put or sync. I get this error:
`WARNING: Retrying failed request: /file.ext (hostname 'BUCKETNAME.s3.amazonaws.com' doesn't match either of '*.s3.amazonaws.com', 's3.amazonaws.com')`

Python version is "2.7.9 (default, Sep 17 2016, 20:26:04) \n[GCC 4.9.2]"

**Comment by fviard** [comment]
What version do you use? can you try with the last master?

**Comment by fviard** [comment]
Please reopen if you are still encountering the issue.
in that case, please give us the version of s3cmd that you are using and if possible run it with the "-d" flag to have more debug.
