### ISSUE TITLE
s3cmd put with –-add-header=x-amz-meta-KEY:VALUE issue

### ISSUE THREAD

**Issue by strus38** [s3tools/s3cmd#878]
Hi
I am looking at the right syntax to put a file in S3 and at the same time setting x-amz-meta-KEY:VALUE properties.

`$ s3cmd --no-check-certificate --access_key="mysuperac" --secret_key="mysupersecretkey" put --add-header=x-amz-meta-foo:bar Makefile s3://<BUCKET>/Makefile
WARNING: Module python-magic is not available. Guessing MIME types based on file extensions.
upload: 'Makefile' -> 's3://<BUCKET>/Makefile'  [1 of 1]
 1287 of 1287   100% in    0s  1580.17 B/s  done
upload: 'Makefile' -> 's3://<BUCKET>/Makefile'  [1 of 1]
 1287 of 1287   100% in    0s     3.45 kB/s  done
upload: 'Makefile' -> 's3://<BUCKET>/Makefile'  [1 of 1]
 1287 of 1287   100% in    0s     3.54 kB/s  done
` 

But no TAGS has been set... (looking at the AWS Console)

Using 'modify' command works.

... well it seems to work fine since this morning ...  not sure what happened.

This can be closed.

Thanks.

**Comment by fviard** [comment]
Ok, happy that your problem solved itself.
Just in case it happens again in the future take care to quote the parameter of your "add-header", i think that ":" can maybe trigger some shell magic.
