### ISSUE TITLE
Potential GPL violation

### ISSUE THREAD

**Issue by tdmalone** [s3tools/s3cmd#879]
FYI, I've [logged an issue](https://github.com/heroku/heroku-buildpack-php/issues/232) with a project that depends on s3cmd as it is potentially violating s3cmd's GPL license. You may like to weigh in on whether that project is or is not violating.

**Comment by dzuelke** [comment]
It's of course not a violation. The Heroku PHP buildpack merely invokes `s3cmd` through shell scripts, and only in the utilities that aid in building platform packages. It can perform its key functionality perfectly fine without `s3cmd`, and it doesn't "share or ship back and forth complex data structures". It also doesn't bundle `s3cmd`.

By your logic, any non-GPL shell script that invokes `cd` or `cat` would also violate the GPL when run on a Linux system.
