### ISSUE TITLE
ERROR: Parameter problem: Destination must be a directory and end with '/' when acting on a folder content or on multiple sources.

### ISSUE THREAD

**Issue by robwalch** [s3tools/s3cmd#886]
With v1.6.1 we could modify files using glob patterns. For example:

`s3cmd modify -v --add-header "Content-Type: text/css" s3://website/assets/*.css`

With v2.0.0 the above outputs an error:

`"ERROR: Parameter problem: Destination must be a directory and end with '/' when acting on a folder content or on multiple sources."`

I don't want to have to list out every file I want to modify and I don't want to apply the same changes to all files in a directory. It's a little unclear why this is being applied to a modify command.

**Comment by fviard** [comment]
Thank you for the report, indeed it is a regression.
Some coded was added to prevent accidents when passing parameters to cp or mv.
As a side effect it did impact "modify" that is using the same base code.
I will fix that.

**Comment by fviard** [comment]
Should be fixed in master, It would be great if you can give it a try.

**Comment by robwalch** [comment]
Thanks @fviard - appreciate the fix!

(I've never installed the tool from source. We've pinned our CI boxes to 1.6.1 for now. I only ran into this issue because of an accidental update to 2.0.0 on there that blocked us from being able to release!)
