### ISSUE TITLE
cfcreate s3://test-stage errors out on 400 (InvalidOrigin):

### ISSUE THREAD

**Issue by ghost** [s3tools/s3cmd#89]
Testing the latest build from, I wanted to convert a brand new bucket I created to CF, this is the command I ran.

s3cmd -d cfcreate s3://test-stage

and it spit out the following:

DEBUG: Command: cfcreate
INFO: Creating distribution from: s3://test-stage/
DEBUG: CreateDistribution(): request_body: <DistributionConfig xmlns="http://cloudfront.amazonaws.com/doc/2010-11-01/"><Origin>test-stage.s3.amazonaws.com</Origin><CallerReference>s3://test-stage/</CallerReference><Comment>http://test-stage.s3.amazonaws.com/</Comment><Enabled>true</Enabled><DefaultRootObject>None</DefaultRootObject></DistributionConfig>
DEBUG: CloudFront.sign_request('Thu, 29 Nov 2012 01:57:59 +0000') = TYLcJNX+5sgYQa+/3gI+oCwFQOU=
DEBUG: send_request(): POST /2010-11-01/distribution
DEBUG: CloudFront: response: {'status': 400, 'headers': {'x-amzn-requestid': '3441191e-39c8-11e2-8dea-73895653cb26', 'date': 'Thu, 29 Nov 2012 01:58:00 GMT', 'content-length': '296', 'content-type': 'text/xml'}, 'reason': 'Bad Request', 'data': '<?xml version="1.0"?>\n<ErrorResponse xmlns="http://cloudfront.amazonaws.com/doc/2010-11-01/"><Error><Type>Sender</Type><Code>InvalidOrigin</Code><Message>The origin server does not exist or is not valid.</Message></Error><RequestId>3441191e-39c8-11e2-8dea-73895653cb26</RequestId></ErrorResponse>'}
DEBUG: S3Error: 400 (Bad Request)
DEBUG: HttpHeader: x-amzn-requestid: 3441191e-39c8-11e2-8dea-73895653cb26
DEBUG: HttpHeader: date: Thu, 29 Nov 2012 01:58:00 GMT
DEBUG: HttpHeader: content-length: 296
DEBUG: HttpHeader: content-type: text/xml
DEBUG: ErrorXML: Type: 'Sender'
DEBUG: ErrorXML: Code: 'InvalidOrigin'
DEBUG: ErrorXML: Message: 'The origin server does not exist or is not valid.'
ERROR: S3 error: 400 (InvalidOrigin): The origin server does not exist or is not valid.

**Comment by fviard** [comment]
Closing as issue is already fixed.
