### ISSUE TITLE
global name json not defined

### ISSUE THREAD

**Issue by yadavshubhanshu** [s3tools/s3cmd#890]
I am getting the following error with s3cmd, pulling from the master branch. It was working fine as of 2 days ago. 

If instead of pulling from master, I use version 1.6, it works fine. 

DEBUG: s3cmd version 2.0.0+
DEBUG: ConfigParser: Reading file '/home/ubuntu/.s3cfg'

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  following lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

DEBUG: Unicodising './s3cmd' using UTF-8
DEBUG: Unicodising '--debug' using UTF-8
DEBUG: Unicodising 'get' using UTF-8
DEBUG: Unicodising '--recursive' using UTF-8
DEBUG: Unicodising 's3://a/b/' using UTF-8
DEBUG: Unicodising '/c/d/' using UTF-8
Invoked as: ./s3cmd --debug get --recursive s3://a/b/ /c/d/
Problem: NameError: global name 'json' is not defined
S3cmd:   2.0.0+
python:   2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "./s3cmd", line 3003, in <module>
    rc = main()
  File "./s3cmd", line 2726, in main
    cfg = Config(options.config, options.access_key, options.secret_key, options.access_token)
  File "/root/s3cmd/S3/Config.py", line 179, in __init__
    self.role_config()
  File "/root/s3cmd/S3/Config.py", line 200, in role_config
    creds=json.load(resp)
NameError: global name 'json' is not defined

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by fviard** [comment]
Fixed in MASTER, thank you for the report!
