### ISSUE TITLE
Compile SyntaxError, Custom_httplib3x.py to Custom_httplib3x.pyc; Python python-2.7.5-48.el7.x86_64 Linux EL 3.10

### ISSUE THREAD

**Issue by dsbcpas** [s3tools/s3cmd#895]
byte-compiling build/bdist.linux-x86_64/egg/S3/Custom_httplib3x.py to Custom_httplib3x.pyc
  File "build/bdist.linux-x86_64/egg/S3/Custom_httplib3x.py", line 33
    (name.title(), data[err.start:err.end], name)) from None
                                                      ^
SyntaxError: invalid syntax

Though no error on exit, neither file exists. I have not tested to see if s3cmd works yet with the above error.

**Comment by fviard** [comment]
The code were you are seeing the syntax error is directly copied from http.lib in python3.
So it is good.
But what i'm thinking is that your byte compiling should be done by "python 2" on all files, including this one that is only import when using s3cmd on python3.
I'm wondering if there is a way to fix the setup.py so any python 3 code is ignored during byte compiling?

**Comment by dsbcpas** [comment]
That compile problem has not yet resulted in any s3cmd run errors.  Appears to just be an issue of elegance. Okay to close issue by me.

**Comment by fviard** [comment]
Sadly i have not found any way to prevent byte-compiling just on py3 sources when installing with py2.
But I did refactor the code to remove 2 negligible py3 idioms and so now it should install without warning again :-)
