### ISSUE TITLE
-e Creates Errors When Using with COPY from S3 to Redshift

### ISSUE THREAD

**Issue by kobym** [s3tools/s3cmd#897]
The command doesn't seem to work with the master_symmetric_key as the passphrase creates errors. Also the metadata for key and iv are not copied over from GPG.

**Comment by fviard** [comment]
Is it possible for you to give us more details?
Example of command, the error, traceback, part of output with the "-d" flag, removing what you consider to be sensitive.
thanks

**Comment by kobym** [comment]
So I am working to put an encrypted file onto S3 and then bring it into a staging table in Redshift using the COPY command. 

I reconfigured s3cmd and gpg to make sure everything was good on that end.

I originally tried using:
`s3cmd -e put /home/*.csv  s3://folder/`

Then when I received a missing metadata error (using Aginity) I tried:
`s3cmd -e --add-header=x-amz-meta-x-amz-key:SECRET put /home/*.csv  s3://
folder/`

Which then prompted me for the IV metadata but it seems wrong to just be manually inserting it.

I also tried encrypting and loading:
`gpg --symmetric --cipher-algo aes256 -o file.csv.gpg file.csv`

But same path of errors occurs. Am I supposed to be converting the passphrase, where is the IV that Amazon is asking for when copying?

Thanks!

**Comment by fviard** [comment]
Hum I'm not sure about the usage of redshift, but i think that you might be using the wrong mode of encryption.
The "-e" option is a kind of "client only" encryption using gpg. Not something related to anything in relation with aws/s3. You encrypt the data on your side, and in theory that should only be decrypted on your client side also.

In your case, i think that it is "SSE" (server side encryption) that you should be using.
On aws, you have to create a "key" with a name. Then you will have to use the following options of s3cmd:

>   --server-side-encryption
>                         Specifies that server-side encryption will be used
>                         when putting objects. [put, sync, cp, modify]
>   --server-side-encryption-kms-id=KMS_KEY
>                         Specifies the key id used for server-side encryption
>                         with AWS KMS-Managed Keys (SSE-KMS) when putting
>                         objects. [put, sync, cp, modify]

And NOT using the "-e" option.
