### ISSUE TITLE
Shallow sync or get in s3Cmd

### ISSUE THREAD

**Issue by codersbrew** [s3tools/s3cmd#899]
Hello,

I am trying to d/l all files within a recursive directory structure but not keep the directory structure on my local drive e.g. ( 2017/01/xxxxx.jpg should just go to /local/xxxxx.jpg).

Is there a way to do this in the current iteration? I can't seem to find it.

**Comment by fviard** [comment]
I don't think that there is a direct way to do that, the best would be to do a shell script that take the output of s3cmd ls -r (that lists all the files), and for each doing a s3cmd get $1 destination/

**Comment by codersbrew** [comment]
That's what I ended up doing. Thanks!
