### ISSUE TITLE
dont know how to edit host base and bucket

### ISSUE THREAD

**Issue by ce314007** [s3tools/s3cmd#901]
![aws](https://user-images.githubusercontent.com/30142658/28558965-6009d152-714f-11e7-8c81-d5de5499e6bc.PNG)
i want build object storage on ceph by s3 amazon and i want to edit host base and bucket like in picture.Where i find the file configuration?

**Comment by fviard** [comment]
You can't 'mix' DNS names and ip address. In you case, I think that you
should just use the ip address in the host_bucket config. (Ie without the
%(bucket)s.
It depends on your ceph config, but I suppose that it should support 'path
style' access for bucket where bucket names are in the path and not in the
'dns name's.
