### ISSUE TITLE
s3cmd reads configuration file but claims it doesn't exist

### ISSUE THREAD

**Issue by brunogirin** [s3tools/s3cmd#903]
I'm using s3cmd to access the Ceph storage provided by my cloud provider. I created a minimal `.s3cfg` file on my VM to do so. When I try to list buckets, it claims that it can't find the configuration file despite `--debug` output showing that it's parsing it:

```
$ s3cmd ls --debug
DEBUG: s3cmd version 1.6.1
DEBUG: ConfigParser: Reading file '/home/ubuntu/.s3cfg'
DEBUG: ConfigParser: access_key->...-3_chars...
DEBUG: ConfigParser: secret_key->...-3_chars...
DEBUG: ConfigParser: enable_multipart->True
DEBUG: ConfigParser: host_base->storage.datacentred.io
DEBUG: ConfigParser: host_bucket->%(bucket)s.storage.datacentred.io
DEBUG: ConfigParser: use_https->True
ERROR: /home/ubuntu/.s3cfg: None
ERROR: Configuration file not available.
ERROR: Consider using --configure parameter to create one.
```

OS: Ubuntu 16.04.2 LTS

Expected behaviour:
- if there is an issue with the config file, point out the issue
- if there is not issue with the config file, execute the command

Actual behaviour:
- reports that the config file is not available even though it parsed it

**Comment by fviard** [comment]
Can you copy the content of your mini config? (not forgetting to scramble the credentials?)
I'm interested to know the line following the one with the key "use_https".

**Comment by brunogirin** [comment]
There is no following line, only a blank line and the end of the file:

```
[default]
access_key = XXXX
secret_key = XXXX
enable_multipart = True
host_base = storage.datacentred.io
host_bucket = %(bucket)s.storage.datacentred.io
use_https = True
```

**Comment by fviard** [comment]
I have pushed to MASTER a few fixes for the handling of config files, can you try with it to see if you are still having your issue ? i'm not able to reproduce it.
thanks.

**Comment by brunogirin** [comment]
No problem, will do and report back.

**Comment by brunogirin** [comment]
I managed to find the root cause of the problem: the `access_key` and `secret_key` entries in my `.s3cfg` file were empty. Entering the correct values fixed it. That said, the error message is confusing, I would have expected the tool to tell me that those config entries were not properly populated. I'll try MASTER to see if it fixes that.

**Comment by brunogirin** [comment]
I tried the MASTER version and the problem persists. Looking into it further, this issue is a duplicate of #834 so I'm closing it.
