### ISSUE TITLE
may ceph status health error 

### ISSUE THREAD

**Issue by ce314007** [s3tools/s3cmd#904]
![err](https://user-images.githubusercontent.com/30142658/28607315-4c937070-7216-11e7-8d82-8862625820c8.PNG)
i have to try with ceph mds reapired 0,but didn't effect. anyone can solve the issue?

**Comment by dannyk81** [comment]
I think you posted in the wrong Repo, this is `s3cmd` related, you should head over to https://github.com/ceph
