### ISSUE TITLE
$AWS_PROFILE is not honored

### ISSUE THREAD

**Issue by matt-pilgrim** [s3tools/s3cmd#906]
[This](https://stackoverflow.com/questions/33551537/how-to-set-the-profile-when-running-the-s3cmd-sync-command) mentions something similar, and suggests using `--configure`, but that apparently uses the `~/.s3cfg` file.  Shouldn't I be able to use a command like `AWS_PROFILE=foo s3cmd ...` and use the "foo" profile from `~/.aws/credentials`?  

As someone who routinely uses multiple aws profiles, this is painful because I don't really want to keep another file in sync, and I also don't want to have to view my credentials files and copy/paste environment variables for AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY.

 If there is agreement that this is a bug, I can probably submit a patch.

EDIT:  found [this](https://github.com/s3tools/s3cmd/issues/104#issuecomment-90974616) comment from 2015 suggesting using the credentials file, and [this](https://github.com/s3tools/s3cmd/issues/104#issuecomment-93788313) mention in the same thread that a patch would be accepted.  Can anyone confirm this is still desired?

**Comment by felipe1982** [comment]
If like this feature. I'm using `awsume` in the meantime which creates environment variables 

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by alexanderkjeldaas** [comment]
@felipe1982 which awesome command do you use?  awesome doesn't set any environment variables for me.

**Comment by felipe1982** [comment]
That's only what awsume does: sets environment variables. Make sure you have the Alias set, or run `. awsume `

**Comment by fviard** [comment]
Should be already fixed with merged PR #966 .
