### ISSUE TITLE
get fails for an s3 directory

### ISSUE THREAD

**Issue by yadavshubhanshu** [s3tools/s3cmd#909]
Probably some issue related with the merges made in the past few days, but the "get" command fails for a directory located in s3.

More details and logs in the gist mentioned below:-

https://gist.github.com/yadavshubhanshu/0ff263d3b0aed8cf3ac61bdb381bac26

Thank You

**Comment by fviard** [comment]
@yadavshubhanshu Can you try again with the last MASTER. I did fix a few things that i have broken with previous commits.

**Comment by yadavshubhanshu** [comment]
@fviard Works fine with the latest master. Thank You.
