### ISSUE TITLE
--max-retries

### ISSUE THREAD

**Issue by eburcat** [s3tools/s3cmd#914]
Currently the retries are hard-coded to 5.
It'd help if it was possible to control the number of retries, especially when we're throttling our traffic and we're trying to upload big files.
If it was possible to set the value to somewhere in the range of 1 to 30 I think it can be reasonable in some cases.

**Comment by fviard** [comment]
I don't think that a lot of people would use this option but that looks ok to me to add that in config options.

**Comment by lfdnas** [comment]
It would be great to have this feature in case of failure!

**Comment by sebastiandanconia** [comment]
A `--max-retries` option could be **part** of a successful solution to my problem.

I use an S3-compatible private cloud which I access over a less-than-reliable connection that is extremely slow in relation to the size of the data I'm sending (> 1TiB over 1.25 MB/s, which takes weeks or more).

Currently, `s3cmd` increases the timeout duration linearly based on the retry number. My preferred backoff intervals would be a few seconds in the beginning, then increase to a maximum of 10-20 minutes or so between retries, finally giving up after 3 days or so. I like the `--max-retries` option, but I additionally advocate tuning the backoff/retry timeout function so it's reasonable for a **really** long retry window before `s3cmd` gives up.

I'm willing to try coding up a solution once I have clarity on what kind of Pull Request you'd accept.

**Comment by fviard** [comment]
A "--max-retries" option was added in MASTER.
(But still anything like retry_profile for the moment).
