### ISSUE TITLE
Does s3cmd support aws in China?

### ISSUE THREAD

**Issue by EricJhon** [s3tools/s3cmd#915]
When I use s3cmd to connect aws in China,I can list buckets.But when I make a bucket,there is an error"ERROR: S3 error: 403 (InvalidAccessKeyId): The AWS Access Key Id you provided does not exist in our records".So,I want to know whether s3cmd supports aws in China.

**Comment by felipe1982** [comment]
Does your user have the permissions to create a bucket? Does your key work in another Region? 

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by fviard** [comment]
@EricJhon It does and normally it works. Please re-open if you are still encountering this issue and it is not an issue of permissions.
