### ISSUE TITLE
Uppercase host name causes SignatureDoesNotMatch in 2.0.0

### ISSUE THREAD

**Issue by JumpyKitten** [s3tools/s3cmd#920]
Set this in .s3cfg:
host_bucket = %(bucket)s.s3.AMAZONAWS.com

s3cmd ls s3://somebucket
ERROR: S3 error: 403 (SignatureDoesNotMatch): The request signature we calculated does not match the signature you provided. Check your key and signing method.

This used to work in 1.6.1. It's a new issue in 2.0.0.
It appears 2.0.0 has changed to emit the Host header in lowercase conversion. But the signature was computed with the original hostname without conversion.

**Comment by fviard** [comment]
Thank you very much for the detailed report and for having investigated it.
This was a nasty bug.
I have a pushed a fix for it. Don't hesitate to give it a try with the MASTER version if you can.

**Comment by JumpyKitten** [comment]
I tested. The fix works. Thanks. I know this is unlikely a problem for out-of-the-box use with Amazon S3. But when used with S3-compatible systems, some people, like me, has a bad habit of using mixed-case hostname, e.g., S3-server-A.acme.com
