### ISSUE TITLE
Connection Error: Error resolving a server hostname

### ISSUE THREAD

**Issue by turbo2ltr** [s3tools/s3cmd#927]
I'm at a loss..
My S3 bucket has an upload dir and folders named Monday through Sunday
I have a script that uploads my cPanel backups every night using s3cmd
It then deletes any files out of the folder for today day and it then moves the backup from the upload dir to  it allowing me to keep 7 days of backups.

The issue I'm having is for months it has stopped working.  Somehwere between uploading 20gb, deleting or moving sequence it will get an error:

`ERROR: [Errno -2] Name or service not known
ERROR: Connection Error: Error resolving a server hostname.
Please check the servers address specified in 'host_base', 'host_bucket', 'cloudfront_host', 'website_endpoint'`

Clearly we know this is not the case because sometimes it works and completes. Most of the time it does not.  I moved the cron job to a completely different hour thinking maybe some other maintenance was bringing down the DNS temporarily but that does not seem to have had any effect.

My settings for these are:
> cloudfront_host = cloudfront.amazonaws.com
> host_base = s3.amazonaws.com
> host_bucket = %(bucket)s.s3.amazonaws.com

It would be really nice if there was a retry for this kind of error instead of just aborting immediately.

Also any ideas on how to troubleshoot this issue?

Here's the last few lines from the log.. in this instance neither the second or third command worked. The previous day, the second command worked, and the the third failed after 50 or so files were copied..

> s3cmd sync -v --delete-removed /home2/backup/`date +%Y-%m-%d`  s3://[mybucket]/cpbackup/ >> /tmp/log/sync.log 2>&1;
> ...
> Done. Uploaded 20667666244 bytes in 1308.8 seconds, 15.06 MB/s.
> Complete at  Thu Oct 19 03:48:01 CDT 2017
> 
>
> *** COPY DAILYS LOG ***
> Thu Oct 19 03:48:01 CDT 2017
> 
> Deleting old daily copy 
> 
> s3cmd del -v --recursive s3://[mybucket]/dailys/`date +%A`/ >> /tmp/log/s3copy.log 2>&1; 
>
> ERROR: [Errno -2] Name or service not known
> ERROR: Connection Error: Error resolving a server hostname.
> Please check the servers address specified in 'host_base', 'host_bucket', 'cloudfront_host', 'website_endpoint'
> 
> ~~ Copying daily to retained dailys 
> 
> s3cmd cp -v --recursive s3://[mybucket]/cpbackup/ s3://[mybucket]/dailys/`date +%A`/  >> /tmp/log/s3copy.log 2>&1;
>
> Start at  Thu Oct 19 03:48:02 CDT 2017
> INFO: Retrieving list of remote files for s3://[mybucket]/cpbackup/ ...
> ERROR: [Errno -2] Name or service not known
> ERROR: Connection Error: Error resolving a server hostname.
> Please check the servers address specified in 'host_base', 'host_bucket', 'cloudfront_host', 'website_endpoint'
> Complete at  Thu Oct 19 03:48:02 CDT 2017

**Comment by fviard** [comment]
I think that it is something related to your network.

First, my advice would be to run the s3cmd with the "-d" flag, you will have more detail of the network connections that are made and where it is failing.
This could give us some informations.

It could be interesting for you to try to do a "dig" in loop or something like for a few hours to see if you have dns resolution issues.

One last thing, what is your version of s3cmd? Maybe it could be interesting for you to try the latest "Master" version.

**Comment by turbo2ltr** [comment]
I tried running the move again.. it failed after a few successful moves.  Here are the last two with -d option.

> s3cmd cp -v -d --recursive s3://[domain].com-host2-backup/cpbackup/ s3://[domain].com-host2-backup/dailys/\`date +%A\`/

```
----------------------
DEBUG: signature-v4 headers: {'x-amz-content-sha256': u'[snip]', 'content-type': 'application/xml', 'Authorization': u'[snip]/20171019/us-west-2/s3/aws4_request,SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date,Signature=[snip]', 'x-amz-date': '20171019T154956Z'}
DEBUG: Processing request, please wait...
DEBUG: get_hostname([domain].com-host2-backup): [domain].com-host2-backup.s3.amazonaws.com
DEBUG: ConnMan.get(): re-using connection: https://[domain].com-host2-backup.s3.amazonaws.com#68
DEBUG: format_uri(): /dailys/Thursday/2017-10-13/accounts/[accntname].tar.gza?acl
DEBUG: Sending request method_string='PUT', uri=u'/dailys/Thursday/2017-10-13/accounts/[accntname].tar.gza?acl', headers={'x-amz-content-sha256': u'[snip]', 'content-type': 'application/xml', 'Authorization': u'[snip]/20171019/us-west-2/s3/aws4_request,SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date,Signature=[snip]', 'x-amz-date': '20171019T154956Z'}, body=(441 bytes)
DEBUG: ConnMan.put(): connection put back to pool (https://[domain].com-host2-backup.s3.amazonaws.com#69)
DEBUG: Response:
{'data': '',
 'headers': {'connection': 'close',
             'content-length': '0',
             'date': 'Thu, 19 Oct 2017 15:49:57 GMT',
             'server': 'AmazonS3',
             'x-amz-id-2': 'M328Z/[snip]=',
             'x-amz-request-id': '[snip]'},
 'reason': 'OK',
 'status': 200}
remote copy: 's3://[domain].com-host2-backup/cpbackup/2017-10-13/accounts/[accntname].tar.gza' -> 's3://[domain].com-host2-backup/dailys/Thursday/2017-10-13/accounts/[accntname].tar.gza'
DEBUG: CreateRequest: resource[uri]=/cpbackup/2017-10-13/accounts/[accntname].tar.gzb
DEBUG: Using signature v4
DEBUG: get_hostname([domain].com-host2-backup): [domain].com-host2-backup.s3.amazonaws.com
DEBUG: canonical_headers = host:[domain].com-host2-backup.s3.amazonaws.com
x-amz-content-sha256:[snip]
x-amz-date:20171019T154956Z

DEBUG: Canonical Request:
GET
/cpbackup/2017-10-13/accounts/[accntname].tar.gzb
acl=
host:[domain].com-host2-backup.s3.amazonaws.com
x-amz-content-sha256:[snip]
x-amz-date:20171019T154956Z

host;x-amz-content-sha256;x-amz-date
[snip]
----------------------
DEBUG: signature-v4 headers: {'x-amz-content-sha256': u'[snip]', 'Authorization': u'AWS4-HMAC-SHA256 Credential=[snip]/20171019/us-west-2/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=[snip]', 'x-amz-date': '20171019T154956Z'}
DEBUG: Processing request, please wait...
DEBUG: get_hostname([domain].com-host2-backup): [domain].com-host2-backup.s3.amazonaws.com
DEBUG: ConnMan.get(): re-using connection: https://[domain].com-host2-backup.s3.amazonaws.com#69
DEBUG: format_uri(): /cpbackup/2017-10-13/accounts/[accntname].tar.gzb?acl
DEBUG: Sending request method_string='GET', uri=u'/cpbackup/2017-10-13/accounts/[accntname].tar.gzb?acl', headers={'x-amz-content-sha256': u'[snip]', 'Authorization': u'AWS4-HMAC-SHA256 Credential=[snip]/20171019/us-west-2/s3/aws4_request,SignedHeaders=host;x-amz-content-sha256;x-amz-date,Signature=[snip]', 'x-amz-date': '20171019T154956Z'}, body=(0 bytes)
DEBUG: Response:
{}
ERROR: [Errno -2] Name or service not known
ERROR: Connection Error: Error resolving a server hostname.
Please check the servers address specified in 'host_base', 'host_bucket', 'cloudfront_host', 'website_endpoint'

```


interesting that the last request says zero bytes..  Wonder if that is a clue.  Not sure what exactly is zero bytes..

I will try the dig..

Thanks!

**Comment by fviard** [comment]
It could be interesting for you to set other dns servers on you server.
Like 8.8.8.8 to see if you still have the issue.

If you have a system using systemd/resolvd or dnsmasq , I think that I have
seen a bug report somewhere that said that on of this daemons choose
randomly in the list of dns servers that you set for each request. Instead
of just picking the second one only if the primary is not replying.

In such a case, you could have one of your dns servers list that is wrong
and some random requests will be pick to use it and so fail.

**Comment by turbo2ltr** [comment]
hmm, looks like you are right..
I just kept running this by hand a bunch of times.  They mostly came back as:

```
# dig  s3.amazonaws.com

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.47.rc1.el6_8.4 <<>> s3.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 15904
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 4, ADDITIONAL: 8

;; QUESTION SECTION:
;s3.amazonaws.com.              IN      A

;; ANSWER SECTION:
s3.amazonaws.com.       3520    IN      CNAME   s3-1.amazonaws.com.
s3-1.amazonaws.com.     5       IN      A       52.216.21.213

;; AUTHORITY SECTION:
s3-1.amazonaws.com.     1500    IN      NS      ns-1084.awsdns-07.org.
s3-1.amazonaws.com.     1500    IN      NS      ns-1726.awsdns-23.co.uk.
s3-1.amazonaws.com.     1500    IN      NS      ns-482.awsdns-60.com.
s3-1.amazonaws.com.     1500    IN      NS      ns-782.awsdns-33.net.

;; ADDITIONAL SECTION:
ns-482.awsdns-60.com.   161425  IN      A       205.251.193.226
ns-482.awsdns-60.com.   161425  IN      AAAA    2600:9000:5301:e200::1
ns-782.awsdns-33.net.   162176  IN      A       205.251.195.14
ns-782.awsdns-33.net.   162176  IN      AAAA    2600:9000:5303:e00::1
ns-1084.awsdns-07.org.  161855  IN      A       205.251.196.60
ns-1084.awsdns-07.org.  161855  IN      AAAA    2600:9000:5304:3c00::1
ns-1726.awsdns-23.co.uk. 161855 IN      A       205.251.198.190
ns-1726.awsdns-23.co.uk. 161855 IN      AAAA    2600:9000:5306:be00::1

;; Query time: 2 msec
;; SERVER: [myip]#53(6[myip])
;; WHEN: Thu Oct 19 11:34:26 2017
;; MSG SIZE  rcvd: 382

```


But one came back like this:

 # dig  s3.amazonaws.com
```

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.47.rc1.el6_8.4 <<>> s3.amazonaws.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 63226
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;s3.amazonaws.com.              IN      A

;; Query time: 0 msec
;; SERVER: [myip]#53([myip])
;; WHEN: Thu Oct 19 11:34:26 2017
;; MSG SIZE  rcvd: 34
```

So there it is..  now to dig into that.. THANKS!!

**Comment by turbo2ltr** [comment]
```
 # dig  s3.amazonaws.com +trace

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.47.rc1.el6_8.4 <<>> s3.amazonaws.com +trace
;; global options: +cmd
.                       90451   IN      NS      b.root-servers.net.
.                       90451   IN      NS      c.root-servers.net.
.                       90451   IN      NS      d.root-servers.net.
.                       90451   IN      NS      e.root-servers.net.
.                       90451   IN      NS      f.root-servers.net.
.                       90451   IN      NS      g.root-servers.net.
.                       90451   IN      NS      h.root-servers.net.
.                       90451   IN      NS      i.root-servers.net.
.                       90451   IN      NS      j.root-servers.net.
.                       90451   IN      NS      k.root-servers.net.
.                       90451   IN      NS      l.root-servers.net.
.                       90451   IN      NS      m.root-servers.net.
.                       90451   IN      NS      a.root-servers.net.
;; Received 508 bytes from [myip]#53([myip]) in 1 ms

;; Truncated, retrying in TCP mode.
com.                    172800  IN      NS      l.gtld-servers.net.
com.                    172800  IN      NS      b.gtld-servers.net.
com.                    172800  IN      NS      c.gtld-servers.net.
com.                    172800  IN      NS      d.gtld-servers.net.
com.                    172800  IN      NS      e.gtld-servers.net.
com.                    172800  IN      NS      f.gtld-servers.net.
com.                    172800  IN      NS      g.gtld-servers.net.
com.                    172800  IN      NS      a.gtld-servers.net.
com.                    172800  IN      NS      h.gtld-servers.net.
com.                    172800  IN      NS      i.gtld-servers.net.
com.                    172800  IN      NS      j.gtld-servers.net.
com.                    172800  IN      NS      k.gtld-servers.net.
com.                    172800  IN      NS      m.gtld-servers.net.
;; Received 830 bytes from 192.5.5.241#53(192.5.5.241) in 2 ms

;; Connection to 2001:502:8cc::30#53(2001:502:8cc::30) for s3.amazonaws.com failed: host unreachable.
amazonaws.com.          172800  IN      NS      u1.amazonaws.com.
amazonaws.com.          172800  IN      NS      u2.amazonaws.com.
amazonaws.com.          172800  IN      NS      r1.amazonaws.com.
amazonaws.com.          172800  IN      NS      r2.amazonaws.com.
;; Received 166 bytes from 192.35.51.30#53(192.35.51.30) in 27 ms

s3.amazonaws.com.       3600    IN      CNAME   s3-1.amazonaws.com.
amazonaws.com.          3600    IN      NS      r1.amazonaws.com.
amazonaws.com.          3600    IN      NS      r2.amazonaws.com.
amazonaws.com.          3600    IN      NS      u1.amazonaws.com.
amazonaws.com.          3600    IN      NS      u2.amazonaws.com.
;; Received 185 bytes from 205.251.192.27#53(205.251.192.27) in 3 ms

```

**Comment by fviard** [comment]
Maybe you can have a network connectivity issue that is not related to dns also.
maybe you should try to do a loop of ping, for one hour or something like that to see if you don't have lost packets.

**Comment by turbo2ltr** [comment]
One difference I see is that it's fine with an IPv4 address, but it failed on the IPv6 address.

Upon testing,  I am unable to get any connections to IPV6 addresses from the server.. 

Researching..

Thanks!

**Comment by fviard** [comment]
Thanks for the update.
I will close the issue as it is not an issue of s3cmd, but don't hesitate to tell us here the final resolution of your problem. That is always interesting as experience of weird issues  ;-)

**Comment by turbo2ltr** [comment]
So turned out to be twofold.  There was indeed an IPV6 issue caused by an upstream datacenter. My hosting provider was able to fix that.  Once that was fixed, I saw the the dig trace was no longer failing on IPv6 addresses, but much to my dismay, the backups were still failing.

The server had it's DNS servers set to what I'm guessing (based on IP range) is the DNS provided by my host. It seems that DNS server would fail to return a query 1 in 10 times. I changed the resolvers to google's DNS and I the backups have completed every night so far.  

Thanks for the help!

**Comment by vonkdoth-solutions** [comment]
ERROR: Connection Error: Error resolving a server hostname.
Please check the servers address specified in 'host_base', 'host_bucket', 'cloudfront_host', 'website_endpoint'
Removing workspace sudo rm -rf /home/centos/backup/workdir/

request: please can you help for this above error
