### ISSUE TITLE
Regression: IAM role support broken in 2.0.0

### ISSUE THREAD

**Issue by Zenexer** [s3tools/s3cmd#930]
In 1.6.1, if I used a blank access key and secret key, I could assign an EC2 instance an IAM role and still access protected resources.  However, in 2.0.0, s3cmd no longer allows me to run anything with a blank access/secret key.  It just outputs the following when I use `get`:

```
ERROR: /home/someone/.s3cfg: None
ERROR: Configuration file not available.
ERROR: Consider using --configure parameter to create one.
```

If I run `--configure` and leave the access and secret keys blank, it'll generate a new config, but I'll still receive the same error.  If I then edit the access and secret keys manually so that they have contents (doesn't matter what it is), it'll let me run commands.

**Comment by fviard** [comment]
There are multiple things that are not right with how access/secret keys are handled between the different ways to get them. It is planned to be fixed soon.

**Comment by rhuddleston** [comment]
Note this only seems broken on python3 if I install via pip2 everything works

**Comment by rhuddleston** [comment]
Any chance we can get s3cmd fixed to work on python3 as it does with python2?

**Comment by rhuddleston** [comment]
This is fixed with this commit: 

https://github.com/s3tools/s3cmd/commit/5d280cb772d67e9f0c3eb79029f984b2b9815e1e#diff-20ab68ce58da12135a33930f59de21d3

Can we please tag a new 2.0.3 release?

**Comment by fviard** [comment]
Release v2.1.0 with the fix is out and available in github and in Pypi.
