### ISSUE TITLE
Remote files are no longer being removed

### ISSUE THREAD

**Issue by turbo2ltr** [s3tools/s3cmd#932]
Using a script I'm pushing daily cPanel backups to S3.  By default, cPanel puts the backups in a directory named with the current date.
My script would upload the whole directory for the day to bucket/cpbackup while removing the upload from the previous day.

``s3cmd sync -v --delete-removed /home2/backup/`date +%Y-%m-%d`  s3://host2-backup/cpbackup/ ``

This no longer seem to work. It uploads the directory, but it is no longer deleting the old ones.  This caused my S3 bill to skyrocket as after I upload, I copy the contents of the cpbackup on s3 to a "day of the week" folder so I maintain 7 days of backups.

I'm currently using 2.0.0.  With my previous issue, I may have updated s3cmd from an older version, which is when I think it broke.

I saw some other old threads about this problem.  So I added a trailing slash on the local path and did a dry run:
`INFO: Summary: 0 local files to upload, 52 files to remote copy, 103 remote files to delete`
Instead of uploading the folder /local/cpbackup/[date] to /s3bucket/[date]/ it uploaded the contents of /local/cpabckup/[date] to /s3bucket/

So I specifically told it to upload to /s3bucket/[date]/ but then that didn't delete the other [date] directory from the previous day.

Sure, the easy thing to do is just delete everything in the folder first before uploading.. but it used to work.. Can I no longer do this? What am I doing wrong?

**Comment by fviard** [comment]
If I understood well your problem, the behavior that you expected was the result of a bug that was fixed.
Now, s3cmd behavior with paths should be similar to the one of rsync.

if you provide a specific source folder, it should only consider this folder at destination.
The thing that was convenient for you is most of the time dangerous for normal users.

So on the current logic, you should do:
/local/cpbackup/ s3bucket/ 
if you want to have [date] copied and other files removed.
But, if in cpbackup you have other folders or other dates they will be copied to.
What can maybe fix your case is to do that, and to use an include or excludes rules?

If that doesn't fix it for you, sadly we don't provide an option like "let's pretend the source folder only has this folder so delete everything else".
If there are other folders in your cpbackup, I can imagine another alternative, create a empty folder like:
/local/cpbackup/toupload
and inside you put a [date] symbolic link to:
 /local/cpbackup/[date]
and then your do:
sync -F /local/cpbackup/ s3bucket/
(-F is to follow symlinks)

**Comment by turbo2ltr** [comment]
OK, this makes sense, Thank you for the explanation.

Correct me if I'm wrong, but I think the last example should have been
sync -F /local/cpbackup/toupload/ s3bucket/

Thanks for the ideas.  My script creates a symlink with the proper date before upload and then I point S3 to the toupload dir.  Thanks!

**Comment by fviard** [comment]
Yes for my last example you are right ;-) Hopefully you understood my point.
