### ISSUE TITLE
Add bucket operations to enable and disable versioning

### ISSUE THREAD

**Issue by jamshid** [s3tools/s3cmd#937]
It would be useful and consistent if s3cmd supported enabling of "versioning" on a bucket (http://docs.aws.amazon.com/AmazonS3/latest/dev/Versioning.html), like it does other configuration options (e.g. `setpolicy` and `accesslog`).
This is related to https://github.com/s3tools/s3cmd/issues/368.

**Comment by rontrompert** [comment]
+1

**Comment by a523** [comment]
+1

**Comment by peterjirak** [comment]
This is completely and utterly necessary. Spaces is not s3 compliant/compatible until it correctly and completely supports versioning. Please fix this!

**Comment by dahitech** [comment]
Is there any update on this request?

**Comment by tomasc** [comment]
I would love to see this implemented as well. Thank you.

**Comment by lukebouch** [comment]
I would like upvote this issue.
