### ISSUE TITLE
Parameter problem error thrown when running from Cron

### ISSUE THREAD

**Issue by afonseca08** [s3tools/s3cmd#952]
I am getting the following error emailed to me when I run s3cmd from a Cron job:

> ERROR: Parameter problem: Expecting S3 URI instead of 'Content-type:'

However, the file upload succeeds and I only get this error message when running from Cron. Running the same command from the command line does not show this error message.

The command:
`/home/user/s3cmd-2.0.1/s3cmd put ./forumbackup*.sql.gz ${dir}`

where ${dir} is set to the output of a PHP script:
`s3://myaccount/backup/website/forum/daily/3_Tuesday/`

In case it helps, I have the almost exact script running in an older version, 1.0.1 and it does not produce this error as it does in 2.0.1.

**Comment by fviard** [comment]
@afonseca08 are you really sure of the content of $dir inside the cron?
Also of the CWD? Because cron strip a lot from the environment.
You can try to add the "-d" flag to the command at the beginning, so you might be able to see what command was called exactly in the error messages.

**Comment by afonseca08** [comment]
@fviard, I figured it out, thank you for pointing me in the right direction. $dir was set from the output of a php script which was adding http headers when run from cron. I added the '-q' argument to suppress those and that resolved the issue. So user error, please go ahead and close this out.
