### ISSUE TITLE
Problem: timeout: timed out

### ISSUE THREAD

**Issue by eligiable** [s3tools/s3cmd#971]
Hi There,
I'm having the below error, it was first not synching using the HTTPS, then I re-configured to use HTTP, after some syncing I'm now getting the below error:

`S3cmd:   2.0.1
python:   2.7.6 (default, Nov 23 2017, 15:49:48)
[GCC 4.8.4]
environment LANG=en_US.UTF-8

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-2.0.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 3073, in <module>
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-2.0.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 2989, in main
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-2.0.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1875, in cmd_sync
  File "/usr/local/lib/python2.7/dist-packages/s3cmd-2.0.1-py2.7.egg/EGG-INFO/scripts/s3cmd", line 1185, in cmd_sync_remote2local
  File "build/bdist.linux-x86_64/egg/S3/FileLists.py", line 460, in fetch_remote_list
    objectlist, tmp_total_size = _get_filelist_remote(uri, recursive = True)
  File "build/bdist.linux-x86_64/egg/S3/FileLists.py", line 397, in _get_filelist_remote
    recursive = recursive, uri_params = uri_params)
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 308, in bucket_list
    for truncated, dirs, objects in self.bucket_list_streaming(bucket, prefix, recursive, uri_params, limit):
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 342, in bucket_list_streaming
    response = self.bucket_list_noparse(bucket, prefix, recursive, uri_params, max_keys)
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 373, in bucket_list_noparse
    response = self.send_request(request)
  File "build/bdist.linux-x86_64/egg/S3/S3.py", line 1256, in send_request
    http_response = conn.c.getresponse()
  File "/usr/lib/python2.7/httplib.py", line 1089, in getresponse
    response.begin()
  File "build/bdist.linux-x86_64/egg/S3/Custom_httplib27.py", line 35, in httpresponse_patched_begin
    version, status, reason = self._read_status()
  File "/usr/lib/python2.7/httplib.py", line 400, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
timeout: timed out

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    An unexpected error has occurred.
  Please try reproducing the error using
  the latest s3cmd code from the git master
  branch found at:
    https://github.com/s3tools/s3cmd
  and have a look at the known issues list:
    https://github.com/s3tools/s3cmd/wiki/Common-known-issues-and-their-solutions
  If the error persists, please report the
  above lines (removing any private
  info as necessary) to:
   s3tools-bugs@lists.sourceforge.net
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
`

**Comment by fviard** [comment]
Hum, that is just a guess but if it didn't work with https and not with http even with a different error, you should check your configuration.

**Comment by fviard** [comment]
You can post it here removing the private parts like secret key if you want that we look into it.
Also, you can run the command with the "-d" flag to have more "debug log" of what is going on.

**Comment by eligiable** [comment]
@fviard I'm now using awsCLI and quit using s3cmd, because the behavior of the tool is changing on each server, the same tool was working fine, and suddenly the issue started happening.

```
access_key = #
access_token =
add_encoding_exts =
add_headers =
bucket_location = EU
ca_certs_file =
cache_file =
check_ssl_certificate = True
check_ssl_hostname = True
cloudfront_host = cloudfront.amazonaws.com
default_mime_type = binary/octet-stream
delay_updates = False
delete_after = False
delete_after_fetch = False
delete_removed = False
dry_run = False
enable_multipart = True
encrypt = False
expiry_date =
expiry_days =
expiry_prefix =
follow_symlinks = False
force = False
get_continue = False
gpg_command = /usr/bin/gpg
gpg_decrypt = %(gpg_command)s -d --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_encrypt = %(gpg_command)s -c --verbose --no-use-agent --batch --yes --passphrase-fd %(passphrase_fd)s -o %(output_file)s %(input_file)s
gpg_passphrase = +CTVAdmin-
guess_mime_type = True
host_base = s3.amazonaws.com
host_bucket = %(bucket)s.s3.amazonaws.com
human_readable_sizes = False
invalidate_default_index_on_cf = False
invalidate_default_index_root_on_cf = True
invalidate_on_cf = False
kms_key =
limit = -1
limitrate = 0
list_md5 = False
log_target_prefix =
long_listing = False
max_delete = -1
mime_type =
multipart_chunk_size_mb = 15
multipart_max_chunks = 10000
preserve_attrs = True
progress_meter = True
proxy_host =
proxy_port = 0
put_continue = False
recursive = False
recv_chunk = 65536
reduced_redundancy = False
requester_pays = False
restore_days = 1
restore_priority = Standard
secret_key = #
send_chunk = 65536
server_side_encryption = False
signature_v2 = False
signurl_use_https = False
simpledb_host = sdb.amazonaws.com
skip_existing = False
socket_timeout = 300
stats = False
stop_on_error = False
storage_class =
urlencoding_mode = normal
use_http_expect = False
use_https = False
use_mime_magic = True
verbosity = WARNING
website_endpoint = http://%(bucket)s.s3-website-%(location)s.amazonaws.com/
website_error =
website_index = index.html
```

**Comment by djdevin** [comment]
fwiw we also started seeing timeouts when doing `s3cmd sync`

it's been running great for months and just recently starting throwing timeouts.

**Comment by fviard** [comment]
Closing obsolete issue.
Code should now behave better and in addition, I think that AWS resolved a lot of timeouts issues that we were encountering before.
