### ISSUE TITLE
Is it possible to create a presigned URL without expiration?

### ISSUE THREAD

**Issue by jasonsweis** [s3tools/s3cmd#984]
Is it possible to create a presigned URL without expiration?

If I try to do this in CLI, I receive an error saying expiration must be no more than a week.

**Comment by fviard** [comment]
From what I know, one week is the maximum allowed by AWS.

For your usage, maybe you should have a look at 'cloudfront'.

**Comment by jasonsweis** [comment]
Sent from Yahoo Mail on Android 
 
  On Sun, Jul 22, 2018 at 4:46 PM, Florent Viard<notifications@github.com> wrote:   
Closed #984.

**Comment by jasonsweis** [comment]
Thank you. I will look into cloudfront.
